# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description:
      'Remove final to allow BraveMultiInstanceOrchestratorImpl to extend it.'
    regex:
      pattern: '/* package */ final class MultiInstanceOrchestratorImpl'
      replace: '/* package */ class MultiInstanceOrchestratorImpl'

  - description:
      'Make constructor package-private to allow
      BraveMultiInstanceOrchestratorImpl to call super().'
    regex:
      pattern:
        'private MultiInstanceOrchestratorImpl(TabReparentingDelegate
        tabReparentingDelegate)'
      replace:
        'MultiInstanceOrchestratorImpl(TabReparentingDelegate
        tabReparentingDelegate)'
