export default {
  currencies: [
    'BTC',
    'ETH',
    'LTC',
    'BCH',
    'ZEC',
    'FIL',
    'ZRX',
    '1INCH',
    'AAVE',
    'AMP',
    'BNT',
    'BAT',
    'BAL',
    'LINK',
    'COMP',
    'CRV',
    'DAI',
    'MANA',
    'ENJ',
    'GRT',
    'KNC',
    'LRC',
    'MKR',
    'OXT',
    'PAXG',
    'REN',
    'SAND',
    'SKL',
    'STORJ',
    'SNX',
    'UMA',
    'UNI',
    'YFI'
  ],
  currencyNames: {
    'BTC': 'Bitcoin',
    'ETH': 'Ethereum',
    'LTC': 'Litecoin',
    'BCH': 'Bitcoin Cash',
    'ZEC': 'Zcash',
    'FIL': 'Filecoin',
    'ZRX': '0x',
    '1INCH': '1INCH',
    'AAVE': 'Aave',
    'AMP': 'Amp',
    'BNT': 'Bancor Network',
    'BAT': 'Basic Attention',
    'BAL': 'Balancer',
    'LINK': 'Chainlink',
    'COMP': 'Compound',
    'CRV': 'Curve',
    'DAI': 'Dai',
    'MANA': 'Decentraland',
    'ENJ': 'Enjin',
    'GRT': 'The Graph',
    'KNC': 'Kyber Network',
    'LRC': 'Loopring',
    'MKR': 'Maker',
    'OXT': 'Orchid',
    'PAXG': 'Pax Gold',
    'REN': 'Ren',
    'SAND': 'The Sandbox',
    'SKL': 'Skale',
    'STORJ': 'Storj',
    'SNX': 'Synthetix',
    'UMA': 'Uma',
    'UNI': 'Uniswap',
    'YFI': 'Yearn Finance'
  }
}
