# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: 'Make the destructor virtual'
    make_virtual:
      class_name: BookmarksSidePanelCoordinator
      method_name: '~BookmarksSidePanelCoordinator'

  - description: 'Make CreateAndRegisterEntry virtual'
    make_virtual:
      class_name: BookmarksSidePanelCoordinator
      method_name: CreateAndRegisterEntry

  - description: 'Friend BraveBookmarksSidePanelView'
    add_friend:
      class_name: BookmarksSidePanelCoordinator
      friend_type: class BraveBookmarksSidePanelView
