# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description:
      Mobile Android has the same profile-before-browser startup order.
    regex:
      re_pattern:
        '#if BUILDFLAG\(IS_DESKTOP_ANDROID\)(\s*//
        TODO\(https://crbug.com/356905053\))'
      replace: '#if BUILDFLAG(IS_ANDROID)\1'
