# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

assert(is_android)

source_set("brave_account") {
  sources = [
    "brave_account_dialog_launcher_helper.cc",
    "brave_account_dialog_launcher_helper.h",
  ]

  deps = [
    "//base",
    "//brave/build/android:jni_headers",
    "//content/public/browser",
  ]
}
