# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Add the public_deps the Brave startup additions need.
    add_literal_to_list:
      target: startup_tab
      list_name: public_deps
      literal: brave_browser_ui_startup_public_deps
      import: //brave/browser/ui/startup/sources.gni
