# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |-
      Ship kSkipUndecryptablePasswords enabled outside of Android/ChromeOS.

      Upstream only enables this by default on Windows. Brave additionally
      wants it enabled on iOS, Linux and Mac, but not on Android, so
      `set_feature_flag_default_state` is not ideal, because we want to be
      alerted whenever anything chnages in upstream.
    regex:
      re_pattern:
        'BASE_FEATURE\(kSkipUndecryptablePasswords,\s*#if
        BUILDFLAG\(IS_WIN\)\s*base::FEATURE_ENABLED_BY_DEFAULT\s*#else\s*base::FEATURE_DISABLED_BY_DEFAULT\s*#endif\s*\);'
      replace: |-
        #if BUILDFLAG(IS_IOS) || BUILDFLAG(IS_LINUX) || BUILDFLAG(IS_MAC) || \
            BUILDFLAG(IS_WIN)
        BASE_FEATURE(kSkipUndecryptablePasswords, base::FEATURE_ENABLED_BY_DEFAULT);
        #else
        BASE_FEATURE(kSkipUndecryptablePasswords, base::FEATURE_DISABLED_BY_DEFAULT);
        #endif
