# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Let BraveTabMenuModel reach TabMenuModel's private members.

      BraveTabMenuModel subclasses TabMenuModel and accesses other private
      members directly.
    add_friend:
      class_name: TabMenuModel
      friend_type: class BraveTabMenuModel
