substitutions:
  - description: |-
      Add accessors for bool opener_was_set_for_empty_new_tab

    add_to_public:
      class_name: TabModel
      code: |-
        void set_opener_was_set_for_empty_new_tab() { opener_was_set_for_empty_new_tab_ = true; }
        bool opener_was_set_for_empty_new_tab() const {
           return opener_was_set_for_empty_new_tab_;
        }

  - description: |
      Add bool opener_was_set_for_empty_new_tab_ private member.

      Used for tree tabs to track whether the opener was set for an empty
      new tab in TabStripModel::AddTab().
    regex:
      re_pattern: (bool reset_opener_on_active_tab_change_ = false;)
      replace: |-
        \1
          bool opener_was_set_for_empty_new_tab_ = false;
