# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/components/traffic_control/buildflags/buildflags.gni")
import("//mojo/public/tools/bindings/mojom.gni")

assert(enable_traffic_control)

mojom("mojom") {
  sources = [ "traffic_control.mojom" ]

  deps = [ "//mojo/public/mojom/base" ]

  webui_module_path = "/"
}
