CI/run-audit-deps:
  - changed-files:
    - any-glob-to-any-file:
      - DEPS
      - package.json
      - package-lock.json
      - script/audit_deps.py
      - "**/Cargo.toml"
      - "**/Cargo.lock"

CI/run-network-audit:
  - changed-files:
    - any-glob-to-any-file:
      - browser/net/*
      - chromium_src/net/**/*
      - chromium_src/**/*features.cc
      - patches/chrome-VERSION.patch

CI/run-perf-smoke-tests:
  - changed-files:
    - any-glob-to-any-file:
      - patches/third_party/catapult/*
      - patches/tools-perf-*
      - tools/perf/*

CI/run-upstream-tests:
  - changed-files:
    - any-glob-to-any-file:
      - browser/about_flags.cc
      - chromium_src/**/*features.cc
      - test/filters/*.filter

CI/storybook-url:
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.svelte"
      - "**/*.css"
      - "**/*.scss"

feature/web3/wallet:
  - changed-files:
    - any-glob-to-any-file:
      - android/java/org/chromium/chrome/browser/app/domain/**/*
      - android/java/org/chromium/chrome/browser/crypto_wallet/**/*
      - browser/brave_wallet/android/**/*
      - browser/resources/settings/brave_wallet_page/**/*
      - browser/ui/brave_wallet/**/*
      - browser/ui/webui/brave_wallet/**/*
      - components/brave_wallet/**/*
      - components/brave_wallet_ui/**/*

feature/web3/wallet/core:
  - changed-files:
    - any-glob-to-any-file:
      - browser/brave_wallet/android/**/*
      - browser/resources/settings/brave_wallet_page/**/*
      - browser/ui/brave_wallet/**/*
      - browser/ui/webui/brave_wallet/**/*
      - components/brave_wallet/**/*
