CI/run-audit-deps:
- DEPS
- package.json
- package-lock.json
- script/audit_deps.py
- "**/Cargo.toml"
- "**/Cargo.lock"

CI/run-network-audit:
- browser/net/*
- chromium_src/net/**/*
- chromium_src/**/*features.cc
- patches/chrome-VERSION.patch

CI/run-upstream-tests:
- browser/about_flags.cc
- chromium_src/**/*features.cc

CI/storybook-url:
- "**/*.ts"
- "**/*.tsx"
- "**/*.svelte"
- "**/*.css"
- "**/*.scss"

feature/web3/wallet:
- android/java/org/chromium/chrome/browser/app/domain/**/*
- android/java/org/chromium/chrome/browser/crypto_wallet/**/*
- browser/brave_wallet/android/**/*
- browser/resources/settings/brave_wallet_page/**/*
- browser/ui/brave_wallet/**/*
- browser/ui/webui/brave_wallet/**/*
- components/brave_wallet/**/*
- components/brave_wallet_ui/**/*

feature/web3/wallet/core:
- browser/brave_wallet/android/**/*
- browser/resources/settings/brave_wallet_page/**/*
- browser/ui/brave_wallet/**/*
- browser/ui/webui/brave_wallet/**/*
- components/brave_wallet/**/*
