#!/usr/bin/env python3
# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
"""Bootstraps a fresh brave-core + Chromium checkout from nothing.

Everything is cloned by depot_tools' own `gclient sync`, so both brave-core
and Chromium go through its git cache (see `--cache-dir` / `GIT_CACHE_PATH`)
instead of a plain, uncached `git clone`. This takes two `gclient sync` passes
against `./.gclient`, because the second pass needs brave-core's own
`package.json` (for Chromium's pinned tag, `custom_deps`, `custom_vars`) which
only exists once the first pass has cloned it:

    1. `solutions = [{"name": "src/brave", "url": <brave-core>}]` -- clones
       brave-core into `./src/brave`.
    2. `solutions = [<chromium>, <brave-core, informational>]` -- clones
       Chromium into `./src`, pinned to the tag/branch/revision brave-core's
       `package.json` expects (see `project_ref`).

Once brave-core exists, depot_tools is vendored into
`./src/brave/vendor/depot_tools` -- the same layout
`build/commands/lib/depotTools.js` deploys to -- so the rest of the brave-core
build tooling (and `tools/cr/*`) finds it without needing it on `$PATH`.

Once Chromium is synced, `pnpm install` and `pnpm run init` finish the job
(applying patches, running hooks, ...), via the `pnpm` shim in this same
directory -- put on `$PATH` for that call if it isn't there already -- which
self-fetches the checkout-local Node/pnpm toolchain on first use.

This runs under plain `python3` (stdlib-only): nothing else is on hand yet.

Usage::

    cd ~/wherever/you/want/the/checkout
    python3 /path/to/existing/checkout/tools/cr/bootstrap/fetch_brave.py
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

# Default remotes for the two repos this script bootstraps.
BRAVE_CORE_URL = 'https://github.com/brave/brave-core.git'
DEPOT_TOOLS_URL = (
    'https://chromium.googlesource.com/chromium/tools/depot_tools.git')

# Header comment left at the top of the generated `.gclient`.
_GCLIENT_HEADER = (
    '# Generated by tools/cr/bootstrap/fetch_brave.py.\n'
    '# Run `npm run sync` from src/brave to keep this up to date afterwards.\n'
    '\n')


def clone_if_missing(url: str, dest: Path) -> bool:
    """Clones `url` into `dest` unless it already looks like a checkout.

    Returns whether a clone was performed; an existing `dest/.git` is left
    untouched so re-running this script is cheap. Plain (uncached) git clone
    -- only used to bootstrap depot_tools itself, which is what everything
    else routes through the git cache for.
    """
    if (dest / '.git').exists():
        return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    subprocess.check_call(['git', 'clone', url, str(dest)])
    return True


def resolve_bootstrap_depot_tools(scratch_dir: Path) -> tuple[Path, bool]:
    """A depot_tools directory usable to drive the clones below.

    Reuses a `gclient` already on `$PATH` if there is one (mirroring
    `ensure_on_path()` in `tools/recipes/recipe_modules/depot_tools/api.py`);
    otherwise clones a fresh copy into `scratch_dir`, since depot_tools' own
    vendored home (`src/brave/vendor/depot_tools`) doesn't exist yet -- it
    lives inside the brave-core checkout this script is about to create.

    Returns `(depot_tools_dir, freshly_cloned)`.
    """
    on_path = shutil.which('gclient')
    if on_path:
        return Path(on_path).resolve().parent, False
    clone_if_missing(DEPOT_TOOLS_URL, scratch_dir)
    return scratch_dir, True


def load_chromium_project(brave_core_dir: Path) -> dict:
    """The `config.projects.chrome` block from brave-core's `package.json`.

    This is the same source of truth `build/commands/lib/config.ts` reads, so
    the checkout this produces matches what `npm run sync` would converge to.
    """
    package_json = json.loads(
        (brave_core_dir / 'package.json').read_text(encoding='utf-8'))
    return package_json['config']['projects']['chrome']


def project_ref(project: dict) -> str:
    """The git ref to pin a project to, mirroring `Config.getProjectRef()` in
    `build/commands/lib/config.ts`: an explicit revision wins, then a tag,
    then a branch, defaulting to `origin/master`.
    """
    revision = project.get('revision')
    if revision:
        return revision
    tag = project.get('tag')
    if tag:
        return f'refs/tags/{tag}'
    branch = project.get('branch')
    if branch:
        return f'origin/{branch}'
    return 'origin/master'


def build_solutions(chromium: dict, brave_core_url: str) -> list[dict]:
    """The `solutions` list for the final, permanent `.gclient`.

    Both entries are `managed: False`, matching `writeGclientConfig()` in
    `build/commands/lib/syncUtils.js`: Chromium's revision is pinned
    explicitly on each sync rather than left to gclient's own auto-update.
    brave-core's entry is never actually cloned from here -- by the time this
    is written, `clone_brave_core` has already cloned it -- but it must stay
    listed so gclient walks its `DEPS` (brave-core's own third-party deps).
    """
    chrome_dir = chromium.get('dir', 'src')
    return [
        {
            'managed': False,
            'name': chrome_dir,
            'url': chromium['repository']['url'],
            'custom_deps': chromium.get('custom_deps', {}),
            'custom_vars': chromium.get('custom_vars', {}),
        },
        {
            'managed': False,
            'name': f'{chrome_dir}/brave',
            'url': brave_core_url,
        },
    ]


def _gclient_literal(value, indent: int = 0) -> str:
    """Renders `value` as the Python literal gclient's parser expects.

    A `.gclient` file is `exec()`-ed by gclient, so this is just JSON with
    `True` / `False` / `None` in place of `true` / `false` / `null`.
    """
    if value is True:
        return 'True'
    if value is False:
        return 'False'
    if value is None:
        return 'None'
    if isinstance(value, dict):
        if not value:
            return '{}'
        pad = '  ' * (indent + 1)
        items = ',\n'.join(
            f'{pad}{json.dumps(k)}: {_gclient_literal(v, indent + 1)}'
            for k, v in value.items())
        return f'{{\n{items}\n{"  " * indent}}}'
    if isinstance(value, list):
        if not value:
            return '[]'
        pad = '  ' * (indent + 1)
        items = ',\n'.join(f'{pad}{_gclient_literal(v, indent + 1)}'
                           for v in value)
        return f'[\n{items}\n{"  " * indent}]'
    return json.dumps(value)


def _gclient_literal_inline(value) -> str:
    """Single-line rendering of `value`, used only to size it against the
    80-column threshold below.
    """
    if value is True:
        return 'True'
    if value is False:
        return 'False'
    if value is None:
        return 'None'
    if isinstance(value, dict):
        return '{' + ', '.join(f'{json.dumps(k)}: {_gclient_literal_inline(v)}'
                               for k, v in value.items()) + '}'
    if isinstance(value, list):
        return '[' + ', '.join(_gclient_literal_inline(v) for v in value) + ']'
    return json.dumps(value)


def render_gclient(solutions: list[dict], cache_dir: Path,
                   target_os: list[str], target_cpu: list[str]) -> str:
    """The full text of a `.gclient` file for `solutions` and `cache_dir`.

    Mirrors `writeGclientConfig()` in `build/commands/lib/syncUtils.js`: each
    top-level assignment is inlined if that fits in 80 columns, else wrapped
    one entry per line.
    """
    out = _GCLIENT_HEADER
    entries = {
        'solutions': solutions,
        'cache_dir': str(cache_dir),
        'target_os': target_os,
        'target_cpu': target_cpu,
    }
    for key, value in entries.items():
        inline = f'{key} = {_gclient_literal_inline(value)}'
        if len(inline) <= 80:
            out += inline + '\n'
        else:
            out += f'{key} = {_gclient_literal(value)}\n'
    return out


def default_cache_dir() -> Path:
    """The git cache dir `gclient sync` should use, so clones can be reused.

    `GIT_CACHE_PATH` matches the env var already honoured as a fallback by
    `build/commands/lib/config.ts`; absent that, this defaults to a location
    shared across checkouts on the same machine rather than one scoped to this
    checkout, since the whole point is to reuse objects across syncs/clones.
    """
    configured = os.environ.get('GIT_CACHE_PATH')
    if configured:
        return Path(configured).expanduser()
    return Path.home() / '.cache' / 'brave' / 'git-cache'


def run_gclient(depot_tools_dir: Path, root: Path,
                sync_args: list[str]) -> None:
    """Runs `gclient <sync_args>` against `root/.gclient`.

    Invokes `gclient.py` directly with the current interpreter (as
    `fetch.py`'s own `run_gclient()` falls back to when `gclient` isn't on
    `$PATH`), so this works whether or not `depot_tools_dir` is on `$PATH`.
    `depot_tools_dir` is still prepended to `$PATH` for the subprocess, since
    gclient's own hooks and self-bootstrapping expect to find the rest of
    depot_tools there.
    """
    env = os.environ.copy()
    env['PATH'] = os.pathsep.join([str(depot_tools_dir), env.get('PATH', '')])
    subprocess.check_call(
        [sys.executable,
         str(depot_tools_dir / 'gclient.py'), *sync_args],
        cwd=root,
        env=env)


def clone_brave_core(depot_tools_dir: Path, root: Path, url: str,
                     ref: str | None, cache_dir: Path) -> None:
    """Clones brave-core into `root/src/brave` via `gclient sync`.

    This -- rather than a plain `git clone` -- is what routes the clone
    through depot_tools' git cache. `src/brave` is hardcoded (rather than read
    from a config that doesn't exist yet): the rest of the codebase does the
    same, e.g. `braveCoreDir` in `build/commands/lib/config.ts`.
    """
    solutions = [{'managed': False, 'name': 'src/brave', 'url': url}]
    (root / '.gclient').write_text(render_gclient(solutions, cache_dir, [],
                                                  []),
                                   encoding='utf-8')
    sync_args = ['sync', '--nohooks']
    if ref:
        sync_args += ['--revision', f'src/brave@{ref}']
    run_gclient(depot_tools_dir, root, sync_args)


def sync_chromium(depot_tools_dir: Path, root: Path, chromium: dict,
                  brave_core_url: str, cache_dir: Path) -> Path:
    """Writes the permanent `.gclient` and syncs Chromium into it.

    Returns the `.gclient` path written.
    """
    solutions = build_solutions(chromium, brave_core_url)
    gclient_file = root / '.gclient'
    gclient_file.write_text(render_gclient(solutions, cache_dir, [], []),
                            encoding='utf-8')
    chrome_dir = chromium.get('dir', 'src')
    ref = project_ref(chromium)
    run_gclient(depot_tools_dir, root, [
        'sync', '--nohooks', '--reset', '--upstream', '--revision',
        f'{chrome_dir}@{ref}'
    ])
    return gclient_file


def vendor_depot_tools(depot_tools_dir: Path, freshly_cloned: bool,
                       brave_core_dir: Path) -> Path:
    """Ensures depot_tools lives at `brave_core_dir/vendor/depot_tools`.

    If `depot_tools_dir` was itself freshly bootstrapped by this run (into a
    scratch location, since brave-core didn't exist yet to vendor it into),
    it's moved into place rather than cloned twice. Otherwise (an existing
    `$PATH` depot_tools was reused) a fresh copy is cloned, matching what
    `installDepotTools()` in `build/commands/lib/depotTools.js` already does.
    """
    vendor_dir = brave_core_dir / 'vendor' / 'depot_tools'
    if (vendor_dir / '.git').exists():
        return vendor_dir
    if freshly_cloned:
        vendor_dir.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(depot_tools_dir), str(vendor_dir))
    else:
        clone_if_missing(DEPOT_TOOLS_URL, vendor_dir)
    return vendor_dir


def ensure_bootstrap_on_path(env: dict[str, str]) -> dict[str, str]:
    """A copy of `env` with this directory (tools/cr/bootstrap) prepended to
    `$PATH`, unless it (or an equivalent path) is already on it.

    The `pnpm` shim there self-fetches the checkout-local Node/pnpm toolchain
    on first use (see README.md's "chicken-and-egg `node` problem"), which is
    what lets `pnpm install`/`pnpm run init` work below with nothing else set
    up yet. Skipping the prepend when it's already present (e.g. the user
    already ran `bootstrap.py install`) avoids a redundant duplicate entry.
    """
    bootstrap_dir = Path(__file__).resolve().parent
    current = env.get('PATH', '')
    entries = [entry for entry in current.split(os.pathsep) if entry]
    if any(Path(entry).resolve() == bootstrap_dir for entry in entries):
        return env
    updated = dict(env)
    updated['PATH'] = os.pathsep.join([str(bootstrap_dir), current])
    return updated


def run_pnpm(brave_core_dir: Path, pnpm_args: list[str]) -> None:
    """Runs `pnpm <pnpm_args>` from `brave_core_dir`, via the bootstrap shim."""
    env = ensure_bootstrap_on_path(os.environ.copy())
    subprocess.check_call(['pnpm', *pnpm_args], cwd=brave_core_dir, env=env)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description='Bootstrap a fresh brave-core + Chromium checkout in the '
        'current directory.')
    parser.add_argument(
        '--url',
        default=BRAVE_CORE_URL,
        help='brave-core remote to clone (default: %(default)s)')
    parser.add_argument(
        '--ref',
        default=None,
        help='brave-core branch/tag to check out (default: remote HEAD)')
    parser.add_argument(
        '--cache-dir',
        type=Path,
        default=None,
        help='git cache dir for gclient sync (default: $GIT_CACHE_PATH, or '
        '~/.cache/brave/git-cache)')
    parser.add_argument(
        '--no-sync',
        action='store_true',
        help='clone brave-core but skip the (much larger) Chromium sync')
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    root = Path.cwd()
    brave_core_dir = root / 'src' / 'brave'
    cache_dir = args.cache_dir or default_cache_dir()
    cache_dir.mkdir(parents=True, exist_ok=True)

    depot_tools_dir, freshly_cloned = resolve_bootstrap_depot_tools(
        root / '.fetch_brave_depot_tools')
    if freshly_cloned:
        print(f'Cloned depot_tools into {depot_tools_dir}')

    if not (brave_core_dir / '.git').exists():
        print('Cloning brave-core via gclient (using the git cache)...')
        clone_brave_core(depot_tools_dir, root, args.url, args.ref, cache_dir)

    chromium = load_chromium_project(brave_core_dir)

    vendor_dir = vendor_depot_tools(depot_tools_dir, freshly_cloned,
                                    brave_core_dir)
    if freshly_cloned:
        depot_tools_dir = vendor_dir
        print(f'Vendored depot_tools into {vendor_dir}')

    if args.no_sync:
        gclient_file = root / '.gclient'
        solutions = build_solutions(chromium, args.url)
        gclient_file.write_text(render_gclient(solutions, cache_dir, [], []),
                                encoding='utf-8')
        print(f'Wrote {gclient_file}')
        return 0

    print('Running gclient sync to fetch Chromium (this can take a while)...')
    gclient_file = sync_chromium(depot_tools_dir, root, chromium, args.url,
                                 cache_dir)
    print(f'Wrote {gclient_file}')

    print('Running pnpm install...')
    run_pnpm(brave_core_dir, ['install', '--frozen-lockfile'])
    print('Running pnpm run init...')
    run_pnpm(brave_core_dir, ['run', 'init'])
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except subprocess.CalledProcessError as error:
        sys.exit(error.returncode)
