#!/usr/bin/env bash
# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Dispatches to tools/cr/plaster.py for the brave-core checkout the current
# directory is in. See launcher.py for the resolution logic.
dir="$(dirname "$0")"
python="$(python3 "$dir/runner.py")" || exit
exec "$python" "$dir/launcher.py" plaster "$@"
