# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description:
      'Let OnCookieChangeExposeForTesting call the private OnCookieChange.'
    add_friend:
      class_name: CookiesEventRouter
      friend_type: struct OnCookieChangeExposeForTesting

  - description:
      'Let OnCookieChangeExposeForTesting reach the private
      cookies_event_router_.'
    add_friend:
      class_name: CookiesAPI
      friend_type: struct OnCookieChangeExposeForTesting
