# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

brave_android_junit_chrome_junit_tests_helper_excluded_public_deps =
    [ "//chrome/browser/ui/android/native_page:junit" ]
