# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import os

from grit.node import message


def GetFormatter(type):
    if type == 'webui_locale_source':
        return _FormatSource
    if type == 'webui_locale_header':
        return _FormatHeader
    if type == 'webui_locale_ts':
        return _FormatTsEnum
    raise ValueError(f'Invalid type: {type}')


def _GetMessageAndIds(root, lang):
    for item in root.ActiveDescendants():
        if not isinstance(item, message.MessageNode):
            continue

        if not 'webui' in item.attrs:
            continue

        if item.attrs['webui'] != lang:
            continue

        name = item.attrs['name']

        # Get the name of the message without the IDS_ prefix
        enum_key = name[4:]
        # Treat the webui=prefix as a prefix for the enum key which should be
        # stripped
        if enum_key.lower().startswith(lang):
            enum_key = enum_key[len(lang) + 1:]

        enum_key = ''.join(word.capitalize() for word in enum_key.split('_'))

        # Lower the first letter of the id to be camel case
        yield (name, enum_key[0].lower() + enum_key[1:])


def _FormatHeader(root, lang, output_dir='.'):
    return f'''\
// This file is automatically generated by GRIT. Do not edit.
#pragma once

#include "base/containers/span.h"
#include "ui/base/webui/web_ui_util.h"

namespace {lang} {{
  base::span<const webui::LocalizedString> GetLocalizedStrings();
}}
'''


def _FormatSource(root, lang, output_dir='.'):
    # TODO: Find the include path for the header file
    header_node = _GetOuputNode(root, 'webui_locale_header', lang)
    if not header_node:
        raise ValueError(f'Header file not found for language: {lang}')

    header = header_node.GetOutputFilename()
    # TODO: Find the include path for the string ids
    string_ids = 'components/grit/brave_components_strings.h'
    yield f'''\
// This file is automatically generated by GRIT. Do not edit.

#include "{header}"

#include <array>

#include "{string_ids}"
#include "ui/base/webui/web_ui_util.h"

namespace {lang} {{
  base::span<const webui::LocalizedString> GetLocalizedStrings() {{
    static constexpr auto kLocalizedStrings = std::to_array<
      webui::LocalizedString>({{
'''

    is_first = True
    for name, ts_id in _GetMessageAndIds(root, lang):
        if not is_first:
            yield ',\n'
        yield f'      {{"{ts_id}", {name}}}'
        is_first = False

    # Output the footer
    yield '''\
  });
      return kLocalizedStrings;
    }
  }
'''


def _FormatTsEnum(root, lang, output_dir='.'):
    # Output the header
    yield '''\
// This file is automatically generated by GRIT. Do not edit.

declare global {
  const enum StringIds {
'''

    # Output the enum values
    for _, ts_id in _GetMessageAndIds(root, lang):
        yield f'    {ts_id[0].upper() + ts_id[1:]} = "{ts_id}",\n'

    # Output the footer
    yield '''\
  }
}

export { }
'''


def _GetOuputNode(root, type, lang):
    for item in root.GetOutputFiles():
        if item.GetType() == type and item.GetLanguage() == lang:
            return item

    return None
