[package]
name = "document-extractor"
version = "0.1.0"
authors = ["Darnell Andries <dandries@brave.com>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
cxx = "1"
kuchikiki = "0.8.7-speedreader"
html5ever = "0.29.1"

[lib]
name = "document_extractor_cxx"
path = "lib.rs"
crate-type = ["rlib"]
