#ifndef BRAVE_CHROMIUM_SRC_IOS_WEB_VIEW_INTERNAL_WEBDATA_SERVICES_WEB_VIEW_WEB_DATA_SERVICE_WRAPPER_FACTORY_H_
#define BRAVE_CHROMIUM_SRC_IOS_WEB_VIEW_INTERNAL_WEBDATA_SERVICES_WEB_VIEW_WEB_DATA_SERVICE_WRAPPER_FACTORY_H_

#include "ios/chrome/browser/webdata_services/model/web_data_service_factory.h"

namespace ios_web_view {
typedef ios::WebDataServiceFactory WebViewWebDataServiceWrapperFactory;
}

#endif
