# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Add the Brave minidump uploader java sources.
    add_literal_to_list:
      target: minidump_uploader_java
      list_name: sources
      literal: brave_components_minidump_uploader_util_java_sources
      import: //brave/components/minidump_uploader/sources.gni

  - description: Add the Brave minidump uploader java deps.
    add_literal_to_list:
      target: minidump_uploader_java
      list_name: deps
      literal: brave_components_minidump_uploader_util_java_deps
      import: //brave/components/minidump_uploader/sources.gni
