/* Copyright 2019 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_COMPONENTS_BRAVE_PERF_PREDICTOR_BROWSER_BANDWIDTH_LINREG_PARAMETERS_H_
#define BRAVE_COMPONENTS_BRAVE_PERF_PREDICTOR_BROWSER_BANDWIDTH_LINREG_PARAMETERS_H_

/* This file is automatically generated, do not edit directly */

#include <string>
#include <map>
#include <vector>
#include <array>

#include "base/containers/flat_set.h"

namespace brave_perf_predictor {

const double model_intercept = {{model.intercept}};
const int feature_count = {{model.coefficients | length}};
const std::array<double, feature_count> model_coefficients = {
{{model.coefficients | join(',\n')}}
};

const unsigned int standardise_feat_count = {{transformers.standardise.features | length}};

const std::array<double, standardise_feat_count> standardise_feat_means = {
{{transformers.standardise.mean | join(',\n')}}
};

const std::array<double, standardise_feat_count> standardise_feat_scale = {
{{transformers.standardise.scale | join(',\n')}}
};

const std::array<std::string, feature_count> feature_sequence = {
  {% for feature in transformers.standardise.features %}
  "{{feature}}",
  {% endfor %}
  {% for feature in transformers.passthrough.features %}
  "{{feature}}",
  {% endfor %}
};

const std::vector<std::string> relevant_entities{
  {% for entity in misc.entities %}
  "{{entity}}",
  {% endfor %}
};

const base::flat_set<std::string> relevant_entity_set(relevant_entities);

struct stdfactor {
    double mean, scale;
};

const std::map<std::string, stdfactor> stdfactor_map = {
  {% for feature, (mean, scale) in transformers.standardise.feature_map %}
  {
    "{{feature}}",
    { {{mean}}, {{scale}} }
  },
  {% endfor %}
};

}  // namespace brave_perf_predictor

#endif  // BRAVE_COMPONENTS_BRAVE_PERF_PREDICTOR_BROWSER_BANDWIDTH_LINREG_PARAMETERS_H_
