# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Force recentlyClosedGroupIsOnlyHeader to be always false

      This is done to prevent `You'll find your recent tabs here`
      sync promo
    regex:
      re_pattern: |-
        (boolean recentlyClosedGroupIsOnlyHeader =)\s+mRecentlyClosedTabsGroup\.getChildrenCount\(\) == 1;
      replace: '\1 false;'
