# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Hide the referrer on redirect in `NavigationRequest::OnRequestRedirected`
    regex:
      re_pattern:
        '(common_params_->referrer->url = GURL\(redirect_info\.new_referrer\);)'
      replace: |-
        \1
          GetContentClient()->browser()->MaybeHideReferrer(
              browser_context, common_params_->url,
              GetTopDocumentGURL(frame_tree_node_), &common_params_->referrer);

  - description: |
      Hide the referrer in `NavigationRequest::OnStartChecksComplete`
    regex:
      re_pattern:
        '(auto loader_type = NavigationURLLoader::LoaderType::kRegular;)'
      replace: |-
        GetContentClient()->browser()->MaybeHideReferrer(
              frame_tree_node_->navigator().controller().GetBrowserContext(),
              common_params_->url, GetTopDocumentGURL(frame_tree_node_),
              &common_params_->referrer);
          \1
