# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Rerun preprocessing when the Brave lit mangler changes.
    add_literal_to_list:
      target: target_name
      list_name: inputs
      literal: brave_lit_mangler_preprocess_if_expr_inputs
      import: //brave/tools/chromium_src/lit_mangler/sources.gni
