# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Add the Brave content settings sources.
    add_literal_to_list:
      target: browser
      list_name: sources
      literal: brave_components_content_settings_core_browser_sources

  - description: Add the Brave content settings deps.
    add_literal_to_list:
      target: browser
      list_name: deps
      literal: brave_components_content_settings_core_browser_deps
