# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Add the Brave network service deps.
    add_literal_to_list:
      target: network_service
      list_name: deps
      literal: brave_services_network_deps
      import: //brave/services/network/sources.gni
