# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/components/brave_wallet/common/buildflags/buildflags.gni")

assert(!is_android)
assert(enable_brave_wallet)

source_set("polkadot") {
  sources = [
    "polkadot_ui.cc",
    "polkadot_ui.h",
  ]
  deps = [
    "//brave/browser/ui/webui/brave_wallet/wallet_panel",
    "//brave/components/brave_wallet/common",
    "//brave/components/brave_wallet/common:common_constants",
    "//brave/components/brave_wallet/common:mojom",
    "//brave/components/brave_wallet_ui:resources",
    "//brave/components/brave_wallet_ui/polkadot:polkadot_bridge_generated",
    "//brave/components/resources:static_resources_grit",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//services/network/public/mojom",
    "//ui/webui",
    "//ui/webui/resources:resources_grit",
  ]
}
