# Copyright (c) 2023 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/components/brave_ads/buildflags/buildflags.gni")

assert(enable_brave_ads)

source_set("services") {
  sources = [
    "bat_ads_service_factory_impl.cc",
    "bat_ads_service_factory_impl.h",
    "bat_ads_service_feature.cc",
    "bat_ads_service_feature.h",
    "bat_ads_service_launch.cc",
    "bat_ads_service_launch.h",
  ]

  deps = [
    "//base",
    "//brave/app:brave_generated_resources_grit",
    "//brave/components/brave_ads/browser",
    "//brave/components/brave_ads/core",
    "//brave/components/services/bat_ads:lib",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//mojo/public/cpp/system",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "bat_ads_service_factory_impl_unittest.cc",
    "bat_ads_service_launch_unittest.cc",
  ]

  deps = [
    ":services",
    "//base/test:test_support",
    "//brave/components/services/bat_ads/public/interfaces",
    "//content/test:test_support",
    "//mojo/public/cpp/bindings",
    "//testing/gtest",
  ]
}
