// Copyright (c) 2021 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// you can obtain one at https://mozilla.org/MPL/2.0/.
export enum CurrencySymbols {
  AED = 'د.إ',
  ARS = '$',
  AUD = '$',
  AWG = 'ƒ',
  BDT = '৳',
  BHD = '.د.ب',
  BMD = '$',
  BRL = 'R$',
  CAD = '$',
  CHF = 'CHF',
  CLP = '$',
  CZK = 'Kč',
  DJF = 'Fdj',
  DKK = 'kr',
  EUR = '€',
  GBP = '£',
  HKD = '$',
  HUF = 'Ft',
  IDR = 'Rp',
  ILS = '₪',
  INR = '₹',
  JPY = '¥',
  KRW = '₩',
  KWD = 'KD',
  LKR = '₨',
  MMK = 'K',
  MXN = '$',
  MYR = 'RM',
  NGN = '₦',
  NOK = 'kr',
  NZD = '$',
  PHP = '₱',
  PKR = '₨',
  PLN = 'zł',
  RUB = '₽',
  SAR = '﷼',
  SEK = 'kr',
  SGD = 'S$',
  THB = '฿',
  TRY = '₺',
  TWD = 'NT$',
  UAH = '₴',
  USD = '$',
  VEF = 'Bs',
  VND = '₫',
  XAG = 'XAG',
  XAU = 'XAU',
  XDR = 'XDR',
  ZAR = 'R',
}
