# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

source_set("topsites") {
  sources = [
    "brave_top_sites_service.h",
    "brave_top_sites_service.mm",
    "brave_top_sites_service_internal.h",
  ]
  deps = [
    "//base",
    "//components/ntp_tiles",
    "//ios/chrome/browser/ntp_tiles/model",
    "//ios/chrome/browser/shared/model/profile",
    "//net",
    "//url",
  ]
  frameworks = [ "Foundation.framework" ]
}
