# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |-
      Append AddQuickAction(DownloadCommands::DELETE_LOCAL_FILE)
    add_after_line:
      line: 'AddQuickAction(DownloadCommands::OPEN_WHEN_COMPLETE);'
      code: 'AddQuickAction(DownloadCommands::DELETE_LOCAL_FILE);'

  - description: |-
      Add case DownloadCommands::DELETE_LOCAL_FILE in the switch statement of
      GetAccessibleNameForQuickAction
    add_before_line:
      line: 'case DownloadCommands::SHOW_IN_FOLDER:'
      code: |-
        case DownloadCommands::DELETE_LOCAL_FILE:
          return l10n_util::GetStringFUTF16(
              IDS_DOWNLOAD_BUBBLE_DELETE_MAIN_BUTTON_ACCESSIBILITY,
              info_->model()->GetFileNameToReportUser().LossyDisplayName());
