sudo: required
dist: trusty
language: node_js
node_js:
  - node

branches:
  only:
    - master
    - /\d+\.\d+\.x/

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8 NODE_ENV=test ACTION=lint
  - CXX=g++-4.8 NODE_ENV=test ACTION=test-unit
  - CXX=g++-4.8 NODE_ENV=test ACTION=test-security

addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8

install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - npm run test-suite
#  - npm run build
# We need to pre-package a Brave build for this
# - npm run test-e2e
