environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '7'

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test
  - npm run build

build: off
