# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

# The friends in this file are being added next to the original declaration to
# be intentionally fragile, and break whenever any of these classes stop being
# a friend, so the privileged access can be review/removed when not needed
# anymore.

[[substitution]]
description = 'Befriend page_actions::chromium_impl::PageActionControllerImpl'
pattern = 'friend class PageActionControllerImpl;'
replace = '''friend class PageActionControllerImpl;
  friend class page_actions::chromium_impl::PageActionControllerImpl;'''
