substitutions:
  - description: |-
      Handle TREE_NODE in BuildMojoTabCollectionData().

      At the moment this API is not used for tree tabs, so just return the
      unpinned tabs collection data, mirroring the UNPINNED case shape.
    regex:
      re_pattern: (case\ tabs::TabCollection::Type::SPLIT:\ {)
      replace: |-
        case tabs::TabCollection::Type::TREE_NODE: {
                auto mojo_container = tabs_api::mojom::UnpinnedTabs::New();
                mojo_container->id = node_id;
                return tabs_api::mojom::Data::NewUnpinnedTabs(std::move(mojo_container));
              }
            \1
