[package]
name = "brave-ads-cxx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
lazy_static = "1.4.0"
regex = "1.5.5"

[lib]
name = "brave_ads_cxx"
path = "lib.rs"
crate-type = ["rlib"]
