# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: 'Ship kCpssUseTfliteSignatureRunner disabled.'
    set_feature_flag_default_state:
      feature_name: kCpssUseTfliteSignatureRunner
      value: base::FEATURE_DISABLED_BY_DEFAULT

  - description: 'Ship kPermissionPredictionsV2 disabled.'
    set_feature_flag_default_state:
      feature_name: kPermissionPredictionsV2
      value: base::FEATURE_DISABLED_BY_DEFAULT

  - description: 'Ship kPermissionsPromptSurvey disabled.'
    set_feature_flag_default_state:
      feature_name: kPermissionsPromptSurvey
      value: base::FEATURE_DISABLED_BY_DEFAULT

  - description: 'Ship kShowRelatedWebsiteSetsPermissionGrants disabled.'
    set_feature_flag_default_state:
      feature_name: kShowRelatedWebsiteSetsPermissionGrants
      value: base::FEATURE_DISABLED_BY_DEFAULT
