# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Enable legacy JS bindings generation for `mojo_bindings`.

      These bindings are used by `brave_new_tab_ui`.
    set_attribute:
      target: mojo_bindings
      attribute: generate_legacy_js_bindings
      value: 'true'

  - description: |
      Enable legacy JS bindings generation for `fusebox_action_mojo_bindings`.

      `mojo_bindings` depends on these bindings and we enabled legacy bindings
      generation there, so they have to be enabled here too.
    set_attribute:
      target: fusebox_action_mojo_bindings
      attribute: generate_legacy_js_bindings
      value: 'true'

  - description: Add the Brave sources to `static_library("browser")`.
    add_literal_to_list:
      target: browser
      list_name: sources
      literal: brave_components_omnibox_browser_sources

  - description: Add the Brave public_deps to `static_library("browser")`.
    add_literal_to_list:
      target: browser
      list_name: public_deps
      literal: brave_components_omnibox_browser_public_deps

  - description: Add the Brave deps to `static_library("browser")`.
    add_literal_to_list:
      target: browser
      list_name: deps
      literal: brave_components_omnibox_browser_deps
