# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description:
      'Return empty GURL for known Brave hosted extensions in GetWebStoreURL'
    re_pattern: '(GetWebStoreURL\([^)]*\)\s*\{)'
    re_flags: [DOTALL]
    count: 1
    replace: |-
      \1
        if (extensions_mv2::IsKnownBraveHostedExtension(extension->id())) {
          return GURL::EmptyGURL();
        }
