# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: 'Make ResetDefaultSearchEngine virtual'
    make_virtual:
      class_name: ProfileResetter
      method_name: ResetDefaultSearchEngine

  - description: 'Friend BraveProfileResetter'
    add_friend:
      class_name: ProfileResetter
      friend_type: class BraveProfileResetter
