# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

[[substitution]]
description = 'Add kActionShowPartitionedStorage to the array'
re_pattern = '(kActionIds = std::to_array<actions::ActionId>\(\{\s+?kActionAiMode,)'
replace = '\1\n    kActionShowPartitionedStorage,'
