/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

export const BOOKMARK_ADDED = 'BOOKMARK_ADDED'
export const BOOKMARK_REMOVED = 'BOOKMARK_REMOVED'
export const NEW_TAB_TOP_SITES_DATA_UPDATED = 'NEW_TAB_TOP_SITES_DATA_UPDATED'
export const NEW_TAB_BACKGROUND_IMAGE_LOAD_FAILED = 'NEW_TAB_BACKGROUND_IMAGE_LOAD_FAILED'
export const NEW_TAB_SITE_PINNED = 'NEW_TAB_SITE_PINNED'
export const NEW_TAB_SITE_UNPINNED = 'NEW_TAB_SITE_UNPINNED'
export const NEW_TAB_SITE_IGNORED = 'NEW_TAB_SITE_IGNORED'
export const NEW_TAB_UNDO_SITE_IGNORED = 'NEW_TAB_UNDO_SITE_IGNORED'
export const NEW_TAB_UNDO_ALL_SITE_IGNORED = 'NEW_TAB_UNDO_ALL_SITE_IGNORED'
export const NEW_TAB_SITE_DRAGGED = 'NEW_TAB_SITE_DRAGGED'
export const NEW_TAB_SITE_DRAG_END = 'NEW_TAB_SITE_DRAG_END'
export const NEW_TAB_HIDE_SITE_REMOVAL_NOTIFICATION = 'NEW_TAB_HIDE_SITE_REMOVAL_NOTIFICATION'
export const NEW_TAB_BOOKMARK_INFO_AVAILABLE = 'NEW_TAB_BOOKMARK_INFO_AVAILABLE'
export const NEW_TAB_GRID_SITES_UPDATED = 'NEW_TAB_GRID_SITES_UPDATED'
export const NEW_TAB_STATS_UPDATED = 'NEW_TAB_STATS_UPDATED'
export const NEW_TAB_USE_ALTERNATIVE_PRIVATE_SEARCH_ENGINE = 'NEW_TAB_USE_ALTERNATIVE_PRIVATE_SEARCH_ENGINE'
