# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Recover launch URLs that were passed on the command line for testing.
    preempt_function_impl:
      function_name: LaunchShimForTesting
      code: |-
        BraveLaunchShimForTesting(shim_path,
                                  urls,
                                  std::move(launched_callback),
                                  std::move(terminated_callback),
                                  chromium_path);
        return;
