/* Copyright (c) 2026 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

// Schema for the empty JSON body.
// Used when no request body is sent or the response body is ignored.
namespace endpoint_client {
  dictionary JSONEmptyBody {};
};
