# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description:
      'Add deps needed by Brave container overrides in the impl target'
    regex:
      re_pattern:
        '(public_deps = \[ "//chrome/browser:browser_public_dependencies" \])'
      replace: |-
        \1\n  import("//brave/browser/ui/web_applications/sources.gni") deps += brave_chrome_browser_ui_web_applications_deps
