[package]
name = "brave-wallet-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.100" # Must match the wasm-bindgen-cli version under brave/tools/crates!
schnorrkel = "=0.11.4"
getrandom = { version = "=0.2.15", features = [ "js" ] }
