/* Copyright (c) 2026 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

// nemotron-speech-streaming-en-0.6b model.

mod attention;
mod builder;
pub mod cache;
mod conformer;
mod encoder;
mod joint;
mod predictor;

use candle_core::Result;
use candle_nn::VarBuilder;
use serde::Deserialize;

pub use builder::ModelBuilder;
pub use cache::EncoderCache;
pub use encoder::ConformerEncoder;
pub use joint::RnntJoint;
pub use predictor::{PredictorState, RnntPredictor};

/// nemotron-speech-streaming-en-0.6b architecture hyperparameters,
/// mirroring the fields of the `config.json` that ships alongside
/// `model.gguf`. Generated by `convert_nemotron_nemo_to_gguf.py` from
/// the upstream `model_config.yaml` -- keep this struct in lockstep
/// with the converter's `derive_config()` output.
#[derive(Deserialize)]
pub struct NemotronConfig {
    // Encoder
    pub hidden_size: usize,
    pub num_heads: usize,
    pub num_layers: usize,
    pub intermediate_size: usize,
    pub conv_kernel_size: usize,
    pub conv_norm_type: String,
    pub num_mel_bins: usize,
    pub subsampling_channels: usize,
    pub subsampling_factor: usize,
    /// Frequency-axis dim after ConvSubsampling. Derived from the
    /// saved `encoder.pre_encode.out.weight` shape since the exact
    /// value depends on NeMo's causal asymmetric padding and is
    /// awkward to compute from yaml fields alone.
    pub subsampled_freq_dim: usize,
    pub xscaling: bool,
    pub causal_downsampling: bool,
    pub use_bias: bool,
    pub pos_emb_max_len: usize,

    // Preprocessor
    pub sample_rate: usize,
    pub n_fft: usize,
    pub win_length: usize,
    pub hop_length: usize,
    pub normalize: String,
    pub preemph: f32,
    pub dither: f32,

    // RNN-T predictor
    pub pred_hidden: usize,
    pub pred_rnn_layers: usize,
    pub blank_as_pad: bool,

    // RNN-T joint
    pub joint_hidden: usize,
    pub joint_activation: String,
    pub encoder_hidden: usize,

    // Vocab + blank
    pub vocab_size: usize,
    pub blank_id: usize,

    // Streaming caches
    pub left_context_frames: usize,
    pub right_context_frames: usize,
    pub conv_cache_frames: usize,
    pub chunk_frames: usize,

    // GGUF
    pub tensor_data_offset: usize,
}

/// Nemotron streaming model: encoder + RNN-T predictor + RNN-T joint.
///
/// ```text
/// per chunk:
///   input mel chunk (B, T_new, num_mel_bins)
///     -> ConformerEncoder.forward(mel, cache)
///     -> (B, T_new/8, hidden) encoder frames
///     -> RNN-T decode loop (driven from lib.rs)
///         per encoder frame f_t:
///           while tok != blank and symbols_this_step < max:
///             g_u = predictor.step(prev_token, state)
///             logits = joint.forward(f_t, g_u)
///             tok = argmax(logits)
///             if tok != blank: emit tok; prev_token = tok
/// ```
pub struct Nemotron {
    pub encoder: ConformerEncoder,
    pub predictor: RnntPredictor,
    pub joint: RnntJoint,
}

impl Nemotron {
    pub fn new(
        cfg: &NemotronConfig,
        vb: VarBuilder,
    ) -> Result<Self> {
        Ok(Self {
            encoder: ConformerEncoder::new(cfg, vb.pp("encoder"))?,
            predictor: RnntPredictor::new(
                cfg,
                vb.pp("decoder").pp("prediction"),
            )?,
            joint: RnntJoint::new(cfg, vb.pp("joint"))?,
        })
    }
}
