// Copyright (c) 2026 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

syntax = "proto3";

package recipes.brave.gerrit.refresh_mirrors;

message InputProperties {
  // Gerrit SSH user the script authenticates as.
  string gerrit_user = 1;

  // Chromium ref (tag or branch) to sync before mirroring the git cache;
  // defaults to "main" when empty.
  string chromium_ref = 2;
}

