# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/components/brave_wallet/common/buildflags/buildflags.gni")

if (enable_snaps) {
  source_set("tar_decompressor") {
    sources = [
      "snap_installer_checksum_calculator.cc",
      "snap_installer_checksum_calculator.h",
      "snap_installer_tar_decompressor.cc",
      "snap_installer_tar_decompressor.h",
      "snap_tar_utils.cc",
      "snap_tar_utils.h",
    ]

    deps = [
      "//base",
      "//crypto",
      "//third_party/zlib/google:compression_utils",
    ]
  }
}
