# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Give ChromeMainDelegate a BraveContentClient

      Brave subclasses ChromeContentClient as BraveContentClient, so the
      content client member should be ours instead of upstream's.
    rename_class:
      class_name: ChromeContentClient
      rename: BraveContentClient
