/* Copyright (c) 2023 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_COMPONENTS_BRAVE_ADS_CORE_INTERNAL_ACCOUNT_UTILITY_REDEEM_CONFIRMATION_REWARD_URL_REQUEST_BUILDERS_CREATE_REWARD_CONFIRMATION_URL_REQUEST_BUILDER_TEST_CONSTANTS_H_
#define BRAVE_COMPONENTS_BRAVE_ADS_CORE_INTERNAL_ACCOUNT_UTILITY_REDEEM_CONFIRMATION_REWARD_URL_REQUEST_BUILDERS_CREATE_REWARD_CONFIRMATION_URL_REQUEST_BUILDER_TEST_CONSTANTS_H_

namespace brave_ads::test {

inline constexpr char kCredentialBase64Url[] =
    R"(eyJzaWduYXR1cmUiOiJkaXZoV2dkM2w0TVpZeG9NV1VwL096RnRnc1VBdXlxcEo4R0J5emp2TFBFWkMzUGo3alhucWFXUmVWbU83cU5FNzNkWThaSk5ZQVBCaTZFV2pGMWpFZz09IiwidCI6Ii9tZlRBQWpIcldtQWxMaUVrdGJxTlMvZHhvTVZkbnoxZXNvVnBsUVVzN3lHL2FwQXEySzZPZVNUNmxCVEtGSm1PcTdyVjhRYlkvREYySEZSTWN6L0pRPT0ifQ==)";

}  // namespace brave_ads::test

#endif  // BRAVE_COMPONENTS_BRAVE_ADS_CORE_INTERNAL_ACCOUNT_UTILITY_REDEEM_CONFIRMATION_REWARD_URL_REQUEST_BUILDERS_CREATE_REWARD_CONFIRMATION_URL_REQUEST_BUILDER_TEST_CONSTANTS_H_
