/* Copyright (c) 2023 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#include "brave/components/ai_chat/core/browser/constants.h"
#include "base/strings/strcat.h"

namespace ai_chat {

base::span<const webui::LocalizedString> GetLocalizedStrings() {
  constexpr webui::LocalizedString kLocalizedStrings[] = {
      {"siteTitle", IDS_CHAT_UI_TITLE},
      {"summarizeFailedLabel", IDS_CHAT_UI_SUMMARIZE_FAILED_LABEL},
      {"acceptButtonLabel", IDS_CHAT_UI_ACCEPT_BUTTON_LABEL},
      {"summarizeButtonLabel", IDS_CHAT_UI_SUMMARIZE_BUTTON_LABEL},
      {"aboutTitle", IDS_CHAT_UI_ABOUT_TITLE},
      {"aboutDescription", IDS_CHAT_UI_ABOUT_DESCRIPTION},
      {"aboutDescription_2", IDS_CHAT_UI_ABOUT_DESCRIPTION_2},
      {"aboutDescription_3", IDS_CHAT_UI_ABOUT_DESCRIPTION_3},
      {"placeholderLabel", IDS_CHAT_UI_PLACEHOLDER_LABEL},
      {"pageContentWarning", IDS_CHAT_UI_PAGE_CONTENT_WARNING},
      {"errorNetworkLabel", IDS_CHAT_UI_ERROR_NETWORK},
      {"errorRateLimit", IDS_CHAT_UI_ERROR_RATE_LIMIT},
      {"retryButtonLabel", IDS_CHAT_UI_RETRY_BUTTON_LABEL},
      {"introMessage-chat-basic", IDS_CHAT_UI_INTRO_MESSAGE_CHAT_BASIC},
      {"introMessage-chat-leo-expanded",
       IDS_CHAT_UI_INTRO_MESSAGE_CHAT_LEO_EXPANDED},
      {"introMessage-chat-claude-instant",
       IDS_CHAT_UI_INTRO_MESSAGE_CHAT_LEO_CLAUDE_INSTANT},
      {"modelNameSyntax", IDS_CHAT_UI_MODEL_NAME_SYNTAX},
      {"modelFreemiumLabelNonPremium",
       IDS_CHAT_UI_MODEL_FREEMIUM_LABEL_NON_PREMIUM},
      {"modelFreemiumLabelPremium", IDS_CHAT_UI_MODEL_FREEMIUM_LABEL_PREMIUM},
      {"modelCategory-chat", IDS_CHAT_UI_MODEL_CATEGORY_CHAT},
      {"menuNewChat", IDS_CHAT_UI_MENU_NEW_CHAT},
      {"menuGoPremium", IDS_CHAT_UI_MENU_GO_PREMIUM},
      {"menuManageSubscription", IDS_CHAT_UI_MENU_MANAGE_SUBSCRIPTION},
      {"menuSettings", IDS_CHAT_UI_MENU_SETTINGS},
      {"menuTitleModels", IDS_CHAT_UI_MENU_TITLE_MODELS},
      {"suggestQuestionsLabel", IDS_CHAT_UI_SUGGEST_QUESTIONS_LABEL},
      {"upgradeButtonLabel", IDS_CHAT_UI_UPGRADE_BUTTON_LABEL},
      {"rateLimitReachedTitle", IDS_CHAT_UI_RATE_LIMIT_REACHED_TITLE},
      {"rateLimitReachedDesc", IDS_CHAT_UI_RATE_LIMIT_REACHED_DESC},
      {"premiumFeature_1", IDS_CHAT_UI_PREMIUM_FEATURE_1},
      {"premiumFeature_2", IDS_CHAT_UI_PREMIUM_FEATURE_2},
      {"premiumFeature_3", IDS_CHAT_UI_PREMIUM_FEATURE_3},
      {"premiumFeature_4", IDS_CHAT_UI_PREMIUM_FEATURE_4},
      {"premiumFeature_1_desc", IDS_CHAT_UI_PREMIUM_FEATURE_1_DESC},
      {"premiumFeature_2_desc", IDS_CHAT_UI_PREMIUM_FEATURE_2_DESC},
      {"premiumFeature_3_desc", IDS_CHAT_UI_PREMIUM_FEATURE_3_DESC},
      {"premiumFeature_4_desc", IDS_CHAT_UI_PREMIUM_FEATURE_4_DESC},
      {"premiumLabel", IDS_CHAT_UI_PREMIUM_LABEL},
      {"premiumPricing", IDS_CHAT_UI_PREMIUM_PRICING},
      {"switchToBasicModelButtonLabel",
       IDS_CHAT_UI_SWITCH_TO_BASIC_MODEL_BUTTON_LABEL},
      {"dismissButtonLabel", IDS_CHAT_UI_DISMISS_BUTTON_LABEL},
      {"unlockPremiumTitle", IDS_CHAT_UI_UNLOCK_PREMIUM_TITLE},
      {"premiumRefreshWarningDescription",
       IDS_CHAT_UI_PREMIUM_REFRESH_WARNING_DESCRIPTION},
      {"premiumRefreshWarningAction",
       IDS_CHAT_UI_PREMIUM_REFRESH_WARNING_ACTION},
      {"feedbackSent", IDS_CHAT_UI_FEEDBACK_SENT},
      {"answerDisliked", IDS_CHAT_UI_ANSWER_DISLIKED},
      {"answerLiked", IDS_CHAT_UI_ANSWER_LIKED},
      {"addFeedbackButtonLabel", IDS_CHAT_UI_ADD_FEEDBACK_BUTTON_LABEL},
      {"copyButtonLabel", IDS_CHAT_UI_COPY_BUTTON_LABEL},
      {"likeAnswerButtonLabel", IDS_CHAT_UI_LIKE_ANSWER_BUTTON_LABEL},
      {"dislikeAnswerButtonLabel", IDS_CHAT_UI_DISLIKE_ANSWER_BUTTON_LABEL},
      {"provideFeedbackTitle", IDS_CHAT_UI_PROVIDE_FEEDBACK_TITLE},
      {"selectFeedbackTopic", IDS_CHAT_UI_SELECT_FEEDBACK_TOPIC},
      {"feedbackCategoryLabel", IDS_CHAT_UI_FEEDBACK_CATEGORY_LABEL},
      {"feedbackDescriptionLabel", IDS_CHAT_UI_FEEDBACK_DESCRIPTION_LABEL},
      {"feedbackPremiumNote", IDS_CHAT_UI_FEEDBACK_PREMIUM_NOTE},
      {"submitButtonLabel", IDS_CHAT_UI_SUBMIT_BUTTON_LABEL},
      {"cancelButtonLabel", IDS_CHAT_UI_CANCEL_BUTTON_LABEL},
      {"optionNotHelpful", IDS_CHAT_UI_OPTION_NOT_HELPFUL},
      {"optionIncorrect", IDS_CHAT_UI_OPTION_INCORRECT},
      {"optionUnsafeHarmful", IDS_CHAT_UI_OPTION_UNSAFE_HARMFUL},
      {"optionOther", IDS_CHAT_UI_OPTION_OTHER},
      {"feedbackError", IDS_CHAT_UI_FEEDBACK_SUBMIT_ERROR},
      {"ratingError", IDS_CHAT_UI_RATING_ERROR},
      {"braveLeoModelSubtitle-chat-basic", IDS_CHAT_UI_CHAT_BASIC_SUBTITLE},
      {"braveLeoModelSubtitle-chat-leo-expanded",
       IDS_CHAT_UI_CHAT_LEO_EXPANDED_SUBTITLE},
      {"braveLeoModelSubtitle-chat-claude-instant",
       IDS_CHAT_UI_CHAT_CLAUDE_INSTANT_SUBTITLE},
      {"clearChatButtonLabel", IDS_CHAT_UI_CLEAR_CHAT_BUTTON_LABEL},
      {"sendChatButtonLabel", IDS_CHAT_UI_SEND_CHAT_BUTTON_LABEL},
      {"errorContextLimitReaching", IDS_CHAT_UI_ERROR_CONTEXT_LIMIT_REACHING},
      {"gotItButtonLabel", IDS_CHAT_UI_GOT_IT_BUTTON_LABEL},
      {"pageContentTooLongWarning", IDS_CHAT_UI_PAGE_CONTENT_TOO_LONG_WARNING},
      {"errorConversationEnd", IDS_CHAT_UI_CONVERSATION_END_ERROR},
      {"leoSettingsTooltipLabel", IDS_CHAT_UI_LEO_SETTINGS_TOOLTIP_LABEL},
      {"summarizePageButtonLabel", IDS_CHAT_UI_SUMMARIZE_PAGE},
      {"welcomeGuideTitle", IDS_CHAT_UI_WELCOME_GUIDE_TITLE},
      {"welcomeGuideSubtitle", IDS_CHAT_UI_WELCOME_GUIDE_SUBTITLE},
      {"welcomeGuideSiteHelpCardTitle",
       IDS_CHAT_UI_WELCOME_GUIDE_SITE_HELP_CARD_TITLE},
      {"welcomeGuideSiteHelpCardDesc",
       IDS_CHAT_UI_WELCOME_GUIDE_SITE_HELP_CARD_DESC},
      {"welcomeGuideSiteHelpCardDescWithAction",
       IDS_CHAT_UI_WELCOME_GUIDE_SITE_HELP_CARD_WITH_ACTION},
      {"welcomeGuideShatCardTitle", IDS_CHAT_UI_WELCOME_GUIDE_CHAT_CARD_TITLE},
      {"welcomeGuideShatCardDesc", IDS_CHAT_UI_WELCOME_GUIDE_CHAT_CARD_DESC},
      {"privacyTitle", IDS_CHAT_UI_PRIVACY_TITLE},
      {"contextToggleLabel", IDS_CHAT_UI_CONTEXT_TOGGLE_LABEL},
      {"contextToggleTooltipInfo", IDS_CHAT_UI_CONTEXT_TOGGLE_TOOLTIP_INFO},
      {"subscriptionPolicyInfo", IDS_CHAT_UI_SUBSCRIPTION_POLICY_INFO}};

  return kLocalizedStrings;
}

}  // namespace ai_chat
