[package]
name = "zcash"
version = "1.0.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
cxx = { version = "1.0" }
orchard = { version = "0.7.1",  default-features = false }

[lib]
name = "zcash"
path = "lib.rs"
crate-type = ["rlib"]
