#!/usr/bin/env vpython3
# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
"""End-to-end tests for `brockit.py lift`.

Where `brockit_test.py` exercises the individual pieces of the lift in
isolation, these tests drive the command the way a user does: `brockit.main()`
is called with an argument list, and everything from argument parsing to the
exit code, the commits left in the branch, and the output printed to the
terminal is asserted on.

The sandbox is genuine. `LiftEnvironment` stands up a fake Chromium checkout
with brave inside it (`FakeChromiumRepo`), real Chromium release tags, real
patch files generated by real `git diff`, and a branch with a real upstream.
Every git command the lift runs -- the version commit, the `--3way` applies,
the fixups, the resets -- runs against that checkout for real. Only the things
a fake checkout cannot serve are emulated (see `test/fake_terminal.py`): the
`npm run` build commands, which are emulated over the same fake repositories,
the `gh` CLI, and the `vpython3` helper scripts.

Consequently a patch conflicts here because git could not merge it, a patch is
reported as deleted because its source is really gone from the tree at the
target tag, and a rename is reported because git's rename detection found it.
"""

from __future__ import annotations

from contextlib import contextmanager, redirect_stderr
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
import io
import os
import re
import shutil
import subprocess
import sys
import unittest

from unittest.mock import MagicMock, patch

import brockit
import plaster
import terminal
import toolchain

from test.fake_chromium_repo import (DEFAULT_BRANCH, FakeChromiumRepo,
                                     GNRT_VERSION_STAMP, L10N_VERSION_STAMP)
from test.fake_gh import FakeGh, ISSUE_URL
from test.fake_terminal import (CHROMIUM_REBASE_L10N, ConsoleCapture,
                                FakeTerminal, GNRT, INIT, PLASTER,
                                UPDATE_PATCHES)

# The Chromium version brave sits at before every lift in this file.
BASE_VERSION = '134.0.7035.0'

# A target in the same major (a minor bump), one in the next major, and a minor
# bump on top of that major.
MINOR_TARGET = '134.0.7038.2'
MAJOR_TARGET = '135.0.7037.1'
MAJOR_FOLLOW_UP = '135.0.7040.0'

# The branch major lifts are required to run on, and the one the fixture puts
# the fake brave repo on.
MAJOR_BRANCH = 'cr135'

# The Chromium sources brave patches in the fixture. `FOO` and `BAR` live in
# `src/`, `BAZ` in the `v8` dependency, so that patches spanning more than one
# repository are covered.
FOO = 'chrome/browser/foo.cc'
BAR = 'chrome/common/bar.cc'
BAZ = 'src/baz.cc'
V8 = 'v8'

# The patch files brave carries for the sources above.
FOO_PATCH = 'patches/chrome-browser-foo.cc.patch'
BAR_PATCH = 'patches/chrome-common-bar.cc.patch'
BAZ_PATCH = 'patches/v8/src-baz.cc.patch'


def _native(path: str) -> str:
    """`path` rendered the way brockit prints a `Patchfile.path`/`.source`:
    as a real `Path`, so separators match the host platform.

    Unlike git-plumbing output (always '/') or the `.as_posix()`-normalised
    continuation-file records, these console lines come from f-string'ing a
    `Path` object directly, which is backslash-separated on Windows.
    """
    return str(Path(path))

# The line each source carries the symbol brave rewrites on, and the upstream
# and brave spellings of that symbol. A patch generated from a change on line 2
# has a hunk covering lines 1 to 5, which is what makes the upstream edits below
# land inside or outside a patch's context.
PATCHED_LINE = 2
UPSTREAM_SYMBOL = 'ChromeThing'
BRAVE_SYMBOL = 'BraveThing'

# An upstream edit on this line touches a patch's context without touching the
# patched line itself: `git apply` then fails and `git apply --3way` merges
# cleanly, which is the ordinary "conflict-resolved patches" case.
CONTEXT_LINE = 4

# An upstream edit this far down is outside every patch context, so the patch
# still applies during `init`.
UNRELATED_LINE = 12

# How many lines each fake source has.
SOURCE_LINES = 20

# Brave files the lift regenerates and commits: the strings, the `gnrt` output,
# and the pinslist timestamp that rides along with the version bump.
# One of each extension: `_save_rebased_l10n` stages all three at once, and git
# fails the whole command when any of the pathspecs matches nothing.
L10N_FILES = ('app/brave_strings.grd', 'app/brave_strings_part.grdp',
              'app/resources/brave_strings_fr.xtb')
GNRT_FILE = 'third_party/rust/chromium_crates_io/BUILD.gn'

# The name of the continuation file a paused lift leaves in the brave root.
VERSION_UPGRADE_NAME = '.version_upgrade'

# The plaster file for `FOO`, used by the tests covering apply-fixed patches.
FOO_PLASTER = f'rewrite/{FOO}.yaml'
FOO_PLASTER_BODY = """substitutions:
  - description: Rewrite the thing brave owns
    regex:
      re_pattern: %s
      replace: %s
""" % (UPSTREAM_SYMBOL, BRAVE_SYMBOL)


def _source_body(name: str) -> str:
    """The upstream contents of a fake Chromium source.

    Line `PATCHED_LINE` carries the symbol brave rewrites; every other line is
    filler that gives patches enough context to be interesting.
    """
    lines = [
        f'// {name} line {number}' for number in range(1, SOURCE_LINES + 1)
    ]
    lines[PATCHED_LINE - 1] = f'  {UPSTREAM_SYMBOL} thing;  // {name}'
    return ''.join(f'{line}\n' for line in lines)


def log_link(from_version: str, to_version: str) -> str:
    """The Googlesource log link brockit prints for a version range."""
    return ('https://chromium.googlesource.com/chromium/src/+log/'
            f'{from_version}..{to_version}?pretty=fuller&n=10000')


def _with_line(body: str, line: int, text: str) -> str:
    """`body` with `line` (1-based) replaced by `text`."""
    lines = body.splitlines(keepends=True)
    lines[line - 1] = f'{text}\n'
    return ''.join(lines)


@dataclass(frozen=True)
class LiftRun:
    """The outcome of one `brockit lift` invocation."""

    # The process exit code `main()` produced (2 for a usage error).
    exit_code: int

    # Everything the run printed to the rich console.
    output: str

    # Everything the run wrote to stderr (argparse usage errors).
    stderr: str


class _AdvancingClock:
    """A `datetime` stand-in whose `now()` moves a minute forward each call.

    The pinslist timestamp is stamped in whole seconds, and the lift treats a
    stamp that did not change as a failure. Two lifts inside the same second
    only ever happen in a test, and this keeps them apart.
    """

    def __init__(self) -> None:
        self._elapsed = timedelta()

    def now(self) -> datetime:
        """The current time, a minute later on every call."""
        self._elapsed += timedelta(minutes=1)
        return datetime.now() + self._elapsed

    @staticmethod
    def fromtimestamp(timestamp: float) -> datetime:
        """Delegates to the real `datetime`."""
        return datetime.fromtimestamp(timestamp)


class _Upstream:
    """Commits Chromium-side changes while building a release.

    Handed out by `LiftEnvironment.upstream_release`. Each method commits on its
    own so that every change has a culprit commit brockit can attribute a
    deleted or renamed source to.
    """

    def __init__(self, repo: FakeChromiumRepo) -> None:
        self._repo = repo

    def _repo_path(self, repo: str) -> Path:
        return self._repo.chromium / repo

    def edit(self,
             source: str,
             *,
             line: int,
             text: str,
             repo: str = '') -> str:
        """Rewrites one line of an existing source and commits it."""
        repo_path = self._repo_path(repo)
        body = (repo_path / source).read_bytes().decode('utf-8')
        self._repo.write_and_stage_file(source, _with_line(body, line, text),
                                        repo_path)
        return self._repo.commit(f'Upstream change to {source}', repo_path)

    def write(self, source: str, content: str, repo: str = '') -> str:
        """Writes a source wholesale (new or existing) and commits it."""
        repo_path = self._repo_path(repo)
        self._repo.write_and_stage_file(source, content, repo_path)
        return self._repo.commit(f'Upstream change to {source}', repo_path)

    def delete(self, source: str, repo: str = '') -> str:
        """Deletes a source and commits the deletion."""
        repo_path = self._repo_path(repo)
        self._repo.delete_file(source, repo_path)
        return self._repo.commit(f'Remove {source}', repo_path)

    def rename(self, source: str, new_source: str, repo: str = '') -> str:
        """Renames a source and commits the rename."""
        repo_path = self._repo_path(repo)
        (repo_path / new_source).parent.mkdir(parents=True, exist_ok=True)
        # pylint: disable=protected-access
        self._repo._run_git_command(['mv', source, new_source], repo_path)
        return self._repo.commit(f'Rename {source} to {new_source}', repo_path)


class LiftEnvironment:
    """A sandbox for driving `brockit lift` end to end.

    The fixture starts from the state a lift starts from in practice:

    * `src/` is synced to `BASE_VERSION` (a real tag) with brave's patches
      applied to the working tree, and the `v8` dependency alongside it,
    * brave is on the `cr135` branch tracking `origin/master`, holding
      `package.json` at `BASE_VERSION`, the pinslist timestamp file, the l10n
      files, the `gnrt` output, and the patch files for every patched source.

    From there a test describes what Chromium did in the meantime through
    `upstream_release`, and runs the command with `run_lift`.
    """

    def __init__(self,
                 *,
                 branch: str = MAJOR_BRANCH,
                 upstream_files: dict[str, str] | None = None) -> None:
        # Declared up front so `cleanup` can run after a half-built fixture:
        # `FakeChromiumRepo.setup` changes the current directory, so a fixture
        # that fails half way through has to be torn down or every test after
        # it runs from a directory that no longer exists.
        self.repo = FakeChromiumRepo()
        self.baseline_commit = ''
        self.console: ConsoleCapture | None = None
        self.terminal: FakeTerminal | None = None
        self.gh = FakeGh()
        self._vscode_patcher = None
        self.vscode = None
        self._clock_patcher = None
        self._saved_upgrade_file = brockit.VERSION_UPGRADE_FILE

        try:
            self._build(branch, upstream_files or {})
        except Exception:
            self.cleanup()
            raise

    def _build(self, branch: str, upstream_files: dict[str, str]) -> None:
        """Builds the checkout and installs the doubles."""
        self.repo.setup()
        self.repo.add_dep(V8)

        self._build_chromium_baseline(upstream_files)
        self._build_brave_baseline(branch)

        # The brave commit the fixture leaves behind, so a test can ask for the
        # commits a lift added on top of it.
        self.baseline_commit = self.head()

        # Doubles: git stays real, and everything else is emulated or captured.
        self.console = ConsoleCapture().install()
        self.terminal = FakeTerminal(self.repo, gh=self.gh).install()

        # Files needing attention are handed to the editor over the VS Code IPC
        # socket, which must never be talked to from a test.
        self._vscode_patcher = patch.object(brockit, 'VsCodeIpcConnection')
        self.vscode = self._vscode_patcher.start()

        # Successive lifts in one test would otherwise stamp the pinslist file
        # with the same second.
        self._clock_patcher = patch.object(brockit, 'datetime',
                                           _AdvancingClock())
        self._clock_patcher.start()

        # The continuation file is resolved against the brave root, which in the
        # fake checkout is the fake brave repo. It is reset here rather than
        # relied upon so this fixture is unaffected by any other test module
        # having overwritten the module global.
        brockit.VERSION_UPGRADE_FILE = (brockit.repository.brave.root /
                                        VERSION_UPGRADE_NAME)

    def cleanup(self) -> None:
        """Uninstalls every double and removes the fake checkout."""
        brockit.VERSION_UPGRADE_FILE = self._saved_upgrade_file
        if self._clock_patcher is not None:
            self._clock_patcher.stop()
            self._clock_patcher = None
        if self._vscode_patcher is not None:
            self._vscode_patcher.stop()
            self._vscode_patcher = None
        if self.terminal is not None:
            self.terminal.uninstall()
            self.terminal = None
        if self.console is not None:
            self.console.uninstall()
            self.console = None
        self.repo.cleanup()

    # -- fixture ------------------------------------------------------------

    def _build_chromium_baseline(self, upstream_files: dict[str, str]) -> None:
        """Commits the patched sources and tags `BASE_VERSION`.

        Args:
            upstream_files: Extra Chromium files (path to contents) to commit
                into the base release, for tests that need Chromium to carry
                something specific -- e.g. a toolchain pin.
        """
        for source in (FOO, BAR):
            self.repo.write_and_stage_file(source, _source_body(source),
                                           self.repo.chromium)
        for path, contents in upstream_files.items():
            self.repo.write_and_stage_file(path, contents, self.repo.chromium)
        self.repo.commit('Add sources', self.repo.chromium)
        self.repo.write_and_stage_file(BAZ, _source_body(BAZ),
                                       self.repo.chromium / V8)
        self.repo.commit('Add v8 sources', self.repo.chromium / V8)
        self.repo.add_tag(BASE_VERSION)

    def _build_brave_baseline(self, branch: str) -> None:
        """Sets brave up on `branch`, with patches for every patched source."""
        brave = self.repo.brave
        self.repo.update_brave_version(BASE_VERSION)

        # The real pinslist file is used so the block brockit rewrites is the
        # one that ships.
        pinslist = Path(brockit.PINSLIST_TIMESTAMP_FILE)
        (brave / pinslist).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(
            Path(__file__).resolve().parents[2] / pinslist, brave / pinslist)
        # `.patchinfo` files are generated by the patching machinery and never
        # committed, as in brave-core itself.
        self.repo.write_file('.gitignore', 'patches/**/*.patchinfo\n', brave)
        for relative_path in L10N_FILES:
            self.repo.write_file(relative_path, f'<!-- {relative_path} -->\n',
                                 brave)
        self.repo.write_file(GNRT_FILE, '# generated by gnrt\n', brave)
        self.git('add', '--all')
        self.repo.commit('Add brave files', brave)

        self.repo.create_brave_remote()
        # The remote is a normal checkout with `master` checked out, so it has
        # to be told to accept pushes to it.
        self.git('config',
                 'receive.denyCurrentBranch',
                 'ignore',
                 repo=self.repo.remote / 'brave')
        # The freshly-initialised remote carries an unrelated initial commit, so
        # the push is forced to make `origin/master` this repo's history.
        self.git('push', '--force', 'origin', f'HEAD:{DEFAULT_BRANCH}')
        self.git('checkout', '-b', branch)
        self.git('branch', f'--set-upstream-to=origin/{DEFAULT_BRANCH}')

        self.apply_brave_changes()
        self.repo.commit_patches('Add patches')

    def apply_brave_changes(self) -> None:
        """Applies brave's own change to every patched source in the tree.

        This is the modification the patch files capture: the upstream symbol on
        the patched line rewritten to brave's.
        """
        for source, repo in ((FOO, ''), (BAR, ''), (BAZ, V8)):
            repo_path = self.repo.chromium / repo
            body = (repo_path / source).read_bytes().decode('utf-8')
            self.repo.write_file(source,
                                 body.replace(UPSTREAM_SYMBOL, BRAVE_SYMBOL),
                                 repo_path)

    @contextmanager
    def upstream_release(self, version: str):
        """Builds the Chromium release `version` on top of the current one.

        Inside the block the yielded `_Upstream` commits changes one at a time.
        Leaving the block tags the release and puts the checkout back where a
        lift starts from: synced to the version in brave's `package.json`, with
        brave's patches applied.
        """
        self.repo.sync_chromium()
        yield _Upstream(self.repo)
        self.repo.add_tag(version)
        self.repo.sync_chromium()
        self.repo.run_apply_patches()

    # -- running ------------------------------------------------------------

    def run_lift(self, *args: str) -> LiftRun:
        """Runs `brockit lift` with `args`, as the command line would.

        A usage error (argparse calling `sys.exit`) is reported as exit code 2
        rather than propagating, so those runs read like any other.
        """
        mark = self.console.mark()
        stderr = io.StringIO()
        with patch.object(sys, 'argv', ['brockit.py', 'lift', *args]):
            with redirect_stderr(stderr):
                try:
                    exit_code = brockit.main()
                except SystemExit as e:
                    exit_code = e.code
        return LiftRun(exit_code=exit_code,
                       output=self.console.since(mark),
                       stderr=stderr.getvalue())

    # -- inspection ---------------------------------------------------------

    def git(self, *args: str, repo: Path | None = None) -> str:
        """Runs a git command in the fake brave repo (or `repo`)."""
        # pylint: disable=protected-access
        return self.repo._run_git_command(list(args), repo or self.repo.brave)

    def head(self) -> str:
        """The brave `HEAD` hash."""
        return self.git('rev-parse', 'HEAD')

    def subjects(self, since: str | None = None) -> list[str]:
        """Subjects of the brave commits after `since`, oldest first.

        Defaults to every commit the fixture did not create.
        """
        log = self.git('log', '--reverse', '--pretty=%s',
                       f'{since or self.baseline_commit}..HEAD')
        return log.splitlines()

    def commit_for(self, subject: str) -> str:
        """The hash of the most recent brave commit with `subject`.

        Empty when the branch has no such commit.
        """
        return self.git('log', '-1', '--format=%H', '--fixed-strings',
                        f'--grep={subject}')

    def files_in(self, commit: str = 'HEAD') -> list[str]:
        """The paths a brave commit touches."""
        return self.git('show', '--name-only', '--pretty=format:',
                        commit).split()

    def source_path(self, source: str, repo: str = '') -> str:
        """The path brockit prints for a Chromium source.

        brockit expresses Chromium paths relative to the directory it was
        invoked from, so the expectation is computed the same way rather than
        being hardcoded.
        """
        return os.path.relpath(self.repo.chromium / repo / source, Path.cwd())

    def brave_path(self, relative_path: str) -> str:
        """The path brockit prints for a file in brave, e.g. a plaster file."""
        return os.path.relpath(self.repo.brave / relative_path, Path.cwd())

    def read_source(self, source: str, repo: str = '') -> str:
        """The working-tree contents of a Chromium source."""
        return (self.repo.chromium / repo /
                source).read_bytes().decode('utf-8')

    def upstream_source(self, source: str, repo: str = '') -> str:
        """The contents of a Chromium source at the synced commit."""
        return self.git('show',
                        f'HEAD:{source}',
                        repo=self.repo.chromium / repo)

    def resolve_conflict(self,
                         source: str,
                         repo: str = '',
                         symbol: str = BRAVE_SYMBOL) -> None:
        """Resolves a conflicted source the way the user is expected to.

        Rewrites the file as the upstream version of it carrying brave's change,
        which is what editing the conflict markers out by hand amounts to.

        Args:
            source: The Chromium source to resolve.
            repo: The repository the source belongs to.
            symbol: The spelling brave's change gives the upstream symbol. Pass
                it when a dev-cycle commit in the branch has moved it on.
        """
        body = self.upstream_source(source,
                                    repo).replace(UPSTREAM_SYMBOL, symbol)
        self.repo.write_file(source, body, self.repo.chromium / repo)

    def continuation(self, target: str) -> brockit.ContinuationFile:
        """The continuation file left in the tree for the `target` lift."""
        return brockit.ContinuationFile.load(
            target_version=brockit.Version(target))

    def has_continuation(self) -> bool:
        """Whether a continuation file is left in the tree."""
        return brockit.VERSION_UPGRADE_FILE.exists()

    def vscode_files(self) -> list[str]:
        """The files handed to the editor, as posix strings."""
        calls = self.vscode.return_value.open_file.call_args_list
        return [Path(f).as_posix() for call in calls for f in call.args[0]]

    def write_plaster(self, relative_path: str, body: str) -> None:
        """Writes a plaster file into brave's `rewrite/` directory."""
        self.repo.write_file(relative_path, body, self.repo.brave)

    def add_plaster_for_foo(self, body: str = FOO_PLASTER_BODY) -> None:
        """Makes `FOO`'s patch plaster-managed, and commits that.

        The patch is regenerated by plaster itself rather than by
        `update_patches`, which is the invariant plaster-managed patches hold in
        brave-core: the patch on disk is exactly what a plaster run produces.
        """
        self.write_plaster(FOO_PLASTER, body)
        plaster.PlasterFile(plaster.PLASTER_FILES_PATH / f'{FOO}.yaml').apply()
        self.git('add', '--all', 'rewrite', 'patches')
        self.repo.commit('Add plaster for foo.cc', self.repo.brave)

    def reapply_plaster_for_foo(self, body: str) -> None:
        """Rewrites `FOO`'s plaster and reapplies it, as the user would.

        This is the fix for a plaster that stopped matching its source: the
        plaster is corrected and re-run so the source and the patch are
        regenerated from it.
        """
        self.write_plaster(FOO_PLASTER, body)
        plaster.PlasterFile(plaster.PLASTER_FILES_PATH / f'{FOO}.yaml').apply()

    def break_patch(self, patch_path: str) -> None:
        """Rewrites a committed patch so that nothing can apply it.

        The blob hashes are replaced with ones the repository does not have, and
        the first context line is mangled, so neither a plain apply nor a 3-way
        merge has anything to work with -- which is what brockit reports as a
        broken patch.
        """
        path = self.repo.brave / patch_path
        body = path.read_bytes().decode('utf-8')
        body = re.sub(r'index [0-9a-f]+\.\.[0-9a-f]+',
                      f'index {"1" * 40}..{"2" * 40}', body)
        body = re.sub(r'(?m)^ .*$',
                      ' // a line that is not in the source',
                      body,
                      count=1)
        path.write_text(body, encoding='utf-8', newline='')
        self.git('add', patch_path)
        self.repo.commit(f'Break {patch_path}', self.repo.brave)

    def stage_file(self, relative_path: str, content: str) -> None:
        """Leaves a staged change in brave, as an interrupted edit would."""
        self.repo.write_and_stage_file(relative_path, content, self.repo.brave)

    def commit_patch_changes(self, message: str) -> str:
        """Commits the patch files as they stand, as the user is asked to.

        This is what brockit expects for patch additions and deletions: the user
        regenerates the patches and commits them with a message of their own.
        """
        return self.repo.commit_patches(message)


class LiftTestCase(unittest.TestCase):
    """Base for the lift tests: one sandbox per test, plus assertions."""

    # The branch the fake brave repo is put on. Named after the major being
    # lifted to, which is what a major lift requires.
    BRANCH = MAJOR_BRANCH

    # Extra Chromium files the base release carries, for tests that need
    # upstream to hold something specific.
    UPSTREAM_FILES: dict[str, str] = {}

    def setUp(self) -> None:
        self.env = LiftEnvironment(branch=self.BRANCH,
                                   upstream_files=self.UPSTREAM_FILES)
        self.addCleanup(self.env.cleanup)

    # -- assertions ---------------------------------------------------------

    @staticmethod
    def normalized(run: LiftRun) -> str:
        """The run's output with commit hashes replaced by a placeholder."""
        return re.sub(r'\b[0-9a-f]{7,40}\b', '<hash>', run.output)

    def assert_output_has(self, run: LiftRun, *lines: str) -> None:
        """Asserts each of `lines` appears in the run's output."""
        for line in lines:
            self.assertIn(line, run.output,
                          f'missing from the output:\n{run.output}')

    def assert_output_lacks(self, run: LiftRun, *lines: str) -> None:
        """Asserts none of `lines` appears in the run's output."""
        for line in lines:
            self.assertNotIn(line, run.output,
                             f'unexpectedly in the output:\n{run.output}')

    def assert_succeeded(self, run: LiftRun) -> None:
        """Asserts the run reported success and was framed by the banners."""
        self.assertEqual(run.exit_code, 0, f'run failed:\n{run.output}')
        self.assert_output_has(run, '🚀 Brockit!', '💥 Done!')

    def assert_failed(self, run: LiftRun, *lines: str) -> None:
        """Asserts the run failed, printing `lines`, and never said it was
        done."""
        self.assertEqual(run.exit_code, 1, f'run succeeded:\n{run.output}')
        self.assert_output_has(run, *lines)
        self.assert_output_lacks(run, '💥 Done!')

    def assert_commit_subjects(self, expected: list[str]) -> None:
        """Asserts the commits added on top of the fixture."""
        self.assertEqual(self.env.subjects(), expected)


class LiftCleanRunTest(LiftTestCase):
    """A lift where every patch still applies."""

    def test_minor_lift_commits_every_stage(self):
        with self.env.upstream_release(MINOR_TARGET) as upstream:
            # An edit this far from the patched line leaves every patch
            # applying cleanly.
            upstream.edit(FOO, line=UNRELATED_LINE, text='// upstream churn')

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_succeeded(run)
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MINOR_TARGET}.',
            f'Update patches from Chromium {BASE_VERSION} to Chromium '
            f'{MINOR_TARGET}.',
            f'Updated strings for Chromium {MINOR_TARGET}.',
            f'`gnrt` run for Chromium {MINOR_TARGET}.',
        ])

    def test_version_commit_carries_package_and_pinslist(self):
        with self.env.upstream_release(MINOR_TARGET):
            pass

        self.env.run_lift(f'--to={MINOR_TARGET}')

        version_commit = self.env.commit_for(
            f'Update from Chromium {BASE_VERSION} to Chromium {MINOR_TARGET}.')
        self.assertTrue(version_commit)
        self.assertEqual(
            sorted(self.env.files_in(version_commit)),
            sorted(['package.json', brockit.PINSLIST_TIMESTAMP_FILE]))
        # The tag brave is pinned to is the one that was lifted to, both in the
        # commit and in the working tree.
        self.assertEqual(self.env.repo.package_version(), MINOR_TARGET)
        self.assertEqual(str(brockit.Version.from_git('HEAD')), MINOR_TARGET)
        # The pinslist timestamp block was rewritten, not just touched.
        self.assertIn(
            '# Last updated:',
            self.env.git(
                'show', f'{version_commit}:{brockit.PINSLIST_TIMESTAMP_FILE}'))

    def test_patches_untouched_upstream_produce_no_update_commit(self):
        """With no upstream change to a patched source, every patch file comes
        out byte-identical, so there is nothing to commit for them."""
        with self.env.upstream_release(MINOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_succeeded(run)
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MINOR_TARGET}.',
            f'Updated strings for Chromium {MINOR_TARGET}.',
            f'`gnrt` run for Chromium {MINOR_TARGET}.',
        ])

    def test_continuation_file_lands_in_the_brave_root(self):
        """The continuation file belongs at the brave root: `--continue` and
        `npm run update_patches` both look for it there, whatever directory
        brockit was invoked from."""
        with self.env.upstream_release(MINOR_TARGET):
            pass

        self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assertEqual(brockit.VERSION_UPGRADE_FILE.resolve(),
                         (self.env.repo.brave /
                          VERSION_UPGRADE_NAME).resolve())
        self.assertTrue((self.env.repo.brave / VERSION_UPGRADE_NAME).exists())

    def test_regenerated_files_land_in_their_own_commits(self):
        with self.env.upstream_release(MINOR_TARGET) as upstream:
            upstream.edit(FOO, line=UNRELATED_LINE, text='// upstream churn')

        self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assertEqual(self.env.files_in('HEAD~2'), [FOO_PATCH])
        self.assertEqual(sorted(self.env.files_in('HEAD~1')),
                         sorted(L10N_FILES))
        self.assertEqual(self.env.files_in('HEAD'), [GNRT_FILE])
        # The regenerated content is the one the emulated commands produced.
        self.assertIn(L10N_VERSION_STAMP.format(version=MINOR_TARGET),
                      self.env.git('show', f'HEAD:{L10N_FILES[0]}'))
        self.assertIn(GNRT_VERSION_STAMP.format(version=MINOR_TARGET),
                      self.env.git('show', f'HEAD:{GNRT_FILE}'))

    def test_lift_leaves_the_checkout_synced_and_patched(self):
        with self.env.upstream_release(MINOR_TARGET) as upstream:
            upstream.edit(FOO, line=UNRELATED_LINE, text='// upstream churn')

        self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assertEqual(self.env.repo.chromium_version(), MINOR_TARGET)
        # Brave's change is in the tree, on top of the upstream churn.
        source = self.env.read_source(FOO)
        self.assertIn(BRAVE_SYMBOL, source)
        self.assertIn('// upstream churn', source)

    def test_an_unrelated_chromium_checkout_is_flagged(self):
        """A checkout synced to neither the branch's version nor the target is
        pointed out before the lift carries on regardless."""
        with self.env.upstream_release(MINOR_TARGET):
            pass
        with self.env.upstream_release(MAJOR_TARGET):
            pass
        self.env.repo.sync_chromium(MINOR_TARGET)

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_succeeded(run)
        self.assert_output_has(
            run, 'seems to be synced to a version entirely unrelated. '
            f'Brave {BASE_VERSION} ➜ Chromium {MINOR_TARGET}')

    def test_major_lift_commits_every_stage(self):
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.edit(FOO, line=UNRELATED_LINE, text='// upstream churn')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_succeeded(run)
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MAJOR_TARGET}.',
            f'Update patches from Chromium {BASE_VERSION} to Chromium '
            f'{MAJOR_TARGET}.',
            f'Updated strings for Chromium {MAJOR_TARGET}.',
            f'`gnrt` run for Chromium {MAJOR_TARGET}.',
        ])

    def test_commands_are_driven_in_order(self):
        with self.env.upstream_release(MINOR_TARGET):
            pass

        self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assertEqual(self.env.terminal.npm_runs(),
                         [INIT, UPDATE_PATCHES, CHROMIUM_REBASE_L10N])
        self.assertTrue(
            self.env.terminal.ran(str(brockit.VPYTHON3_PATH), plaster.__file__,
                                  'check'))
        self.assertTrue(
            self.env.terminal.ran(str(brockit.VPYTHON3_PATH),
                                  './tools/crates/run_gnrt.py', 'vendor'))

    def test_nothing_is_left_dirty_in_brave(self):
        with self.env.upstream_release(MINOR_TARGET) as upstream:
            upstream.edit(FOO, line=UNRELATED_LINE, text='// upstream churn')

        self.env.run_lift(f'--to={MINOR_TARGET}')

        # `.version_upgrade` aside, the branch is clean once a lift finishes.
        status = [
            line
            for line in self.env.git('status', '--porcelain').splitlines()
            if '.version_upgrade' not in line
        ]
        self.assertEqual(status, [])


class LiftOutputRenderingTest(LiftTestCase):
    """What the user sees on a run that goes through."""

    def test_clean_run_renders_the_whole_report(self):
        with self.env.upstream_release(MINOR_TARGET) as upstream:
            upstream.edit(FOO, line=UNRELATED_LINE, text='// upstream churn')

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assertEqual(
            self.normalized(run), '\n'.join([
                '🚀 Brockit!',
                '* Changes since base version: '
                'https://chromium.googlesource.com/chromium/src/+log/'
                f'{BASE_VERSION}..{MINOR_TARGET}?pretty=fuller&n=10000',
                f'* ✔️  <hash> Update from Chromium {BASE_VERSION} to Chromium '
                f'{MINOR_TARGET}.',
                f'* ✔️  <hash> Update patches from Chromium {BASE_VERSION} to '
                f'Chromium {MINOR_TARGET}.',
                f'* ✔️  <hash> Updated strings for Chromium {MINOR_TARGET}.',
                f'* ✔️  <hash> `gnrt` run for Chromium {MINOR_TARGET}.',
                '💥 Done!',
            ]))

    def test_minor_bump_reports_both_diff_links(self):
        """A branch already ahead of its base reports the changes for the bump
        itself as well as the ones since the base version."""
        with self.env.upstream_release(MINOR_TARGET):
            pass
        self.env.run_lift(f'--to={MINOR_TARGET}')
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_succeeded(run)
        self.assert_output_has(
            run,
            f'* Changes for this bump: {log_link(MINOR_TARGET, MAJOR_TARGET)}',
            '* Changes since base version: '
            f'{log_link(BASE_VERSION, MAJOR_TARGET)}')

    def test_first_bump_reports_only_the_base_diff_link(self):
        with self.env.upstream_release(MINOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_output_lacks(run, 'Changes for this bump')

    def test_plaster_check_failure_is_reported_without_failing_the_lift(self):
        with self.env.upstream_release(MINOR_TARGET):
            pass
        self.env.terminal.fail(PLASTER)

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_succeeded(run)
        self.assert_output_has(run,
                               '* ❌ Plaster check. Please investigate it.')

    def test_gnrt_failure_is_reported_without_failing_the_lift(self):
        with self.env.upstream_release(MINOR_TARGET):
            pass
        self.env.terminal.fail(GNRT)

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_succeeded(run)
        self.assert_output_has(run, '* ❌ GNRT rerun. Please investigate it.')
        self.assertEqual(self.env.commit_for('`gnrt` run for Chromium'), '')

    def test_init_failure_unrelated_to_patches_stops_the_lift(self):
        with self.env.upstream_release(MINOR_TARGET):
            pass
        self.env.terminal.fail(INIT, stderr='gclient blew up')

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_failed(run, 'Failures found when running npm run init',
                           'gclient blew up')
        # The version commit is already in, so a restart is what recovers.
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MINOR_TARGET}.'
        ])


class LiftArgumentTest(LiftTestCase):
    """Flag combinations rejected before any work starts."""

    def _assert_usage_error(self, run: LiftRun, message: str) -> None:
        self.assertEqual(run.exit_code, 2)
        self.assertIn(message, run.stderr)
        self.assert_commit_subjects([])

    def test_from_ref_is_rejected_with_continue(self):
        run = self.env.run_lift(f'--to={MINOR_TARGET}', '--continue',
                                '--from-ref=origin/master')
        self._assert_usage_error(
            run, 'Switch --from-ref not supported with --continue.')

    def test_no_conflict_change_requires_continue(self):
        run = self.env.run_lift(f'--to={MINOR_TARGET}', '--no-conflict-change')
        self._assert_usage_error(
            run, '--no-conflict-change can only be used with --continue')

    def test_restart_is_rejected_with_continue(self):
        run = self.env.run_lift(f'--to={MINOR_TARGET}', '--restart',
                                '--continue')
        self._assert_usage_error(run, '--restart does not support --continue')

    def test_ack_advisory_is_rejected_with_continue(self):
        run = self.env.run_lift(f'--to={MINOR_TARGET}', '--ack-advisory',
                                '--continue')
        self._assert_usage_error(run,
                                 '--ack-advisory does not support --continue')

    def test_to_is_required(self):
        run = self.env.run_lift()
        self._assert_usage_error(run,
                                 'the following arguments are required: --to')


class LiftVersionValidationTest(LiftTestCase):
    """Version and reference resolution refusing to run."""

    def test_target_not_higher_than_base_is_rejected(self):
        run = self.env.run_lift(f'--to={BASE_VERSION}')

        self.assert_failed(
            run, f'Target version {BASE_VERSION} is not higher than base '
            f'version {BASE_VERSION}.')
        self.assert_commit_subjects([])

    def test_invalid_from_ref_is_rejected(self):
        run = self.env.run_lift(f'--to={MINOR_TARGET}',
                                '--from-ref=not-a-real-ref')

        self.assert_failed(
            run, 'Value provided to --from-ref is not a valid git ref: '
            'not-a-real-ref')

    def test_missing_upstream_is_rejected(self):
        self.env.git('branch', '--unset-upstream')

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_failed(run, 'Could not determine the upstream branch.')

    def test_lifting_to_the_version_already_in_the_branch_is_rejected(self):
        with self.env.upstream_release(MINOR_TARGET):
            pass
        self.env.run_lift(f'--to={MINOR_TARGET}')

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_failed(
            run, f'This branch is already in {MINOR_TARGET}. (Maybe you meant '
            'to pass --continue?)')

    def test_lifting_to_an_older_version_is_rejected(self):
        with self.env.upstream_release(MINOR_TARGET):
            pass
        with self.env.upstream_release(MAJOR_TARGET):
            pass
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        # The wording reads backwards, but the pair of versions is the point.
        self.assert_failed(
            run, f'Cannot upgrade version from {MINOR_TARGET} to '
            f'{MAJOR_TARGET}')

    def test_from_ref_takes_a_hash(self):
        """An explicit base ref is used in place of the upstream branch."""
        with self.env.upstream_release(MINOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MINOR_TARGET}',
                                f'--from-ref={self.env.baseline_commit}')

        self.assert_succeeded(run)
        self.assert_output_has(run, log_link(BASE_VERSION, MINOR_TARGET))

    def test_previous_label_resolves_the_last_bump(self):
        """`@previous` names the version the branch was on before its last
        bump, which is what a minor bump on top of a lift is based on."""
        with self.env.upstream_release(MINOR_TARGET):
            pass
        self.env.run_lift(f'--to={MINOR_TARGET}')
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--from-ref=@previous')

        self.assert_succeeded(run)
        # The base is the version the previous bump started from.
        self.assert_output_has(
            run, '* Changes since base version: '
            f'{log_link(BASE_VERSION, MAJOR_TARGET)}')

    def test_previous_major_label_resolves_across_the_major_bump(self):
        with self.env.upstream_release(MAJOR_TARGET):
            pass
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        with self.env.upstream_release(MAJOR_FOLLOW_UP):
            pass

        run = self.env.run_lift(f'--to={MAJOR_FOLLOW_UP}',
                                '--from-ref=@previous-major')

        self.assert_succeeded(run)
        self.assert_output_has(
            run, f'* Changes since base version: '
            f'{log_link(BASE_VERSION, MAJOR_FOLLOW_UP)}')


class LiftBranchNameTest(LiftTestCase):
    """Major lifts are pinned to the branch named after the target major."""

    BRANCH = 'a-branch-of-my-own'

    def test_major_lift_requires_the_cr_branch(self):
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_failed(
            run, 'Major version upgrades must be done on a branch named '
            f'"{MAJOR_BRANCH}", but the current branch is "{self.BRANCH}".')
        self.assert_commit_subjects([])

    def test_minor_lift_runs_on_any_branch(self):
        with self.env.upstream_release(MINOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_succeeded(run)


class LiftConflictResolutionTest(LiftTestCase):
    """Patches that need a `--3way` apply, and the continuation that follows."""

    def _release_with_conflict(self) -> None:
        """A release that conflicts with `FOO`'s patch and shifts `BAR`'s.

        `FOO`'s patched line changes upstream, which no merge can resolve. The
        edit to `BAR` lands on a context line of its patch instead, so the patch
        fails to apply but merges cleanly with `--3way`.
        """
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.edit(
                FOO,
                line=PATCHED_LINE,
                text=f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')
            upstream.edit(BAR, line=CONTEXT_LINE, text='// upstream context')

    def test_conflict_stops_the_lift_with_a_report(self):
        self._release_with_conflict()

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(run.exit_code, 1)
        self.assertEqual(
            self.normalized(run), '\n'.join([
                '🚀 Brockit!',
                f'* Changes since base version: '
                f'{log_link(BASE_VERSION, MAJOR_TARGET)}',
                f'* ✔️  <hash> Update from Chromium {BASE_VERSION} to Chromium '
                f'{MAJOR_TARGET}.',
                '* Reapplying patch files with --3way:',
                f'    * {_native(FOO_PATCH)}',
                f'    * {_native(BAR_PATCH)}',
                '* Manually resolve conflicts for (action needed):',
                f'    ✘ {self.env.source_path(FOO)}',
                '👋 (Address all sections with (action needed) above, and then '
                'rerun 🚀Brockit! with --continue)',
            ]))
        # Only the version commit was made: the rest waits for the user.
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MAJOR_TARGET}.'
        ])

    def test_conflict_markers_are_left_in_the_source(self):
        self._release_with_conflict()

        self.env.run_lift(f'--to={MAJOR_TARGET}')

        source = self.env.read_source(FOO)
        self.assertIn('<<<<<<< ours', source)
        self.assertIn(f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak', source)
        self.assertIn(f'  {BRAVE_SYMBOL} thing;', source)
        # The patch that merged cleanly is simply applied.
        self.assertIn(BRAVE_SYMBOL, self.env.read_source(BAR))
        self.assertNotIn('<<<<<<<', self.env.read_source(BAR))

    def test_conflict_is_recorded_in_the_continuation_file(self):
        self._release_with_conflict()

        self.env.run_lift(f'--to={MAJOR_TARGET}')

        continuation = self.env.continuation(MAJOR_TARGET)
        self.assertEqual(str(continuation.working_version), BASE_VERSION)
        self.assertEqual(str(continuation.base_version), BASE_VERSION)
        record = continuation.apply_record
        self.assertEqual([str(path) for path in record.files_with_conflicts],
                         [self.env.source_path(FOO)])
        self.assertEqual(
            sorted(patch.path.as_posix()
                   for patch in record.all_conflict_resolved_patches()),
            sorted([FOO_PATCH, BAR_PATCH]))
        self.assertEqual(record.broken_patches, [])
        self.assertEqual(record.patches_to_deleted_files, [])
        self.assertTrue(record.requires_conflict_resolution())

    def test_conflicted_files_are_opened_in_the_editor(self):
        self._release_with_conflict()

        self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(self.env.vscode_files(),
                         [Path(self.env.source_path(FOO)).as_posix()])

    def test_continue_commits_the_resolved_patches(self):
        self._release_with_conflict()
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.env.resolve_conflict(FOO)
        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_succeeded(run)
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MAJOR_TARGET}.',
            f'Conflict-resolved patches from Chromium {BASE_VERSION} to '
            f'Chromium {MAJOR_TARGET}.',
            f'Updated strings for Chromium {MAJOR_TARGET}.',
            f'`gnrt` run for Chromium {MAJOR_TARGET}.',
        ])
        # Both patches that went through `--3way` are in that commit.
        self.assertEqual(
            sorted(
                self.env.files_in(
                    self.env.commit_for('Conflict-resolved patches'))),
            sorted([FOO_PATCH, BAR_PATCH]))
        # And the continuation file is gone once the lift is through.
        self.assertFalse(self.env.has_continuation())

    def test_resolved_patches_apply_to_the_new_version(self):
        """The committed patches are the resolution, not the conflict: a fresh
        `init` reproduces the resolved tree from them."""
        self._release_with_conflict()
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        self.env.resolve_conflict(FOO)
        self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.env.repo.sync_chromium()
        self.assertEqual(self.env.repo.run_apply_patches(), [])
        self.assertIn(f'  {BRAVE_SYMBOL} thing;  // upstream tweak',
                      self.env.read_source(FOO))

    def test_continue_without_a_continuation_file_is_rejected(self):
        with self.env.upstream_release(MAJOR_TARGET):
            pass
        # A branch already on the target version, but with no lift in progress.
        self.env.repo.update_brave_version(MAJOR_TARGET)

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run,
            'continuation file does not exist. (Are you sure you meant to '
            'pass --continue?)')

    def test_continue_on_a_branch_at_another_version_is_rejected(self):
        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run, 'Running with `--continue` on a branch with a different '
            f'version what the target should be. {MAJOR_TARGET} vs '
            f'{BASE_VERSION}')

    def test_continue_with_chromium_out_of_sync_is_rejected(self):
        self._release_with_conflict()
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        # A checkout left behind at the old version, e.g. a sync that was
        # interrupted or reverted by hand.
        self.env.repo.sync_chromium(BASE_VERSION)

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run, 'To run with --continue the Chromium version has to be in '
            f'Sync with Brave. Brave {MAJOR_TARGET} ➜ Chromium {BASE_VERSION}')

    def test_continue_with_nothing_resolved_is_rejected(self):
        """A continuation is expected to bring resolved patches with it."""
        self._release_with_conflict()
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        # The user regenerated and committed the patches themselves, leaving
        # nothing for the conflict-resolved commit.
        self.env.resolve_conflict(FOO)
        self.env.commit_patch_changes('Update patches by hand')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run,
            'Nothing has been staged to commit conflict-resolved patches. '
            '(Did you mean to pass --no-conflict-change?)')

    def test_continue_with_no_conflict_change_finishes(self):
        self._release_with_conflict()
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        self.env.resolve_conflict(FOO)
        self.env.commit_patch_changes('Update patches by hand')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue',
                                '--no-conflict-change')

        self.assert_succeeded(run)
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MAJOR_TARGET}.',
            'Update patches by hand',
            f'Updated strings for Chromium {MAJOR_TARGET}.',
            f'`gnrt` run for Chromium {MAJOR_TARGET}.',
        ])

    def test_continue_with_staged_files_is_rejected(self):
        self._release_with_conflict()
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        self.env.resolve_conflict(FOO)
        self.env.stage_file('some_file.txt', 'left staged by accident')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run, 'Staged files detected after running update_patches.',
            'some_file.txt')

    def test_continue_with_a_bigger_patch_is_rejected(self):
        """A resolution that adds hunks is a change of its own, and has to be
        submitted with a culprit rather than hidden in the lift."""
        self._release_with_conflict()
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        self.env.resolve_conflict(FOO)
        # A second, unrelated change to the same source, far enough from the
        # patched line to produce a hunk of its own.
        self.env.repo.write_file(
            FOO,
            _with_line(self.env.read_source(FOO), UNRELATED_LINE,
                       '// an extra brave change'), self.env.repo.chromium)

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run,
            'The following modified patches have changes in the number of '
            'hunks, and are expected to be submitted separately as fixes with '
            'Chromium culprits:', f'* {FOO_PATCH}: 1 hunks before, 2 hunks '
            'after')

    def test_conflict_in_a_dependency_is_reported_and_resolved(self):
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.edit(BAZ,
                          line=PATCHED_LINE,
                          text=f'  {UPSTREAM_SYMBOL} thing;  // v8 tweak',
                          repo=V8)

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_output_has(run, f'    * {_native(BAZ_PATCH)}',
                               f'    ✘ {self.env.source_path(BAZ, V8)}')

        self.env.resolve_conflict(BAZ, V8)
        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_succeeded(run)
        self.assertEqual(
            self.env.files_in(
                self.env.commit_for('Conflict-resolved patches')), [BAZ_PATCH])

    def test_init_reset_warning_is_surfaced(self):
        """`init` mixes a warning about failed resets into its own failure
        output, and the lift passes it on before carrying on with the 3-way
        applies."""
        self._release_with_conflict()
        self.env.terminal.init_extra_stderr = (
            'There were some failures during git reset of specific repo paths: '
            f'{FOO}\n')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_output_has(run,
                               'npm run init is failing to reset some paths.',
                               '* Reapplying patch files with --3way:')

    def test_the_index_is_left_clean_after_the_3way_applies(self):
        """A `--3way` apply stages what it manages to merge, and the lift has to
        undo that so the patches it generates next are not affected."""
        self._release_with_conflict()

        self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(
            self.env.git('diff',
                         '--cached',
                         '--name-only',
                         repo=self.env.repo.chromium), '')


class LiftDeletedSourceTest(LiftTestCase):
    """A patched source that upstream removed."""

    def _release_deleting_bar(self) -> None:
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.delete(BAR)

    def test_deleted_source_is_reported_with_its_culprit(self):
        self._release_deleting_bar()

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(run.exit_code, 1)
        self.assert_output_has(
            run, '* Files that cannot be patched anymore (action needed):',
            f'    ✘ {_native(BAR)} (deleted)', f'        Remove {BAR}',
            '👋 (Address all sections with (action needed) above, and then '
            'rerun 🚀Brockit! with --continue)')
        # Nothing is decided for the user: the patch is still there.
        self.assertTrue((self.env.repo.brave / BAR_PATCH).exists())

    def test_deleted_patch_is_recorded_in_the_continuation_file(self):
        self._release_deleting_bar()

        self.env.run_lift(f'--to={MAJOR_TARGET}')

        record = self.env.continuation(MAJOR_TARGET).apply_record
        self.assertEqual([
            patch.path.as_posix() for patch in record.patches_to_deleted_files
        ], [BAR_PATCH])

    def test_continue_before_committing_the_deletion_is_rejected(self):
        self._release_deleting_bar()
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run,
            'Deleted patches detected. These should be committed as their '
            f'own changes:\n{BAR_PATCH}')

    def test_continue_after_committing_the_deletion_finishes(self):
        self._release_deleting_bar()
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        # The user commits the removal on its own, explaining why the patch is
        # not needed anymore.
        self.env.commit_patch_changes(f'Remove patch for deleted {BAR}')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue',
                                '--no-conflict-change')

        self.assert_succeeded(run)
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MAJOR_TARGET}.',
            f'Remove patch for deleted {BAR}',
            f'Updated strings for Chromium {MAJOR_TARGET}.',
            f'`gnrt` run for Chromium {MAJOR_TARGET}.',
        ])
        self.assertFalse((self.env.repo.brave / BAR_PATCH).exists())


class LiftRenamedSourceTest(LiftTestCase):
    """A patched source that upstream renamed."""

    RENAMED = 'chrome/common/renamed_bar.cc'
    RENAMED_PATCH = 'patches/chrome-common-renamed_bar.cc.patch'

    def _release_renaming_bar(self) -> None:
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.rename(BAR, self.RENAMED)

    def test_renamed_source_is_reported_with_its_new_name(self):
        self._release_renaming_bar()

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(run.exit_code, 1)
        self.assert_output_has(
            run, '* Files that cannot be patched anymore (action needed):',
            f'    ✘ {self.env.source_path(BAR)}',
            f'        (renamed to {self.env.source_path(self.RENAMED)})',
            f'        Rename {BAR} to {self.RENAMED}')

    def test_both_ends_of_the_rename_are_opened_in_the_editor(self):
        self._release_renaming_bar()

        self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(self.env.vscode_files(), [
            BAR_PATCH,
            Path(self.env.source_path(self.RENAMED)).as_posix(),
        ])

    def test_a_new_patch_left_untracked_is_rejected(self):
        self._release_renaming_bar()
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        # The user drops the stale patch, then carries brave's change over to
        # the renamed source, but does not commit the patch it produces.
        self.env.commit_patch_changes(f'Drop patch for renamed {BAR}')
        self.env.repo.write_file(
            self.RENAMED,
            self.env.upstream_source(self.RENAMED).replace(
                UPSTREAM_SYMBOL, BRAVE_SYMBOL), self.env.repo.chromium)

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        # The list is every untracked path rather than just the patch files,
        # which is why `.version_upgrade` shows up in it as well.
        self.assert_failed(
            run,
            'Untracked patch files detected. These should be committed as '
            'their own changes:', self.RENAMED_PATCH)

    def test_continue_after_carrying_the_patch_over_finishes(self):
        self._release_renaming_bar()
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        self.env.repo.write_file(
            self.RENAMED,
            self.env.upstream_source(self.RENAMED).replace(
                UPSTREAM_SYMBOL, BRAVE_SYMBOL), self.env.repo.chromium)
        self.env.commit_patch_changes(f'Follow the rename of {BAR}')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue',
                                '--no-conflict-change')

        self.assert_succeeded(run)
        self.assertFalse((self.env.repo.brave / BAR_PATCH).exists())
        self.assertTrue((self.env.repo.brave / self.RENAMED_PATCH).exists())


class LiftBrokenPatchTest(LiftTestCase):
    """A patch that cannot be applied at all, however it is tried."""

    def test_broken_patch_is_reported(self):
        self.env.break_patch(FOO_PATCH)
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(run.exit_code, 1)
        self.assert_output_has(
            run, '* Broken patches that fail to apply entirely '
            '(action needed):',
            f'    ✘ {_native(FOO_PATCH)} ➜ {self.env.source_path(FOO)}')
        record = self.env.continuation(MAJOR_TARGET).apply_record
        self.assertEqual(
            [patch.path.as_posix() for patch in record.broken_patches],
            [FOO_PATCH])

    def test_broken_patch_opens_the_patch_and_its_source(self):
        self.env.break_patch(FOO_PATCH)
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(self.env.vscode_files(), [
            FOO_PATCH,
            Path(self.env.source_path(FOO)).as_posix(),
        ])


class LiftFixupRoutingTest(LiftTestCase):
    """Patches last touched by dev-cycle commits are committed as fixups.

    In a `cr` branch every bump is a major one as far as the lift is concerned
    (the base branch is still on the previous major), so a patch that a
    dev-cycle commit in the branch owns is committed as a `fixup!` for it
    instead of being folded into the conflict-resolved change. That keeps
    `rebase --squash-minor-bumps` from having to resolve the same conflict
    twice.
    """

    # The symbol a dev-cycle commit in the branch rewrites `FOO` to.
    DEV_SYMBOL = 'BraveThingV2'

    def _lift_then_dev_cycle_change(self) -> None:
        """Lifts once, then changes `FOO`'s patch as a dev-cycle commit."""
        with self.env.upstream_release(MAJOR_TARGET):
            pass
        self.assert_succeeded(self.env.run_lift(f'--to={MAJOR_TARGET}'))
        self.env.repo.write_file(
            FOO,
            self.env.read_source(FOO).replace(BRAVE_SYMBOL, self.DEV_SYMBOL),
            self.env.repo.chromium)
        self.env.commit_patch_changes('Dev-cycle change to foo.cc')

    def test_dev_cycle_patch_is_committed_as_a_fixup(self):
        self._lift_then_dev_cycle_change()
        marker = self.env.head()
        with self.env.upstream_release(MAJOR_FOLLOW_UP) as upstream:
            upstream.edit(
                FOO,
                line=PATCHED_LINE,
                text=f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')

        self.env.run_lift(f'--to={MAJOR_FOLLOW_UP}')
        self.env.resolve_conflict(FOO, symbol=self.DEV_SYMBOL)
        run = self.env.run_lift(f'--to={MAJOR_FOLLOW_UP}', '--continue')

        self.assert_succeeded(run)
        self.assertEqual(self.env.subjects(marker), [
            f'Update from Chromium {BASE_VERSION} to Chromium '
            f'{MAJOR_FOLLOW_UP}.',
            'fixup! Dev-cycle change to foo.cc',
            f'Updated strings for Chromium {MAJOR_FOLLOW_UP}.',
            f'`gnrt` run for Chromium {MAJOR_FOLLOW_UP}.',
        ])
        self.assertEqual(self.env.files_in(self.env.commit_for('fixup!')),
                         [FOO_PATCH])

    def test_patches_owned_by_the_lift_are_not_fixups(self):
        """A patch whose most recent branch commit is one of the lift's own is
        committed as a conflict-resolved change, not as a fixup."""
        self._lift_then_dev_cycle_change()
        marker = self.env.head()
        with self.env.upstream_release(MAJOR_FOLLOW_UP) as upstream:
            upstream.edit(
                BAR,
                line=PATCHED_LINE,
                text=f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')

        self.env.run_lift(f'--to={MAJOR_FOLLOW_UP}')
        self.env.resolve_conflict(BAR)
        run = self.env.run_lift(f'--to={MAJOR_FOLLOW_UP}', '--continue')

        self.assert_succeeded(run)
        self.assertEqual(self.env.subjects(marker), [
            f'Update from Chromium {BASE_VERSION} to Chromium '
            f'{MAJOR_FOLLOW_UP}.',
            f'Conflict-resolved patches from Chromium {BASE_VERSION} to '
            f'Chromium {MAJOR_FOLLOW_UP}.',
            f'Updated strings for Chromium {MAJOR_FOLLOW_UP}.',
            f'`gnrt` run for Chromium {MAJOR_FOLLOW_UP}.',
        ])
        self.assertEqual(self.env.commit_for('fixup!'), '')


class LiftPlasterTest(LiftTestCase):
    """Patches whose apply failure plaster can (or cannot) take care of."""

    # A plaster that no longer matches its source, once upstream renames the
    # symbol it was written for.
    RENAMED_SYMBOL = 'RenamedThing'
    FIXED_PLASTER_BODY = FOO_PLASTER_BODY.replace(UPSTREAM_SYMBOL,
                                                  RENAMED_SYMBOL)

    def _release_reworking_the_patched_line(self, text: str) -> None:
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.edit(FOO, line=PATCHED_LINE, text=text)

    def test_plaster_fixed_patch_is_committed_on_its_own(self):
        self.env.add_plaster_for_foo()
        self._release_reworking_the_patched_line(
            f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        # The patch is marked as plaster-managed in the reapply list, and the
        # fix it produced is committed under its own subject.
        self.assert_output_has(
            run, f'    * {_native(FOO_PATCH)} 🩹',
            'Apply-fixed 🩹 patches from Chromium '
            f'{BASE_VERSION} to Chromium {MAJOR_TARGET}.')
        self.assertEqual(self.env.files_in(self.env.commit_for('Apply-fixed')),
                         [FOO_PATCH])
        # The source carries brave's change on top of the upstream rework.
        self.assertIn(f'  {BRAVE_SYMBOL} thing;  // upstream tweak',
                      self.env.read_source(FOO))

    def test_plaster_only_failures_stop_the_lift(self):
        """A lift whose only apply failures were fixed by plaster still stops:
        the continuation it runs expects conflict-resolved patches to commit and
        finds none. Recovering takes another run (see the test below)."""
        self.env.add_plaster_for_foo()
        self._release_reworking_the_patched_line(
            f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_failed(
            run,
            'Nothing has been staged to commit conflict-resolved patches. '
            '(Did you mean to pass --no-conflict-change?)')

    def test_plaster_only_failures_finish_on_continue(self):
        self.env.add_plaster_for_foo()
        self._release_reworking_the_patched_line(
            f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue',
                                '--no-conflict-change')

        self.assert_succeeded(run)
        self.assert_commit_subjects([
            'Add plaster for foo.cc',
            f'Update from Chromium {BASE_VERSION} to Chromium {MAJOR_TARGET}.',
            f'Apply-fixed 🩹 patches from Chromium {BASE_VERSION} to Chromium '
            f'{MAJOR_TARGET}.',
            f'Updated strings for Chromium {MAJOR_TARGET}.',
            f'`gnrt` run for Chromium {MAJOR_TARGET}.',
        ])

    def test_plaster_fix_alongside_a_conflict_to_resolve(self):
        """The plaster fix is committed, and the lift still stops for the
        conflict the user has to resolve by hand."""
        self.env.add_plaster_for_foo()
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.edit(
                FOO,
                line=PATCHED_LINE,
                text=f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')
            upstream.edit(
                BAR,
                line=PATCHED_LINE,
                text=f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_output_has(
            run, f'Apply-fixed 🩹 patches from Chromium {BASE_VERSION} to '
            f'Chromium {MAJOR_TARGET}.',
            '* Manually resolve conflicts for (action needed):',
            f'    ✘ {self.env.source_path(BAR)}')

        self.env.resolve_conflict(BAR)
        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_succeeded(run)
        self.assertEqual(
            self.env.files_in(
                self.env.commit_for('Conflict-resolved patches')), [BAR_PATCH])

    def test_plaster_that_no_longer_matches_is_reported(self):
        self.env.add_plaster_for_foo()
        self._release_reworking_the_patched_line(
            f'  {self.RENAMED_SYMBOL} thing;  // upstream rework')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(run.exit_code, 1)
        self.assert_output_has(
            run, '* Plaster failed to fix patches (action needed):',
            f'    ✘ {self.env.brave_path(FOO_PLASTER)} ➜ '
            f'{self.env.source_path(FOO)}')
        record = self.env.continuation(MAJOR_TARGET).apply_record
        self.assertEqual(
            [patch.path.as_posix() for patch in record.plaster_broken_patches],
            [FOO_PATCH])
        self.assertEqual(record.plaster_fixed_patches, [])

    def test_continue_with_an_unfixed_plaster_is_reported(self):
        """Continuing without having fixed the plaster is reported as a
        regular failure, rather than a raw plaster exception escaping the
        lift."""
        self.env.add_plaster_for_foo()
        self._release_reworking_the_patched_line(
            f'  {self.RENAMED_SYMBOL} thing;  // upstream rework')
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run, 'Plaster file has not been fixed and re-applied: '
            f'{self.env.brave_path(FOO_PLASTER)}',
            'Unexpected number of matches (0 vs 1)')

    def test_continue_with_the_plaster_deleted_but_the_patch_kept(self):
        """Dropping the plaster file means dropping the patch it owns; keeping
        one without the other is refused."""
        self.env.add_plaster_for_foo()
        self._release_reworking_the_patched_line(
            f'  {self.RENAMED_SYMBOL} thing;  // upstream rework')
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        (self.env.repo.brave / FOO_PLASTER).unlink()
        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run, 'Plaster file was deleted but patch still exists: '
            f'{_native(FOO_PATCH)}')

    def test_continue_after_fixing_the_plaster_finishes(self):
        self.env.add_plaster_for_foo()
        self._release_reworking_the_patched_line(
            f'  {self.RENAMED_SYMBOL} thing;  // upstream rework')
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        # The user points the plaster at the renamed symbol and reapplies it.
        self.env.reapply_plaster_for_foo(self.FIXED_PLASTER_BODY)
        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue',
                                '--no-conflict-change')

        self.assert_succeeded(run)
        self.assertIn(f'  {BRAVE_SYMBOL} thing;  // upstream rework',
                      self.env.read_source(FOO))


class LiftOrphanedPlasterTest(LiftTestCase):
    """A plaster-managed patch whose source upstream deletes entirely.

    The plaster's target is gone, not just changed, so there is nothing for
    plaster to re-match against: the patch is reported both as deleted and as
    an orphaned plaster.
    """

    def _release_deleting_foo(self) -> None:
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.delete(FOO)

    def test_orphaned_plaster_is_reported_alongside_the_deletion(self):
        self.env.add_plaster_for_foo()
        self._release_deleting_foo()

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(run.exit_code, 1)
        self.assert_output_has(
            run, '* Files that cannot be patched anymore (action needed):',
            f'    ✘ {_native(FOO)} (deleted)',
            '* Plaster failed to fix patches (action needed):',
            f'    ✘ {self.env.brave_path(FOO_PLASTER)} (orphaned)')

    def test_orphaned_plaster_opens_only_the_plaster_in_the_editor(self):
        """There is no source left to open alongside it, unlike a plaster
        whose source still exists (see `LiftPlasterTest`)."""
        self.env.add_plaster_for_foo()
        self._release_deleting_foo()

        self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(self.env.vscode_files(), [
            FOO_PATCH,
            Path(self.env.brave_path(FOO_PLASTER)).as_posix(),
        ])

    def test_orphaned_plaster_is_recorded_in_the_continuation_file(self):
        self.env.add_plaster_for_foo()
        self._release_deleting_foo()

        self.env.run_lift(f'--to={MAJOR_TARGET}')

        record = self.env.continuation(MAJOR_TARGET).apply_record
        self.assertEqual(
            [patch.path.as_posix() for patch in record.plaster_broken_patches],
            [FOO_PATCH])
        self.assertEqual([
            patch.path.as_posix() for patch in record.patches_to_deleted_files
        ], [FOO_PATCH])

    def test_continue_without_removing_the_orphaned_plaster_is_rejected(self):
        self.env.add_plaster_for_foo()
        self._release_deleting_foo()
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_failed(
            run, 'Plaster file has not been fixed and re-applied: '
            f'{self.env.brave_path(FOO_PLASTER)}',
            'Failed to read the source targeted by '
            f'{self.env.brave_path(FOO_PLASTER)} from git: {_native(FOO)}. '
            'The upstream file may have been moved or deleted')

    def test_continue_after_removing_the_orphaned_plaster_and_patch_finishes(
            self):
        """Resolving an orphaned plaster means dropping both the plaster and
        the patch it owns, the same way a plain deleted patch is dropped."""
        self.env.add_plaster_for_foo()
        self._release_deleting_foo()
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        (self.env.repo.brave / FOO_PLASTER).unlink()
        self.env.git('add', '--all', 'rewrite')
        self.env.commit_patch_changes(
            f'Remove patch and plaster for deleted {FOO}')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue',
                                '--no-conflict-change')

        self.assert_succeeded(run)
        self.assertFalse((self.env.repo.brave / FOO_PATCH).exists())
        self.assertFalse((self.env.repo.brave / FOO_PLASTER).exists())


class LiftRestartTest(LiftTestCase):
    """`--restart` throwing the previous attempt away."""

    def _stop_on_a_conflict(self) -> None:
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.edit(
                FOO,
                line=PATCHED_LINE,
                text=f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')
        run = self.env.run_lift(f'--to={MAJOR_TARGET}')
        self.assertEqual(run.exit_code, 1)

    def test_restart_discards_the_previous_attempt(self):
        self._stop_on_a_conflict()
        first_attempt = self.env.head()

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--restart')

        self.assert_output_has(
            run,
            'Discarding the following changes:',
            f'Update from Chromium {BASE_VERSION} to Chromium {MAJOR_TARGET}.',
            # The checkout is left at the target version by the discarded run,
            # which the restarted one points out.
            'Chromium is checked out with the target version. '
            f'Brave {BASE_VERSION} ➜ Chromium {MAJOR_TARGET}')
        # The version commit was redone rather than duplicated, and the run
        # stopped on the same conflict as before.
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MAJOR_TARGET}.'
        ])
        self.assertNotEqual(self.env.head(), first_attempt)
        self.assert_output_has(
            run, '* Manually resolve conflicts for (action needed):')

    def test_restart_with_another_target_is_rejected(self):
        self._stop_on_a_conflict()
        with self.env.upstream_release(MAJOR_FOLLOW_UP):
            pass

        run = self.env.run_lift(f'--to={MAJOR_FOLLOW_UP}', '--restart')

        self.assert_failed(
            run, 'Running with `--restart` but the target version does not '
            f'match the current version. {MAJOR_FOLLOW_UP} vs {MAJOR_TARGET}')

    def test_restart_without_a_version_commit_to_discard_is_rejected(self):
        self._stop_on_a_conflict()
        # Anything committed on top of the pinslist file hides the version
        # commit `--restart` keys off.
        self.env.stage_file(brockit.PINSLIST_TIMESTAMP_FILE,
                            'unrelated rewrite\n')
        self.env.repo.commit('Rewrite the pinslist file', self.env.repo.brave)

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--restart')

        self.assert_failed(
            run, 'Running with `--restart` but the last change does not match '
            'the arguments provided.')


class LiftGitHubTest(LiftTestCase):
    """`--with-github` creating or refreshing the version issue."""

    ISSUE_TITLE = 'Upgrade from Chromium 134 to Chromium 135'

    def test_with_github_creates_the_issue(self):
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--with-github')

        self.assert_succeeded(run)
        self.assert_output_has(
            run, f'GitHub Issue created for this bump: {ISSUE_URL}')
        create = self.env.gh.issue_create_cmd()
        self.assertIn(self.ISSUE_TITLE, create)
        self.assertIn(log_link(BASE_VERSION, MAJOR_TARGET), ' '.join(create))
        # The issue is created, but a pull request is not: `lift` leaves that to
        # `update-version-issue`.
        self.assertIsNone(self.env.gh.pr_create_cmd())

    def test_with_github_refreshes_a_stale_issue(self):
        self.env.gh.issue_list = [{
            'number': 42,
            'title': self.ISSUE_TITLE,
            'url': ISSUE_URL,
            'body': f'Some text\n{log_link("111.0.0.0", "112.0.0.0")}\nmore',
        }]
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--with-github')

        self.assert_succeeded(run)
        self.assert_output_has(run, f'GitHub issue updated {ISSUE_URL}.')
        edit = self.env.gh.issue_edit_cmd()
        self.assertIn(log_link(BASE_VERSION, MAJOR_TARGET), ' '.join(edit))
        self.assertIsNone(self.env.gh.issue_create_cmd())

    def test_with_github_leaves_an_up_to_date_issue_alone(self):
        self.env.gh.issue_list = [{
            'number': 42,
            'title': self.ISSUE_TITLE,
            'url': ISSUE_URL,
            'body': log_link(BASE_VERSION, MAJOR_TARGET),
        }]
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--with-github')

        self.assert_succeeded(run)
        self.assert_output_has(
            run, f'A Github issue with the title "{self.ISSUE_TITLE}" is '
            f'already created and up-to-date. {ISSUE_URL}')
        self.assertIsNone(self.env.gh.issue_edit_cmd())

    def test_with_github_without_a_login_stops_before_any_work(self):
        self.env.gh.logged_in = False
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--with-github')

        self.assert_failed(run, 'GitHub CLI is not logged in.')
        self.assert_commit_subjects([])

    def test_gh_is_left_alone_without_with_github(self):
        with self.env.upstream_release(MAJOR_TARGET):
            pass

        self.assert_succeeded(self.env.run_lift(f'--to={MAJOR_TARGET}'))

        self.assertEqual(self.env.gh.calls, [])


class LiftToolchainAdvisoryTest(LiftTestCase):
    """The pre-run advisory raised when Chromium repins a toolchain."""

    # Chromium's Windows toolchain pin, which the lift diffs across the range.
    VS_TOOLCHAIN = 'build/vs_toolchain.py'
    OLD_PIN = ('10.0.22621.0', 'oldtoolchainhash')
    NEW_PIN = ('10.0.26100.0', 'newtoolchainhash')

    UPSTREAM_FILES = {
        VS_TOOLCHAIN: (f"SDK_VERSION = '{OLD_PIN[0]}'\n"
                       f"TOOLCHAIN_HASH = '{OLD_PIN[1]}'\n")
    }

    def setUp(self) -> None:
        super().setUp()
        # Recovery kicks off a CI build and waits for it, which a test has no
        # business doing; the advisory is what is under test here.
        patcher = patch.object(toolchain.WindowsToolchain, 'recover')
        self.recover = patcher.start()
        self.recover.return_value = False
        self.addCleanup(patcher.stop)

    def _release_repinning_the_toolchain(self) -> str:
        """Releases `MAJOR_TARGET` with a new toolchain pin.

        Returns:
            The hash of the Chromium commit that repinned it, i.e. the culprit
            the advisory is expected to attribute the change to.
        """
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            return upstream.write(
                self.VS_TOOLCHAIN, f"SDK_VERSION = '{self.NEW_PIN[0]}'\n"
                f"TOOLCHAIN_HASH = '{self.NEW_PIN[1]}'\n")

    def test_advisory_stops_the_lift_before_anything_is_committed(self):
        culprit = self._release_repinning_the_toolchain()

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assertEqual(run.exit_code, 1)
        self.assert_output_has(
            run, '* Pre-run advisory (attention needed)',
            '               * Windows SDK has been updated. '
            f'{"-".join(self.OLD_PIN)} ➜ {"-".join(self.NEW_PIN)}',
            f'                   CL: Upstream change to {self.VS_TOOLCHAIN}',
            '                   Generate the new toolchain in '
            'https://ci.brave.com/view/toolchains/',
            '👋 (Address advisories and then rerun with --ack-advisory)')
        self.assert_commit_subjects([])
        # The culprit commit is linked, so it can be read on Googlesource.
        self.assert_output_has(
            run, brockit.GOOGLESOURCE_COMMIT_LINK.format(commit=culprit))
        # And the advisory is recorded, which is what makes `--ack-advisory`
        # acceptable on the next run.
        self.assertTrue(self.env.continuation(MAJOR_TARGET).has_shown_advisory)

    def test_ack_advisory_carries_on(self):
        self._release_repinning_the_toolchain()
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--ack-advisory')

        self.assert_succeeded(run)
        self.assert_output_lacks(run, 'Pre-run advisory')
        self.assert_commit_subjects([
            f'Update from Chromium {BASE_VERSION} to Chromium {MAJOR_TARGET}.',
            f'Updated strings for Chromium {MAJOR_TARGET}.',
            f'`gnrt` run for Chromium {MAJOR_TARGET}.',
        ])

    def test_a_recovered_toolchain_raises_no_advisory(self):
        """When the toolchain could be built and repinned on the spot there is
        nothing left for the user to do, so the lift just carries on."""
        self.recover.return_value = True
        self._release_repinning_the_toolchain()

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_succeeded(run)
        self.assert_output_lacks(run, 'Pre-run advisory')
        self.recover.assert_called_once()

    def test_ack_advisory_without_an_advisory_shown_is_rejected(self):
        """`--ack-advisory` is only meant for the run that follows an advisory,
        so that it cannot grow into a general `--force`."""
        self._release_repinning_the_toolchain()
        # A continuation file from a run that never showed an advisory.
        brockit.ContinuationFile(
            target_version=brockit.Version(MAJOR_TARGET),
            working_version=brockit.Version(BASE_VERSION),
            base_version=brockit.Version(BASE_VERSION)).save()

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--ack-advisory')

        self.assert_failed(
            run, 'Use --ack-advisory just after being shown advisories.')
        self.assert_commit_subjects([])

    def test_no_toolchain_change_raises_no_advisory(self):
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.edit(FOO, line=UNRELATED_LINE, text='// upstream churn')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}')

        self.assert_succeeded(run)
        self.assert_output_lacks(run, 'Pre-run advisory')
        self.recover.assert_not_called()


class LiftTargetLabelTest(LiftTestCase):
    """`--to` accepting labels instead of a version number.

    Resolving a label is the one part of a lift that genuinely reaches out to
    the network, so the two seams that do -- the Googlesource tag listing and
    ChromiumDash -- are the only things stubbed here. The version that comes
    back then drives a real lift.
    """

    def setUp(self) -> None:
        super().setUp()
        with self.env.upstream_release(MINOR_TARGET):
            pass

    def test_latest_tag_label(self):
        with patch.object(
                brockit.Version,
                'get_latest_googlesource_tag_version',
                return_value=brockit.Version(MINOR_TARGET)) as latest:
            run = self.env.run_lift('--to=@latest-tag')

        self.assert_succeeded(run)
        latest.assert_called_once_with()
        self.assertEqual(self.env.repo.package_version(), MINOR_TARGET)

    def test_latest_major_label(self):
        with patch.object(
                brockit.Version,
                'get_latest_googlesource_tag_version',
                return_value=brockit.Version(MINOR_TARGET)) as latest:
            run = self.env.run_lift('--to=@latest-m134')

        self.assert_succeeded(run)
        latest.assert_called_once_with(major=134)

    def test_latest_for_branch_label_uses_the_branch_name(self):
        """`@latest-for-branch` reads the major off the `cr{MAJOR}` branch."""
        with patch.object(
                brockit.Version,
                'get_latest_googlesource_tag_version',
                return_value=brockit.Version(MINOR_TARGET)) as latest:
            self.env.run_lift('--to=@latest-for-branch')

        latest.assert_called_once_with(major=135)

    def test_channel_label_queries_chromium_dash(self):
        response = MagicMock()
        response.json.return_value = [{'version': MINOR_TARGET}]
        with patch.object(brockit.requests, 'get',
                          return_value=response) as get:
            run = self.env.run_lift('--to=@latest-canary')

        self.assert_succeeded(run)
        self.assertEqual(self.env.repo.package_version(), MINOR_TARGET)
        # Every platform is queried, plus the ASAN variant for canary.
        queried = [call.args[0] for call in get.call_args_list]
        self.assertEqual(len(queried), 6)
        self.assertTrue(all('channel=canary' in url for url in queried))
        self.assertTrue(any('channel=canary_asan' in url for url in queried))

    def test_unknown_label_is_rejected(self):
        run = self.env.run_lift('--to=@latest-and-greatest')

        self.assert_failed(run, 'Invalid @latest channel: "and-greatest".')
        self.assert_commit_subjects([])

    def test_label_with_a_bad_major_is_rejected(self):
        run = self.env.run_lift('--to=@latest-mFIVE')

        self.assert_failed(run, 'Invalid major version in "@latest-mFIVE"')

    def test_unknown_prefix_is_rejected(self):
        run = self.env.run_lift('--to=@whatever')

        self.assert_failed(run, 'Unknown label: "@whatever".')


class LiftForBranchLabelTest(LiftTestCase):
    """`@latest-for-branch` on a branch that is not named `cr{MAJOR}`."""

    BRANCH = 'a-branch-of-my-own'

    def test_label_requires_a_cr_branch(self):
        run = self.env.run_lift('--to=@latest-for-branch')

        self.assert_failed(
            run, '@latest-for-branch requires the current branch to be named '
            f'cr{{MAJOR}} (e.g. cr135), but the current branch is '
            f'"{self.BRANCH}".')


class LiftInfraModeTest(LiftTestCase):
    """Running under `--infra-mode`."""

    def setUp(self) -> None:
        super().setUp()
        # `terminal.set_infra_mode` also starts a keep-alive thread that lives
        # for the rest of the process, so the flag it sets is what gets flipped
        # here instead.
        terminal.terminal.infra_mode = True
        self.addCleanup(setattr, terminal.terminal, 'infra_mode', False)

    def test_init_carries_the_workaround_flag(self):
        """On infra, `init` is run with the flag that works around
        https://github.com/brave/brave-browser/issues/44921."""
        with self.env.upstream_release(MINOR_TARGET):
            pass

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_succeeded(run)
        init = next(cmd for cmd in self.env.terminal.calls
                    if cmd[1:3] == ['run', INIT])
        self.assertIn('--with_issue_44921', init)


class LiftRoughEdgesTest(LiftTestCase):
    """Current behaviour that is arguably wrong, pinned down deliberately.

    Each of these records what the lift does today. They are here so that the
    behaviour is visible and so that whoever improves it has a test to update
    rather than a surprise to discover.
    """

    def test_unresolved_conflict_markers_are_committed(self):
        """Nothing checks the resolution: a `--continue` run over a source that
        still has conflict markers in it commits them into the patch."""
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.edit(
                FOO,
                line=PATCHED_LINE,
                text=f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')
        self.env.run_lift(f'--to={MAJOR_TARGET}')

        run = self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        self.assert_succeeded(run)
        self.assertIn(
            '<<<<<<< ours',
            self.env.git(
                'show', f'{self.env.commit_for("Conflict-resolved")}:'
                f'{FOO_PATCH}'))

    def test_init_failing_during_a_continuation_is_not_handled(self):
        """The `init` run that closes a continuation is not guarded, so a
        failure there escapes as a raw subprocess error."""
        with self.env.upstream_release(MAJOR_TARGET) as upstream:
            upstream.edit(
                FOO,
                line=PATCHED_LINE,
                text=f'  {UPSTREAM_SYMBOL} thing;  // upstream tweak')
        self.env.run_lift(f'--to={MAJOR_TARGET}')
        self.env.resolve_conflict(FOO)
        self.env.terminal.fail(INIT, stderr='gclient blew up')

        with self.assertRaises(subprocess.CalledProcessError):
            self.env.run_lift(f'--to={MAJOR_TARGET}', '--continue')

        # The conflict-resolved commit did land before the failure.
        self.assertNotEqual(self.env.commit_for('Conflict-resolved patches'),
                            '')

    def test_update_patches_failing_is_reported_as_an_init_failure(self):
        """A failure in `update_patches` is reported under `init`'s name,
        because both run inside the same guard."""
        with self.env.upstream_release(MINOR_TARGET):
            pass
        self.env.terminal.fail(UPDATE_PATCHES, stderr='update_patches blew up')

        run = self.env.run_lift(f'--to={MINOR_TARGET}')

        self.assert_failed(run, 'Failures found when running npm run init',
                           'update_patches blew up')


if __name__ == '__main__':
    unittest.main()
