# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

fastlane_version "2.86.0"

default_platform :ios

CONFIG_PATH = "../App/Configuration"
LOCAL_PATH = "#{CONFIG_PATH}/Local"

platform :ios do
  before_all do |lane, options|
    unless lane == :test || options[:skip_bootstrap]
      sh("pushd .. && ./bootstrap.sh --ci && popd")
    end
    # Verify clean repo by default
    unless options[:ignore_git_status]
      UI.message "Running git status check"
      ensure_git_status_clean(show_uncommitted_changes: true, show_diff: true)
    end
  end

  after_all do |lane, options|
    # If no uncommitted changes existed before running `lane`, reset any potential fastlane changes
    reset_git_repo(skip_clean: true) unless options[:ignore_git_status]
  end

  desc "Run Unit Tests"
  lane :test do |options|
    run_tests(
      project: "App/Client.xcodeproj",
      scheme: "Debug",
      devices: options[:test_all] ? ["iPhone 14 (16.4)", "iPhone 14 (17.0)"] : ["iPhone 14 (16.4)"],
      code_coverage: true,
      ensure_devices_found: true,
      skip_testing: [
	"CertificateUtilitiesTests/CertificatePinningTest/testSelfSignedRootAllowed",
        "CertificateUtilitiesTests/CertificatePinningTest/testSelfSignedRootAllowed2",
        "ClientTests/TabManagerTests/testQueryAddedTabs",
        "ClientTests/TabManagerTests/testQueryAddedPrivateTabs",
        "ClientTests/TabManagerTests/testQueryAddedMixedTabs",
        "ClientTests/TestFavicons",
        "ClientTests/FingerprintProtectionTest/testFingerprintProtection",
        "ClientTests/TabSessionTests",
        "ClientTests/ContentBlockerTests",
        "ClientTests/HttpCookieExtensionTest/testSaveAndLoadCookie",
        "ClientTests/UserAgentTests",
        "ClientTests/CachedAdBlockEngineTests/testPerformance",
        "DataTests",
        "BraveWalletTests/ManageSiteConnectionsStoreTests/testRemoveAllPermissions",
        "BraveWalletTests/ManageSiteConnectionsStoreTests/testRemovePermissions",
        "BraveWalletTests/ManageSiteConnectionsStoreTests/testRemovePermissionsLastPermission",
        "BraveWalletTests/SendTokenStoreTests/testResolvedAddressUsedInSolTxIfAvailable",
        "BraveWalletTests/SendTokenStoreTests/testResolvedAddressUsedInEthTxIfAvailable",
        "BraveWalletTests/SendTokenStoreTests/testUDAddressResolutionEthNetwork",
        "BraveWalletTests/SendTokenStoreTests/testUDAddressResolutionSolNetwork",
        "BraveWalletTests/SendTokenStoreTests/testUDAddressResolutionFailure",
        "BraveWalletTests/SendTokenStoreTests/testUDAddressResolutionTokenChange",
        "BraveWalletTests/TransactionConfirmationStoreTests/testPrepareERC20Approve",
        "BraveWalletTests/TransactionConfirmationStoreTests/testPrepareTransactionNotOnSelectedNetwork",
      ]
    )

    run_tests(
      project: "App/Client.xcodeproj",
      scheme: "Debug",
      devices: options[:test_all] ? ["iPad (10th generation) (16.4)", "iPad (10th generation) (17.0)"] : ["iPad (10th generation) (16.4)"],
      code_coverage: true,
      ensure_devices_found: true,
      skip_testing: [
        "ClientTests/UserAgentTests"
      ],
      xcargs: "-testPlan Brave_iPad"
    )
  end

  desc "Creates a Brave Beta Release build for TestFlight."
  lane :beta do |options|
    overrideParams = {
      scheme: "Beta",
      export_method: "app-store",
      export_options: {
        manageAppVersionAndBuildNumber: false
      }
    }
    testflight_build({overrideParams: overrideParams, skip_upload: options[:skip_upload]})
  end

  desc "Creates a Brave Internal Beta Release build for TestFlight."
  lane :internal do |options|

    overrideParams = {
      scheme: "Dev",
      export_method: "app-store",
      export_options: {
        manageAppVersionAndBuildNumber: false
      }
    }
    testflight_build({overrideParams: overrideParams, skip_upload: options[:skip_upload]})
  end

  desc "Create an archive to be uploaded to the App Store"
  lane :release do |options|
    ENV["BRAVE_APPSTORE_BUILD"] = "1"
    overrideParams = {
      scheme: "Release (AppStore)",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.brave.ios.browser" => "Brave iOS",
          "com.brave.ios.browser.ShareExtension" => "Brave iOS Share Extension",
          "com.brave.ios.browser.BrowserIntents" => "Brave iOS Intents Extension",
          "com.brave.ios.browser.BraveWidgetsExtension" => "Brave iOS Widgets Extension",
          "com.brave.ios.browser.BraveWireGuard" => "Brave iOS WireGuard Extension",
        },
        manageAppVersionAndBuildNumber: false
      },
    }
    testflight_build({overrideParams: overrideParams, skip_upload: options[:skip_upload]})
  end

  desc "All Testflight releases use this as the foundation. Pass in `gym` override params."
  private_lane :testflight_build do |options|
    defaultParams = gym_params()
    gym(defaultParams.merge!(options[:overrideParams]))
    unless options[:skip_upload]
      api_key = app_store_connect_api_key()
      pilot(
        api_key: api_key,
        skip_submission: true,
        skip_waiting_for_build_processing: true
      )
    end
  end

  # Private helper methods ---------------------------------------

  desc "Returns the parameters that should be used in any fastlane build"
  lane :gym_params do
    {
      project: "App/Client.xcodeproj",
      sdk: "iphoneos",
      clean: true,
      output_directory: "build",
      xcargs: "-allowProvisioningUpdates"
    }
  end

end
