/* Copyright (c) 2025 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

// Schema for the polkadot_substrate_rpc.
namespace polkadot_substrate_rpc_responses {
  dictionary Error {
    long code;
    DOMString? message;
  };

  dictionary PolkadotSystemChainResponse {
    DOMString jsonrpc;
    long id;
    DOMString? result;
    Error? error;
  };

  // any[] => sequence<sequence<DOMString>>
  dictionary AccountInfo {
    DOMString block;
    any[] changes;
  };

  dictionary PolkadotAccountBalanceResponse {
    DOMString jsonrpc;
    long id;
    AccountInfo[]? result;
    Error? error;
  };
};
