/* Copyright (c) 2025 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

// Schema for the polkadot_substrate_rpc.
[none_as_absent_optional]
namespace polkadot_substrate_rpc_responses {
  dictionary Error {
    long code;
    DOMString? message;
  };

  dictionary PolkadotSystemChainResponse {
    DOMString jsonrpc;
    long id;
    DOMString? result;
    Error? error;
  };

  // any[] => sequence<sequence<DOMString>>
  // See https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#11111-state_querystorage
  // for more information on the shape of this JSON.
  dictionary AccountInfo {
    DOMString block;
    any[] changes;
  };

  dictionary PolkadotAccountBalanceResponse {
    DOMString jsonrpc;
    long id;
    AccountInfo[]? result;
    Error? error;
  };

  dictionary PolkadotFinalizedHead {
    DOMString jsonrpc;
    long id;
    DOMString? result;
    Error? error;
  };

  // chain_getHeader's RPC structure is described here:
  // https://github.com/w3f/PSPs/blob/b6d570173146e7a012cf43d270177e02ed886e2e/PSPs/drafts/psp-6.md#192-chain_getheader

  dictionary ChainHeader {
    // The hex-encoded hash of the parent block's header.
    DOMString parentHash;

    // The number of the block in the current chain.
    DOMString number;
  };

  dictionary PolkadotChainHeader {
    DOMString jsonrpc;
    long id;
    ChainHeader? result;
    Error? error;
  };
};
