# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Build the Brave elevation service IDL instead of Chromium's.
    set_attribute:
      target: elevation_service_idl
      attribute: sources:list
      value: //brave/chromium_src/chrome/elevation_service/elevation_service_idl.idl

  - description: Add the Brave elevation service deps.
    add_literal_to_list:
      target: lib
      list_name: deps
      literal: brave_elevation_service_lib_deps
