# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

from collections import defaultdict
import json

from override_utils import override_function, override_method

from grit.node import message

# Length of the 'IDS_' prefix in message names
_IDS_PREFIX_LEN = 4


def _GetSwiftExportMessageIds(root):
    """Collects all messages with their IDs."""

    ids_map = root.GetIdMap()
    messages = []

    for item in root.ActiveDescendants():
        if not isinstance(item, message.MessageNode):
            continue

        name = item.attrs['name']
        messages.append((name[_IDS_PREFIX_LEN:], ids_map[name]))

    return messages


def _FormatObjCHeader(root, *_args, **_kwargs):
    """Generates Objective-C header file with exported string resource IDs."""

    yield ('// This file is automatically generated by GRIT. Do not edit.\n\n'
           '#pragma once\n\n'
           '#if !__swift__\n'
           '#error "This header is intended to be consumed by the Swift Clang '
           'importer."\n'
           '#endif\n')

    messages = _GetSwiftExportMessageIds(root)
    if not messages:
        return

    yield '\n#import <Foundation/Foundation.h>\n\n'
    yield '#import "l10n_utils_typed_bridge.h"\n\n'

    for name, _ in messages:
        yield f'OBJC_EXTERN const MessageIDTyped MessageIDTyped{name};\n'


def _FormatObjCMm(root, *_args, **_kwargs):
    """Generates Objective-C mm file with string resource ID definitions."""

    yield '// This file is automatically generated by GRIT. Do not edit.\n'

    messages = _GetSwiftExportMessageIds(root)
    if not messages:
        return

    yield '\n#import <Foundation/Foundation.h>\n\n'
    yield '#import "l10n_utils_typed_bridge.h"\n\n'

    for name, ids_value in messages:
        yield (f'OBJC_EXPORT const MessageIDTyped '
               f'MessageIDTyped{name} = {ids_value};\n')


def _GetMessageText(msg_or_ph):
    """Get the content of a <message> or <ph> node. This is the text used in
       as the mock content and is English text of the message
       (excluding examples)."""
    result = ''
    for child in msg_or_ph.mixed_content:
        if isinstance(child, message.PhNode):
            result += _GetMessageText(child)
        elif isinstance(child, str):
            result += child

    return result

def _GetWebuiMessageAndIds(root):
    """Collects webui messages grouped by their webui attribute value.
    Supports comma-separated values, e.g. webui=BraveAccount,BraveSettings
    will add the message to both groups.
    """

    ids_map = root.GetIdMap()
    grouped_messages = defaultdict(list)

    for item in root.ActiveDescendants():
        if not isinstance(item, message.MessageNode):
            continue

        webui = item.formatter_data.get('webui')
        if not webui:
            continue

        name = item.attrs['name']
        # Strip 'IDS_' prefix from message names.
        message_data = (name[_IDS_PREFIX_LEN:], ids_map[name],
                        _GetMessageText(item))

        # Support comma-separated group names.
        for group in webui.split(','):
            grouped_messages[group].append(message_data)

    return grouped_messages


def _FormatWebuiHeader(root, *_args, **_kwargs):
    """Generates C++ header with webui::LocalizedString arrays
       for each group."""

    yield ('// This file is automatically generated by GRIT. Do not edit.\n\n'
           '#pragma once\n\n'
           '#include <array>\n\n')

    if root.IsAllowlistSupportEnabled():
        yield '#include "ui/base/resource/allowlist.h"\n'
    yield '#include "ui/base/webui/web_ui_util.h"\n\n'

    yield 'namespace webui {\n'

    for group, messages in _GetWebuiMessageAndIds(root).items():
        # Create constexpr array of LocalizedString structs.
        yield (f'\ninline constexpr auto k{group}Strings = '
               'std::to_array<LocalizedString>({\n')

        for name, ids_value, _ in messages:
            if root.IsAllowlistSupportEnabled():
                yield (f'    {{"{name}", '
                       f'(::ui::AllowlistedResource<{ids_value}>(), '
                       f'{ids_value})}},\n')
            else:
                yield f'    {{"{name}", {ids_value}}},\n'

        yield '});\n'

    yield '\n}  // namespace webui\n'


def _FormatWebuiMock(root, *_args, **_kwargs):
    """Generates a Typescript file with the strings for mock usage (ie. for
       Storybook or tests)."""

    yield '// This file is automatically generated by GRIT. Do not edit.\n\n'

    yield 'export default {\n'

    # Deduplicate messages that appear in multiple groups.
    seen = {}
    for _, messages in _GetWebuiMessageAndIds(root).items():
        for name, _, text in messages:
            if name not in seen:
                seen[name] = text

    for name, text in seen.items():
        yield f"  {name}: {json.dumps(text, ensure_ascii=False)},\n"

    yield '}\n'


def _FormatWebuiTs(root, *_args, **_kwargs):
    """Generates TypeScript enums with string constants for webui usage."""

    yield '// This file is automatically generated by GRIT. Do not edit.\n'

    for group, messages in _GetWebuiMessageAndIds(root).items():
        yield f'\nexport const enum {group}Strings {{\n'

        for name, _, _ in messages:
            # Enum values are the same as their keys and IDS_ for easy grepping.
            yield f'  {name} = "{name}",\n'

        yield '}\n'


_CUSTOM_FORMATTERS = {
    'objc_header': _FormatObjCHeader,
    'objc_mm': _FormatObjCMm,
    'webui_header': _FormatWebuiHeader,
    'webui_mock': _FormatWebuiMock,
    'webui_ts': _FormatWebuiTs,
}


@override_function(globals())
def GetFormatter(original_function, formatter_type):
    """Add support for additional formats."""
    if formatter := _CUSTOM_FORMATTERS.get(formatter_type):
        return formatter

    return original_function(formatter_type)


@override_method(RcBuilder)
def _EncodingForOutputType(_, original_method, output_type):
    """We need to override the encoding for our formats to be utf_8, as grit
       outputs utf_16 by default.
    """
    if output_type in _CUSTOM_FORMATTERS:
        return 'utf_8'

    return original_method(output_type)
