# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |-
      Adjusts ShouldBlockExtensionInstallation to take an additional
      parameter - extension id - so that the extension can be checked against
      Brave-hosted list.
    re_pattern: '(ShouldBlockExtensionInstallation\(\s+)(int\smanifest_version,)'
    re_flags: [DOTALL]
    replace: |-
      \1const ExtensionId& extension_id,
          \2
  - description: |-
      Adjusts ShouldBlockExtensionInstallation code to pass an additional
      parameter - extension id - to impact_checker.IsExtensionAffected so that
      the extension can be checked against Brave-hosted list.
    re_pattern: '(impact_checker_\.IsExtensionAffected\()(manifest_version,)'
    replace: |-
      \1extension_id,
                                                   \2
  - description: |-
      Adjusts ShouldBlockExtensionEnable code to pass an additional parameter -
      extension id - to impact_checker.IsExtensionAffected so that the extension
      can be checked against Brave-hosted list.
    re_pattern: '(impact_checker_\.IsExtensionAffected\(\s+)(extension\.manifest_version)'
    re_flags: [DOTALL]
    replace: |-
      \1extension.id(),
            \2
