/* Copyright (c) 2020 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_UI_BRAVE_ADS_PUBLIC_CPP_CONSTANTS_H_
#define BRAVE_UI_BRAVE_ADS_PUBLIC_CPP_CONSTANTS_H_

#include <stddef.h>

#include "build/build_config.h"
#include "third_party/skia/include/core/SkColor.h"
#include "ui/gfx/color_palette.h"

// TODO(estade): many of these constants could be internalized.
namespace brave_ads {

// Exported values /////////////////////////////////////////////////////////////

// Square image sizes in DIPs.
const int kNotificationIconSize = 80;

// DIP dimension; H size of the whole card.
const int kNotificationWidth = 360;

// Within a notification ///////////////////////////////////////////////////////
const int kControlButtonBorderSize = 6;

// Colors.
// Background of the card.
constexpr SkColor kNotificationBackgroundColor =
    SkColorSetRGB(0xED, 0xF0, 0xF2);
constexpr SkColor kDimTextColorMD = SkColorSetRGB(0x75, 0x75, 0x75);
// The focus border.
constexpr SkColor kFocusBorderColor = SK_ColorTRANSPARENT;
// Background of the close button and the settings button.
#if defined(OS_CHROMEOS)
constexpr SkColor kControlButtonBackgroundColor =
    SkColorSetA(SK_ColorWHITE, 0.9 * 0xff);
#else
constexpr SkColor kControlButtonBackgroundColor = SK_ColorTRANSPARENT;
#endif

// Line limits.
const int kMessageExpandedLineLimit = 5;

// Default accent color of notifications that are not generated by system.
constexpr SkColor kNotificationDefaultAccentColor = gfx::kChromeIconGrey;

constexpr SkColor kBraveAdsCloseButtonIconColor = SkColorSetRGB(76, 54, 210);

#if !defined(OS_LINUX) || defined(USE_AURA)
constexpr SkColor kHoveredButtonBackgroundColor = SkColorSetRGB(243, 243, 243);
#endif

// Around notifications ////////////////////////////////////////////////////////

// Radius of the rounded corners of a notification.
// The corners are only rounded in Chrome OS.
constexpr int kNotificationCornerRadius = 0;

}  // namespace brave_ads

#endif  // BRAVE_UI_BRAVE_ADS_PUBLIC_CPP_CONSTANTS_H_
