/* Copyright (c) 2024 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

import { StringKey } from '../lib/locale_strings'

export const localeStrings: { [K in StringKey]: string }  = {
  adsBrowserUpgradeRequiredText: 'Your browser needs to be updated to continue seeing ads.',
  adsHistoryButtonLabel: '30-day Ads History',
  adsHistoryMarkInappropriateLabel: 'Mark as inappropriate',
  adsHistoryEmptyText: 'There is currently no Brave Ads history.',
  adsHistoryTitle: 'Ads history',
  adsHistoryText: 'Ads you\'ve received in the past 30 days',
  adsRegionNotSupportedText: 'Brave Private Ads are not yet available in your region.',
  adsSettingsAdsPerHourNoneText: 'None',
  adsSettingsAdsPerHourText: 'Max $1/hr',
  adsSettingsAdTypeTitle: 'Ad type',
  adsSettingsAdViewsTitle: 'Views this month',
  adsSettingsButtonLabel: 'Ads Settings',
  adsSettingsPayoutDateLabel: 'Next earnings payout date',
  adsSettingsTotalAdsLabel: 'Total ads received this month',
  adsSettingsNewsOffTooltip: 'Brave News is currently disabled.',
  adsSettingsNewsOnTooltip: 'Brave News contains ads that cannot be independently disabled.',
  adsSettingsSearchConnectedTooltip: 'You cannot earn BAT from Brave Search Ads yet, but you help support Brave by having them on.',
  adsSettingsSearchTooltip: 'Brave Search Ads appear on $1Brave Search$2.',
  adsSettingsSubdivisionLabel: 'Regional ad relevance',
  adsSettingsSubdivisionText: 'This allows Brave to show you ads meant specifically for your region.',
  adsSettingsSubdivisionDisabledLabel: 'Disabled',
  adsSettingsSubdivisionAutoLabel: 'Auto-detect',
  adsSettingsTitle: 'Ads settings',
  adsSettingsText: 'Control what kinds of Brave Ads you see, and how often. The more you see, the more you can earn.',
  adTypeInlineContentLabel: 'Brave News ads',
  adTypeNewTabPageLabel: 'New tab page ads',
  adTypeNotificationLabel: 'Notification ads',
  adTypeOffLabel: 'Off',
  adTypeOnLabel: 'On',
  adTypeSearchResultLabel: 'Search ads',
  appErrorTitle: 'Something went wrong',
  authorizeDeviceLimitReachedText: 'You\'ve reached the maximum device limit for this $1 account.',
  authorizeDeviceLimitReachedTitle: 'Device limit reached',
  authorizeErrorTitle: 'Error',
  authorizeFlaggedWalletText1: 'Unfortunately, your Brave Rewards profile was flagged because our automated checks found some unexpected Brave Ads activity.',
  authorizeFlaggedWalletText2: 'While your profile is flagged, you may continue to see ads, but won\'t be eligible to receive payouts. You also won\'t be able to connect a custodial account to Brave Rewards.',
  authorizeFlaggedWalletText3: 'It\'s possible your profile was flagged in error, and no immediate action is required on your part. The flag on your profile may be removed in the future.',
  authorizeFlaggedWalletText4: 'Learn more about Brave\'s process for flagging Rewards profiles.',
  authorizeFlaggedWalletTitle: 'Brave Rewards profile is flagged',
  authorizeKycRequiredText: 'Please try again after you have completed ID verification on $1.',
  authorizeKycRequiredTitle: 'You need a verified account to log in',
  authorizeMismatchedCountriesText: 'Hmm, it looks like your Brave Rewards country does not match the country of the $1 account you\'re trying to connect.',
  authorizeMismatchedCountriesTitle: 'Country mismatch',
  authorizeMismatchedProviderAccountsText: 'Hmm, it looks like your Brave Rewards has already been verified with another $1 account. Please try verifying again using your previous account.',
  authorizeMismatchedProviderAccountsTitle: 'Different account',
  authorizeProcessingText: 'Your request is still being processed, please wait.',
  authorizeProviderUnavailableTitle: 'Connecting to selected custodian temporarily unavailable',
  authorizeProviderUnavailableText1: 'It looks like connecting $1 to Brave Rewards is temporarily unavailable. Please try again later.',
  authorizeProviderUnavailableText2: 'You can view $2service status here$3.',
  authorizeRegionNotSupportedText1: 'Your $1 account can\'t be connected to your Brave Rewards profile at this time. Your $1 account is registered in a country that\'s not currently supported for connecting to Brave Rewards.',
  authorizeRegionNotSupportedText2: 'See the $2current list of supported regions and learn more$3 about connecting a custodial account to Brave Rewards.',
  authorizeRegionNotSupportedTitle: 'Region currently not supported',
  authorizeSignatureVerificationErrorText: 'There was a problem validating your request to connect your $1 account to Brave Rewards. You can $2contact support$3 for more help.',
  authorizeSignatureVerificationErrorTitle: 'Request could not be validated',
  authorizeUnexpectedErrorText: 'We weren’t able to complete your request. Please try again, and $2contact support$3 if the problem persists.',
  authorizeUnexpectedErrorTitle: 'Something went wrong',
  authorizeUpholdBatNotAllowedText: 'BAT is not yet supported in your region on Uphold.',
  authorizeUpholdBatNotAllowedTitle: 'BAT unavailable',
  authorizeUpholdInsufficientCapabilitiesText: 'According to Uphold, there are currently some limitations on your Uphold account. Please log in to your Uphold account and check whether there are any notices or remaining account requirements to complete, then try again. For example, you may need to submit more information to Uphold.',
  authorizeUpholdInsufficientCapabilitiesTitle: 'Limited Uphold account functionality',
  benefitsStoreSubtext: 'Get Brave-branded products.',
  benefitsStoreText: 'Brave merch store',
  benefitsTitle: 'Your benefits',
  cancelButtonLabel: 'Cancel',
  captchaMaxAttemptsExceededText: 'Looks like this is not working, Brave ads will remain paused. Contact us if you need help with the captcha.',
  captchaMaxAttemptsExceededTitle: 'Max attempts exceeded',
  captchaSolvedText: 'Brave Ads will resume. Thanks for helping us protect Brave Rewards.',
  captchaSolvedTitle: 'Solved!',
  captchaSupportButtonLabel: 'Contact support',
  closeButtonLabel: 'Close',
  communityTitle: 'Community',
  connectedAdsViewedText: 'You\'re earning for seeing $1# Ads$2 this month',
  connectAccountSubtext: 'Connect a payout account',
  connectAccountText: 'Ready to start earning?',
  connectButtonLabel: 'Connect account',
  connectCustodialTitle: 'Custodial accounts (requires ID verification)',
  connectCustodialTooltip: 'Custodial accounts are accounts with trusted third-party services that hold your BAT for you.',
  connectLoginText: 'Log in or sign up',
  connectProviderNotAvailable: 'Currently not available in your region',
  connectRegionsLearnMoreText: 'Learn more about regions and support',
  connectSelfCustodyError: 'Something went wrong. Please try again',
  connectSelfCustodyNote: 'With self-custody, BAT earnings will be paid out as SPL-BAT on the Solana network.',
  connectSelfCustodyTerms: '$1Terms of Use$2 and $3Privacy Policy$4',
  connectSelfCustodyTitle: 'Self-custody',
  connectSelfCustodyTooltip: 'Self-custody gives you exclusive control over your BAT, along with complete responsibility for its security.',
  connectSolanaButtonLabel: 'Brave Wallet',
  connectSolanaMessage: 'Or other wallet that supports Solana',
  connectText: 'To begin earning Basic Attention Token (BAT) rewards, connect an account. BAT you earn will be automatically transferred to your account every month.',
  connectTitle: 'Choose where you\'d like to receive BAT',
  continueButtonLabel: 'Continue',
  contributeAboutMethodsLink: 'Learn more about contribution methods',
  contributeAmountTitle: 'Contribution amount',
  contributeAvailableMethodsText: 'This creator currently only accepts contributions via the following methods:',
  contributeBalanceTitle: 'Rewards Balance',
  contributeBalanceUnavailableText: 'Not available',
  contributeButtonLabel: 'Contribute',
  contributeChooseMethodText: 'Choose the method you want to use to contribute to Brave Software:',
  contributeCustodialSubtext: 'Custodial wallet',
  contributeErrorText: 'You can try again later.',
  contributeErrorTitle: 'There was a problem sending your contribution',
  contributeInsufficientFundsButtonLabel: 'Insufficient Funds',
  contributeLoginButtonLabel: 'Log in to $1',
  contributeLoggedOutText: 'It looks like you’re logged out of $1 for Brave Rewards. Log in again to continue.',
  contributeLoggedOutTitle: 'Logged out of $1',
  contributeLoggedOutWeb3ButtonLabel: 'Use Web3 Wallet',
  contributeLoggedOutWeb3Text: 'You can also send crypto contributions to this creator by using your Web3 wallet.',
  contributeMonthlyLabel: 'Monthly',
  contributeOtherLabel: 'Other',
  contributeRecurringLabel: 'Recurring contribution',
  contributeSendAmountButtonLabel: 'Send $1 BAT',
  contributeSendButtonLabel: 'Send',
  contributeSendingText: 'Sending contribution',
  contributeSuccessText: 'Thanks for supporting your favorite creators',
  contributeSuccessTitle: 'Contribution sent!',
  contributeWeb3Label: 'Web3 Wallet',
  contributeWeb3Subtext: 'Use your Web3 wallet',
  countrySelectPlaceholder: 'Select',
  countrySelectTitle: 'Select your region',
  countrySelectText: 'Select your region so we can show you the right options and ads for your region.',
  doneButtonLabel: 'Done',
  earningsAdsReceivedText: '$1 ads received this month',
  helpButtonLabel: 'Help',
  learnMoreLink: 'Learn more',
  merchStoreTitle: 'Brave merch store',
  moreButtonLabel: 'More',
  navigationCreatorsLabel: 'Creators',
  navigationExploreLabel: 'Explore',
  navigationHomeLabel: 'Home',
  newBadgeText: 'NEW',
  notificationWalletDisconnectedAction: 'Log in again',
  notificationWalletDisconnectedText: 'This happens from time to time to keep your $1 account secure. While logged out, you will continue to receive payouts, but won\'t be able to see your balance or send contributions from your $1 account.',
  notificationWalletDisconnectedTitle: 'You are logged out',
  notificationMonthlyContributionFailedTitle: 'Monthly contribution failed',
  notificationMonthlyContributionFailedText: 'There was a problem processing your contribution.',
  notificationMonthlyTipCompletedText: 'Your monthly contributions have been processed.',
  notificationMonthlyTipCompletedTitle: 'Contributions',
  onboardingButtonLabel: 'Start using Brave Rewards',
  onboardingErrorCountryDeclaredText: 'Unfortunately, there was an error while trying to set your country. Please try again.',
  onboardingErrorDisabledText: 'New signups for Brave Rewards are currently disabled in your region. However, you can always try again later. $1Learn more$2',
  onboardingErrorDisabledTitle: 'Brave Rewards not available',
  onboardingErrorText: 'Unfortunately, there was an error while trying to set up Brave Rewards. Please try again.',
  onboardingErrorTitle: 'Something went wrong',
  onboardingLearnMoreLabel: 'How does it work?',
  onboardingSuccessLearnMoreLabel: 'How does Brave Rewards work?',
  onboardingSuccessText: 'Now you can get rewarded for viewing ads. You’re helping make the web a better place for everyone. And that’s awesome!',
  onboardingSuccessTitle: 'Woohoo! You\'re all set!',
  onboardingTermsText: 'By enabling Rewards, you agree to the $1Terms of Service$2 and $3Privacy Policy$4.',
  onboardingTextItem1: 'Get paid for private ads you see in Brave',
  onboardingTextItem2: 'Get special benefits and discounts',
  onboardingTitle: 'Turn on Brave Rewards',
  payoutAccountBalanceLabel: 'Your balance',
  payoutAccountConnectedLabel: 'Connected',
  payoutAccountDetailsTitle: '$1 wallet',
  payoutAccountLabel: 'Payout account',
  payoutAccountLink: 'Go to my account',
  payoutAccountLoggedOutTitle: 'Logged Out',
  payoutAccountLoginButtonLabel: 'Log in to $1',
  payoutAccountLoginText: 'Log in to $1 to see your balance',
  payoutAccountTitle: 'Payout Account',
  payoutAccountTooltip: 'Your BAT earnings will be paid to this payout account.',
  payoutCheckStatusLink: 'Check status',
  payoutCompletedText: 'The payout for $1 rewards has completed.',
  payoutPendingText: 'The payout for $1 rewards will begin processing by $2.',
  payoutProcessingText: 'The payout for $1 rewards is in progress.',
  payoutSupportLink: 'Support',
  recurringListEmptyText: 'You don\'t have any recurring contributions set up yet.',
  recurringNextContributionLabel: 'Next contribution:',
  recurringTitle: 'Recurring Contributions',
  removeButtonLabel: 'Remove',
  resetButtonLabel: 'Reset',
  resetConsentText: 'I understand that my current Brave Rewards profile and Brave Rewards data will be deleted from my device, and I\'ve read the $1support article about resetting$2.',
  resetRewardsButtonLabel: 'Disable and reset Rewards',
  resetRewardsText: 'By resetting, your current Brave Rewards profile will be deleted, and Brave Rewards will no longer be enabled. If you enable Brave Rewards again later, you will start with a new profile. Read our $1support article about resetting$2 for more details.',
  resetRewardsTitle: 'Reset Brave Rewards',
  rewardsPageTitle: 'Rewards',
  selfCustodyInviteDismissButtonLabel: 'Not now',
  selfCustodyInviteText: 'We’ve added a new way for you to receive your monthly BAT rewards. Connect an account from one of our partners or use the new self-custody option to start earning now.',
  selfCustodyInviteTitle: 'Receive BAT directly to a self-custody crypto address',
  showAllButtonLabel: 'Show all',
  tosUpdateAcceptButtonLabel: 'I agree',
  tosUpdateLink: 'See $1Brave Rewards Terms of Service$2',
  tosUpdateRequiredText: 'We’ve updated the Terms of Service for Brave Rewards. We’ve made these updates to clarify our terms and ensure they cover new features. If you continue to use Brave Rewards, you are agreeing to the updated Terms of Service. If you do not agree, you can $1reset$2 Brave Rewards, which will disable the feature.',
  tosUpdateRequiredTitle: 'Updated Terms of Service',
  unconnectedAdsViewedText: 'You\'ve seen $1# Ads$2 this month',
  viewAllLink: 'View all',
  viewStoreLink: 'View Store',
  wdpCheckboxLabel: 'Yes, I’d also like to contribute to Brave Search and opt in to $1Web Discovery Project$2.',
  wdpOptInText: 'Contribute some anonymous search and browsing data to refine Brave Search with Web Discovery Project. It’s completely open-source.',
  wdpOptInTitle: 'Web Discovery Project'
}
