# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      ApplyDisableSyncChanges looks on kBraveAndroidSyncPasswordsInProfileStore flag

      When the flag is enabled, then account store should not be wiped
      to preserve records till the migration at startup.
      Under the profile-store flag the account store is drained to
      the profile store by a startup migrator.
      Change wipe_model_upon_sync_disabled_behavior_ to act as the
      kNever case.
    preempt_function_impl:
      function_name: PasswordSyncBridge::ApplyDisableSyncChanges
      code: |-
        #if BUILDFLAG(IS_ANDROID)
          if (base::FeatureList::IsEnabled(
                  brave_sync::features::kBraveAndroidSyncPasswordsInProfileStore)) {
            wipe_model_upon_sync_disabled_behavior_ =
                syncer::WipeModelUponSyncDisabledBehavior::kNever;
          }
        #endif
  - description: |
      Suppress CHECK when flag is on

      Otherwise wipe_model_upon_sync_disabled_behavior_ is kNever
      and IsAccountStore() is true => failed CHECK
    regex:
      re_pattern: ' *CHECK\(!password_store_sync_->IsAccountStore\(\)\);'
      replace: |-
        #if BUILDFLAG(IS_ANDROID)
              CHECK(!password_store_sync_->IsAccountStore() ||
                    base::FeatureList::IsEnabled(
                        brave_sync::features::kBraveAndroidSyncPasswordsInProfileStore));
        #else
              CHECK(!password_store_sync_->IsAccountStore());
        #endif
