# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Remove const from wipe_model_upon_sync_disabled_behavior_

      We need this to modify iyt later at
      PasswordSyncBridge::ApplyDisableSyncChanges to preserve records
      at the account store till the migration at startup.
    regex:
      re_pattern: |-
        const (syncer::WipeModelUponSyncDisabledBehavior\s+wipe_model_upon_sync_disabled_behavior_\;)
      replace: \1
