# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Add `vertical tab controller` to the ctor.

      This `vertical_tab_controller_` field is required for `NormalBrowserSupportsWindowFeature`.
    re_pattern: '(WindowFeatureController::WindowFeatureController\(.*?)(\)\n\s+:)'
    re_flags: [DOTALL]
    replace: |-
      \1,
          VerticalTabController& vertical_tab_controller\2

  - description: |
      Initialise `vertical_tab_controller_` in the constructor

      This `vertical_tab_controller_` field is required for `NormalBrowserSupportsWindowFeature`.
    re_pattern: '(WindowFeatureController::WindowFeatureController\(.*?)( \{\})'
    re_flags: [DOTALL]
    replace: |-
      \1,
            vertical_tab_controller_(vertical_tab_controller)\2

  - description: |
      Make `NormalBrowserSupportsWindowFeature` an internal method

      This is done so we can provide our own `NormalBrowserSupportsWindowFeature` with
      specific handling for Windows.
    pattern: 'WindowFeatureController::NormalBrowserSupportsWindowFeature('
    replace: 'WindowFeatureController::NormalBrowserSupportsWindowFeature_ChromiumImpl('
