# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Add `vertical tab controller` to the ctor arg list

      This `vertical_tab_controller_` field is required for `NormalBrowserSupportsWindowFeature`.
    re_pattern: '(WindowFeatureController\((?=[^)]*ui::UnownedUserDataHost).*?)(\);)'
    re_flags: [DOTALL]
    replace: |-
      \1,
            VerticalTabController& vertical_tab_controller\2

  - description: |
      Add `vertical_tab_controller_` as the last member of WindowFeatureController

      This `vertical_tab_controller_` field is required for `NormalBrowserSupportsWindowFeature`.
    re_pattern: '(class WindowFeatureController \{.*)(\n\};)'
    re_flags: [DOTALL]
    replace: |-
      \1
        const raw_ref<VerticalTabController> vertical_tab_controller_;\2

  - description: |
      Mirror NormalBrowserSupportsWindowFeature as `_ChromiumImpl`

      This sibling function is required for the customisation of
      NormalBrowserSupportsWindowFeature.
    re_pattern:
      '(bool )(NormalBrowserSupportsWindowFeature)(\([\s\S]*?\) const;)'
    replace: |-
      \1\2\3
        \1\2_ChromiumImpl\3
