# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Add the Brave content browser sources.
    add_literal_to_list:
      target: browser
      list_name: sources
      literal: brave_content_browser_sources
      import: //brave/content/browser/sources.gni

  - description: Add the Brave content browser deps.
    add_literal_to_list:
      target: browser
      list_name: deps
      literal: brave_content_browser_deps
      import: //brave/content/browser/sources.gni

  - description: Widen the content test visibility for Brave.
    add_literal_to_list:
      target: for_content_tests
      list_name: visibility
      literal: brave_content_browser_for_content_tests_visibility
      import: //brave/content/browser/sources.gni
