# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Add the Brave sandbox sources.
    add_literal_to_list:
      target: sandbox
      list_name: sources
      literal: brave_sandbox_win_sandbox_sources
      import: //brave/sandbox/win/sources.gni
