# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: 'Ship kLiveCaption disabled.'
    set_feature_flag_default_state:
      feature_name: kLiveCaption
      value: base::FEATURE_DISABLED_BY_DEFAULT

  - description: 'Ship kEnableTabMuting enabled.'
    set_feature_flag_default_state:
      feature_name: kEnableTabMuting
      value: base::FEATURE_ENABLED_BY_DEFAULT

  - description: |-
      Ship kGetDisplayMediaConfersActivation disabled, because it treats
      permission grants as blanket user gestures.
    set_feature_flag_default_state:
      feature_name: kGetDisplayMediaConfersActivation
      value: base::FEATURE_DISABLED_BY_DEFAULT

  - description: |-
      Ship kAutoplayBypassForMicCamera disabled, because if you grant permission
      for mic/camera, the website can always autoplay in the future. Seems like
      a bad idea, especially for audio-based fingerprinting attacks.
    set_feature_flag_default_state:
      feature_name: kAutoplayBypassForMicCamera
      value: base::FEATURE_DISABLED_BY_DEFAULT

  - description: |-
      Ship kMediaDrmGetStatusForPolicy disabled, because it reveals hardware
      info related to DRM about the user on Android. The worry here is that
      websites might default to lower media quality but we can revisit this
      later if there is legit website support.
    set_feature_flag_default_state:
      feature_name: kMediaDrmGetStatusForPolicy
      value: base::FEATURE_DISABLED_BY_DEFAULT
