# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: 'Ship kLiveCaption disabled.'
    set_feature_flag_default_state:
      feature_name: kLiveCaption
      value: base::FEATURE_DISABLED_BY_DEFAULT

  - description: 'Ship kEnableTabMuting enabled.'
    set_feature_flag_default_state:
      feature_name: kEnableTabMuting
      value: base::FEATURE_ENABLED_BY_DEFAULT
