/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

export const enum types {
  // actions triggered by the sync back-end
  SYNC_ON_SHOW_SETTINGS = '@@sync/SYNC_ON_SHOW_SETTINGS',
  SYNC_ON_HAVE_SYNC_WORDS = '@@sync/SYNC_ON_HAVE_SYNC_WORDS',
  SYNC_ON_HAVE_SEED_FOR_QR_CODE = '@@sync/SYNC_ON_HAVE_SEED_FOR_QR_CODE',
  SYNC_ON_LOG_MESSAGE = '@@sync/SYNC_ON_LOG_MESSAGE',

  // other actions
  SYNC_INIT = '@@sync/SYNC_INIT',
  SYNC_SETUP_OWN_DEVICE = '@@sync/SYNC_SETUP_OWN_DEVICE',
  SYNC_SETUP_ANOTHER_DEVICE = '@@sync/SYNC_SETUP_ANOTHER_DEVICE',
  SYNC_REQUEST_QR_CODE = '@@sync/SYNC_REQUEST_QR_CODE',
  SYNC_REQUEST_SYNC_WORDS = '@@sync/SYNC_REQUEST_SYNC_WORDS',
  SYNC_TOGGLE_OWN_DEVICE_SYNCING = '@@sync/SYNC_TOGGLE_OWN_DEVICE_SYNCING',
  SYNC_BOOKMARKS_DATA = '@@sync/SYNC_BOOKMARKS_DATA',
  SYNC_SAVED_SITE_SETTINGS = '@@sync/SYNC_SAVED_SITE_SETTINGS',
  SYNC_BROWSING_HISTORY = '@@sync/SYNC_BROWSING_HISTORY',
  SYNC_REMOVE_DEVICE = '@@sync/SYNC_REMOVE_DEVICE',
  SYNC_RESET = '@@sync/SYNC_RESET',
  //  legacy actions from browser-laptop: check
  APP_CREATE_SYNC_CACHE = '@@sync/APP_CREATE_SYNC_CACHE',
  APP_PENDING_SYNC_RECORDS_ADDED = '@@sync/APP_PENDING_SYNC_RECORDS_ADDED',
  APP_PENDING_SYNC_RECORDS_REMOVED = '@@sync/APP_PENDING_SYNC_RECORDS_REMOVED',
  APP_SAVE_SYNC_DEVICES = '@@sync/APP_SAVE_SYNC_DEVICES',
  APP_SAVE_SYNC_INIT_DATA = '@@sync/APP_SAVE_SYNC_INIT_DATA',
  APP_RESET_SYNC_DATA = '@@sync/APP_RESET_SYNC_DATA',
  APP_SET_SYNC_SETUP_ERROR = '@@sync/APP_SET_SYNC_SETUP_ERROR'
}
