# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Use download_crx_util.cc, not the Android stub, with the core.
    regex:
      pattern: 'if (is_android && !enable_desktop_android_extensions) {'
      replace: 'if (is_android && !enable_extensions_core) {'
