# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

[[substitution]]
description = '''Using `chromium_impl::CookieMonster` for this type.

`CookieMonsterChangeDispatcher` has to use `chromium_impl::CookieMonster`
because it gets used by the Chromium implementation of `CookieMonster`.
'''
re_pattern = '\bCookieMonster\b'
replace = 'chromium_impl::CookieMonster'
count = 4

[[substitution]]
description = '''Fixing foward decl for chromium_impl::CookieMonster.

The previous substitution replaces all occurrences of `CookieMonster`,
including the one that was foward-declaring `CookieMonster`, this results in
broken C++ syntax that has to be corrected, to open a namespace and then
forward-declare inside it.
'''
pattern = 'class chromium_impl::CookieMonster;'
replace = '''namespace chromium_impl {
class CookieMonster;
}'''
