// Copyright (c) 2023 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

namespace config {

    dictionary BackoffPolicy {
        long num_errors_to_ignore;
        long initial_delay_ms;
        double multiply_factor;
        double jitter_factor;
        DOMString maximum_backoff_ms;
        boolean always_use_initial_delay;
    };

    dictionary ModelSpec {
        long num_params;
        long batch_size;
        double learning_rate;
        long num_iterations;
        double threshold;
    };

    dictionary Config {
        BackoffPolicy reconnect_policy;
        BackoffPolicy request_task_policy;
        BackoffPolicy post_results_policy;
        ModelSpec model_spec;
    };
};

