# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: 'Make PaintClientEdge virtual'
    make_virtual:
      class_name: OpaqueBrowserFrameView
      method_name: PaintClientEdge

  - description:
      'Make UpdateCaptionButtonPlaceholderContainerBackground virtual'
    make_virtual:
      class_name: OpaqueBrowserFrameView
      method_name: UpdateCaptionButtonPlaceholderContainerBackground

  - description: 'Friend BraveOpaqueBrowserFrameView'
    add_friend:
      class_name: OpaqueBrowserFrameView
      friend_type: class BraveOpaqueBrowserFrameView
