# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Add the Brave password manager java sources.
    add_literal_to_list:
      target: java
      list_name: sources
      literal: brave_browser_password_manager_java_sources
      import: //brave/browser/password_manager/android/java_sources.gni

  - description: Add the Brave password manager java deps.
    add_literal_to_list:
      target: java
      list_name: deps
      literal: brave_browser_password_manager_deps
      import: //brave/browser/password_manager/android/java_sources.gni

  - description: Add the Brave password manager JNI headers.
    add_literal_to_list:
      target: jni_headers
      list_name: sources
      literal: brave_browser_password_manager_jni_headers
      import: //brave/browser/password_manager/android/java_sources.gni
