# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description:
      'Add deps needed by Brave overrides in the lifetime:impl target'
    regex:
      re_pattern:
        '(\n    sources \+= \[\n      "application_lifetime_desktop\.cc")'
      replace: |-
        \n    import("//brave/chromium_src/chrome/browser/lifetime/sources.gni") deps += brave_chrome_browser_lifetime_impl_deps\1
