// Copyright (c) 2023 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

#include "brave/components/webui/webui_resources.h"

#include <vector>

#include "base/containers/flat_map.h"
#include "base/no_destructor.h"
#include "base/strings/utf_string_conversions.h"
#include "brave/components/brave_vpn/common/buildflags/buildflags.h"
#include "brave/components/constants/url_constants.h"
#include "brave/components/tor/buildflags/buildflags.h"
#include "build/build_config.h"
#include "components/grit/brave_components_resources.h"
#include "components/grit/brave_components_strings.h"
#include "components/grit/components_resources.h"
#include "ui/base/l10n/l10n_util.h"
#include "ui/base/webui/resource_path.h"
#include "ui/base/webui/web_ui_util.h"

#if !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_IOS)
#include "brave/components/brave_rewards/resources/grit/brave_rewards_resources.h"
#endif

namespace brave {

base::span<const webui::ResourcePath> GetWebUIResources(
    std::string_view webui_name) {
  static const base::NoDestructor<
      base::flat_map<std::string_view, std::vector<webui::ResourcePath>>>
      kResources{{
#if !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_IOS)
          {"newtab",
           {{"img/toolbar/menu_btn.svg", IDR_BRAVE_COMMON_TOOLBAR_IMG},
            // Hash path is the MD5 of the file contents,
            // webpack image loader does this
            {"fd85070af5114d6ac462c466e78448e4.svg", IDR_BRAVE_NEW_TAB_IMG1},
            {"314e7529efec41c8867019815f4d8dad.svg", IDR_BRAVE_NEW_TAB_IMG4},
            {"6c337c63662ee0ba4e57f6f8156d69ce.svg", IDR_BRAVE_NEW_TAB_IMG2},
            // New tab Backgrounds
            {"dylan-malval_sea-min.webp", IDR_BRAVE_NEW_TAB_BACKGROUND1},
            // private tab
            {"c168145d6bf1abf2c0322636366f7dbe.svg",
             IDR_BRAVE_PRIVATE_TAB_TOR_IMG},
            {"dbdc336ccc651b8a7c925b3482d6e65a.svg",
             IDR_BRAVE_PRIVATE_TAB_IMG}}},
          {"rewards",
           {
               {"favicon.ico", IDR_BRAVE_REWARDS_FAVICON},
           }},
          {"welcome", {{"favicon.ico", IDR_BRAVE_WELCOME_PAGE_FAVICON}}},
#endif
          {"adblock", {}},
      }};

  if (auto it = kResources->find(webui_name); it != kResources->end()) {
    return it->second;
  }
  return {};
}  // NO-LINT (readability/fn_size)

base::span<const webui::LocalizedString> GetWebUILocalizedStrings(
    std::string_view webui_name) {
  static const base::NoDestructor<
      base::flat_map<std::string_view, std::vector<webui::LocalizedString>>>
      kLocalizedStrings{{
          {"newtab",
           {
               {"adsTrackersBlocked",
                IDS_BRAVE_NEW_TAB_TOTAL_ADS_TRACKERS_BLOCKED},
               {"httpsUpgraded", IDS_BRAVE_NEW_TAB_TOTAL_HTTPS_UPGRADES},
               {"estimatedTimeSaved", IDS_BRAVE_NEW_TAB_TOTAL_TIME_SAVED},
               {"estimatedBandwidthSaved",
                IDS_BRAVE_NEW_TAB_ESTIMATED_BANDWIDTH_SAVED},
               {"thumbRemoved", IDS_BRAVE_NEW_TAB_THUMB_REMOVED},
               {"undoRemoved", IDS_BRAVE_NEW_TAB_UNDO_REMOVED},
               {"close", IDS_BRAVE_NEW_TAB_CLOSE},
               {"restoreAll", IDS_BRAVE_NEW_TAB_RESTORE_ALL},
               {"second", IDS_BRAVE_NEW_TAB_SECOND},
               {"seconds", IDS_BRAVE_NEW_TAB_SECONDS},
               {"minute", IDS_BRAVE_NEW_TAB_MINUTE},
               {"minutes", IDS_BRAVE_NEW_TAB_MINUTES},
               {"hour", IDS_BRAVE_NEW_TAB_HOUR},
               {"hours", IDS_BRAVE_NEW_TAB_HOURS},
               {"day", IDS_BRAVE_NEW_TAB_DAY},
               {"days", IDS_BRAVE_NEW_TAB_DAYS},
               {"B", IDS_BRAVE_NEW_TAB_BYTES},
               {"KB", IDS_BRAVE_NEW_TAB_KILOBYTES},
               {"MB", IDS_BRAVE_NEW_TAB_MEGABYTES},
               {"GB", IDS_BRAVE_NEW_TAB_GIGABYTES},
               {"photoBy", IDS_BRAVE_NEW_TAB_PHOTO_BY},
               {"hide", IDS_BRAVE_NEW_TAB_HIDE},
               {"dashboardSettingsTitle",
                IDS_BRAVE_NEW_TAB_DASHBOARD_SETTINGS_TITLE},
               {"customize", IDS_BRAVE_NEW_TAB_CUSTOMIZE},
               {"showBackgroundImage", IDS_BRAVE_NEW_TAB_SHOW_BACKGROUND_IMAGE},
               {"braveBackgroundImageOptionTitle",
                IDS_BRAVE_NEW_TAB_BRAVE_BACKGROUND_IMAGE_OPTION_TITLE},
               {"customBackgroundImageOptionTitle",
                IDS_BRAVE_NEW_TAB_CUSTOM_BACKGROUND_IMAGE_OPTION_TITLE},
               {"customBackgroundImageOptionUploadLabel",
                IDS_BRAVE_NEW_TAB_CUSTOM_BACKGROUND_IMAGE_OPTION_UPLOAD_LABEL},
               {"showBraveStats", IDS_BRAVE_NEW_TAB_SHOW_BRAVE_STATS},
               {"showClock", IDS_BRAVE_NEW_TAB_SHOW_CLOCK},
               {"clockFormat", IDS_BRAVE_NEW_TAB_CLOCK_FORMAT},
               {"clockFormatDefault", IDS_BRAVE_NEW_TAB_CLOCK_FORMAT_DEFAULT},
               {"clockFormat12", IDS_BRAVE_NEW_TAB_CLOCK_FORMAT_12},
               {"clockFormat24", IDS_BRAVE_NEW_TAB_CLOCK_FORMAT_24},
               {"addTopSiteDialogTitle",
                IDS_BRAVE_NEW_TAB_ADD_TOP_SITE_DIALOG_TITLE},
               {"editTopSiteDialogTitle",
                IDS_BRAVE_NEW_TAB_EDIT_TOP_SITE_DIALOG_TITLE},
               {"editSiteTileMenuItem",
                IDS_BRAVE_NEW_TAB_EDIT_SITE_TILE_MENU_ITEM},
               {"removeTileMenuItem", IDS_BRAVE_NEW_TAB_REMOVE_TILE_MENU_ITEM},
               {"addTopSiteDialogURLLabel",
                IDS_BRAVE_NEW_TAB_ADD_TOP_SITE_DIALOG_URL_LABEL},
               {"addTopSiteDialogURLInputPlaceHolder",
                IDS_BRAVE_NEW_TAB_ADD_TOP_SITE_DIALOG_URL_INPUT_PLACEHOLDER},
               {"addTopSiteDialogNameLabel",
                IDS_BRAVE_NEW_TAB_ADD_TOP_SITE_DIALOG_NAME_LABEL},
               {"addTopSiteDialogNameInputPlaceHolder",
                IDS_BRAVE_NEW_TAB_ADD_TOP_SITE_DIALOG_NAME_INPUT_PLACEHOLDER},
               {"addTopSiteDialogSaveButtonLabel",
                IDS_BRAVE_NEW_TAB_ADD_TOP_SITE_DIALOG_SAVE_BUTTON_LABEL},
               {"addTopSiteDialogCancelButtonLabel",
                IDS_BRAVE_NEW_TAB_ADD_TOP_SITE_DIALOG_CANCEL_BUTTON_LABEL},
               {"showTopSites", IDS_BRAVE_NEW_TAB_SHOW_TOP_SITES},
               {"showFavoritesLabel", IDS_BRAVE_NEW_TAB_SHOW_FAVORITES_LABEL},
               {"showFavoritesDesc", IDS_BRAVE_NEW_TAB_SHOW_FAVORITES_DESC},
               {"showFrecencyLabel", IDS_BRAVE_NEW_TAB_SHOW_FRECENCY_LABEL},
               {"showFrecencyDesc", IDS_BRAVE_NEW_TAB_SHOW_FRECENCY_DESC},
               {"addSiteMenuLabel", IDS_BRAVE_NEW_TAB_ADD_SITE_MENU_LABEL},
               {"showFrecencyMenuLabel",
                IDS_BRAVE_NEW_TAB_SHOW_FRECENCY_MENU_LABEL},
               {"showFavoritesMenuLabel",
                IDS_BRAVE_NEW_TAB_SHOW_FAVORITES_MENU_LABEL},
               {"searchCustomizeList", IDS_BRAVE_NEW_TAB_SEARCH_CUSTOMIZE_LIST},
               {"searchBravePlaceholder",
                IDS_BRAVE_NEW_TAB_SEARCH_BRAVE_PLACEHOLDER},
               {"searchHide", IDS_BRAVE_NEW_TAB_SEARCH_HIDE_SEARCH},
               {"searchAskLeo", IDS_OMNIBOX_ASK_LEO_DESCRIPTION},
               {"searchNonBravePlaceholder",
                IDS_BRAVE_NEW_TAB_SEARCH_NON_BRAVE_PLACEHOLDER},
               {"searchShowSetting", IDS_BRAVE_NEW_TAB_SEARCH_SHOW_SETTING},
               {"searchEnableSearchEnginesTitle",
                IDS_BRAVE_NEW_TAB_SEARCH_ENABLE_SEARCH_ENGINES_TITLE},
               {"searchCustomizeSearchEngines",
                IDS_BRAVE_NEW_TAB_SEARCH_CUSTOMIZE_SEARCH_ENGINES},
               {"searchEnableSuggestionsPromptTitle",
                IDS_BRAVE_NEW_TAB_SEARCH_ENABLE_SEARCH_SUGGESTIONS_TITLE},
               {"searchEnableSuggestionsPromptExplanation",
                IDS_BRAVE_NEW_TAB_SEARCH_ENABLE_SEARCH_SUGGESTIONS_EXPLANATION},
               {"searchEnableSuggestionsPromptEnable",
                IDS_BRAVE_NEW_TAB_SEARCH_ENABLE_SEARCH_SUGGESTIONS_ENABLE},
               {"searchEnableSuggestionsPromptDismiss",
                IDS_BRAVE_NEW_TAB_SEARCH_ENABLE_SEARCH_SUGGESTIONS_DISMISS},
               {"showRewards", IDS_BRAVE_NEW_TAB_SHOW_REWARDS},
               {"cards", IDS_BRAVE_NEW_TAB_SHOW_CARDS},
               {"brandedWallpaperOptIn",
                IDS_BRAVE_NEW_TAB_BRANDED_WALLPAPER_OPT_IN},
               {"sponsoredImageEarningTitle",
                IDS_BRAVE_NEW_TAB_SPONSORED_IMAGE_EARNING_TITLE},
               {"sponsoredImageEnableRewards",
                IDS_BRAVE_NEW_TAB_SPONSORED_IMAGE_ENABLE_REWARDS},
               {"sponsoredImageNotEarningTitle",
                IDS_BRAVE_NEW_TAB_SPONSORED_IMAGE_NOT_EARNING_TITLE},
               {"sponsoredImageOffRewardsOnDescription",
                IDS_BRAVE_NEW_TAB_SPONSORED_IMAGE_OFF_REWARDS_ON_DESCRPTION},
               {"sponsoredImageOnDescription",
                IDS_BRAVE_NEW_TAB_SPONSORED_IMAGE_ON_DESCRIPTION},
               {"sponsoredImageOnRewardsOnNoCustodianDescription",
                IDS_BRAVE_NEW_TAB_SPONSORED_IMAGE_ON_REWARDS_ON_NO_CUSTODIAN_DESCRIPTION},
               {"sponsoredImageRewardsOffDescription",
                IDS_BRAVE_NEW_TAB_SPONSORED_IMAGE_REWARDS_OFF_DESCRIPTION},
               {"topSitesTitle", IDS_BRAVE_NEW_TAB_TOP_SITES},
               {"statsTitle", IDS_BRAVE_NEW_TAB_STATS},
               {"clockTitle", IDS_BRAVE_NEW_TAB_CLOCK},
               {"searchTitle", IDS_BRAVE_NEW_TAB_SEARCH},
               {"backgroundImageTitle", IDS_BRAVE_NEW_TAB_BACKGROUND_IMAGE},
               {"settingsNavigateBack", IDS_BRAVE_NEW_TAB_SETTINGS_BACK},
               {"braveBackgroundsTitle", IDS_BRAVE_NEW_TAB_BRAVE_BACKGROUND},
               {"solidColorTitle", IDS_BRAVE_NEW_TAB_SOLID_COLOR},
               {"gradientColorTitle", IDS_BRAVE_NEW_TAB_GRADIENT_COLOR},
               {"refreshBackgroundOnNewTab",
                IDS_BRAVE_NEW_TAB_REFRESH_BACKGROUND_ON_NEW_TAB},
               {"rewardsOpenPanel", IDS_BRAVE_NEW_TAB_REWARDS_OPEN_PANEL},

               // search promotion
               {"searchPromotionNTPPopupTitle1",
                IDS_BRAVE_NEW_TAB_SEARCH_PROMOTION_POPUP_TITLE_1},
               {"searchPromotionNTPPopupTitle2",
                IDS_BRAVE_NEW_TAB_SEARCH_PROMOTION_POPUP_TITLE_2},
               {"searchPromotionNTPPopupDesc",
                IDS_BRAVE_NEW_TAB_SEARCH_PROMOTION_POPUP_DESC},
               {"searchPromotionNTPPopupBottom",
                IDS_BRAVE_NEW_TAB_SEARCH_PROMOTION_POPUP_BOTTOM},
               {"searchPromotionSearchBoxPlaceholderLabel",
                IDS_BRAVE_NEW_TAB_SEARCH_PROMOTION_SEARCH_BOX_PLACEHOLDER},

               {"braveNewsTitle", IDS_BRAVE_NEWS_TITLE},
               {"braveNewsStatusFetching", IDS_BRAVE_NEWS_STATUS_FETCHING},
               {"braveNewsActionRefresh", IDS_BRAVE_NEWS_ACTION_REFRESH},
               {"braveNewsScrollHint", IDS_BRAVE_NEWS_SCROLL_HINT},
               {"braveNewsResetAction", IDS_BRAVE_NEWS_RESET_ACTION},
               {"braveNewsResetConfirm", IDS_BRAVE_NEWS_RESET_CONFIRM},
               {"braveNewsCategoryNameAll", IDS_BRAVE_NEWS_CATEGORY_NAME_ALL},
               {"braveNewsSourcesTitle", IDS_BRAVE_NEWS_SOURCES_TITLE},
               {"braveNewsDisableSourceCommand",
                IDS_BRAVE_NEWS_DISABLE_SOURCE_COMMAND},
               {"promoted", IDS_BRAVE_NEWS_PROMOTED},
               {"ad", IDS_BRAVE_NEWS_DISPLAY_AD_LABEL},

               {"braveNewsIntroTitle", IDS_BRAVE_NEWS_INTRO_TITLE},
               {"braveNewsIntroDescription", IDS_BRAVE_NEWS_INTRO_DESCRIPTION},
               {"braveNewsIntroDescriptionTwo",
                IDS_BRAVE_NEWS_INTRO_DESCRIPTION_TWO},
               {"braveNewsOptInActionLabel",
                IDS_BRAVE_NEWS_OPT_IN_ACTION_LABEL},
               {"braveNewsOptOutActionLabel",
                IDS_BRAVE_NEWS_OPT_OUT_ACTION_LABEL},
               {"braveNewsBackToDashboard", IDS_BRAVE_NEWS_BACK_TO_DASHBOARD},
               {"braveNewsBackButton", IDS_BRAVE_NEWS_BACK_BUTTON},
               {"braveNewsSearchPlaceholderLabel",
                IDS_BRAVE_NEWS_SEARCH_PLACEHOLDER_LABEL},
               {"braveNewsChannelsHeader",
                IDS_BRAVE_NEWS_BROWSE_CHANNELS_HEADER},
               {"braveNewsViewAllButton", IDS_BRAVE_NEWS_VIEW_ALL_BUTTON},
               {"braveNewsAllSourcesHeader", IDS_BRAVE_NEWS_ALL_SOURCES_HEADER},
               {"braveNewsFeedsHeading", IDS_BRAVE_NEWS_FEEDS_HEADING},
               {"braveNewsFollowButtonFollowing",
                IDS_BRAVE_NEWS_FOLLOW_BUTTON_FOLLOWING},
               {"braveNewsFollowButtonNotFollowing",
                IDS_BRAVE_NEWS_FOLLOW_BUTTON_NOT_FOLLOWING},
               {"braveNewsDirectSearchButton",
                IDS_BRAVE_NEWS_DIRECT_SEARCH_BUTTON},
               {"braveNewsDirectSearchNoResults",
                IDS_BRAVE_NEWS_DIRECT_SEARCH_NO_RESULTS},
               {"braveNewsSearchResultsNoResults",
                IDS_BRAVE_NEWS_SEARCH_RESULTS_NO_RESULTS},
               {"braveNewsSearchResultsLocalResults",
                IDS_BRAVE_NEWS_SEARCH_RESULTS_LOCAL_RESULTS},
               {"braveNewsSearchResultsDirectResults",
                IDS_BRAVE_NEWS_SEARCH_RESULTS_DIRECT_RESULTS},
               {"braveNewsSearchQueryTooShort",
                IDS_BRAVE_NEWS_SEARCH_QUERY_TOO_SHORT},
               {"braveNewsSuggestionsTitle", IDS_BRAVE_NEWS_SUGGESTIONS_TITLE},
               {"braveNewsSuggestionsSubtitle",
                IDS_BRAVE_NEWS_SUGGESTIONS_SUBTITLE},
               {"braveNewsErrorHeading", IDS_BRAVE_NEWS_ERROR_HEADING},
               {"braveNewsErrorMessage", IDS_BRAVE_NEWS_ERROR_MESSAGE},
               {"braveNewsErrorActionLabel", IDS_BRAVE_NEWS_ERROR_ACTION_LABEL},
               {"braveNewsNoContentHeading", IDS_BRAVE_NEWS_NO_CONTENT_HEADING},
               {"braveNewsNoContentMessage", IDS_BRAVE_NEWS_NO_CONTENT_MESSAGE},
               {"braveNewsNoContentActionLabel",
                IDS_BRAVE_NEWS_NO_CONTENT_ACTION_LABEL},
               {"braveNewsPopularTitle", IDS_BRAVE_NEWS_POPULAR_TITLE},
               {"braveNewsNewsPeek", IDS_BRAVE_NEWS_NEWS_PEEK},
               {"braveNewsForYouFeed", IDS_BRAVE_NEWS_FOR_YOU_FEED},
               {"braveNewsFollowingFeed", IDS_BRAVE_NEWS_FOLLOWING_FEED},
               {"braveNewsPublishersHeading",
                IDS_BRAVE_NEWS_PUBLISHERS_HEADING},
               {"braveNewsShowAll", IDS_BRAVE_NEWS_SHOW_ALL},
               {"braveNewsShowLess", IDS_BRAVE_NEWS_SHOW_LESS},
               {"braveNewsAdvertBadge", IDS_BRAVE_NEWS_ADVERT_BADGE},
               {"braveNewsHideContentFrom", IDS_BRAVE_NEWS_HIDE_CONTENT_FROM},
               {"braveNewsSourcesRecommendation",
                IDS_BRAVE_NEWS_SOURCES_RECOMMENDATION},
               {"braveNewsNoArticlesTitle", IDS_BRAVE_NEWS_NO_ARTICLES_TITLE},
               {"braveNewsNoArticlesMessage",
                IDS_BRAVE_NEWS_NO_ARTICLES_MESSAGE},
               {"braveNewsOfflineTitle", IDS_BRAVE_NEWS_OFFLINE_TITLE},
               {"braveNewsOfflineMessage", IDS_BRAVE_NEWS_OFFLINE_MESSAGE},
               {"braveNewsCustomizeFeed", IDS_BRAVE_NEWS_CUSTOMIZE_FEED},
               {"braveNewsRefreshFeed", IDS_BRAVE_NEWS_REFRESH_FEED},
               {"braveNewsOpenArticlesIn", IDS_BRAVE_NEWS_OPEN_ARTICLES_IN},
               {"braveNewsOpenArticlesInNewTab",
                IDS_BRAVE_NEWS_OPEN_ARTICLES_IN_NEW_TAB},
               {"braveNewsOpenArticlesInCurrentTab",
                IDS_BRAVE_NEWS_OPEN_ARTICLES_IN_CURRENT_TAB},
               {"braveNewsCaughtUp", IDS_BRAVE_NEWS_CAUGHT_UP},
               {"braveNewsNewContentAvailable",
                IDS_BRAVE_NEWS_NEW_CONTENT_AVAILABLE},

               // Brave News Channels
               {"braveNewsChannel-Brave", IDS_BRAVE_NEWS_CHANNEL_BRAVE},
               {"braveNewsChannel-Business", IDS_BRAVE_NEWS_CHANNEL_BUSINESS},
               {"braveNewsChannel-Cars", IDS_BRAVE_NEWS_CHANNEL_CARS},
               {"braveNewsChannel-Celebrities",
                IDS_BRAVE_NEWS_CHANNEL_CELEBRITIES},
               {"braveNewsChannel-Crypto", IDS_BRAVE_NEWS_CHANNEL_CRYPTO},
               {"braveNewsChannel-Culture", IDS_BRAVE_NEWS_CHANNEL_CULTURE},
               {"braveNewsChannel-Education", IDS_BRAVE_NEWS_CHANNEL_EDUCATION},
               {"braveNewsChannel-Entertainment",
                IDS_BRAVE_NEWS_CHANNEL_ENTERTAINMENT},
               {"braveNewsChannel-Fashion", IDS_BRAVE_NEWS_CHANNEL_FASHION},
               {"braveNewsChannel-Film and TV",
                IDS_BRAVE_NEWS_CHANNEL_FILM_AND_TV},
               {"braveNewsChannel-Food", IDS_BRAVE_NEWS_CHANNEL_FOOD},
               {"braveNewsChannel-Fun", IDS_BRAVE_NEWS_CHANNEL_FUN},
               {"braveNewsChannel-Gaming", IDS_BRAVE_NEWS_CHANNEL_GAMING},
               {"braveNewsChannel-Health", IDS_BRAVE_NEWS_CHANNEL_HEALTH},
               {"braveNewsChannel-Home", IDS_BRAVE_NEWS_CHANNEL_HOME},
               {"braveNewsChannel-Lifestyle", IDS_BRAVE_NEWS_CHANNEL_LIFESTYLE},
               {"braveNewsChannel-Music", IDS_BRAVE_NEWS_CHANNEL_MUSIC},
               {"braveNewsChannel-Politics", IDS_BRAVE_NEWS_CHANNEL_POLITICS},
               {"braveNewsChannel-Regional News",
                IDS_BRAVE_NEWS_CHANNEL_REGIONAL_NEWS},
               {"braveNewsChannel-Science", IDS_BRAVE_NEWS_CHANNEL_SCIENCE},
               {"braveNewsChannel-Sports", IDS_BRAVE_NEWS_CHANNEL_SPORTS},
               {"braveNewsChannel-Travel", IDS_BRAVE_NEWS_CHANNEL_TRAVEL},
               {"braveNewsChannel-Technology",
                IDS_BRAVE_NEWS_CHANNEL_TECHNOLOGY},
               {"braveNewsChannel-Top News", IDS_BRAVE_NEWS_CHANNEL_TOP_NEWS},
               {"braveNewsChannel-Top Sources",
                IDS_BRAVE_NEWS_CHANNEL_TOP_SOURCES},
               {"braveNewsChannel-UK News", IDS_BRAVE_NEWS_CHANNEL_UK_NEWS},
               {"braveNewsChannel-US News", IDS_BRAVE_NEWS_CHANNEL_US_NEWS},
               {"braveNewsChannel-Weather", IDS_BRAVE_NEWS_CHANNEL_WEATHER},
               {"braveNewsChannel-World News",
                IDS_BRAVE_NEWS_CHANNEL_WORLD_NEWS},

               {"addWidget", IDS_BRAVE_NEW_TAB_WIDGET_ADD},
               {"hideWidget", IDS_BRAVE_NEW_TAB_WIDGET_HIDE},
               {"rewardsWidgetDesc", IDS_BRAVE_NEW_TAB_REWARDS_WIDGET_DESC},
               {"cardsToggleTitle", IDS_BRAVE_NEW_TAB_CARDS_TITLE},
               {"cardsToggleDesc", IDS_BRAVE_NEW_TAB_CARDS_DESC},
               {"editCardsTitle", IDS_EDIT_CARDS_TITLE},
               {"braveRewardsTitle", IDS_BRAVE_NEW_TAB_BRAVE_REWARDS_TITLE},
#if !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_IOS)
               // Private Tab - General
               {"learnMore", IDS_BRAVE_PRIVATE_NEW_TAB_LEARN_MORE},
               {"done", IDS_BRAVE_PRIVATE_NEW_TAB_DONE},
               {"headerLabel", IDS_BRAVE_PRIVATE_NEW_TAB_THIS_IS_A},

               // Private Tab - Header Private Window
               {"headerTitle", IDS_BRAVE_PRIVATE_NEW_TAB_PRIVATE_WINDOW},
               {"headerText", IDS_BRAVE_PRIVATE_NEW_TAB_PRIVATE_WINDOW_DESC},
               {"headerText1", IDS_BRAVE_PRIVATE_NEW_TAB_PRIVATE_WINDOW_DESC1},
               {"headerText2", IDS_BRAVE_PRIVATE_NEW_TAB_PRIVATE_WINDOW_DESC2},
               {"headerButton",
                IDS_BRAVE_PRIVATE_NEW_TAB_PRIVATE_WINDOW_BUTTON},

               // Private Tab - Header Private Window with Tor
               {"headerTorTitle", IDS_BRAVE_PRIVATE_NEW_TAB_PRIVATE_WINDOW_TOR},
               {"headerTorText",
                IDS_BRAVE_PRIVATE_NEW_TAB_PRIVATE_WINDOW_TOR_DESC},

               // Private Tab - Box for DDG
               {"boxDdgButton", IDS_BRAVE_PRIVATE_NEW_TAB_BOX_DDG_BUTTON},

               // Private Tab - Box for Tor
               {"boxTorLabel", IDS_BRAVE_PRIVATE_NEW_TAB_BOX_TOR_LABEL},
               {"boxTorLabel2", IDS_BRAVE_PRIVATE_NEW_TAB_BOX_TOR_LABEL_2},
               {"boxTorTitle", IDS_BRAVE_PRIVATE_NEW_TAB_BOX_TOR_TITLE},

               // Private Tab - Private Window with Tor - Tor Box
               {"boxTorText", IDS_BRAVE_PRIVATE_NEW_TAB_BOX_TOR_TEXT_1},

               // Private Tab - Private Window - Tor Box
               {"boxTorText2", IDS_BRAVE_PRIVATE_NEW_TAB_BOX_TOR_TEXT_2},
               {"boxTorButton", IDS_BRAVE_PRIVATE_NEW_TAB_BOX_TOR_BUTTON},
#endif  // !BUILDFLAG(IS_ANDROID)

               // Rewards widget
               {"rewardsAboutRewards", IDS_REWARDS_WIDGET_ABOUT_REWARDS},
               {"rewardsBraveRewards", IDS_REWARDS_WIDGET_BRAVE_REWARDS},
               {"rewardsConnectAccount", IDS_REWARDS_CONNECT_ACCOUNT},
               {"rewardsConnectAccountText", IDS_REWARDS_CONNECT_ACCOUNT_TEXT},
               {"rewardsContinue", IDS_REWARDS_WIDGET_CONTINUE},
               {"rewardsEarningsTitle", IDS_REWARDS_ESTIMATED_EARNINGS_TITLE},
               {"rewardsEarningInfoText", IDS_REWARDS_WIDGET_EARNING_INFO_TEXT},
               {"rewardsHowDoesItWork", IDS_REWARDS_WIDGET_HOW_DOES_IT_WORK},
               {"rewardsLearnMore", IDS_REWARDS_LEARN_MORE},
               {"rewardsManageAds", IDS_REWARDS_WALLET_MANAGE_ADS},
               {"rewardsNotNow", IDS_REWARDS_NOT_NOW},
               {"rewardsOptInHeader", IDS_REWARDS_WIDGET_OPT_IN_HEADER},
               {"rewardsOptInTerms", IDS_BRAVE_REWARDS_ONBOARDING_TERMS},
               {"rewardsOptInText", IDS_REWARDS_WIDGET_OPT_IN_TEXT},
               {"rewardsLogInToSeeBalance", IDS_REWARDS_LOG_IN_TO_SEE_BALANCE},
               {"rewardsPaymentCheckStatus", IDS_REWARDS_PAYMENT_CHECK_STATUS},
               {"rewardsPaymentCompleted", IDS_REWARDS_PAYMENT_COMPLETED},
               {"rewardsPaymentPending", IDS_REWARDS_PAYMENT_PENDING},
               {"rewardsPaymentProcessing", IDS_REWARDS_PAYMENT_PROCESSING},
               {"rewardsPaymentSupport", IDS_REWARDS_PAYMENT_SUPPORT},
               {"rewardsSelectCountryHeader",
                IDS_REWARDS_WIDGET_SELECT_COUNTRY_HEADER},
               {"rewardsSelectCountryText",
                IDS_REWARDS_WIDGET_SELECT_COUNTRY_TEXT},
               {"rewardsSelfCustodyInviteHeader",
                IDS_REWARDS_SELF_CUSTODY_INVITE_HEADER},
               {"rewardsSelfCustodyInviteText",
                IDS_REWARDS_SELF_CUSTODY_INVITE_TEXT},
               {"rewardsTosUpdateHeading", IDS_REWARDS_TOS_UPDATE_HEADING},
               {"rewardsTosUpdateText", IDS_REWARDS_TOS_UPDATE_TEXT},
               {"rewardsTosUpdateLinkText", IDS_REWARDS_TOS_UPDATE_LINK_TEXT},
               {"rewardsTosUpdateButtonLabel",
                IDS_REWARDS_TOS_UPDATE_BUTTON_LABEL},
               {"rewardsSettings", IDS_REWARDS_WIDGET_SETTINGS},
               {"rewardsStartUsingRewards",
                IDS_REWARDS_WIDGET_START_USING_REWARDS},
               {"rewardsBalanceTitle", IDS_REWARDS_WIDGET_BALANCE_TITLE},
               {"rewardsWidgetBraveRewards", IDS_BRAVE_UI_BRAVE_REWARDS},
               {"rewardsBrowserCannotReceiveAds",
                IDS_REWARDS_BROWSER_CANNOT_RECEIVE_ADS},
               {"rewardsBrowserNeedsUpdateToSeeAds",
                IDS_REWARDS_BROWSER_NEEDS_UPDATE_TO_SEE_ADS},
               {"rewardsVBATNoticeText1", IDS_REWARDS_VBAT_NOTICE_TEXT1},
               {"rewardsVBATNoticeTitle1", IDS_REWARDS_VBAT_NOTICE_TITLE1},

               {"loading", IDS_BRAVE_REWARDS_LOADING_LABEL},

#if BUILDFLAG(ENABLE_BRAVE_VPN) & !BUILDFLAG(IS_ANDROID)
               // Brave VPN Widget
               {"braveVpnWidgetTitle", IDS_BRAVE_VPN_WIDGET_TITLE},
               {"braveVpnWidgetSettingTitle", IDS_BRAVE_VPN_WIDGET_TITLE},
               {"braveVpnWidgetSettingDesc", IDS_BRAVE_VPN_WIDGET_SETTING_DESC},
               {"braveVpnFeature1", IDS_BRAVE_VPN_FEATURE_1},
               {"braveVpnFeature2", IDS_BRAVE_VPN_FEATURE_2},
               {"braveVpnWidgetFeature3", IDS_BRAVE_VPN_WIDGET_FEATURE_3},
               {"braveVpnConnected", IDS_BRAVE_VPN_CONNECTED},
               {"braveVpnConnecting", IDS_BRAVE_VPN_CONNECTING},
               {"braveVpnDisconnected", IDS_BRAVE_VPN_DISCONNECTED},
               {"braveVpnDisconnecting", IDS_BRAVE_VPN_DISCONNECTING},
               {"braveVpnPoweredBy", IDS_BRAVE_VPN_POWERED_BY},
               {"braveVpnOptimal",
                IDS_BRAVE_VPN_SERVER_SELECTION_OPTIMAL_LABEL},
               {"braveVpnChangeRegion", IDS_BRAVE_VPN_WIDGET_CHANGE_LABEL},
               {"braveVpnCTA", IDS_BRAVE_VPN_WIDGET_CTA},
               {"braveVpnPurchased", IDS_BRAVE_VPN_HAS_PURCHASED},
#endif

               // Brave Talk  Widget
               {"braveTalkWidgetTitle", IDS_BRAVE_TALK_WIDGET_TITLE},
               {"braveTalkWidgetWelcomeTitle",
                IDS_BRAVE_TALK_WIDGET_WELCOME_TITLE},
               {"braveTalkWidgetStartButton",
                IDS_BRAVE_TALK_WIDGET_START_BUTTON},
               {"braveTalkWidgetAboutData", IDS_BRAVE_TALK_WIDGET_ABOUT_DATA},
           }},
          {"wallet",
           {{"cryptoWalletsWelcome", IDS_BRAVE_WALLET_WELCOME},
            {"cryptoWalletsDisclosureOne", IDS_BRAVE_WALLET_DISCLOSURE_ONE},
            {"cryptoWalletsDisclosureTwo", IDS_BRAVE_WALLET_DISCLOSURE_TWO},
            {"cryptoWalletsDisclosureThree", IDS_BRAVE_WALLET_DISCLOSURE_THREE},
            {"cryptoWalletsDisclosureFour", IDS_BRAVE_WALLET_DISCLOSURE_FOUR},
            {"cryptoWalletsBraveRewards", IDS_BRAVE_WALLET_BRAVE_REWARDS},
            {"cryptoWalletsDownloading", IDS_BRAVE_WALLET_DOWNLOADING},
            {"cryptoWalletsDisclosureConfirm",
             IDS_BRAVE_WALLET_DISCLOSURE_CONFIRM}}},
          {"rewards",
           {
               {"adsCurrentEarnings",
                IDS_BRAVE_REWARDS_LOCAL_ADS_CURRENT_EARNINGS},
               {"adsDescription", IDS_BRAVE_REWARDS_LOCAL_ADS_DESCRIPTION},
               {"adsDescriptionEarn",
                IDS_BRAVE_REWARDS_LOCAL_ADS_DESCRIPTION_EARN},
               {"adsTotalReceivedLabel",
                IDS_BRAVE_REWARDS_LOCAL_ADS_TOTAL_RECEIVED},
               {"adsNotSupportedRegion",
                IDS_BRAVE_REWARDS_LOCAL_ADS_NOT_SUPPORTED_REGION},
               {"adsNotSupportedDevice",
                IDS_BRAVE_REWARDS_LOCAL_ADS_NOT_SUPPORTED_DEVICE},
               {"adsPaymentDate", IDS_BRAVE_REWARDS_LOCAL_ADS_PAYMENT_DATE},
               {"adsPerHour", IDS_BRAVE_REWARDS_LOCAL_ADS_PER_HOUR},
               {"adsPerHour0", IDS_BRAVE_REWARDS_LOCAL_ADS_PER_HOUR_0},
               {"adsPerHour1", IDS_BRAVE_REWARDS_LOCAL_ADS_PER_HOUR_1},
               {"adsPerHour2", IDS_BRAVE_REWARDS_LOCAL_ADS_PER_HOUR_2},
               {"adsPerHour3", IDS_BRAVE_REWARDS_LOCAL_ADS_PER_HOUR_3},
               {"adsPerHour4", IDS_BRAVE_REWARDS_LOCAL_ADS_PER_HOUR_4},
               {"adsPerHour5", IDS_BRAVE_REWARDS_LOCAL_ADS_PER_HOUR_5},
               {"adsPerHour10", IDS_BRAVE_REWARDS_LOCAL_ADS_PER_HOUR_10},
               {"adsSubdivisionTargetingTitle",
                IDS_BRAVE_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_TITLE},
               {"adsSubdivisionTargetingDescription",
                IDS_BRAVE_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_DESCRIPTION},
               {"adsSubdivisionTargetingLearn",
                IDS_BRAVE_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_LEARN},
               {"adsSubdivisionTargetingAutoDetectedAs",
                IDS_BRAVE_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_AUTO_DETECTED_AS},
               {"adsSubdivisionTargetingAutoDetect",
                IDS_BRAVE_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_AUTO_DETECT},
               {"adsSubdivisionTargetingDisable",
                IDS_BRAVE_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_DISABLE},
               {"adsSubdivisionTargetingDisabled",
                IDS_BRAVE_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_DISABLED},
               {"adsTitle", IDS_BRAVE_REWARDS_LOCAL_ADS_TITLE},
               {"newTabAdCountLabel", IDS_BRAVE_REWARDS_NEW_TAB_AD_COUNT_LABEL},
               {"notificationAdCountLabel",
                IDS_BRAVE_REWARDS_NOTIFICATION_AD_COUNT_LABEL},
               {"searchAdCountLabel", IDS_BRAVE_REWARDS_SEARCH_AD_COUNT_LABEL},
               {"searchAdInfo", IDS_BRAVE_REWARDS_SEARCH_AD_INFO},
               {"searchAdConnectedInfo",
                IDS_BRAVE_REWARDS_SEARCH_AD_CONNECTED_INFO},
               {"newsAdCountLabel", IDS_BRAVE_REWARDS_NEWS_AD_COUNT_LABEL},
               {"newsAdInfo", IDS_BRAVE_REWARDS_NEWS_AD_INFO},
               {"newsAdInfoDisabled", IDS_BRAVE_REWARDS_NEWS_AD_INFO_DISABLED},
               {"appErrorTitle", IDS_REWARDS_APP_ERROR_TITLE},

               {"bat", IDS_BRAVE_UI_BAT_REWARDS_TEXT},
               {"contributionTitle", IDS_BRAVE_REWARDS_LOCAL_CONTR_TITLE},
               {"contributionDesc", IDS_BRAVE_REWARDS_LOCAL_CONTR_DESC},
               {"contributionMonthly", IDS_BRAVE_REWARDS_LOCAL_CONTR_MONTHLY},
               {"contributionNextDate",
                IDS_BRAVE_REWARDS_LOCAL_CONTR_NEXT_DATE},
               {"contributionSites", IDS_BRAVE_REWARDS_LOCAL_CONTR_SITES},
               {"contributionVisitSome",
                IDS_BRAVE_REWARDS_LOCAL_CONTR_VISIT_SOME},
               {"contributionMinTime", IDS_BRAVE_REWARDS_LOCAL_CONTR_MIN_TIME},
               {"contributionMinVisits",
                IDS_BRAVE_REWARDS_LOCAL_CONTR_MIN_VISITS},
               {"contributionOther", IDS_BRAVE_REWARDS_LOCAL_CONTR_OTHER},
               {"contributionVisit1", IDS_BRAVE_REWARDS_LOCAL_CONTR_VISIT_1},
               {"contributionVisit5", IDS_BRAVE_REWARDS_LOCAL_CONTR_VISIT_5},
               {"contributionVisit10", IDS_BRAVE_REWARDS_LOCAL_CONTR_VISIT_10},
               {"contributionTime5", IDS_BRAVE_REWARDS_LOCAL_CONTR_TIME_5},
               {"contributionTime8", IDS_BRAVE_REWARDS_LOCAL_CONTR_TIME_8},
               {"contributionTime60", IDS_BRAVE_REWARDS_LOCAL_CONTR_TIME_60},
               {"contributionUpTo", IDS_BRAVE_REWARDS_LOCAL_CONTR_UP_TO},

               {"disconnectWalletFailed",
                IDS_BRAVE_REWARDS_LOCAL_SERVER_DISCONNECT_FAILED},
               {"donationTitle", IDS_BRAVE_REWARDS_LOCAL_DONAT_TITLE},
               {"donationDesc", IDS_BRAVE_REWARDS_LOCAL_DONAT_DESC},
               {"donationDescLearnMore",
                IDS_BRAVE_REWARDS_LOCAL_DONAT_DESC_LEARN_MORE},
               {"donationTotalDonations",
                IDS_BRAVE_REWARDS_LOCAL_DONAT_TOTAL_DONATIONS},
               {"donationVisitSome", IDS_BRAVE_REWARDS_LOCAL_DONAT_VISIT_SOME},
               {"monthlyTipsTitle", IDS_BRAVE_REWARDS_LOCAL_MONTHLY_TIPS_TITLE},
               {"monthlyTipsDesc", IDS_BRAVE_REWARDS_LOCAL_MONTHLY_TIPS_DESC},
               {"monthlyTipsEmpty", IDS_BRAVE_REWARDS_LOCAL_MONTHLY_TIPS_EMPTY},
               {"nextContribution", IDS_BRAVE_REWARDS_LOCAL_NEXT_CONTRIBUTION},
               {"redirectModalSomethingWentWrong",
                IDS_REWARDS_AUTHORIZE_UNEXPECTED_ERROR_TITLE},
               {"redirectModalUnableToCompleteRequest",
                IDS_REWARDS_AUTHORIZE_UNEXPECTED_ERROR_TEXT},
               {"redirectModalClose",
                IDS_BRAVE_REWARDS_LOCAL_REDIRECT_MODAL_CLOSE},
               {"redirectModalDeviceLimitReachedText",
                IDS_REWARDS_AUTHORIZE_DEVICE_LIMIT_REACHED_TEXT},
               {"redirectModalDeviceLimitReachedTitle",
                IDS_REWARDS_AUTHORIZE_DEVICE_LIMIT_REACHED_TITLE},
               {"redirectModalFlaggedWalletText1",
                IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TEXT_1},
               {"redirectModalFlaggedWalletText2",
                IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TEXT_2},
               {"redirectModalFlaggedWalletText3",
                IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TEXT_3},
               {"redirectModalFlaggedWalletText4",
                IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TEXT_4},
               {"redirectModalFlaggedWalletTitle",
                IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TITLE},
               {"redirectModalKYCRequiredTitle",
                IDS_REWARDS_AUTHORIZE_KYC_REQUIRED_TITLE},
               {"redirectModalKYCRequiredText",
                IDS_REWARDS_AUTHORIZE_KYC_REQUIRED_TEXT},
               {"redirectModalMismatchedCountriesText",
                IDS_REWARDS_AUTHORIZE_MISMATCHED_COUNTRIES_TEXT},
               {"redirectModalMismatchedCountriesTitle",
                IDS_REWARDS_AUTHORIZE_MISMATCHED_COUNTRIES_TITLE},
               {"redirectModalMismatchedProviderAccountsText",
                IDS_REWARDS_AUTHORIZE_MISMATCHED_PROVIDER_ACCOUNTS_TEXT},
               {"redirectModalMismatchedProviderAccountsTitle",
                IDS_REWARDS_AUTHORIZE_MISMATCHED_PROVIDER_ACCOUNTS_TITLE},
               {"redirectModalProviderUnavailableText1",
                IDS_REWARDS_AUTHORIZE_PROVIDER_UNAVAILABLE_TEXT_1},
               {"redirectModalProviderUnavailableText2",
                IDS_REWARDS_AUTHORIZE_PROVIDER_UNAVAILABLE_TEXT_2},
               {"redirectModalProviderUnavailableTitle",
                IDS_REWARDS_AUTHORIZE_PROVIDER_UNAVAILABLE_TITLE},
               {"redirectModalRegionNotSupportedText1",
                IDS_REWARDS_AUTHORIZE_REGION_NOT_SUPPORTED_TEXT_1},
               {"redirectModalRegionNotSupportedText2",
                IDS_REWARDS_AUTHORIZE_REGION_NOT_SUPPORTED_TEXT_2},
               {"redirectModalRegionNotSupportedTitle",
                IDS_REWARDS_AUTHORIZE_REGION_NOT_SUPPORTED_TITLE},
               {"redirectModalUpholdBATNotAllowedText",
                IDS_REWARDS_AUTHORIZE_UPHOLD_BAT_NOT_ALLOWED_TEXT},
               {"redirectModalUpholdBATNotAllowedTitle",
                IDS_REWARDS_AUTHORIZE_UPHOLD_BAT_NOT_ALLOWED_TITLE},
               {"redirectModalUpholdInsufficientCapabilitiesText",
                IDS_REWARDS_AUTHORIZE_UPHOLD_INSUFFICIENT_CAPABILITIES_TEXT},
               {"redirectModalUpholdInsufficientCapabilitiesTitle",
                IDS_REWARDS_AUTHORIZE_UPHOLD_INSUFFICIENT_CAPABILITIES_TITLE},
               {"redirectModalWalletOwnershipVerificationFailureText",
                IDS_REWARDS_AUTHORIZE_SIGNATURE_VERIFICATION_ERROR_TEXT},
               {"redirectModalWalletOwnershipVerificationFailureTitle",
                IDS_REWARDS_AUTHORIZE_SIGNATURE_VERIFICATION_ERROR_TITLE},
               {"tosAndPp", IDS_BRAVE_REWARDS_LOCAL_TOS_AND_PP},

               {"click", IDS_BRAVE_REWARDS_LOCAL_ADS_CONFIRMATION_TYPE_CLICK},
               {"dismiss",
                IDS_BRAVE_REWARDS_LOCAL_ADS_CONFIRMATION_TYPE_DISMISS},
               {"landed", IDS_BRAVE_REWARDS_LOCAL_ADS_CONFIRMATION_TYPE_LANDED},
               {"view", IDS_BRAVE_REWARDS_LOCAL_ADS_CONFIRMATION_TYPE_VIEW},

               {"rewardsBrowserCannotReceiveAds",
                IDS_REWARDS_BROWSER_CANNOT_RECEIVE_ADS},
               {"rewardsBrowserNeedsUpdateToSeeAds",
                IDS_REWARDS_BROWSER_NEEDS_UPDATE_TO_SEE_ADS},

               {"activityCopy", IDS_BRAVE_UI_ACTIVITY_COPY},
               {"activityNote", IDS_BRAVE_UI_ACTIVITY_NOTE},
               {"ads", IDS_BRAVE_UI_ADS},
               {"adsCurrentlyViewing", IDS_BRAVE_UI_ADS_CURRENTLY_VIEWING},
               {"adsHistoryNone", IDS_BRAVE_UI_ADS_HISTORY_NONE},
               {"adsHistorySubTitle", IDS_BRAVE_UI_ADS_HISTORY_SUBTITLE},
               {"adsHistoryTitle", IDS_BRAVE_UI_ADS_HISTORY_TITLE},
               {"all", IDS_BRAVE_UI_ADS_ALL},
               {"amount", IDS_BRAVE_UI_AMOUNT},
               {"autoContribute", IDS_BRAVE_UI_BRAVE_CONTRIBUTE_TITLE},
               {"autoContributeTransaction",
                IDS_BRAVE_UI_BRAVE_CONTRIBUTE_TRANSACTION},
               {"braveRewards", IDS_BRAVE_UI_BRAVE_REWARDS},
               {"cancel", IDS_BRAVE_UI_CANCEL},
               {"captchaDrag", IDS_BRAVE_UI_CAPTCHA_DRAG},
               {"captchaTarget", IDS_BRAVE_UI_CAPTCHA_TARGET},
               {"category", IDS_BRAVE_UI_ADS_CATEGORY},
               {"contribute", IDS_BRAVE_UI_CONTRIBUTE},
               {"date", IDS_BRAVE_UI_DATE},
               {"deposits", IDS_BRAVE_UI_DEPOSITS},
               {"description", IDS_BRAVE_UI_DESCRIPTION},
               {"donation", IDS_BRAVE_UI_DONATION},
               {"done", IDS_BRAVE_UI_DONE},
               {"earningsAds", IDS_BRAVE_UI_EARNINGS_ADS},
               {"earningsViewDepositHistory",
                IDS_BRAVE_UI_EARNINGS_VIEW_DEPOSIT_HISTORY},
               {"excludeSite", IDS_BRAVE_UI_EXCLUDE_SITE},
               {"excludedSitesText", IDS_BRAVE_UI_EXCLUDED_SITES},
               {"import", IDS_BRAVE_UI_IMPORT},
               {"learnMore", IDS_BRAVE_UI_LEARN_MORE},
               {"markAsInappropriate", IDS_BRAVE_UI_ADS_MARK_AS_INAPPROPRIATE},
               {"markAsInappropriateChecked",
                IDS_BRAVE_UI_ADS_MARK_AS_INAPPROPRIATE_CHECKED},
               {"monthlyTipsBang", IDS_BRAVE_UI_MONTHLY_TIPS_BANG},
               {"monthlyTips", IDS_BRAVE_UI_MONTHLY_TIPS},
               {"noActivity", IDS_BRAVE_UI_NO_ACTIVITY},
               {"noAdsHistory", IDS_BRAVE_UI_ADS_NO_ADS_HISTORY},
               {"off", IDS_BRAVE_UI_OFF},
               {"ok", IDS_BRAVE_UI_OK},
               {"on", IDS_BRAVE_UI_ON},
               {"onboardingEarnHeader",
                IDS_BRAVE_REWARDS_ONBOARDING_EARN_HEADER},
               {"onboardingEarnText", IDS_BRAVE_REWARDS_ONBOARDING_EARN_TEXT},
               {"onboardingStartUsingRewards",
                IDS_BRAVE_REWARDS_ONBOARDING_START_USING_REWARDS},
               {"onboardingStartUsingRewardsTextOnly",
                IDS_BRAVE_REWARDS_ONBOARDING_START_USING_REWARDS_TEXT_ONLY},
               {"onboardingTerms", IDS_BRAVE_REWARDS_ONBOARDING_TERMS},
               {"oneTimeDonation", IDS_BRAVE_UI_ONE_TIME_DONATION},
               {"openAdsHistory", IDS_BRAVE_UI_OPEN_ADS_HISTORY},
               {"optOutTooltip", IDS_BRAVE_UI_ADS_OPT_OUT_TOOLTIP},
               {"payment", IDS_BRAVE_UI_PAYMENT},
               {"pinnedSitesHeader", IDS_BRAVE_UI_PAYMENT_PINNED_SITES_HEADER},
               {"pinnedSitesMsg", IDS_BRAVE_UI_PAYMENT_PINNED_SITES_MSG},
               {"pinnedSitesOne", IDS_BRAVE_UI_PAYMENT_PINNED_SITES_ONE},
               {"pinnedSitesTwo", IDS_BRAVE_UI_PAYMENT_PINNED_SITES_TWO},
               {"pinnedSitesThree", IDS_BRAVE_UI_PAYMENT_PINNED_SITES_THREE},
               {"pinnedSitesFour", IDS_BRAVE_UI_PAYMENT_PINNED_SITES_FOUR},
               {"pleaseNote", IDS_BRAVE_UI_PLEASE_NOTE},
               {"print", IDS_BRAVE_UI_PRINT},
               {"processingRequest", IDS_REWARDS_AUTHORIZE_PROCESSING_TEXT},
               {"processorBraveTokens", IDS_BRAVE_UI_PROCESSOR_BRAVE_TOKENS},
               {"processorUphold", IDS_BRAVE_UI_PROCESSOR_UPHOLD},
               {"processorBitflyer", IDS_BRAVE_UI_PROCESSOR_BITFLYER},
               {"processorGemini", IDS_BRAVE_UI_PROCESSOR_GEMINI},
               {"recurring", IDS_BRAVE_UI_RECURRING},
               {"recurringDonations", IDS_BRAVE_UI_RECURRING_DONATIONS},
               {"relaunch", IDS_BRAVE_UI_RELAUNCH},
               {"remove", IDS_BRAVE_UI_REMOVE},
               {"removeAdFromSaved", IDS_BRAVE_UI_REMOVE_AD_FROM_SAVED},
               {"reset", IDS_BRAVE_UI_RESET},
               {"resetWallet", IDS_BRAVE_UI_RESET_WALLET},
               {"clearExcludeList", IDS_BRAVE_UI_CLEAR_EXCLUDE_LIST},
               {"reviewSitesMsg", IDS_BRAVE_UI_REVIEW_SITE_MSG},
               {"rewardsConnectAccount", IDS_REWARDS_CONNECT_ACCOUNT},
               {"rewardsContribute", IDS_BRAVE_UI_REWARDS_CONTRIBUTE},
               {"rewardsContributeAttention",
                IDS_BRAVE_UI_REWARDS_CONTRIBUTE_ATTENTION},
               {"rewardsLearnMore", IDS_REWARDS_LEARN_MORE},
               {"rewardsLogInToSeeBalance", IDS_REWARDS_LOG_IN_TO_SEE_BALANCE},
               {"rewardsPaymentCheckStatus", IDS_REWARDS_PAYMENT_CHECK_STATUS},
               {"rewardsPaymentCompleted", IDS_REWARDS_PAYMENT_COMPLETED},
               {"rewardsPaymentPending", IDS_REWARDS_PAYMENT_PENDING},
               {"rewardsPaymentProcessing", IDS_REWARDS_PAYMENT_PROCESSING},
               {"rewardsPaymentSupport", IDS_REWARDS_PAYMENT_SUPPORT},
               {"rewardsResetConsent", IDS_BRAVE_UI_REWARDS_RESET_CONSENT},
               {"rewardsResetText", IDS_BRAVE_UI_REWARDS_RESET_TEXT},
               {"rewardsSummary", IDS_BRAVE_UI_REWARDS_SUMMARY},
               {"rewardsTosUpdateHeading", IDS_REWARDS_TOS_UPDATE_HEADING},
               {"rewardsTosUpdateText", IDS_REWARDS_TOS_UPDATE_TEXT},
               {"rewardsTosUpdateLinkText", IDS_REWARDS_TOS_UPDATE_LINK_TEXT},
               {"rewardsTosUpdateButtonLabel",
                IDS_REWARDS_TOS_UPDATE_BUTTON_LABEL},
               {"rewardsVBATNoticeText1", IDS_REWARDS_VBAT_NOTICE_TEXT1},
               {"rewardsVBATNoticeTitle1", IDS_REWARDS_VBAT_NOTICE_TITLE1},
               {"saved", IDS_BRAVE_UI_ADS_SAVED},
               {"saveAd", IDS_BRAVE_UI_ADS_SAVE_AD},
               {"seeAllItems", IDS_BRAVE_UI_SEE_ALL_ITEMS},
               {"sendTip", IDS_BRAVE_UI_SEND_TIP},
               {"settings", IDS_BRAVE_UI_SETTINGS},
               {"site", IDS_BRAVE_UI_SITE},
               {"tipOnLike", IDS_BRAVE_UI_TIP_ON_LIKE},
               {"token", IDS_BRAVE_UI_TOKEN},
               {"tokens", IDS_BRAVE_UI_TOKENS},
               {"total", IDS_BRAVE_UI_TOTAL},
               {"transactions", IDS_BRAVE_UI_TRANSACTIONS},
               {"type", IDS_BRAVE_UI_TYPE},
               {"unsupportedRegionNoticeHeader",
                IDS_BRAVE_REWARDS_UNSUPPORTED_REGION_NOTICE_HEADER},
               {"unsupportedRegionNoticeSubheader",
                IDS_BRAVE_REWARDS_UNSUPPORTED_REGION_NOTICE_SUBHEADER},
               {"unsupportedRegionNoticeLearnMore",
                IDS_BRAVE_REWARDS_UNSUPPORTED_REGION_NOTICE_LEARN_MORE},
               {"unsupportedRegionNoticeText1",
                IDS_BRAVE_REWARDS_UNSUPPORTED_REGION_NOTICE_TEXT_1},
               {"unsupportedRegionNoticeText2",
                IDS_BRAVE_REWARDS_UNSUPPORTED_REGION_NOTICE_TEXT_2},
               {"verifiedPublisher", IDS_BRAVE_UI_VERIFIED_PUBLISHER},
               {"viewDetails", IDS_BRAVE_UI_VIEW_DETAILS},
               {"viewMonthly", IDS_BRAVE_UI_VIEW_MONTHLY},
               {"walletActivity", IDS_BRAVE_UI_WALLET_ACTIVITY},
               {"walletBalance", IDS_BRAVE_UI_WALLET_BALANCE},
               {"yourWallet", IDS_BRAVE_UI_YOUR_WALLET},

               {"excludedSites", IDS_BRAVE_UI_EXCLUDED_SITES_TEXT},
               {"removeFromExcluded", IDS_BRAVE_UI_REMOVE_FROM_EXCLUDED},
               {"rewardsExcludedText1", IDS_BRAVE_UI_REWARDS_EXCLUDED_TEXT_1},
               {"rewardsExcludedText2", IDS_BRAVE_UI_REWARDS_EXCLUDED_TEXT_2},
               {"showAll", IDS_BRAVE_UI_SHOW_ALL},
               {"viewedSites", IDS_BRAVE_UI_VIEWED_SITES},

               {"promoLearnMore", IDS_BRAVE_UI_PROMO_LEARN_MORE},
               {"promoDismiss", IDS_BRAVE_UI_PROMO_DISMISS},

               {"bitflyerVerificationPromoTitle",
                IDS_BRAVE_UI_BITFLYER_VERIFICATION_PROMO_TITLE},
               {"bitflyerVerificationPromoInfo",
                IDS_BRAVE_UI_BITFLYER_VERIFICATION_PROMO_INFO},

               {"braveCreatorsPromoTitle",
                IDS_BRAVE_UI_BRAVE_CREATORS_PROMO_TITLE},
               {"braveCreatorsPromoInfo1",
                IDS_BRAVE_UI_BRAVE_CREATORS_PROMO_INFO_1},
               {"braveCreatorsPromoInfo2",
                IDS_BRAVE_UI_BRAVE_CREATORS_PROMO_INFO_2},

               {"tapNetworkTitle", IDS_BRAVE_UI_TAP_NETWORK_TITLE},
               {"tapNetworkInfo", IDS_BRAVE_UI_TAP_NETWORK_INFO},
               {"tapNetworkDisclaimer", IDS_BRAVE_UI_TAP_NETWORK_DISCLAIMER},

               {"upholdPromoTitle", IDS_BRAVE_UI_UPHOLD_PROMO_TITLE},
               {"upholdPromoInfo", IDS_BRAVE_UI_UPHOLD_PROMO_INFO},

               {"connectAccountText", IDS_REWARDS_CONNECT_ACCOUNT_TEXT},
               {"learnMore", IDS_REWARDS_LEARN_MORE},
               {"connectWalletCustodialHeader",
                IDS_REWARDS_CONNECT_CUSTODIAL_TITLE},
               {"connectWalletCustodialTooltip",
                IDS_REWARDS_CONNECT_CUSTODIAL_TOOLTIP},
               {"connectWalletSelfCustodyHeader",
                IDS_REWARDS_CONNECT_SELF_CUSTODY_TITLE},
               {"connectWalletSelfCustodyTooltip",
                IDS_REWARDS_CONNECT_SELF_CUSTODY_TOOLTIP},
               {"connectWalletSelfCustodyNote",
                IDS_REWARDS_CONNECT_SELF_CUSTODY_NOTE},
               {"connectWalletHeader", IDS_REWARDS_CONNECT_TITLE},
               {"connectWalletLearnMore",
                IDS_REWARDS_CONNECT_REGIONS_LEARN_MORE_TEXT},
               {"connectWalletProviderNotAvailable",
                IDS_REWARDS_CONNECT_PROVIDER_NOT_AVAILABLE},
               {"connectWalletText", IDS_REWARDS_CONNECT_TEXT},
               {"connectWalletSolanaLabel",
                IDS_REWARDS_CONNECT_SOLANA_BUTTON_LABEL},
               {"connectWalletSolanaMessage",
                IDS_REWARDS_CONNECT_SOLANA_MESSAGE},
               {"connectWalletSelfCustodyTerms",
                IDS_REWARDS_CONNECT_SELF_CUSTODY_TERMS},
               {"connectWalletSelfCustodyError",
                IDS_REWARDS_CONNECT_SELF_CUSTODY_ERROR},
               {"connectWalletLoginText", IDS_REWARDS_CONNECT_LOGIN_TEXT},
               {"newBadgeText", IDS_REWARDS_NEW_BADGE_TEXT},
               {"contributionPendingUntil",
                IDS_BRAVE_REWARDS_CONTRIBUTION_PENDING_UNTIL},

               {"walletAccountLink", IDS_REWARDS_WALLET_ACCOUNT_LINK},
               {"walletAutoContribute", IDS_REWARDS_WALLET_AUTO_CONTRIBUTE},
               {"walletDisconnected", IDS_REWARDS_WALLET_DISCONNECTED},
               {"walletEstimatedEarnings",
                IDS_REWARDS_ESTIMATED_EARNINGS_TITLE},
               {"walletLogIntoYourAccount",
                IDS_REWARDS_WALLET_LOG_INTO_YOUR_ACCOUNT},
               {"walletMonthlyTips", IDS_REWARDS_WALLET_MONTHLY_TIPS},
               {"walletOneTimeTips", IDS_REWARDS_WALLET_ONE_TIME_TIPS},
               {"walletRewardsFromAds", IDS_REWARDS_WALLET_REWARDS_FROM_ADS},
               {"walletRewardsSummary", IDS_REWARDS_WALLET_REWARDS_SUMMARY},
               {"walletUnverified", IDS_REWARDS_WALLET_UNVERIFIED},
               {"walletViewStatement", IDS_REWARDS_WALLET_VIEW_STATEMENT},
               {"walletVerified", IDS_REWARDS_WALLET_VERIFIED},
               {"walletBalanceTitle", IDS_REWARDS_WALLET_BALANCE_TITLE},
               {"walletEarningInfoText", IDS_REWARDS_WIDGET_EARNING_INFO_TEXT},

               {"loading", IDS_BRAVE_REWARDS_LOADING_LABEL},
           }},
          {"adblock",
           {
               {"additionalFiltersTitle", IDS_ADBLOCK_ADDITIONAL_FILTERS_TITLE},
               {"additionalFiltersWarning",
                IDS_ADBLOCK_ADDITIONAL_FILTERS_WARNING},
               {"adsBlocked", IDS_ADBLOCK_TOTAL_ADS_BLOCKED},
               {"customFiltersTitle", IDS_ADBLOCK_CUSTOM_FILTERS_TITLE},
               {"customFiltersInstructions",
                IDS_ADBLOCK_CUSTOM_FILTERS_INSTRUCTIONS},
               {"customListSubscriptionsTitle",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_TITLE},
               {"customListSubscriptionsInstructions",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_INSTRUCTIONS},
               {"customListSubscriptionsDisclaimer",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_DISCLAIMER},

               {"customListSubscriptionsEnterSubscriptionUrlPlaceholder",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_ENTER_SUBSCRIPTION_URL_PLACEHOLDER},
               {"customListSubscriptionsSubmitNewSubscription",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_SUBMIT_NEW_SUBSCRIPTION},
               {"customListSubscriptionsCancelAddSubscription",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_CANCEL_ADD_SUBSCRIPTION},
               {"customListSubscriptionsAddNewFilterList",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_ADD_NEW_FILTER_LIST},
               {"customListSubscriptionsTableFilterListColumn",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_TABLE_FILTER_LIST_COLUMN},
               {"customListSubscriptionsTableLastUpdatedColumn",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_TABLE_LAST_UPDATED_COLUMN},
               {"customListSubscriptionsTriggerUpdate",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_TRIGGER_UPDATE},
               {"customListSubscriptionsViewListSource",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_VIEW_LIST_SOURCE},
               {"customListSubscriptionsUnsubscribe",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_UNSUBSCRIBE},
           }},
          {"rewards-internals",
           {
               {"adDiagnosticId", IDS_BRAVE_REWARDS_INTERNALS_AD_DIAGNOSTIC_ID},
               {"adDiagnosticInfo",
                IDS_BRAVE_REWARDS_INTERNALS_AD_DIAGNOSTIC_INFO},
               {"adsNotInitialized",
                IDS_BRAVE_REWARDS_INTERNALS_ADS_NOT_INITIALIZED},
               {"amount", IDS_BRAVE_REWARDS_INTERNALS_AMOUNT},
               {"autoRefresh", IDS_BRAVE_REWARDS_INTERNALS_AUTO_REFRESH},
               {"balanceInfo", IDS_BRAVE_REWARDS_INTERNALS_BALANCE_INFO},
               {"bat", IDS_BRAVE_UI_BAT_TEXT},
               {"bootStamp", IDS_BRAVE_REWARDS_INTERNALS_BOOT_STAMP},
               {"clearButton", IDS_BRAVE_REWARDS_INTERNALS_CLEAR_BUTTON},
               {"contributedAmount",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTED_AMOUNT},
               {"contributionCreatedAt",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTED_CREATED_AT},
               {"contribution", IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION},
               {"contributionProcessor",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_PROCESSOR},
               {"contributionStep",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP},
               {"contributionStepAutoContributeTableEmpty",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_AUTO_CONTRIBUTE_TABLE_EMPTY},
               {"contributionStepNotEnoughFunds",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_NOT_ENOUGH_FUNDS},
               {"contributionStepFailed",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_FAILED},
               {"contributionStepCompleted",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_COMPLETED},
               {"contributionStepNo",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_NO},
               {"contributionStepStart",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_START},
               {"contributionStepPrepare",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_PREPARE},
               {"contributionStepReserve",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_RESERVE},
               {"contributionStepExternalTransaction",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_EXTERNAL_TRANSACTION},
               {"contributionStepCreds",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_CREDS},
               {"contributionStepRewardsOff",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_REWARDS_OFF},
               {"contributionStepAutoContributeOff",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_AUTO_CONTRIBUTE_OFF},
               {"contributionStepRetryCount",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_STEP_RETRY_COUNT},
               {"eventLogKey", IDS_BRAVE_REWARDS_INTERNALS_EVENT_LOG_KEY},
               {"eventLogValue", IDS_BRAVE_REWARDS_INTERNALS_EVENT_LOG_VALUE},
               {"eventLogTime", IDS_BRAVE_REWARDS_INTERNALS_EVENT_LOG_TIME},
               {"mainDisclaimer", IDS_BRAVE_REWARDS_INTERNALS_MAIN_DISCLAIMER},
               {"logDisclaimer", IDS_BRAVE_REWARDS_INTERNALS_LOG_DISCLAIMER},
               {"rewardsTypeAuto",
                IDS_BRAVE_REWARDS_INTERNALS_REWARDS_TYPE_AUTO},
               {"rewardsTypeOneTimeTip",
                IDS_BRAVE_REWARDS_INTERNALS_REWARDS_TYPE_ONE_TIME_TIP},
               {"rewardsTypeRecurringTip",
                IDS_BRAVE_REWARDS_INTERNALS_REWARDS_TYPE_RECURRING_TIP},
               {"contributionType",
                IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTION_TYPE},
               {"contributions", IDS_BRAVE_REWARDS_INTERNALS_CONTRIBUTIONS},
               {"externalWalletType",
                IDS_BRAVE_REWARDS_INTERNALS_EXTERNAL_WALLET_TYPE},
               {"externalWalletAccount",
                IDS_BRAVE_REWARDS_INTERNALS_EXTERNAL_WALLET_ACCOUNT},
               {"downloadButton", IDS_BRAVE_REWARDS_INTERNALS_DOWNLOAD_BUTTON},
               {"externalWallet", IDS_BRAVE_REWARDS_INTERNALS_EXTERNAL_WALLET},
               {"invalid", IDS_BRAVE_REWARDS_INTERNALS_INVALID},
               {"keyInfoSeed", IDS_BRAVE_REWARDS_INTERNALS_KEY_INFO_SEED},
               {"logNotice", IDS_BRAVE_REWARDS_INTERNALS_LOG_NOTICE},
               {"mainTitle", IDS_BRAVE_REWARDS_INTERNALS_MAIN_TITLE},
               {"notSet", IDS_BRAVE_REWARDS_INTERNALS_NOT_SET},
               {"personaId", IDS_BRAVE_REWARDS_INTERNALS_PERSONA_ID},
               {"processorBraveTokens", IDS_BRAVE_UI_PROCESSOR_BRAVE_TOKENS},
               {"processorUphold", IDS_BRAVE_UI_PROCESSOR_UPHOLD},
               {"processorBitflyer", IDS_BRAVE_UI_PROCESSOR_BITFLYER},
               {"processorGemini", IDS_BRAVE_UI_PROCESSOR_GEMINI},
               {"processorZebPay", IDS_BRAVE_UI_PROCESSOR_ZEBPAY},
               {"processorSolana", IDS_BRAVE_UI_PROCESSOR_SOLANA},
               {"refreshButton", IDS_BRAVE_REWARDS_INTERNALS_REFRESH_BUTTON},
               {"retryCount", IDS_BRAVE_REWARDS_INTERNALS_RETRY_COUNT},
               {"rewardsCountry", IDS_BRAVE_REWARDS_INTERNALS_REWARDS_COUNTRY},
               {"tabAdDiagnostics",
                IDS_BRAVE_REWARDS_INTERNALS_TAB_AD_DIAGNOSTICS},
               {"tabGeneralInfo", IDS_BRAVE_REWARDS_INTERNALS_TAB_GENERAL_INFO},
               {"tabLogs", IDS_BRAVE_REWARDS_INTERNALS_TAB_LOGS},
               {"tabContributions",
                IDS_BRAVE_REWARDS_INTERNALS_TAB_CONTRIBUTIONS},
               {"tabEventLogs", IDS_BRAVE_REWARDS_INTERNALS_TAB_EVENT_LOGS},
               {"totalAmount", IDS_BRAVE_REWARDS_INTERNALS_TOTAL_AMOUNT},
               {"totalBalance", IDS_BRAVE_REWARDS_INTERNALS_TOTAL_BALANCE},
               {"userId", IDS_BRAVE_REWARDS_INTERNALS_USER_ID},
               {"valid", IDS_BRAVE_REWARDS_INTERNALS_VALID},
               {"walletAddress", IDS_BRAVE_REWARDS_INTERNALS_WALLET_ADDRESS},
               {"walletHistory", IDS_BRAVE_REWARDS_INTERNALS_WALLET_HISTORY},
               {"walletInfo", IDS_BRAVE_REWARDS_INTERNALS_WALLET_INFO},
               {"walletNotCreated",
                IDS_BRAVE_REWARDS_INTERNALS_WALLET_NOT_CREATED},
               {"walletPaymentId",
                IDS_BRAVE_REWARDS_INTERNALS_WALLET_PAYMENT_ID},
               {"walletStatus", IDS_BRAVE_REWARDS_INTERNALS_WALLET_STATUS},
               {"walletStatusNotConnected",
                IDS_BRAVE_REWARDS_INTERNALS_WALLET_STATUS_NOT_CONNECTED},
               {"walletStatusConnected",
                IDS_BRAVE_REWARDS_INTERNALS_WALLET_STATUS_CONNECTED},
               {"walletStatusDisconnected",
                IDS_BRAVE_REWARDS_INTERNALS_WALLET_STATUS_DISCONNECTED},
               {"walletCreationEnvironment",
                IDS_BRAVE_REWARDS_INTERNALS_WALLET_CREATION_ENVIRONMENT},
               {"currentEnvironment",
                IDS_BRAVE_REWARDS_INTERNALS_CURRENT_ENVIRONMENT},

               {"loading", IDS_BRAVE_REWARDS_LOADING_LABEL},
           }},
          {
#if BUILDFLAG(ENABLE_TOR)
              "tor-internals",
              {
                  {"tabGeneralInfo", IDS_TOR_INTERNALS_TAB_GENERAL_INFO},
                  {"tabLogs", IDS_TOR_INTERNALS_TAB_LOGS},
                  {"torControlEvents", IDS_TOR_INTERNALS_TOR_CONTROL_EVENTS},
                  {"torVersion", IDS_TOR_INTERNALS_TOR_VERSION},
                  {"torPid", IDS_TOR_INTERNALS_TOR_PID},
                  {"torProxyURI", IDS_TOR_INTERNALS_TOR_PROXY_URI},
                  {"torConnectionStatus",
                   IDS_TOR_INTERNALS_TOR_CONNECTION_STATUS},
                  {"torInitProgress", IDS_TOR_INTERNALS_TOR_INIT_PROGRESS},
              }},
          {
#endif
#if !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_IOS)
              "webcompat",
              {
                  // Report modal
                  {"reportModalTitle",
                   IDS_BRAVE_WEBCOMPATREPORTER_REPORT_MODAL_TITLE},
                  {"reportExplanation",
                   IDS_BRAVE_WEBCOMPATREPORTER_REPORT_EXPLANATION},
                  {"reportNonHttpExplanation",
                   IDS_BRAVE_WEBCOMPATREPORTER_REPORT_NON_HTTP_EXPLANATION},
                  {"reportLocalExplanation",
                   IDS_BRAVE_WEBCOMPATREPORTER_REPORT_LOCAL_EXPLANATION},
                  {"reportErrorPageExplanation",
                   IDS_BRAVE_WEBCOMPATREPORTER_REPORT_ERROR_PAGE_EXPLANATION},
                  {"reportDisclaimer",
                   IDS_BRAVE_WEBCOMPATREPORTER_REPORT_DISCLAIMER2},
                  {"reportInfoLink", IDS_BRAVE_WEBCOMPATREPORTER_INFO_LINK},
                  {"reportDetails", IDS_BRAVE_WEBCOMPATREPORTER_REPORT_DETAILS},
                  {"reportContactPlaceholder",
                   IDS_BRAVE_WEBCOMPATREPORTER_REPORT_CONTACT_PLACEHOLDER},
                  {"reportContactLabel",
                   IDS_BRAVE_WEBCOMPATREPORTER_REPORT_CONTACT_LABEL},
                  {"attachScreenshotLabel",
                   IDS_BRAVE_WEBCOMPATREPORTER_ATTACH_SCREENSHOT_LABEL},
                  {"viewScreenshotLabel",
                   IDS_BRAVE_WEBCOMPATREPORTER_VIEW_SCREENSHOT_LABEL},
                  {"cancel", IDS_BRAVE_WEBCOMPATREPORTER_CANCEL},
                  {"close", IDS_BRAVE_WEBCOMPATREPORTER_CLOSE},
                  {"submit", IDS_BRAVE_WEBCOMPATREPORTER_SUBMIT},
                  // Confirmation modal
                  {"thankYou", IDS_BRAVE_WEBCOMPATREPORTER_THANK_YOU},
                  {"confirmationNotice",
                   IDS_BRAVE_WEBCOMPATREPORTER_CONFIRMATION_NOTICE},
              }
#endif
          },
      }};

  if (auto it = kLocalizedStrings->find(webui_name);
      it != kLocalizedStrings->end()) {
    return it->second;
  }
  return {};
}  // NOLINT (readability/fn_size)

}  // namespace brave
