[package]
name = "candle_embedding_gemma"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candle-core = "=0.9.1"
candle-nn = "=0.9.1"
candle-transformers = "=0.9.1"
tokenizers = { version = "0.21.0", default-features = false, features = ["unstable_wasm"] }
serde_json = "1.0.99"
serde = { version = "1.0", features = ["derive"] }
safetensors = "0.4"

# WASM-specific dependencies
wasm-bindgen = "=0.2.100" # Must match the wasm-bindgen-cli version under brave/tools/crates!
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.2", features = ["js"] }
serde-wasm-bindgen = "0.6.0"
js-sys = "0.3"
