/* Copyright (c) 2023 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

// IDL definitions for message requests.
namespace eth_requests {
  dictionary CowSwapOrder {
    DOMString appData;
    DOMString buyAmount;
    DOMString buyToken;
    DOMString feeAmount;
    DOMString kind;
    boolean partiallyFillable;
    DOMString receiver;
    DOMString sellAmount;
    DOMString sellToken;
    DOMString validTo;
  };
};
