/* Copyright (c) 2025 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

// Cardano RPC structures.
namespace cardano_rpc {
  // https://docs.blockfrost.io/#tag/cardano--blocks/GET/blocks/latest
  dictionary Block {
    // uint32_t
    DOMString height;

    // uint64_t
    DOMString slot;

    // uint32_t
    DOMString epoch;
  };

  // https://docs.blockfrost.io/#tag/cardano--epochs/GET/epochs/latest
  dictionary EpochParameters {
    // uint64_t
    DOMString min_fee_a;

    // uint64_t
    DOMString min_fee_b;
  };


  // https://docs.blockfrost.io/#tag/cardano--addresses/GET/addresses/%7Baddress%7D/utxos
  dictionary UnspentOutputAsset {
    DOMString unit;
    DOMString quantity;
  };

  // https://docs.blockfrost.io/#tag/cardano--addresses/GET/addresses/%7Baddress%7D/utxos
  dictionary UnspentOutput {
    DOMString tx_hash;

    // uint32_t
    DOMString output_index;

    UnspentOutputAsset[] amount;
  };
};
