runner:
  semgrep:
    name: semgrep
    cmd: |
      [ "$(git --no-pager diff --name-only HEAD $(git merge-base HEAD origin/${GITHUB_BASE_REF:-development}) | xargs ls  -d 2>/dev/null)" != "" ] &&\
      semgrep \
        -c p/ci \
        -c p/security-audit \
        -c p/xss \
        -c p/nginx \
        -c p/docker \
        -c p/terraform \
        -c p/secrets \
        $(find semgrep_rules -name '*.yml' | sed 's/^/-c /g') \
        --baseline-commit origin/${GITHUB_BASE_REF:-development} \
        --metrics=off \
        --json \
        | jq -r '.results[] | "\(.extra.severity[0:1]):\(.path):\(.end.line) \(.extra.message)"' \
        | sed 's/$/ (Cc @brave\/sec-team @thypon @stoletheminerals)/g' | tee semgrep.log &&\
        find semgrep.log -type f -empty -delete
    errorformat:
      - "%t:%f:%l %m"
