[package]
name = "zcash-cxx"
version = "1.0.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
orchard = { version = "0.7.1",  default-features = false }
zip32 = { version = "0.1.1" }

[lib]
name = "brave_wallet_cxx"
path = "lib.rs"
crate-type = ["rlib"]
