# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Add Brave's extensions resources to the WebUI data source.
    re_pattern:
      '(content::WebUIDataSource\*
      CreateAndAddExtensionsSource\([^{]*\{.+?\n)(  return source;)'
    re_flags: [DOTALL]
    replace: |-
      \1  BraveAddExtensionsResources(source, profile);
      \2
  - description: |
      Use Brave's Chrome Web Store item string.
    pattern: 'IDS_EXTENSIONS_ITEM_CHROME_WEB_STORE'
    replace: 'IDS_EXTENSIONS_BRAVE_ITEM_CHROME_WEB_STORE'
  - description: |
      Use Brave's webstore item-source string.
    pattern: 'IDS_EXTENSIONS_ITEM_SOURCE_WEBSTORE'
    replace: 'IDS_EXTENSIONS_BRAVE_ITEM_SOURCE_WEBSTORE'
