/* Copyright (c) 2022 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_COMPONENTS_P3A_METRIC_NAMES_H_
#define BRAVE_COMPONENTS_P3A_METRIC_NAMES_H_

#include <string_view>

#include "base/containers/fixed_flat_map.h"
#include "brave/components/p3a/metric_config.h"

namespace p3a {

// Allowlist for histograms that we collect.
// A metric must be listed here to be reported.
//
// Please keep them properly sorted within their categories.
//
// Could be replaced with something built dynamically,
// although so far we've found it a useful review point.
//
// TODO(iefremov) Clean up obsolete metrics.
//
// clang-format off
inline constexpr auto kCollectedTypicalHistograms =
  base::MakeFixedFlatMap<std::string_view, std::optional<MetricConfig>>({
    {"Brave.AIChat.AcquisitionSource", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.AvgPromptCount", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.ChatCount", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.ChatCount.Nebula", MetricConfig{.ephemeral = true,.nebula = true}},
    {"Brave.AIChat.ContextMenu.FreeUsages", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.ContextMenu.MostUsedAction", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.ContextMenu.PremiumUsages", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.Enabled.2", {}},
    {"Brave.AIChat.Enabled.SidebarEnabledA", {}},
    {"Brave.AIChat.MostUsedEntryPoint", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.NewUserReturning", {}},
    {"Brave.AIChat.OmniboxOpens", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.OmniboxWeekCompare", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.UsageWeekly", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.UsageWeekly.SidebarEnabledA", MetricConfig{.ephemeral = true}},
    {"Brave.Ads.ClearData", MetricConfig{.ephemeral = true}},
    {"Brave.Core.BookmarkCount", {}},
    {"Brave.Core.CrashReportsEnabled", {}},
    {"Brave.Core.DomainsLoaded", {}},
    {"Brave.Core.FailedHTTPSUpgrades.2", MetricConfig{.ephemeral = true}},
    {"Brave.Core.FirstPageLoadTime", MetricConfig{.ephemeral = true}},
    {"Brave.Core.IsDefault", {}},
    {"Brave.Core.NumberOfExtensions", {}},
    {"Brave.Core.PagesReloaded", {}},
    {"Brave.Core.TabCount", {}},
    {"Brave.Core.WeeklyUsage", {}},
    {"Brave.Core.WeeklyUsage.Nebula", MetricConfig{.nebula = true}},
    {"Brave.Core.WindowCount.2", {}},
    {"Brave.DNS.AutoSecureRequests.2", MetricConfig{.ephemeral = true}},
    {"Brave.DNS.AutoSecureRequests.Cloudflare.2", MetricConfig{.ephemeral = true}},
    {"Brave.DNS.AutoSecureRequests.Quad9.2", MetricConfig{.ephemeral = true}},
    {"Brave.DNS.AutoSecureRequests.Wikimedia.2", MetricConfig{.ephemeral = true}},
    {"Brave.DNS.SecureSetting", {}},
    {"Brave.Extensions.AdBlock", {}},
    {"Brave.IOS.IsLikelyDefault", {}},

    {"Brave.Importer.ImporterSource.2", {}},
    {"Brave.NTP.CustomizeUsageStatus.2", {}},
    {"Brave.NTP.NewTabsCreated.3", {}},
    {"Brave.NTP.SponsoredMediaType", {}},
    {"Brave.Omnibox.SearchCount.3", {}},

    // P2A
    // Ad Impressions
    {"Brave.P2A.ad_notification.impressions", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.architecture", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.artsentertainment", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.automotive", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.business", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.careers", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.cellphones", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.crypto", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.education", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.familyparenting", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.fashion", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.folklore", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.fooddrink", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.gaming", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.healthfitness", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.history", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.hobbiesinterests", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.home", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.law", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.military", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.other", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.personalfinance", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.pets", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.realestate", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.science", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.sports", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.technologycomputing", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.travel", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.untargeted", {}},
    {"Brave.P2A.ad_notification.impressions_per_segment.weather", {}},
    // Ad Opportunities
    {"Brave.P2A.ad_notification.opportunities", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.architecture", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.artsentertainment", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.automotive", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.business", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.careers", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.cellphones", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.crypto", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.education", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.familyparenting", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.fashion", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.folklore", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.fooddrink", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.gaming", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.healthfitness", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.history", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.hobbiesinterests", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.home", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.law", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.military", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.other", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.personalfinance", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.pets", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.realestate", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.science", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.sports", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.technologycomputing", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.travel", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.untargeted", {}},
    {"Brave.P2A.ad_notification.opportunities_per_segment.weather", {}},
    {"Brave.P2A.inline_content_ad.impressions", {}},
    {"Brave.P2A.inline_content_ad.opportunities", {}},
    {"Brave.P2A.new_tab_page_ad.impressions", {}},
    {"Brave.P2A.new_tab_page_ad.opportunities", {}},
    {"Brave.P3A.SentAnswersCount", {}},
    {"Brave.Playlist.FirstTimeOffset", MetricConfig{.ephemeral = true}},
    {"Brave.Playlist.NewUserReturning", {}},
    {"Brave.Playlist.UsageDaysInWeek", MetricConfig{.ephemeral = true}},
    {"Brave.Rewards.AdTypesEnabled.2", {}},
    {"Brave.Rewards.AutoContributionsState.3", {}},
    {"Brave.Rewards.DesktopPanelCount", MetricConfig{.ephemeral = true}},
    {"Brave.Rewards.EnabledSource", MetricConfig{.ephemeral = true}},
    {"Brave.Rewards.MobileConversion", MetricConfig{.ephemeral = true}},
    {"Brave.Rewards.MobilePanelCount", MetricConfig{.ephemeral = true}},
    {"Brave.Rewards.SearchResultAdsOptin", MetricConfig{.ephemeral = true}},
    {"Brave.Rewards.TipsState.2", {}},
    {"Brave.Rewards.ToolbarButtonTrigger", MetricConfig{.ephemeral = true}},
    {"Brave.Rewards.WalletBalance.3", {}},
    {"Brave.Rewards.WalletState", {}},
    {"Brave.Search.GoogleWidgetUsage", MetricConfig{.ephemeral = true}},
    {"Brave.Search.Promo.BannerB", {}},
    {"Brave.Search.Promo.BannerC", {}},
    {"Brave.Search.Promo.BannerD", {}},
    {"Brave.Search.Promo.Button", {}},
    {"Brave.Search.Promo.DDGBannerA", {}},
    {"Brave.Search.Promo.DDGBannerB", {}},
    {"Brave.Search.Promo.DDGBannerC", {}},
    {"Brave.Search.Promo.DDGBannerD", {}},
    {"Brave.Search.Promo.NewTabPage", {}},
    {"Brave.Search.QueriesBeforeChurn", MetricConfig{.ephemeral = true}},
    {"Brave.Search.SwitchEngine", {}},
    {"Brave.Search.WebDiscoveryAndAds", {}},
    {"Brave.Search.WebDiscoveryEnabled", {}},
    {"Brave.Search.WidgetDefault", {}},
    {"Brave.Search.WidgetUsage", MetricConfig{.ephemeral = true}},
    {"Brave.Shields.AdBlockSetting", {}},
    {"Brave.Shields.CookieListEnabled", {}},
    {"Brave.Shields.DomainAdsSettingsAboveGlobal", {}},
    {"Brave.Shields.DomainAdsSettingsBelowGlobal", {}},
    {"Brave.Shields.FingerprintBlockSetting", {}},
    {"Brave.Shields.UsageStatus", {}},
    {"Brave.Sidebar.Enabled", {}},
    {"Brave.Sidebar.SettingChange.SidebarEnabledA", {}},
    {"Brave.Sync.JoinType", MetricConfig{.ephemeral = true}},
    {"Brave.Sync.Status.2", {}},
    {"Brave.Today.ClickCardDepth", MetricConfig{.ephemeral = true}},
    {"Brave.Today.LastUsageTime", {}},
    {"Brave.Today.NewUserReturning", {}},
    {"Brave.Today.NonRewardsAdViews", {}},
    {"Brave.Today.RewardsAdViews", {}},
    {"Brave.Today.SidebarFilterUsages", MetricConfig{.ephemeral = true}},
    {"Brave.Today.WeeklySessionCount", {}},
    {"Brave.Today.WeeklyTotalCardClicks", MetricConfig{.ephemeral = true}},
    {"Brave.Today.WeeklyTotalCardViews", {}},
    {"Brave.VPN.HideWidget", MetricConfig{.ephemeral = true}},
    {"Brave.VPN.LastUsageTime", {}},
    {"Brave.VPN.NewUserReturning", {}},
    {"Brave.VPN.WidgetUsage", MetricConfig{.ephemeral = true}},
    {"Brave.VerticalTabs.GroupTabs", MetricConfig{.ephemeral = true}},
    {"Brave.VerticalTabs.OpenTabs", MetricConfig{.ephemeral = true}},
    {"Brave.VerticalTabs.PinnedTabs", MetricConfig{.ephemeral = true}},
    {"Brave.Wallet.ActiveBtcAccounts", {}},
    {"Brave.Wallet.ActiveEthAccounts", {}},
    {"Brave.Wallet.ActiveSolAccounts", {}},
    {"Brave.Wallet.ActiveZecAccounts", {}},
    {"Brave.Wallet.BtcTransactionSent", {}},
    {"Brave.Wallet.EthTransactionSent", {}},
    {"Brave.Wallet.NFTCount", MetricConfig{.ephemeral = true}},
    {"Brave.Wallet.NewUserBalance", MetricConfig{.ephemeral = true}},
    {"Brave.Wallet.NewUserReturning", {}},
    {"Brave.Wallet.OnboardingConversion.3", MetricConfig{.ephemeral = true}},
    {"Brave.Wallet.SolTransactionSent", {}},
    {"Brave.Wallet.ZecTransactionSent", {}},
    {"Brave.WebTorrent.UsageWeekly", MetricConfig{.ephemeral = true}},
    {"Brave.Welcome.InteractionStatus.2", {}},
});

inline constexpr auto kCollectedSlowHistograms =
  base::MakeFixedFlatMap<std::string_view, std::optional<MetricConfig>>({
    {"Brave.AIChat.ContextMenu.LastUsageTime", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.LastUsageTime", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.UsageMonthly", MetricConfig{.ephemeral = true}},
    {"Brave.Core.PrimaryLang", MetricConfig{.constellation_only = true}},
    {"Brave.Core.ProfileCount", {}},
    {"Brave.Core.UsageMonthly", {}},
    {"Brave.P3A.TestSlowMetric", {}},
    {"Brave.Playlist.LastUsageTime", {}},
    {"Brave.Rewards.PageViewCount", MetricConfig{.ephemeral = true}},
    {"Brave.Rewards.RecurringTip", MetricConfig{.ephemeral = true}},
    {"Brave.Rewards.TipsSent.2", MetricConfig{.ephemeral = true}},
    {"Brave.Search.SearchSuggest", {}},
    {"Brave.Shields.ForgetFirstParty", {}},
    {"Brave.Sync.EnabledTypes", {}},
    {"Brave.Sync.SyncedObjectsCount.2", {}},
    {"Brave.Today.ChannelCount.2", MetricConfig{.ephemeral = true}},
    {"Brave.Today.DirectFeedsTotal.3", MetricConfig{.ephemeral = true}},
    {"Brave.Today.PublisherCount.2", MetricConfig{.ephemeral = true}},
    {"Brave.Today.UsageMonthly", MetricConfig{.ephemeral = true}},
    {"Brave.Wallet.UsageMonthly", MetricConfig{.ephemeral = true}},
});

inline constexpr auto kCollectedExpressHistograms =
  base::MakeFixedFlatMap<std::string_view, std::optional<MetricConfig>>({
    {"Brave.AIChat.UsageDaily.2", MetricConfig{.ephemeral = true}},
    {"Brave.AIChat.UsageDaily.SidebarEnabledA", MetricConfig{.ephemeral = true}},
    {"Brave.Core.UsageDaily", {}},
    {"Brave.DayZero.A.InstallTime", MetricConfig{
      .ephemeral = true,
      .constellation_only = true,
      .append_attributes = MetricAttributesToAppend{MetricAttribute::kRef}
    }},
    {"Brave.DayZero.B.InstallTime", MetricConfig{
      .ephemeral = true,
      .constellation_only = true,
      .append_attributes = MetricAttributesToAppend{MetricAttribute::kRef}
    }},
    {"Brave.Rewards.EnabledInstallationTime", MetricConfig{.ephemeral = true}},
    {"Brave.Search.BraveDaily", MetricConfig{.ephemeral = true}},
    {"Brave.Search.DefaultEngine.4", {}},
    {"Brave.Today.IsEnabled", MetricConfig{.ephemeral = true}},
    {"Brave.Today.UsageDaily", MetricConfig{.ephemeral = true}},
    {"Brave.Uptime.BrowserOpenTime.2", MetricConfig{.ephemeral = true}},
    {"Brave.Wallet.UsageDaily", MetricConfig{.ephemeral = true}},
    {"creativeInstanceId.total.count", {}},
});

}  // namespace p3a

// clang-format on

#endif  // BRAVE_COMPONENTS_P3A_METRIC_NAMES_H_
