/* Copyright (c) 2024 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#include "brave/components/p3a/region.h"

#include <utility>

#include "base/containers/fixed_flat_map.h"

namespace p3a {

namespace {

constexpr char kOtherIdentifier[] = "other";

enum class Region {
  kAsia,
  kEurope,
  kAfrica,
  kOceania,
  kAmericas,
};

enum class Subregion {
  kSouthernAsia,
  kNorthernEurope,
  kSouthernEurope,
  kNorthernAfrica,
  kSubSaharanAfrica,
  kLatinAmericaAndTheCaribbean,
  kWesternAsia,
  kWesternEurope,
  kEasternEurope,
  kNorthernAmerica,
  kSoutheasternAsia,
  kEasternAsia,
  kOceania,
  kCentralAsia,
};

inline constexpr auto kCountryRegions =
    base::MakeFixedFlatMap<std::string_view, std::pair<Region, Subregion>>({
        {"AD", {Region::kEurope, Subregion::kSouthernEurope}},
        {"AE", {Region::kAsia, Subregion::kWesternAsia}},
        {"AF", {Region::kAsia, Subregion::kSouthernAsia}},
        {"AG", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"AI", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"AL", {Region::kEurope, Subregion::kSouthernEurope}},
        {"AM", {Region::kAsia, Subregion::kWesternAsia}},
        {"AO", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"AR", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"AS", {Region::kOceania, Subregion::kOceania}},
        {"AT", {Region::kEurope, Subregion::kWesternEurope}},
        {"AU", {Region::kOceania, Subregion::kOceania}},
        {"AW", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"AX", {Region::kEurope, Subregion::kNorthernEurope}},
        {"AZ", {Region::kAsia, Subregion::kWesternAsia}},
        {"BA", {Region::kEurope, Subregion::kSouthernEurope}},
        {"BB", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"BD", {Region::kAsia, Subregion::kSouthernAsia}},
        {"BE", {Region::kEurope, Subregion::kWesternEurope}},
        {"BF", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"BG", {Region::kEurope, Subregion::kEasternEurope}},
        {"BH", {Region::kAsia, Subregion::kWesternAsia}},
        {"BI", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"BJ", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"BL", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"BM", {Region::kAmericas, Subregion::kNorthernAmerica}},
        {"BN", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"BO", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"BQ", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"BR", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"BS", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"BT", {Region::kAsia, Subregion::kSouthernAsia}},
        {"BV", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"BW", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"BY", {Region::kEurope, Subregion::kEasternEurope}},
        {"BZ", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"CA", {Region::kAmericas, Subregion::kNorthernAmerica}},
        {"CC", {Region::kOceania, Subregion::kOceania}},
        {"CD", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"CF", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"CG", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"CH", {Region::kEurope, Subregion::kWesternEurope}},
        {"CI", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"CK", {Region::kOceania, Subregion::kOceania}},
        {"CL", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"CM", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"CN", {Region::kAsia, Subregion::kEasternAsia}},
        {"CO", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"CR", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"CU", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"CV", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"CW", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"CX", {Region::kOceania, Subregion::kOceania}},
        {"CY", {Region::kAsia, Subregion::kWesternAsia}},
        {"CZ", {Region::kEurope, Subregion::kEasternEurope}},
        {"DE", {Region::kEurope, Subregion::kWesternEurope}},
        {"DJ", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"DK", {Region::kEurope, Subregion::kNorthernEurope}},
        {"DM", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"DO", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"DZ", {Region::kAfrica, Subregion::kNorthernAfrica}},
        {"EC", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"EE", {Region::kEurope, Subregion::kNorthernEurope}},
        {"EG", {Region::kAfrica, Subregion::kNorthernAfrica}},
        {"EH", {Region::kAfrica, Subregion::kNorthernAfrica}},
        {"ER", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"ES", {Region::kEurope, Subregion::kSouthernEurope}},
        {"ET", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"FI", {Region::kEurope, Subregion::kNorthernEurope}},
        {"FJ", {Region::kOceania, Subregion::kOceania}},
        {"FK", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"FM", {Region::kOceania, Subregion::kOceania}},
        {"FO", {Region::kEurope, Subregion::kNorthernEurope}},
        {"FR", {Region::kEurope, Subregion::kWesternEurope}},
        {"GA", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"GB", {Region::kEurope, Subregion::kNorthernEurope}},
        {"GD", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"GE", {Region::kAsia, Subregion::kWesternAsia}},
        {"GF", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"GG", {Region::kEurope, Subregion::kNorthernEurope}},
        {"GH", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"GI", {Region::kEurope, Subregion::kSouthernEurope}},
        {"GL", {Region::kAmericas, Subregion::kNorthernAmerica}},
        {"GM", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"GN", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"GP", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"GQ", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"GR", {Region::kEurope, Subregion::kSouthernEurope}},
        {"GS", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"GT", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"GU", {Region::kOceania, Subregion::kOceania}},
        {"GW", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"GY", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"HK", {Region::kAsia, Subregion::kEasternAsia}},
        {"HM", {Region::kOceania, Subregion::kOceania}},
        {"HN", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"HR", {Region::kEurope, Subregion::kSouthernEurope}},
        {"HT", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"HU", {Region::kEurope, Subregion::kEasternEurope}},
        {"ID", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"IE", {Region::kEurope, Subregion::kNorthernEurope}},
        {"IL", {Region::kAsia, Subregion::kWesternAsia}},
        {"IM", {Region::kEurope, Subregion::kNorthernEurope}},
        {"IN", {Region::kAsia, Subregion::kSouthernAsia}},
        {"IO", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"IQ", {Region::kAsia, Subregion::kWesternAsia}},
        {"IR", {Region::kAsia, Subregion::kSouthernAsia}},
        {"IS", {Region::kEurope, Subregion::kNorthernEurope}},
        {"IT", {Region::kEurope, Subregion::kSouthernEurope}},
        {"JE", {Region::kEurope, Subregion::kNorthernEurope}},
        {"JM", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"JO", {Region::kAsia, Subregion::kWesternAsia}},
        {"JP", {Region::kAsia, Subregion::kEasternAsia}},
        {"KE", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"KG", {Region::kAsia, Subregion::kCentralAsia}},
        {"KH", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"KI", {Region::kOceania, Subregion::kOceania}},
        {"KM", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"KN", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"KP", {Region::kAsia, Subregion::kEasternAsia}},
        {"KR", {Region::kAsia, Subregion::kEasternAsia}},
        {"KW", {Region::kAsia, Subregion::kWesternAsia}},
        {"KY", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"KZ", {Region::kAsia, Subregion::kCentralAsia}},
        {"LA", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"LB", {Region::kAsia, Subregion::kWesternAsia}},
        {"LC", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"LI", {Region::kEurope, Subregion::kWesternEurope}},
        {"LK", {Region::kAsia, Subregion::kSouthernAsia}},
        {"LR", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"LS", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"LT", {Region::kEurope, Subregion::kNorthernEurope}},
        {"LU", {Region::kEurope, Subregion::kWesternEurope}},
        {"LV", {Region::kEurope, Subregion::kNorthernEurope}},
        {"LY", {Region::kAfrica, Subregion::kNorthernAfrica}},
        {"MA", {Region::kAfrica, Subregion::kNorthernAfrica}},
        {"MC", {Region::kEurope, Subregion::kWesternEurope}},
        {"MD", {Region::kEurope, Subregion::kEasternEurope}},
        {"ME", {Region::kEurope, Subregion::kSouthernEurope}},
        {"MF", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"MG", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"MH", {Region::kOceania, Subregion::kOceania}},
        {"MK", {Region::kEurope, Subregion::kSouthernEurope}},
        {"ML", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"MM", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"MN", {Region::kAsia, Subregion::kEasternAsia}},
        {"MO", {Region::kAsia, Subregion::kEasternAsia}},
        {"MP", {Region::kOceania, Subregion::kOceania}},
        {"MQ", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"MR", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"MS", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"MT", {Region::kEurope, Subregion::kSouthernEurope}},
        {"MU", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"MV", {Region::kAsia, Subregion::kSouthernAsia}},
        {"MW", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"MX", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"MY", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"MZ", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"NA", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"NC", {Region::kOceania, Subregion::kOceania}},
        {"NE", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"NF", {Region::kOceania, Subregion::kOceania}},
        {"NG", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"NI", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"NL", {Region::kEurope, Subregion::kWesternEurope}},
        {"NO", {Region::kEurope, Subregion::kNorthernEurope}},
        {"NP", {Region::kAsia, Subregion::kSouthernAsia}},
        {"NR", {Region::kOceania, Subregion::kOceania}},
        {"NU", {Region::kOceania, Subregion::kOceania}},
        {"NZ", {Region::kOceania, Subregion::kOceania}},
        {"OM", {Region::kAsia, Subregion::kWesternAsia}},
        {"PA", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"PE", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"PF", {Region::kOceania, Subregion::kOceania}},
        {"PG", {Region::kOceania, Subregion::kOceania}},
        {"PH", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"PK", {Region::kAsia, Subregion::kSouthernAsia}},
        {"PL", {Region::kEurope, Subregion::kEasternEurope}},
        {"PM", {Region::kAmericas, Subregion::kNorthernAmerica}},
        {"PN", {Region::kOceania, Subregion::kOceania}},
        {"PR", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"PS", {Region::kAsia, Subregion::kWesternAsia}},
        {"PT", {Region::kEurope, Subregion::kSouthernEurope}},
        {"PW", {Region::kOceania, Subregion::kOceania}},
        {"PY", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"QA", {Region::kAsia, Subregion::kWesternAsia}},
        {"RE", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"RO", {Region::kEurope, Subregion::kEasternEurope}},
        {"RS", {Region::kEurope, Subregion::kSouthernEurope}},
        {"RU", {Region::kEurope, Subregion::kEasternEurope}},
        {"RW", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"SA", {Region::kAsia, Subregion::kWesternAsia}},
        {"SB", {Region::kOceania, Subregion::kOceania}},
        {"SC", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"SD", {Region::kAfrica, Subregion::kNorthernAfrica}},
        {"SE", {Region::kEurope, Subregion::kNorthernEurope}},
        {"SG", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"SH", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"SI", {Region::kEurope, Subregion::kSouthernEurope}},
        {"SJ", {Region::kEurope, Subregion::kNorthernEurope}},
        {"SK", {Region::kEurope, Subregion::kEasternEurope}},
        {"SL", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"SM", {Region::kEurope, Subregion::kSouthernEurope}},
        {"SN", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"SO", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"SR", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"SS", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"ST", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"SV", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"SX", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"SY", {Region::kAsia, Subregion::kWesternAsia}},
        {"SZ", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"TC", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"TD", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"TF", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"TG", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"TH", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"TJ", {Region::kAsia, Subregion::kCentralAsia}},
        {"TK", {Region::kOceania, Subregion::kOceania}},
        {"TL", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"TM", {Region::kAsia, Subregion::kCentralAsia}},
        {"TN", {Region::kAfrica, Subregion::kNorthernAfrica}},
        {"TO", {Region::kOceania, Subregion::kOceania}},
        {"TR", {Region::kAsia, Subregion::kWesternAsia}},
        {"TT", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"TV", {Region::kOceania, Subregion::kOceania}},
        {"TW", {Region::kAsia, Subregion::kEasternAsia}},
        {"TZ", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"UA", {Region::kEurope, Subregion::kEasternEurope}},
        {"UG", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"UM", {Region::kOceania, Subregion::kOceania}},
        {"US", {Region::kAmericas, Subregion::kNorthernAmerica}},
        {"UY", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"UZ", {Region::kAsia, Subregion::kCentralAsia}},
        {"VA", {Region::kEurope, Subregion::kSouthernEurope}},
        {"VC", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"VE", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"VG", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"VI", {Region::kAmericas, Subregion::kLatinAmericaAndTheCaribbean}},
        {"VN", {Region::kAsia, Subregion::kSoutheasternAsia}},
        {"VU", {Region::kOceania, Subregion::kOceania}},
        {"WF", {Region::kOceania, Subregion::kOceania}},
        {"WS", {Region::kOceania, Subregion::kOceania}},
        {"YE", {Region::kAsia, Subregion::kWesternAsia}},
        {"YT", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"ZA", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"ZM", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
        {"ZW", {Region::kAfrica, Subregion::kSubSaharanAfrica}},
    });

inline constexpr auto kRegionToString =
    base::MakeFixedFlatMap<Region, std::string_view>({
        {Region::kAsia, "asia"},
        {Region::kEurope, "europe"},
        {Region::kAfrica, "africa"},
        {Region::kOceania, "oceania"},
        {Region::kAmericas, "americas"},
    });

inline constexpr auto kSubregionToString =
    base::MakeFixedFlatMap<Subregion, std::string_view>({
        {Subregion::kSouthernAsia, "southern-asia"},
        {Subregion::kNorthernEurope, "northern-europe"},
        {Subregion::kSouthernEurope, "southern-europe"},
        {Subregion::kNorthernAfrica, "northern-africa"},
        {Subregion::kSubSaharanAfrica, "subsaharan-africa"},
        {Subregion::kLatinAmericaAndTheCaribbean, "latin-america-caribbean"},
        {Subregion::kWesternAsia, "western-asia"},
        {Subregion::kWesternEurope, "western-europe"},
        {Subregion::kEasternEurope, "eastern-europe"},
        {Subregion::kNorthernAmerica, "northern-america"},
        {Subregion::kSoutheasternAsia, "southeastern-asia"},
        {Subregion::kEasternAsia, "eastern-asia"},
        {Subregion::kOceania, "oceania"},
        {Subregion::kCentralAsia, "central-asia"},
    });

}  // namespace

RegionIdentifiers GetRegionIdentifiers(std::string_view country_code) {
  auto region_data = kCountryRegions.find(country_code);

  if (region_data == kCountryRegions.end()) {
    return {kOtherIdentifier, kOtherIdentifier};
  }

  auto region_str_it = kRegionToString.find(region_data->second.first);
  auto subregion_str_it = kSubregionToString.find(region_data->second.second);

  std::string_view region_str;
  std::string_view subregion_str;
  if (region_str_it == kRegionToString.end()) {
    region_str = kOtherIdentifier;
  } else {
    region_str = region_str_it->second;
  }
  if (subregion_str_it == kSubregionToString.end()) {
    subregion_str = kOtherIdentifier;
  } else {
    subregion_str = subregion_str_it->second;
  }

  return {region_str, subregion_str};
}

}  // namespace p3a
