# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

[[substitution]]
description = 'Point Learn More link to the Brave support article.'
re_pattern = '(kCRSLearnMoreLink[^=]*=\s*)(?:"[^"]*"\s*)+;'
replace = '\1"https://github.com/brave/brave-browser/wiki/TLS-Policy#root-store";'
count = 1
