# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: 'Make Init virtual'
    make_virtual:
      class_name: BrowserProcessImpl
      method_name: Init

  - description: 'Make PreMainMessageLoopRun virtual'
    make_virtual:
      class_name: BrowserProcessImpl
      method_name: PreMainMessageLoopRun

  - description: 'Make StartTearDown virtual'
    make_virtual:
      class_name: BrowserProcessImpl
      method_name: StartTearDown

  - description: 'Make PostDestroyThreads virtual'
    make_virtual:
      class_name: BrowserProcessImpl
      method_name: PostDestroyThreads

  - description: 'Friend BraveBrowserProcessImpl'
    add_friend:
      class_name: BrowserProcessImpl
      friend_type: class BraveBrowserProcessImpl
