# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Register Brave's extensions API provider.
    re_pattern:
      '(ChromeExtensionsClient::ChromeExtensionsClient\(\) \{.+?\n)(\})'
    re_flags: [DOTALL]
    replace: |-
      \1  AddAPIProvider(std::make_unique<BraveExtensionsAPIProvider>());
      \2
