# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

assert(is_win)

source_set("os_crypt") {
  sources = [
    "os_crypt_key_backup.cc",
    "os_crypt_key_backup.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/os_crypt",
    "//chrome/common:constants",
    "//components/prefs",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [ "//brave/browser/os_crypt/os_crypt_key_backup_unittest.cc" ]

  deps = [
    ":os_crypt",
    "//base",
    "//base/test:test_support",
    "//chrome/browser/os_crypt",
    "//components/prefs:test_support",
    "//testing/gtest",
  ]
}
