// Copyright (c) 2023 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

// Schema types used by brave wallet asset ratio service.
namespace asset_ratio {

  enum TokenType {
    ERC20,
    ERC721
  };

  // A token info result dictionary. The whole dictionary looks like:
  //
  // {
  //   "contractAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
  //   "tokenName": "Tether USD",
  //   "symbol": "USDT",
  //   "divisor": "6",
  //   "tokenType": "ERC20",
  //   "totalSupply": "39828710009874796",
  //   "blueCheckmark": "true",
  //   "description": "Tether gives you the joint benefits of open...",
  //   "website": "https://tether.to/",
  //   "email": "support@tether.to",
  //   "blog": "https://tether.to/category/announcements/",
  //   "reddit": "",
  //   "slack": "",
  //   "facebook": "",
  //   "twitter": "https://twitter.com/Tether_to",
  //   "bitcointalk": "",
  //   "github": "",
  //   "telegram": "",
  //   "wechat": "",
  //   "linkedin": "",
  //   "discord": "",
  //   "whitepaper": "https://path/to/TetherWhitePaper.pdf",
  //   "tokenPriceUSD": "1.000000000000000000"
  // }
  //
  dictionary TokenInfoResult {
    // e.g. "0xdac17f958d2ee523a2206206994597c13d831ec7"
    DOMString contractAddress;

    // e.g. Tether USD
    DOMString tokenName;

    // e.g. "USDT"
    DOMString symbol;

    // e.g. "6"
    DOMString divisor;

    // An enumeration of toke type strings.
    TokenType tokenType;
  };

  // A token info payload dictionary. Looks like:
  //
  //   "payload": {
  //     "status": "1",
  //     "message": "OK",
  //     "result": []
  //
  dictionary TokenInfoPayload {
    // A list with result records.
    TokenInfoResult[] result;
  };


  // A token info dictionary. Looks like this:
  // {
  //   "payload": {
  //     "status": "1",
  //     "message": "OK",
  //     "result": [
  //       {
  //         "contractAddress": "0xdac17f958d2ee523a2206206994597c13d831ec7",
  //         "tokenName": "Tether USD",
  //         "symbol": "USDT",
  //         "divisor": "6",
  //         "tokenType": "ERC20",
  //         "totalSupply": "39828710009874796",
  //         "blueCheckmark": "true",
  //         "description": "Tether gives you the joint benefits of open...",
  //         "website": "https://tether.to/",
  //         "email": "support@tether.to",
  //         "blog": "https://tether.to/category/announcements/",
  //         "reddit": "",
  //         "slack": "",
  //         "facebook": "",
  //         "twitter": "https://twitter.com/Tether_to",
  //         "bitcointalk": "",
  //         "github": "",
  //         "telegram": "",
  //         "wechat": "",
  //         "linkedin": "",
  //         "discord": "",
  //         "whitepaper": "https://path/to/TetherWhitePaper.pdf",
  //         "tokenPriceUSD": "1.000000000000000000"
  //       }
  //     ]
  //   },
  //   "lastUpdated": "2021-12-09T22:02:23.187Z"
  // }
  dictionary TokenInfo {
    // A list with result records.
    TokenInfoPayload payload;
  };
};
