name: security
on:
  workflow_dispatch:
  push:
    branches: [development]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [development]

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # CodeQL analyzed languages
      matrix:
        language: [ 'generic', 'javascript', 'python' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: brave/security-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }} # optional
          assignees: |
            stoletheminerals
            thypon