# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Handle new cases in GetOriginList

      We add a number of cases to OriginFilter that now need to be handled
      exhaustively in GetOriginList
    regex:
      re_pattern: '(GetOriginList\([^)]*\)\s*\{.*?\n\s*switch[^{]*\{.*?)(\n\s*\})'
      re_flags: [DOTALL]
      replace: |-
        \1
            case web::OriginFilter::kYouTube:
              return @[
                @"https://youtube.com",
                @"https://www.youtube.com",
                @"https://m.youtube.com",
              ];
            case web::OriginFilter::kBraveSearch:
              return @[
                @"https://safesearch.brave.com",
                @"https://safesearch.brave.software",
                @"https://safesearch.bravesoftware.com",
                @"https://search-dev-local.brave.com",
                @"https://search.brave.com",
                @"https://search.brave.software",
                @"https://search.bravesoftware.com",
              ];
            case web::OriginFilter::kBraveTalk:
              return @[
                @"https://talk.brave.com",
                @"https://talk.bravesoftware.com",
                @"https://talk.brave.software",
              ];
            case web::OriginFilter::kBraveAccount:
              return @[
                @"https://account.brave.com",
                @"https://account.bravesoftware.com",
                @"https://account.brave.software",
              ];\2
