/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */
export default {
  'AED': 'United Arab Emirates dirham',
  'ARS': 'Argentine peso',
  'AUD': 'Australian dollar',
  'AZN': 'Azerbaijani manat',
  'BGN': 'Bulgarian lev',
  'BRL': 'Brazilian real',
  'CAD': 'Canadian dollar',
  'CHF': 'Swiss franc',
  'CLP': 'Chilean peso',
  'COP': 'Colombian peso',
  'CRC': 'Costa Rican colon',
  'CZK': 'Czech koruna',
  'DKK': 'Danish krone',
  'DOP': 'Dominican peso',
  'EUR': 'Euro',
  'GBP': 'Pound sterling',
  'GEL': 'Georgian lari',
  'HKD': 'Hong Kong dollar',
  'HUF': 'Hungarian forint',
  'IDR': 'Indonesian rupiah',
  'ILS': 'Israeli new shekel',
  'INR': 'Indian rupee',
  'JPY': 'Japanese yen',
  'KRW': 'South Korean won',
  'KZT': 'Kazakhstani tenge',
  'MAD': 'Moroccan dirham',
  'MDL': 'Moldovan leu',
  'MXN': 'Mexican peso',
  'MYR': 'Malaysian ringgit',
  'NAD': 'Namibian dollar',
  'NGN': 'Nigerian naira',
  'NOK': 'Norwegian krone',
  'NZD': 'New Zealand dollar',
  'PEN': 'Peruvian sol',
  'PHP': 'Philippine peso',
  'PLN': 'Polish złoty',
  'QAR': 'Qatari riyal',
  'RON': 'Romanian leu',
  'RUB': 'Russian ruble',
  'SEK': 'Swedish krona',
  'SGD': 'Singapore dollar',
  'TRY': 'Turkish lira',
  'TWD': 'New Taiwan dollar',
  'UAH': 'Ukrainian hryvnia',
  'USD': 'United States dollar',
  'UYU': 'Uruguayan peso',
  'UZS': 'Uzbekistan som',
  'VND': 'Vietnamese đồng',
  'ZAR': 'South African rand'
}
