/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */
export default {
  'AUD': 'Australian dollar',
  'BGN': 'Bulgarian lev',
  'CAD': 'Canadian dollar',
  'CHF': 'Swiss franc',
  'CNY': 'Chinese yuan',
  'COP': 'Colombia peso',
  'CZK': 'Czech Koruna',
  'DKK': 'Danish krone',
  'DOP': 'Dominican peso',
  'EGP': 'Egyptian pound',
  'EUR': 'Euro',
  'GBP': 'Pound sterling',
  'HKD': 'Hong Kong dollar',
  'HRK': 'Croatian kuna',
  'IDR': 'Indonesian rupiah',
  'ILS': 'Israeli new shekel',
  'JPY': 'Japanese yen',
  'JOD': 'Jordanian dollar',
  'KES': 'Kenyan shilling',
  'KRW': 'South Korean won',
  'KWD': 'Kuwaiti dinar',
  'LKR': 'Sri Lankan rupee',
  'MAD': 'Moroccan dirham',
  'MXN': 'Mexican peso',
  'MYR': 'Malaysian ringgit',
  'NGN': 'Nigerian naira',
  'NOK': 'Norwegian krone',
  'NZD': 'New Zealand dollar',
  'OMR': 'Omani rial',
  'PEN': 'Peruvian sol',
  'PKR': 'Pakistanee rupee',
  'PLN': 'Polish złoty',
  'RON': 'Romanian leu',
  'RUB': 'Russian ruble',
  'SEK': 'Swedish krona',
  'SGD': 'Singapore dollar',
  'THB': 'Thai baht',
  'TRY': 'Turkish lira',
  'TWD': 'Taiwan dollar',
  'USD': 'United States dollar',
  'VND': 'Vietnamese đồng',
  'ZAR': 'South African rand'
}
