import("//build/config/features.gni")

source_set("bns_security") {
  sources = [
    "bns_constants.h",
    "bns_security.cc",
    "bns_security.h",
  ]
  deps = [
    "//base",
    "//url",
  ]
}

source_set("scheme_handler") {
  sources = [
    "bns_scheme_handler.cc",
    "bns_scheme_handler.h",
    "bns_resolver.cc",
    "bns_resolver.h",
  ]
  deps = [
    ":bns_security",
    "//base",
    "//net",
    "//services/network/public/cpp",
    "//url",
  ]
}
