# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |-
      Instantiate Brave's tile interaction delegate, which adds "Add site",
      "Show frequently visited", "Show shortcuts", and "Hide widget" items to
      the tile long-press context menu.
    regex:
      re_pattern: |-
        new (TileInteractionDelegateImpl\()
      replace: |-
        new Brave\1
