/* Copyright (c) 2025 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

// Schema for Brave PSST script responses.
namespace psst_script_responses {
    enum PolicyScriptStatus {
        STARTED,
        COMPLETED
    };

    dictionary PsstTask {
        DOMString url;
        DOMString description;
        DOMString? error_description;
    };

    dictionary PolicyScriptResult {
        PolicyScriptStatus status;
        long progress;
        PsstTask[] applied_tasks;
    };
};
