/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

export const currencyNames = {
  'BTC': 'Bitcoin',
  'ETH': 'Ethereum',
  'CRO': 'Crypto.com',
  'BAT': 'Basic Attention Token',
  'XRP': 'Ripple',
  'UNI': 'Uniswap',
  'BCH': 'Bitcoin Cash',
  'LTC': 'Litecoin',
  'OMG': 'OMG Network',
  'LINK': 'Chainlink',
  'NEO': 'Neo',
  'VET': 'VeChain',
  'YFI': 'yearn.finance',
  'EOS': 'EOS',
  'KNC': 'Kyber Network',
  'XLM': 'Stellar',
  'ENJ': 'Enjin Coin',
  'XTZ': 'Tezos',
  'MKR': 'Maker',
  'DAI': 'Dai',
  'ICX': 'ICON',
  'ADA': 'Cardano',
  'MANA': 'Decentraland',
  'ATOM': 'Atomic Coin',
  'COMP': 'Compound Coin',
  'PAXG': 'Pax Gold',
  'USDC': 'USD Coin',
  'ALGO': 'Algorand',
  'CELR': 'Celer Network',
  'QTUM': 'Qtum',
  'BAND': 'Band Protocol',
  'SKL': 'SKALE Network',
  'GRT': 'The Graph',
  'KSM': 'Kusama',
  'CRV': 'Curve DAO Token',
  'THETA': 'THETA',
  'ZIL': 'Zilliqa',
  'REN': 'Ren',
  'LRC': 'Loopring',
  'NEAR': 'NEAR Protocol',
  'OCEAN': 'Ocean Protocol',
  'MATIC': 'Polygon',
  'ZRX': '0x',
  'SAND': 'The Sandbox',
  'DOT': 'Polkadot',
  'CHZ': 'Chiliz',
  'WAVES': 'Waves',
  'FLOW': 'Flow',
  'STX': 'Stacks',
  'ANKR': 'Ankr',
  'FIL': 'Filecoin',
  'EGLD': 'Elrond',
  'ONT': 'Ontology',
  'SNX': 'Synthetix',
  'BNT': 'Bancor',
  'DOGE': 'Dogecoin',
  'AAVE': 'Aave',
  'UMA': 'UMA',
  'BAL': 'Balancer',
  'RLY': 'Rally',
  'WBTC': 'Wrapped Bitcoin'
}
