#!/usr/bin/env vpython3
# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
"""Generate a git config that redirects from googlesource.com to our mirrors.

The generated file, `.gitconfig_gerrit_mirror_redirect` at the brave-core
root, includes the user's global git config and adds the mirror redirects on
top. The global config itself is never modified: callers opt in by pointing
`GIT_CONFIG_GLOBAL` at the generated file.

Two subcommands:

  install   Query Gerrit and write the generated file.
  uninstall Delete the generated file.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import urllib.parse
import urllib.request
from pathlib import Path

# Our gerrit endpoint. Keep in sync with recipes/gerrit/refresh_mirrors.py.
GERRIT_SSH_HOST = 'gerrit-ssh.brave.com'
GERRIT_SSH_PORT = 29418

# The same instance's web frontend, for anonymous REST queries.
GERRIT_HTTPS_URL = 'https://gerrit.brave.com'

# The parent project under which all mirrors are created.
MIRROR_PARENT = 'mirror'

# Where `install` writes the generated config: the brave-core root (this file
# is at tools/recipes/recipe_modules/brave_core_checkout/resources/). Ignored
# in brave-core's .gitignore.
OUTPUT_PATH = (
    Path(__file__).resolve().parents[5] / '.gitconfig_gerrit_mirror_redirect'
)

# The first line of the generated file. It records the user, so a plain
# `install` for a different user regenerates instead of reusing the file.
_HEADER = '# Generated by mirror_git_config.py install --user %s. Do not edit.'


def _fetch(url: str) -> str:
    """GET *url* and return the body as text."""
    logging.debug('>>> GET %s', url)
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode('utf-8')


def list_mirror_projects() -> list[str]:
    """Return every project name under the `mirror/` parent, sorted.

    Uses Gerrit's REST API anonymously; listing projects needs no account.

    Raises:
        RuntimeError: If the query fails (connectivity, bad response, ...).
    """
    projects: list[str] = []
    while True:
        query = urllib.parse.urlencode(
            {'p': f'{MIRROR_PARENT}/', 'S': len(projects)}
        )
        try:
            body = _fetch(f'{GERRIT_HTTPS_URL}/projects/?{query}')
            # Gerrit prefixes JSON responses with `)]}'` against XSSI.
            page = json.loads(body.split('\n', 1)[1])
        except (OSError, IndexError, ValueError) as e:
            raise RuntimeError(f'Gerrit project listing failed: {e}') from e
        projects.extend(page)
        if not page or not any(
            info.get('_more_projects') for info in page.values()
        ):
            return sorted(projects)


def upstream_urls_for(project: str) -> tuple[str, str] | None:
    """Return the (bare, `.git`-suffixed) upstream URLs *project* mirrors.

    `mirror/<host>/<path...>` mirrors `https://<host>/<path...>`.
    """
    if not project.startswith(f'{MIRROR_PARENT}/'):
        return None
    rest = project[len(MIRROR_PARENT) + 1 :]
    if '/' not in rest:
        # we shouldn't have a mirror of just a host, it must be host/path.
        return None
    bare = f'https://{rest}'
    return bare, f'{bare}.git'


def build_git_config(projects: list[str], user: str) -> str:
    """Return git-config text redirecting each mirrored upstream to *projects*.

    One `[url "<mirror>"]` stanza per project, each carrying both upstream
    forms as separate `insteadOf` values (see `upstream_urls_for`). A project
    name that doesn't decode into an upstream URL is logged and skipped rather
    than failing the whole run. *user* is the Gerrit SSH username fetches
    authenticate as.
    """
    lines = []
    for project in projects:
        urls = upstream_urls_for(project)
        if urls is None:
            logging.warning(
                'Skipping unrecognised mirror project name: %s', project
            )
            continue
        mirror_url = (
            f'ssh://{user}@{GERRIT_SSH_HOST}:{GERRIT_SSH_PORT}/{project}'
        )
        lines.append(f'[url "{mirror_url}"]')
        for upstream in urls:
            lines.append(f'\tinsteadOf = {upstream}')
    return '\n'.join(lines) + ('\n' if lines else '')


def default_global_configs() -> list[Path]:
    """Return the global git config file(s) the generated file includes.

    `$GIT_CONFIG_GLOBAL` when set, unless it already points at our own output
    (a caller re-running us with it exported); otherwise the two files git
    reads by default, in git's order: `$XDG_CONFIG_HOME/git/config` (or
    `~/.config/git/config`), then `~/.gitconfig`. Missing files are harmless,
    git skips an `[include]` whose file doesn't exist.
    """
    override = os.environ.get('GIT_CONFIG_GLOBAL')
    if override and Path(override).resolve() != OUTPUT_PATH.resolve():
        return [Path(override)]
    xdg = os.environ.get('XDG_CONFIG_HOME') or Path.home() / '.config'
    return [Path(xdg) / 'git' / 'config', Path.home() / '.gitconfig']


def _quote(value: str) -> str:
    """Quote *value* as a git config string, so `#`/`;` aren't comments."""
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def build_output(user: str, global_configs: list[Path], redirects: str) -> str:
    """Return the generated file: include *global_configs*, then *redirects*."""
    lines = [_HEADER % user, '[include]']
    lines.extend(f'\tpath = {_quote(p.as_posix())}' for p in global_configs)
    return '\n'.join(lines) + '\n' + redirects


def _installed_for(user: str) -> bool:
    """Return whether the generated file exists and was made for *user*."""
    if not OUTPUT_PATH.exists():
        return False
    with OUTPUT_PATH.open(encoding='utf-8') as f:
        return f.readline().rstrip('\r\n') == _HEADER % user


def _cmd_install(args: argparse.Namespace) -> int:
    """Handle the `install` subcommand.

    Leaves an existing file for the same user alone unless `--update` is
    given, so a plain `install` makes no network request once installed.
    """
    if not args.update and _installed_for(args.user):
        logging.info(
            'Already installed at %s. Pass --update to regenerate', OUTPUT_PATH
        )
        return 0
    projects = list_mirror_projects()
    logging.info('Found %d mirror(s) under %s/', len(projects), MIRROR_PARENT)
    output = build_output(
        args.user,
        default_global_configs(),
        build_git_config(projects, args.user),
    )
    OUTPUT_PATH.write_text(output, encoding='utf-8', newline='')
    logging.info(
        'Wrote %s. Set GIT_CONFIG_GLOBAL to it to use the mirrors', OUTPUT_PATH
    )
    return 0


def _cmd_uninstall(_args: argparse.Namespace) -> int:
    """Handle the `uninstall` subcommand."""
    if not OUTPUT_PATH.exists():
        logging.info('Nothing to remove at %s', OUTPUT_PATH)
        return 0
    OUTPUT_PATH.unlink()
    logging.info('Removed %s', OUTPUT_PATH)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Manage a git config redirecting googlesource.com '
        'to our infra.'
    )
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Print progress and debug output; silent otherwise.',
    )
    subparsers = parser.add_subparsers(dest='command', required=True)

    install_parser = subparsers.add_parser(
        'install',
        help='Query Gerrit and write a git config that includes the global '
        'one plus the mirror redirects.',
    )
    install_parser.add_argument(
        '--user',
        required=True,
        help='Gerrit SSH username the mirror fetches authenticate as.',
    )
    install_parser.add_argument(
        '--update',
        action='store_true',
        help='Regenerate and overwrite an existing '
        'file instead of leaving it alone.',
    )
    install_parser.set_defaults(handler=_cmd_install)

    uninstall_parser = subparsers.add_parser(
        'uninstall', help='Delete the generated git config.'
    )
    uninstall_parser.set_defaults(handler=_cmd_uninstall)

    args = parser.parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.ERROR,
        format='%(message)s',
    )
    return args.handler(args)


if __name__ == '__main__':
    raise SystemExit(main())
