#!/usr/bin/env vpython3
# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
"""Generate a git config that redirects from googlesource.com to our mirrors.

Two subcommands:

  install   Query Gerrit, write the mirror-redirecting config to a file, and
            point the global git config's `[include]` at it.
  uninstall Undo `install`: drop the include section, delete the file.
"""

from __future__ import annotations

import argparse
import logging
import os
import re
import subprocess
from pathlib import Path

# Our gerrit endpoint. Keep in sync with recipes/gerrit/refresh_mirrors.py.
GERRIT_SSH_HOST = 'gerrit-ssh.brave.com'
GERRIT_SSH_PORT = 29418

# The parent project under which all mirrors are created.
MIRROR_PARENT = 'mirror'

# A header to the `[include]` addition for the global config.
_INCLUDE_HEADER = '# Generated by mirror_git_config.py install. Do not edit.'

# The template for the `[include]` statement we add with `install`.
_INCLUDE_TEMPLATE = f'{_INCLUDE_HEADER}\n[include]\n\tpath = %s\n'

# A regex to capture our changes to the global config, and update it or
# remove it.
_INCLUDE_RE = re.compile(
    re.escape(_INCLUDE_HEADER) +
    r'\r?\n\[include\]\r?\n[ \t]*path[ \t]*=[ \t]*(?P<path>.+)\r?\n?')


def _run(*command: str) -> subprocess.CompletedProcess[str]:
    """Run *command*, capturing output and never raising on a non-zero exit.
    """
    logging.debug('>>> %s', ' '.join(command))
    return subprocess.run(list(command),
                          capture_output=True,
                          encoding='utf-8',
                          check=False)


def list_mirror_projects(user: str) -> list[str]:
    """Return every project name under the `mirror/` parent, sorted.

    Raises:
        RuntimeError: If the query fails (auth, connectivity, ...).
    """
    result = _run('ssh', '-p', str(GERRIT_SSH_PORT),
                  f'{user}@{GERRIT_SSH_HOST}', 'gerrit', 'ls-projects',
                  '--prefix', f'{MIRROR_PARENT}/')
    if result.returncode != 0:
        raise RuntimeError(
            f'gerrit ls-projects failed: {result.stderr.strip()}')
    return sorted(line.strip() for line in result.stdout.splitlines()
                  if line.strip())


def upstream_urls_for(project: str) -> tuple[str, str] | None:
    """Return the (bare, `.git`-suffixed) upstream URLs *project* mirrors.

    `mirror/<host>/<path...>` mirrors `https://<host>/<path...>`.
    """
    if not project.startswith(f'{MIRROR_PARENT}/'):
        return None
    rest = project[len(MIRROR_PARENT) + 1:]
    if '/' not in rest:
        # we shouldn't have a mirror of just a host, it must be host/path.
        return None
    bare = f'https://{rest}'
    return bare, f'{bare}.git'


def build_git_config(projects: list[str], user: str) -> str:
    """Return git-config text redirecting each mirrored upstream to *projects*.

    One `[url "<mirror>"]` stanza per project, each carrying both upstream
    forms as separate `insteadOf` values (see module docstring and
    `upstream_urls_for`). A project name that doesn't decode into an upstream
    URL is logged and skipped rather than failing the whole run. *user* is the
    Gerrit SSH username fetches authenticate as.
    """
    lines = []
    for project in projects:
        urls = upstream_urls_for(project)
        if urls is None:
            logging.warning('Skipping unrecognised mirror project name: %s',
                            project)
            continue
        mirror_url = f'ssh://{user}@{GERRIT_SSH_HOST}:{GERRIT_SSH_PORT}/{project}'
        lines.append(f'[url "{mirror_url}"]')
        for upstream in urls:
            lines.append(f'\tinsteadOf = {upstream}')
    return '\n'.join(lines) + ('\n' if lines else '')


def default_global_config() -> Path:
    """Return the global git config file `install`/`uninstall` manage.
    """
    override = os.environ.get('GIT_CONFIG_GLOBAL')
    return Path(override) if override else Path.home() / '.gitconfig'


def _remove_managed_include(text: str) -> tuple[str, Path | None]:
    """Strip the `[include]` statement `install` added, if present.
    """
    match = _INCLUDE_RE.search(text)
    if match is None:
        return text, None
    path = Path(match.group('path').strip())
    start, end = match.span()
    remainder = text[:start] + text[end:]
    remainder = re.sub(r'\n{3,}', '\n\n', remainder)
    return remainder, path


def install(path: Path, global_config: Path) -> None:
    """Point *global_config*'s `[include]` at *path*, replacing any prior edits.
    """
    text = global_config.read_bytes().decode(
        'utf-8') if global_config.exists() else ''
    text, _ = _remove_managed_include(text)
    prefix = text.rstrip('\n')

    stanza = _INCLUDE_TEMPLATE % path.as_posix()
    new_text = f'{prefix}\n\n{stanza}' if prefix else stanza
    global_config.parent.mkdir(parents=True, exist_ok=True)
    global_config.write_text(new_text, encoding='utf-8', newline='')


def uninstall(global_config: Path) -> Path | None:
    """Undo `install`: drop the managed include stanza, delete its target file.

    Returns the path that was un-included (whether or not the file at it
    still existed to delete), or None if *global_config* had no managed
    stanza (including when *global_config* itself doesn't exist).
    """
    if not global_config.exists():
        return None
    text, path = _remove_managed_include(
        global_config.read_bytes().decode('utf-8'))
    if path is None:
        return None
    global_config.write_text(text, encoding='utf-8', newline='')
    if path.exists():
        path.unlink()
    return path


def _cmd_install(args: argparse.Namespace) -> int:
    """Handle the `install` subcommand: generate, write, then include."""
    projects = list_mirror_projects(args.user)
    logging.info('Found %d mirror(s) under %s/', len(projects), MIRROR_PARENT)
    output = args.output.resolve()
    output.write_text(build_git_config(projects, args.user),
                      encoding='utf-8',
                      newline='')
    logging.info('Wrote mirror overrides to %s', output)
    install(output, args.global_config)
    logging.info('Included %s from %s', output, args.global_config)
    return 0


def _cmd_uninstall(args: argparse.Namespace) -> int:
    """Handle the `uninstall` subcommand."""
    path = uninstall(args.global_config)
    if path is None:
        logging.info('No managed include found in %s', args.global_config)
        return 0
    logging.info('Removed include for %s from %s', path, args.global_config)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Manage a git config redirecting googlesource.com '
        'to our infra.')
    parser.add_argument('--verbose',
                        action='store_true',
                        help='Enable debug logging.')
    subparsers = parser.add_subparsers(dest='command', required=True)

    install_parser = subparsers.add_parser(
        'install',
        help='Query Gerrit, write the mirror-redirecting config, and point '
        "the global git config's [include] at it.")
    install_parser.add_argument('--user',
                                required=True,
                                help='Gerrit SSH username for the '
                                'ls-projects query.')
    install_parser.add_argument('--output',
                                required=True,
                                type=Path,
                                help='Git config file to write (created or '
                                'overwritten) and include.')
    install_parser.add_argument('--global-config',
                                type=Path,
                                default=None,
                                help='Global git config file to edit '
                                '(defaults to $GIT_CONFIG_GLOBAL, or '
                                '~/.gitconfig).')
    install_parser.set_defaults(handler=_cmd_install)

    uninstall_parser = subparsers.add_parser(
        'uninstall',
        help='Undo install: drop the include section, delete its file.')
    uninstall_parser.add_argument('--global-config',
                                  type=Path,
                                  default=None,
                                  help='Global git config file to edit '
                                  '(defaults to $GIT_CONFIG_GLOBAL, or '
                                  '~/.gitconfig).')
    uninstall_parser.set_defaults(handler=_cmd_uninstall)

    args = parser.parse_args()
    if hasattr(args, 'global_config') and args.global_config is None:
        args.global_config = default_global_config()

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO,
                        format='%(message)s')
    return args.handler(args)


if __name__ == '__main__':
    raise SystemExit(main())
