#!/usr/bin/env vpython3
# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
"""Generate a git config that redirects from googlesource.com to our mirrors.

Two subcommands:

  install   Query Gerrit, write the mirror-redirecting config to
            `.gerrit_mirror_redirect` at the brave-core root, and point the
            global git config's `[include]` at it.
  uninstall Undo `install`: drop the include section, delete the file.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
import urllib.parse
import urllib.request
from pathlib import Path

# Our gerrit endpoint. Keep in sync with recipes/gerrit/refresh_mirrors.py.
GERRIT_SSH_HOST = 'gerrit-ssh.brave.com'
GERRIT_SSH_PORT = 29418

# The same instance's web frontend, for anonymous REST queries.
GERRIT_HTTPS_URL = 'https://gerrit.brave.com'

# The parent project under which all mirrors are created.
MIRROR_PARENT = 'mirror'

# Where `install` writes the generated config: the brave-core root (this file
# is at tools/recipes/recipe_modules/brave_core_checkout/resources/). Ignored
# in brave-core's .gitignore.
OUTPUT_PATH = Path(__file__).resolve().parents[5] / '.gerrit_mirror_redirect'

# A header to the `[include]` addition for the global config.
_INCLUDE_HEADER = '# Generated by mirror_git_config.py install. Do not edit.'

# The template for the `[include]` statement we add with `install`.
_INCLUDE_TEMPLATE = f'{_INCLUDE_HEADER}\n[include]\n\tpath = %s\n'

# A regex to capture our changes to the global config, and update it or
# remove it. The optional leading newline is the blank separator line
# `install` puts before the stanza, so removal restores the original text.
_INCLUDE_RE = re.compile(
    r'(?:\r?\n)?' + re.escape(_INCLUDE_HEADER) +
    r'\r?\n\[include\]\r?\n[ \t]*path[ \t]*=[ \t]*(?P<path>.+)\r?\n?')


def _fetch(url: str) -> str:
    """GET *url* and return the body as text.
    """
    logging.debug('>>> GET %s', url)
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode('utf-8')


def list_mirror_projects() -> list[str]:
    """Return every project name under the `mirror/` parent, sorted.

    Uses Gerrit's REST API anonymously; listing projects needs no account.

    Raises:
        RuntimeError: If the query fails (connectivity, bad response, ...).
    """
    projects: list[str] = []
    while True:
        query = urllib.parse.urlencode({
            'p': f'{MIRROR_PARENT}/',
            'S': len(projects)
        })
        try:
            body = _fetch(f'{GERRIT_HTTPS_URL}/projects/?{query}')
            # Gerrit prefixes JSON responses with `)]}'` against XSSI.
            page = json.loads(body.split('\n', 1)[1])
        except (OSError, IndexError, ValueError) as e:
            raise RuntimeError(f'Gerrit project listing failed: {e}') from e
        projects.extend(page)
        if not page or not any(
                info.get('_more_projects') for info in page.values()):
            return sorted(projects)


def upstream_urls_for(project: str) -> tuple[str, str] | None:
    """Return the (bare, `.git`-suffixed) upstream URLs *project* mirrors.

    `mirror/<host>/<path...>` mirrors `https://<host>/<path...>`.
    """
    if not project.startswith(f'{MIRROR_PARENT}/'):
        return None
    rest = project[len(MIRROR_PARENT) + 1:]
    if '/' not in rest:
        # we shouldn't have a mirror of just a host, it must be host/path.
        return None
    bare = f'https://{rest}'
    return bare, f'{bare}.git'


def build_git_config(projects: list[str]) -> str:
    """Return git-config text redirecting each mirrored upstream to *projects*.

    One `[url "<mirror>"]` stanza per project, each carrying both upstream
    forms as separate `insteadOf` values (see `upstream_urls_for`). A project
    name that doesn't decode into an upstream URL is logged and skipped rather
    than failing the whole run. Mirror URLs carry no user, so ssh picks it (and
    the key) from the caller's ssh config.
    """
    lines = []
    for project in projects:
        urls = upstream_urls_for(project)
        if urls is None:
            logging.warning('Skipping unrecognised mirror project name: %s',
                            project)
            continue
        mirror_url = f'ssh://{GERRIT_SSH_HOST}:{GERRIT_SSH_PORT}/{project}'
        lines.append(f'[url "{mirror_url}"]')
        for upstream in urls:
            lines.append(f'\tinsteadOf = {upstream}')
    return '\n'.join(lines) + ('\n' if lines else '')


def default_global_config() -> Path:
    """Return the global git config file `install`/`uninstall` manage.
    """
    override = os.environ.get('GIT_CONFIG_GLOBAL')
    return Path(override) if override else Path.home() / '.gitconfig'


def _quote(value: str) -> str:
    """Quote *value* as a git config string, so `#`/`;` aren't comments.
    """
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _unquote(value: str) -> str:
    """Undo `_quote`; unquoted values (older installs) pass through as-is.
    """
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        return re.sub(r'\\(.)', r'\1', value[1:-1])
    return value


def _remove_managed_include(text: str) -> tuple[str, Path | None]:
    """Strip the `[include]` statement `install` added, if present.
    """
    match = _INCLUDE_RE.search(text)
    if match is None:
        return text, None
    path = Path(_unquote(match.group('path')))
    start, end = match.span()
    return text[:start] + text[end:], path


def install(path: Path, global_config: Path) -> None:
    """Point *global_config*'s `[include]` at *path*, replacing any prior edits.

    A previously included file at a different path is deleted, as `uninstall`
    would.
    """
    text = global_config.read_bytes().decode(
        'utf-8') if global_config.exists() else ''
    text, previous = _remove_managed_include(text)
    prefix = text.rstrip('\n')

    stanza = _INCLUDE_TEMPLATE % _quote(path.as_posix())
    new_text = f'{prefix}\n\n{stanza}' if prefix else stanza
    global_config.parent.mkdir(parents=True, exist_ok=True)
    global_config.write_text(new_text, encoding='utf-8', newline='')

    if (previous is not None and previous.exists()
            and previous.resolve() != path.resolve()):
        previous.unlink()


def installed_path(global_config: Path) -> Path | None:
    """Return the file *global_config*'s managed include points at, if any.

    An include whose file no longer exists doesn't count as installed.
    """
    if not global_config.exists():
        return None
    _, path = _remove_managed_include(
        global_config.read_bytes().decode('utf-8'))
    return path if path is not None and path.exists() else None


def uninstall(global_config: Path) -> Path | None:
    """Undo `install`: drop the managed include stanza, delete its target file.

    Returns the path that was un-included (whether or not the file at it
    still existed to delete), or None if *global_config* had no managed
    stanza (including when *global_config* itself doesn't exist).
    """
    if not global_config.exists():
        return None
    text, path = _remove_managed_include(
        global_config.read_bytes().decode('utf-8'))
    if path is None:
        return None
    global_config.write_text(text, encoding='utf-8', newline='')
    if path.exists():
        path.unlink()
    return path


def _cmd_install(args: argparse.Namespace) -> int:
    """Handle the `install` subcommand: generate, write, then include.

    Leaves an existing install alone unless `--update` is given.
    """
    existing = installed_path(args.global_config)
    if existing is not None and not args.update:
        logging.info(
            'Already installed (%s included from %s); pass --update '
            'to regenerate', existing, args.global_config)
        return 0
    projects = list_mirror_projects()
    logging.info('Found %d mirror(s) under %s/', len(projects), MIRROR_PARENT)
    OUTPUT_PATH.write_text(build_git_config(projects),
                           encoding='utf-8',
                           newline='')
    logging.info('Wrote mirror overrides to %s', OUTPUT_PATH)
    install(OUTPUT_PATH, args.global_config)
    logging.info('Included %s from %s', OUTPUT_PATH, args.global_config)
    return 0


def _cmd_uninstall(args: argparse.Namespace) -> int:
    """Handle the `uninstall` subcommand."""
    path = uninstall(args.global_config)
    if path is None:
        logging.info('No managed include found in %s', args.global_config)
        return 0
    logging.info('Removed include for %s from %s', path, args.global_config)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Manage a git config redirecting googlesource.com '
        'to our infra.')
    parser.add_argument('--verbose',
                        action='store_true',
                        help='Enable debug logging.')
    subparsers = parser.add_subparsers(dest='command', required=True)

    install_parser = subparsers.add_parser(
        'install',
        help='Query Gerrit, write the mirror-redirecting config, and point '
        "the global git config's [include] at it.")
    install_parser.add_argument('--update',
                                action='store_true',
                                help='Regenerate and overwrite an existing '
                                'install instead of leaving it alone.')
    install_parser.add_argument('--global-config',
                                type=Path,
                                default=None,
                                help='Global git config file to edit '
                                '(defaults to $GIT_CONFIG_GLOBAL, or '
                                '~/.gitconfig).')
    install_parser.set_defaults(handler=_cmd_install)

    uninstall_parser = subparsers.add_parser(
        'uninstall',
        help='Undo install: drop the include section, delete its file.')
    uninstall_parser.add_argument('--global-config',
                                  type=Path,
                                  default=None,
                                  help='Global git config file to edit '
                                  '(defaults to $GIT_CONFIG_GLOBAL, or '
                                  '~/.gitconfig).')
    uninstall_parser.set_defaults(handler=_cmd_uninstall)

    args = parser.parse_args()
    if args.global_config is None:
        args.global_config = default_global_config()

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO,
                        format='%(message)s')
    return args.handler(args)


if __name__ == '__main__':
    raise SystemExit(main())
