[package]
name = "brave-rewards-cxx"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
async-trait = { version = "0.1", git = "https://github.com/dtolnay/async-trait" }
futures-preview = { version = "0.3.0-alpha.17" }
libc = { version = "0.2" }
brave-rewards = { git = "ssh://git@github.com/brave-intl/br-rs", branch = "skus" }
serde_json = "1.0"
tracing-subscriber = "0.2"
tracing = "0.1"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib", "rlib"]
name = "brave_rewards_cxx"
