# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: 'Add Brave-specific methods to TabStripLayoutHelper'
    add_to_public:
      class_name: TabStripLayoutHelper
      code: |
        void set_use_vertical_tabs(bool vertical);
        void set_tab_strip(TabStrip* tab_strip);
        void set_use_tree_tabs(bool tree);
        const std::map<tab_groups::TabGroupId, gfx::Rect>& group_header_ideal_bounds() const;

  - description: 'Add Brave-specific helper methods to protected section'
    add_to_protected:
      class_name: TabStripLayoutHelper
      code: |
        friend class BraveTabContainer;
        bool FillGroupInfo(std::vector<TabWidthConstraints>& tab_widths);
        bool FillNestingInfo(std::vector<TabWidthConstraints>& tab_widths);
        BraveTabStrip* GetBraveTabStrip() const;
        bool use_vertical_tabs_ = false;
        bool use_tree_tabs_ = false;
        raw_ptr<TabStrip> tab_strip_ = nullptr;
