/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

export const SHIELDS_PANEL_DATA_UPDATED = 'SHIELDS_PANEL_DATA_UPDATED'
export const SHIELDS_TOGGLED = 'SHIELDS_TOGGLED'
export const REPORT_BROKEN_SITE = 'REPORT_BROKEN_SITE'
export const RESOURCE_BLOCKED = 'RESOURCE_BLOCKED'
export const BLOCK_ADS_TRACKERS = 'BLOCK_ADS_TRACKERS'
export const CONTROLS_TOGGLED = 'CONTROLS_TOGGLED'
export const HTTPS_EVERYWHERE_TOGGLED = 'HTTPS_EVERYWHERE_TOGGLED'
export const JAVASCRIPT_TOGGLED = 'JAVASCRIPT_TOGGLED'
export const BLOCK_FINGERPRINTING = 'BLOCK_FINGERPRINTING'
export const BLOCK_COOKIES = 'BLOCK_COOKIES'
export const ALLOW_SCRIPT_ORIGINS_ONCE = 'ALLOW_SCRIPT_ORIGINS_ONCE'
export const SET_SCRIPT_BLOCKED_ONCE_CURRENT_STATE = 'SET_SCRIPT_BLOCKED_ONCE_CURRENT_STATE'
export const SET_GROUPED_SCRIPTS_BLOCKED_ONCE_CURRENT_STATE = 'SET_GROUPED_SCRIPTS_BLOCKED_ONCE_CURRENT_STATE'
export const SET_ALL_SCRIPTS_BLOCKED_ONCE_CURRENT_STATE = 'SET_ALL_SCRIPTS_BLOCKED_ONCE_CURRENT_STATE'
export const SET_FINAL_SCRIPTS_BLOCKED_ONCE_STATE = 'SET_FINAL_SCRIPTS_BLOCKED_ONCE_STATE'
export const SET_ADVANCED_VIEW_FIRST_ACCESS = 'SET_ADVANCED_VIEW_FIRST_ACCESS'
export const TOGGLE_ADVANCED_VIEW = 'TOGGLE_ADVANCED_VIEW'
export const SHIELDS_READY = 'SHIELDS_READY'
