# Copyright (c) 2021 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/build/config.gni")
import("//brave/components/playlist/core/common/buildflags/buildflags.gni")

assert(enable_playlist)

# TODO(sko) This should be component() target.
# https://github.com/brave/brave-browser/issues/27764
static_library("browser") {
  sources = [
    "media_detector_component_installer.cc",
    "media_detector_component_installer.h",
    "media_detector_component_manager.cc",
    "media_detector_component_manager.h",
    "media_stream_classifier.cc",
    "media_stream_classifier.h",
    "mime_util.cc",
    "mime_util.h",
    "playlist_background_web_contents_helper.cc",
    "playlist_background_web_contents_helper.h",
    "playlist_background_web_contentses.cc",
    "playlist_background_web_contentses.h",
    "playlist_constants.h",
    "playlist_dash_parser.cc",
    "playlist_dash_parser.h",
    "playlist_manifest_writer.cc",
    "playlist_manifest_writer.h",
    "playlist_media_file_download_manager.cc",
    "playlist_media_file_download_manager.h",
    "playlist_media_file_downloader.cc",
    "playlist_media_file_downloader.h",
    "playlist_media_handler.cc",
    "playlist_media_handler.h",
    "playlist_media_session_observer.cc",
    "playlist_media_session_observer.h",
    "playlist_network_media_detector.cc",
    "playlist_network_media_detector.h",
    "playlist_network_observer.cc",
    "playlist_network_observer.h",
    "playlist_p3a.cc",
    "playlist_p3a.h",
    "playlist_service.cc",
    "playlist_service.h",
    "playlist_stream_downloader.cc",
    "playlist_stream_downloader.h",
    "playlist_streaming.cc",
    "playlist_streaming.h",
    "playlist_tab_helper.cc",
    "playlist_tab_helper.h",
    "playlist_tab_helper_observer.h",
    "playlist_thumbnail_downloader.cc",
    "playlist_thumbnail_downloader.h",
    "type_converter.cc",
    "type_converter.h",
  ]

  public_deps = [ "//brave/components/playlist/core/common" ]

  deps = [
    "//base",
    "//brave/components/api_request_helper",
    "//brave/components/brave_component_updater/browser:public",
    "//brave/components/p3a_utils",
    "//brave/components/resources:static_resources",
    "//brave/components/resources:strings",
    "//components/component_updater",
    "//components/download/public/common:public",
    "//components/keyed_service/core",
    "//components/prefs",
    "//components/user_prefs",
    "//content/public/browser",
    "//content/public/common",
    "//crypto",
    "//media",
    "//net",
    "//services/data_decoder/public/cpp",
    "//services/media_session/public/cpp",
    "//services/media_session/public/mojom",
    "//services/network/public/cpp",
    "//services/preferences/public/cpp",
    "//third_party/blink/public/common",
    "//third_party/re2",
    "//ui/gfx",
    "//url",
  ]
}
