/* Copyright (c) 2023 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_COMPONENTS_BRAVE_VPN_BROWSER_CONNECTION_WIREGUARD_WIN_BRAVE_VPN_WIREGUARD_SERVICE_INTERACTIVE_BRAVE_VPN_TRAY_COMMAND_IDS_H_
#define BRAVE_COMPONENTS_BRAVE_VPN_BROWSER_CONNECTION_WIREGUARD_WIN_BRAVE_VPN_WIREGUARD_SERVICE_INTERACTIVE_BRAVE_VPN_TRAY_COMMAND_IDS_H_

// First command id must be higher than last command.
#define IDC_BRAVE_VPN_TRAY_EXIT_ICON 1000
#define IDC_BRAVE_VPN_TRAY_CONNECT_VPN_ITEM 1001
#define IDC_BRAVE_VPN_TRAY_DISCONNECT_VPN_ITEM 1002
#define IDC_BRAVE_VPN_TRAY_STATUS_ITEM 1003
#define IDC_BRAVE_VPN_TRAY_MANAGE_ACCOUNT_ITEM 1004
#define IDC_BRAVE_VPN_TRAY_ABOUT_ITEM 1005

#endif  // BRAVE_COMPONENTS_BRAVE_VPN_BROWSER_CONNECTION_WIREGUARD_WIN_BRAVE_VPN_WIREGUARD_SERVICE_INTERACTIVE_BRAVE_VPN_TRAY_COMMAND_IDS_H_
