/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

export const currencyNames = {
  'BTC': 'Bitcoin',
  'ETH': 'Ethereum',
  'CRO': 'Crypto.com',
  'BAT': 'Basic Attention Token',
  'XRP': 'Ripple',
  'UNI': 'Uniswap',
  'BCH': 'Bitcoin Cash',
  'LTC': 'Litecoin',
  'OMG': 'OMG Network',
  'LINK': 'Chainlink',
  'NEO': 'Neo',
  'VET': 'VeChain',
  'YFI': 'yearn.finance',
  'EOS': 'EOS',
  'KNC': 'Kyber Network',
  'XLM': 'Stellar',
  'ENJ': 'Enjin Coin',
  'XTZ': 'Tezos',
  'MKR': 'Maker',
  'DAI': 'Dai',
  'ICX': 'ICON',
  'ADA': 'Cardano',
  'MANA': 'Decentraland',
  'ATOM': 'Atomic Coin',
  'COMP': 'Compound Coin',
  'PAXG': 'Pax Gold',
  'USDC': 'USD Coin',
  'ALGO': 'Algorand',
  'CELR': 'Celer Network',
  'QTUM': 'Qtum',
  'BAND': 'Band Protocol',
  'SKL': 'SKALE Network',
  'GRT': 'The Graph',
  'KSM': 'Kusama',
  'CRV': 'Curve DAO Token',
  'THETA': 'THETA',
  'ZIL': 'Zilliqa',
  'REN': 'Ren',
  'LRC': 'Loopring',
  'NEAR': 'NEAR Protocol',
  'OCEAN': 'Ocean Protocol',
  'MATIC': 'Polygon',
  'ZRX': '0x',
  'SAND': 'The Sandbox',
  'DOT': 'Polkadot',
  'CHZ': 'Chiliz',
  'WAVES': 'Waves',
  'FLOW': 'Flow',
  'STX': 'Stacks',
  'ANKR': 'Ankr',
  'FIL': 'Filecoin',
  'EGLD': 'Elrond',
  'ONT': 'Ontology',
  'SNX': 'Synthetix',
  'BNT': 'Bancor',
  'DOGE': 'Dogecoin',
  'AAVE': 'Aave',
  'UMA': 'UMA',
  'BAL': 'Balancer',
  'RLY': 'Rally',
  'WBTC': 'Wrapped Bitcoin',
  'RSR': 'Reserve Rights',
  'SHIB': 'SHIBA INU',
  'FORTH': 'Ampleforth Governance Token',
  'HOT': 'Holo',
  'AXS': 'Axie Infinity',
  'CKB': 'Nervos Network',
  'KAVA': 'Kava.io',
  'INJ': 'Injective Protocol',
  'OGN': 'Origin Protocol',
  'TFUEL': 'Theta Fuel',
  'NANO': 'Nano',
  '1INCH': '1inch',
  'RLC': 'iExec RLC',
  'RARI': 'Rarible',
  'VTHO': 'VeThor Token',
  'TRB': 'Tellor',
  'SOL': 'Solana',
  'CHR': 'Chromia',
  'GTC': 'Gitcoin',
  'ONE': 'Harmony',
  'NKN': 'NKN',
  'CTSI': 'Cartesi',
  'STORJ': 'Storj',
  'AVAX': 'Avalanche',
  'AUDIO': 'Audius',
  'SUSHI': 'SushiSwap',
  'MIR': 'Mirror Protocol',
  'ALCX': 'Alchemix',
  'ALPHA': 'Alpha Finance',
  'ALT': 'Altcoin Index',
  'AMPL': 'Ampleforth',
  'AR': 'Arweave',
  'ASD': 'AscendEx Token',
  'BADGER': 'Badger',
  'BAO': 'BaoToken',
  'BNB': 'BNB',
  'BRZ': 'Brazilian Digital Token',
  'BSV': 'Bitcoin SV',
  'BTT': 'BitTorrent',
  'CAKE': 'PancakeSwap',
  'CEL': 'Celsius Network',
  'CONV': 'Convergence',
  'CREAM': 'Cream',
  'CUSDT': 'Compound USDT',
  'DASH': 'Dash',
  'DAWN': 'Dawn Protocol',
  'DEFI': 'DeFi Index',
  'DENT': 'Dent',
  'DMG': 'DMM Governance',
  'DODO': 'DODO',
  'DRGN': 'Dragon Index',
  'ETC': 'Ethereum Classic',
  'EXCH': 'Exchange Token Index',
  'FIDA': 'Bonfida Token',
  'FLM': 'Flamingo',
  'FTM': 'Fantom',
  'FTT': 'FTT',
  'HBAR': 'Hedera Hashgraph',
  'HNT': 'Helium',
  'HOLY': 'Holy Trinity Pool',
  'HT': 'Huobi Token',
  'HUM': 'Humanscape',
  'ICP': 'Internet Computer',
  'IOTA': 'MIOTA',
  'KIN': 'Kin',
  'LEO': 'LEO',
  'LINA': 'Linear Token',
  'LUNA': 'Terra',
  'MAPS': 'Maps.me Token',
  'MEDIA': 'MEDIA',
  'MER': 'Mercurial',
  'MID': 'Midcap Index',
  'MTA': 'Meta',
  'MTL': 'Metal',
  'MVDA10': 'MVIS Digital Assets 10 Index',
  'MVDA25': 'MVIS Digital Assets 25 Index',
  'OKB': 'OKB',
  'ORBS': 'OKB',
  'OXY': 'Oxygen Protocol',
  'PERP': 'Perpetual',
  'PRIV': 'Privacy Index',
  'PROM': 'Prometeus',
  'PUNDIX': 'Pundi X',
  'RAMP': 'RAMP',
  'RAY': 'Raydium',
  'REEF': 'Reef Finance',
  'ROOK': 'KeeperDAO',
  'RUNE': 'Thorchain',
  'SC': 'Siacoin',
  'SECO': 'Serum Ecosystem Pool Token',
  'SHIT': 'Shitcoin Index',
  'SRM': 'Serum',
  'SRN': 'Sirin Labs Token',
  'STEP': 'Step Finance',
  'STMX': 'StormX',
  'SXP': 'Swipe',
  'TOMO': 'TomoChain',
  'TRU': 'TrueFi',
  'TRX': 'TRX',
  'TRYB': 'BiLira',
  'UNISWAP': 'Uniswap Index',
  'USDT': 'Tether',
  'XAUT': 'Tether Gold',
  'XEM': 'NEM',
  'XMR': 'Monero',
  'YFII': 'DFI.Money',
  'ZEC': 'Zcash'
}
