// Copyright (c) 2026 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

// @generated — do not edit manually.
// Regenerated from model_service.cc on every `npm run ai-chat-app:build`.

import * as Mojom from '../../common/mojom'

export const APP_MODELS: Mojom.Model[] = [
  {
    key: "chat-automatic",
    displayName: "Automatic",
    visionSupport: true,
    supportsTools: true,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.CONTENT_AGENT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: true,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "automatic",
        displayMaker: "",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.BASIC_AND_PREMIUM,
        maxAssociatedContentLength: 180000,
        longConversationWarningCharacterLimit: 320000,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-claude-haiku",
    displayName: "Claude Haiku",
    visionSupport: true,
    supportsTools: true,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.CONTENT_AGENT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "claude-3-haiku",
        displayMaker: "Anthropic",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.BASIC_AND_PREMIUM,
        maxAssociatedContentLength: 180000,
        longConversationWarningCharacterLimit: 320000,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-claude-sonnet",
    displayName: "Claude Sonnet",
    visionSupport: true,
    supportsTools: true,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.CONTENT_AGENT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: true,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "claude-3-sonnet",
        displayMaker: "Anthropic",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.PREMIUM,
        maxAssociatedContentLength: 180000,
        longConversationWarningCharacterLimit: 320000,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-basic",
    displayName: "Llama 3.1 8B",
    visionSupport: false,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "llama-3-8b-instruct",
        displayMaker: "Meta",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.BASIC_AND_PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-qwen",
    displayName: "Qwen VL 30B",
    visionSupport: true,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: true,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "qwen-14b-instruct",
        displayMaker: "Alibaba Cloud",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.BASIC_AND_PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-glm-4-7-flash",
    displayName: "GLM 4.7 Flash",
    visionSupport: true,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "glm-4-7-flash",
        displayMaker: "Z.ai",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.BASIC_AND_PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-llama-4-maverick",
    displayName: "Llama 4 Maverick",
    visionSupport: true,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "llama-4-maverick",
        displayMaker: "Meta",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.BASIC_AND_PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-gpt-oss-20b",
    displayName: "GPT OSS 20B",
    visionSupport: false,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "gpt-oss-20b",
        displayMaker: "OpenAI",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.BASIC_AND_PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-gpt-oss-120b",
    displayName: "GPT OSS 120B",
    visionSupport: false,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "gpt-oss-120b",
        displayMaker: "OpenAI",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-mistral-large",
    displayName: "Mistral Large",
    visionSupport: true,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "mistral-large",
        displayMaker: "Mistral",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-kimi-k2-5",
    displayName: "Kimi K2.5",
    visionSupport: false,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "kimi-k2-5",
        displayMaker: "Moonshot AI",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-qwen-3-235b",
    displayName: "Qwen VL 235B",
    visionSupport: true,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "qwen-3-235b",
        displayMaker: "Alibaba Cloud",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-deepseek-v3-2",
    displayName: "Deepseek V3.2",
    visionSupport: false,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "deepseek-v3-2",
        displayMaker: "Deepseek",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-qwen-3-coder-480b",
    displayName: "Qwen 3 Coder 480B",
    visionSupport: false,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "qwen-3-coder-480b",
        displayMaker: "Alibaba Cloud",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.PREMIUM,
        maxAssociatedContentLength: 64000,
        longConversationWarningCharacterLimit: 9700,
      },
    } as Mojom.ModelOptions,
  },
  {
    key: "chat-claude-opus",
    displayName: "Claude Opus",
    visionSupport: true,
    supportsTools: false,
    audioSupport: false,
    videoSupport: false,
    supportedCapabilities: [Mojom.ConversationCapability.CHAT, Mojom.ConversationCapability.DEEP_RESEARCH],
    isSuggestedModel: false,
    isNearModel: false,
    options: {
      leoModelOptions: {
        name: "claude-opus",
        displayMaker: "Anthropic",
        description: '',
        category: Mojom.ModelCategory.CHAT,
        access: Mojom.ModelAccess.PREMIUM,
        maxAssociatedContentLength: 180000,
        longConversationWarningCharacterLimit: 320000,
      },
    } as Mojom.ModelOptions,
  },
]

export const DEFAULT_MODEL_KEY = 'chat-automatic'
