# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

source_set("test_support") {
  testonly = true

  sources = [
    "privacy_capturing_test_clipboard.cc",
    "privacy_capturing_test_clipboard.h",
  ]

  public_deps = [ "//ui/base/clipboard:clipboard_test_support" ]
}
