# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: Add the deps the Brave history_embeddings overrides need.
    add_literal_to_list:
      target: impl
      list_name: deps
      literal: brave_chromium_src_chrome_browser_history_embeddings_impl_deps
      import: //brave/chromium_src/chrome/browser/history_embeddings/sources.gni
