# Copyright (c) 2020 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

if (!is_android) {
  source_set("new_tab") {
    sources = [
      "new_tab_shows_navigation_throttle.h",
      "new_tab_shows_options.h",
    ]
    public_deps = [
      "//base",
      "//content/public/browser",
      "//url",
    ]

    if (is_win) {
      sources += [ "background_color_tab_helper.h" ]
      public_deps += [ "//chrome/browser/ui/tabs:tabs_public" ]
    }
  }

  source_set("impl") {
    visibility = [ "//brave/browser:core" ]

    sources = [
      "new_tab_shows_navigation_throttle.cc",
      "new_tab_shows_options.cc",
    ]

    public_deps = [ ":new_tab" ]

    deps = [
      "//base",
      "//brave/app:brave_generated_resources_grit",
      "//brave/components/constants",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/ui/webui/ntp",
      "//chrome/common",
      "//components/prefs",
      "//content/public/browser",
      "//ui/base",
      "//url",
    ]

    if (is_win) {
      sources += [ "background_color_tab_helper.cc" ]
      deps += [
        "//chrome/browser/ui/color:color_headers",
        "//ui/color",
      ]
    }
  }
}

source_set("browser_tests") {
  testonly = true

  if (is_win) {
    sources = [ "background_color_tab_helper_browsertest.cc" ]
    deps = [
      "//chrome/browser",
      "//chrome/browser:browser_process",
      "//chrome/browser/profiles:profile",
      "//chrome/browser/themes",
      "//chrome/browser/ui",
      "//chrome/browser/ui/views/frame:browser_view_header",
      "//chrome/test:test_support",
      "//chrome/test:test_support_ui",
    ]

    defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  }
}

source_set("unittest") {
  testonly = true

  if (!is_android) {
    sources = [ "new_tab_shows_options_unittest.cc" ]
    deps = [
      ":new_tab",
      "//brave/browser",
      "//brave/common",
      "//brave/components/constants",
      "//chrome/common",
      "//chrome/test:test_support",
      "//components/prefs",
      "//content/test:test_support",
      "//testing/gtest",
      "//url",
    ]
  }
}
