/* Copyright (c) 2024 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#include "chrome/browser/ui/webui/cr_components/theme_color_picker/theme_color_picker_handler.h"

#include "chrome/browser/new_tab_page/chrome_colors/generated_colors_info.h"
#include "chrome/browser/ui/webui/cr_components/theme_color_picker/customize_chrome_colors.h"
#include "chrome/common/themes/autogenerated_theme_util.h"
#include "ui/base/l10n/l10n_util.h"

theme_color_picker::mojom::ChromeColorPtr CreateChromeColor(
    chrome_colors::ColorInfo color_info) {
  auto theme_colors = GetAutogeneratedThemeColors(color_info.color);
  auto color = theme_color_picker::mojom::ChromeColor::New();
  color->name = l10n_util::GetStringUTF8(color_info.label_id);
  color->seed = color_info.color;
  color->background = theme_colors.active_tab_color;
  color->foreground = theme_colors.frame_color;
  color->variant = ui::mojom::BrowserColorVariant::kSystem;
  return color;
}

// In order to revert to the bi-color theme picker, we want
// ThemeColorPickerHandler::GetChromeColors to work how it used to work before
// ChromeRefresh2023: it should iterate over kCustomizeChromeColors and call
// GetChromeColor for each color. To achieve that, we patch
// ThemeColorPickerHandler::GetChromeColors and use kCustomizeChromeColors.
#define BRAVE_THEME_COLOR_PICKER_HANDLER_GET_CHROME_COLORS \
  for (const auto& color_info : kCustomizeChromeColors) {  \
    colors.push_back(CreateChromeColor(color_info));       \
  }                                                        \
  if (false)

// Override the effect of SetSeedColor to correct the theme coloring for tabs
// and the tab strip.
#define SetUserColorAndBrowserColorVariant(SEED_COLOR, VARIANT) \
  BuildAutogeneratedThemeFromColor(SEED_COLOR);

#include "src/chrome/browser/ui/webui/cr_components/theme_color_picker/theme_color_picker_handler.cc"

#undef SetUserColorAndBrowserColorVariant
#undef BRAVE_THEME_COLOR_PICKER_HANDLER_GET_CHROME_COLORS
