/* Copyright (c) 2024 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#include "chrome/browser/new_tab_page/chrome_colors/generated_colors_info.h"
#include "chrome/browser/themes/theme_service.h"
#include "chrome/browser/ui/webui/cr_components/theme_color_picker/customize_chrome_colors.h"

namespace chrome_colors {
const std::array<ColorInfo, std::size(kCustomizeChromeColorIds)>
    kBraveGeneratedColorsInfo = kCustomizeChromeColors;
}

// Override kGeneratedColorsInfo to use a chrome_colors namespaced version of
// kCustomizeChromeColors (see above), allowing us to return to the bi-color
// theme picker in brave://settings and the profile dialog. We call
// getChromeColors with extended_list=true from TypeScript in order to take
// advantage of this code path.
#define kGeneratedColorsInfo kBraveGeneratedColorsInfo

// Override the effect of SetSeedColor to correct the theme coloring for tabs
// and the tab strip.
#define SetUserColorAndBrowserColorVariant(SEED_COLOR, VARIANT) \
  BuildAutogeneratedThemeFromColor(SEED_COLOR);

#include "src/chrome/browser/ui/webui/cr_components/theme_color_picker/theme_color_picker_handler.cc"

#undef SetUserColorAndBrowserColorVariant
#undef kGeneratedColorsInfo
