# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/components/brave_vpn/common/buildflags/buildflags.gni")
import("//brave/components/brave_vpn/common/v2/branding.gni")
import("//build/buildflag_header.gni")

assert(enable_brave_vpn_v2)

buildflag_header("branding_buildflags") {
  header = "branding_buildflags.h"
  if (is_mac) {
    flags = [ "VPN_AGENT_APP_NAME=\"$vpn_agent_product_full_name.app\"" ]
  } else if (is_win) {
    flags = [ "VPN_AGENT_EXE_NAME=\"$vpn_agent_executable_name.exe\"" ]
  } else {
    flags = [ "VPN_AGENT_EXE_NAME=\"$vpn_agent_executable_name\"" ]
  }
}

source_set("common") {
  sources = []

  public_deps = []

  if (enable_brave_vpn_v2_apps) {
    sources += [
      "agent_utils.cc",
      "agent_utils.h",
    ]

    public_deps += [
      "//base",
      "//mojo/public/cpp/platform",
    ]
  }
}

source_set("unit_tests") {
  testonly = true

  sources = []

  deps = []

  if (enable_brave_vpn_v2_apps) {
    sources += [ "agent_utils_unittest.cc" ]

    deps += [
      ":common",
      "//base",
      "//mojo/public/cpp/platform",
      "//testing/gtest",
    ]
  }
}
