/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

export const enum types {
  ADBLOCK_ENABLE_FILTER_LIST = '@@adblock/ADBLOCK_ENABLE_FILTER_LIST',
  ADBLOCK_GET_CUSTOM_FILTERS = '@@adblock/ADBLOCK_GET_CUSTOM_FILTERS',
  ADBLOCK_GET_REGIONAL_LISTS = '@@adblock/ADBLOCK_GET_REGIONAL_LISTS',
  ADBLOCK_GET_LIST_SUBSCRIPTIONS = '@@adblock/ADBLOCK_GET_LIST_SUBSCRIPTIONS',
  ADBLOCK_ON_GET_CUSTOM_FILTERS = '@@adblock/ADBLOCK_ON_GET_CUSTOM_FILTERS',
  ADBLOCK_ON_GET_REGIONAL_LISTS = '@@adblock/ADBLOCK_ON_GET_REGIONAL_LISTS',
  ADBLOCK_ON_GET_LIST_SUBSCRIPTIONS = '@@adblock/ADBLOCK_ON_GET_LIST_SUBSCRIPTIONS',
  ADBLOCK_UPDATE_CUSTOM_FILTERS = '@@adblock/ADBLOCK_UPDATE_CUSTOM_FILTERS',
  ADBLOCK_SUBMIT_NEW_SUBSCRIPTION = '@@adblock/ADBLOCK_SUBMIT_NEW_SUBSCRIPTION',
  ADBLOCK_SET_SUBSCRIPTION_ENABLED = '@@adblock/ADBLOCK_SET_SUBSCRIPTION_ENABLED',
  ADBLOCK_DELETE_SUBSCRIPTION = '@@adblock/ADBLOCK_DELETE_SUBSCRIPTION',
  ADBLOCK_REFRESH_SUBSCRIPTION = '@@adblock/ADBLOCK_REFRESH_SUBSCRIPTION',
  ADBLOCK_VIEW_SUBSCRIPTION_SOURCE = '@@adblock/ADBLOCK_VIEW_SUBSCRIPTION_SOURCE'
}
