# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: >-
      Rename GetAcceleratorList() to GetAcceleratorList_ChromiumImpl() so that
      we can have our own implementation of GetAcceleratorList().
    re_pattern: '(std::vector<AcceleratorMapping>\ GetAcceleratorList)(\(\)\ {)'
    replace: '\1_ChromiumImpl\2'
