# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//build/config/android/rules.gni")

android_library("java") {
  sources = [
    "java/src/org/chromium/chrome/browser/webauthn/BraveCredManUiRecommender.java",
    "java/src/org/chromium/components/webauthn/BraveGmsCoreUtils.java",
    "java/src/org/chromium/components/webauthn/cred_man/BraveCredManSupportProvider.java",
    "java/src/org/chromium/components/webauthn/cred_man/BraveCredManSupportProviderDummySuper.java",
  ]

  deps = [
    "//base:base_java",
    "//build/android:build_java",
    "//components/webauthn/android:java",
  ]
}
