/* Copyright (c) 2020 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_COMPONENTS_BRAVE_WALLET_BROWSER_BRAVE_WALLET_CONSTANTS_H_
#define BRAVE_COMPONENTS_BRAVE_WALLET_BROWSER_BRAVE_WALLET_CONSTANTS_H_

#include <vector>

#include "base/no_destructor.h"
#include "brave/components/brave_wallet/browser/brave_wallet_types.h"
#include "brave/components/brave_wallet/common/brave_wallet.mojom.h"
#include "components/grit/brave_components_strings.h"
#include "ui/base/webui/web_ui_util.h"

namespace brave_wallet {

extern const char kAssetRatioBaseURL[];

constexpr uint256_t kDefaultSendEthGasLimit = 21000;
constexpr uint256_t kDefaultSendEthGasPrice = 150000000000ULL;  // 150 Gwei

constexpr int32_t kAutoLockMinutesMin = 1;
constexpr int32_t kAutoLockMinutesMax = 10080;

// List of assets from Wyre, available to buy
static base::NoDestructor<std::vector<mojom::ERCToken>> kBuyTokens(
    {{"", "Basic Attention Token", "bat.svg", true, false, "BAT", 0, true},
     {"", "Ethereum", "", false, false, "ETH", 0, true},
     {"", "USD Coin", "usdc.svg", true, false, "USDC", 0, true},
     {"", "DAI", "dai.svg", true, false, "DAI", 0, true},
     {"", "AAVE", "AAVE.svg", true, false, "AAVE", 0, true},
     {"", "Binance USD", "busd.svg", true, false, "BUSD", 0, true},
     {"", "Compound", "comp.svg", true, false, "Comp", 0, true},
     {"", "Curve", "", true, false, "CRV", 0, true},
     {"", "Gemini Dollar", "gusd.svg", true, false, "GUSD", 0, true},
     {"", "Chainlink", "chainlink.svg", true, false, "LINK", 0, true},
     {"", "Maker", "mkr.svg", true, false, "MKR", 0, true},
     {"", "Paxos Standard", "pax.svg", true, false, "PAX", 0, true},
     {"", "Synthetix", "synthetix.svg", true, false, "SNX", 0, true},
     {"", "UMA", "UMA.png", true, false, "UMA", 0, true},
     {"", "Uniswap", "uni.svg", true, false, "UNI", 0, true},
     {"", "Stably Dollar", "usds.svg", true, false, "USDS", 0, true},
     {"", "Tether", "usdt.svg", true, false, "USDT", 0, true},
     {"", "Wrapped Bitcoin", "wbtc.svg", true, false, "WBTC", 0, true},
     {"", "Year.Finance", "yfi.svg", true, false, "YFI", 0, true},
     {"", "Palm DAI", "", true, false, "PDAI", 0, true},
     {"", "Matic USDC", "", true, false, "MUSDC", 0, true}});

const char kWalletBaseDirectory[] = "BraveWallet";
const char kImageSourceHost[] = "erc-token-images";
const char kWyreID[] = "AC_MGNVBGHPA9T";
const char kBuyUrl[] =
    "https://pay.sendwyre.com/?dest=ethereum:%s"
    "&destCurrency=%s&amount=%s&accountId=%s&paymentMethod=debit-card";

constexpr webui::LocalizedString kLocalizedStrings[] = {
    {"braveWallet", IDS_BRAVE_WALLET},
    {"braveWalletDefiCategory", IDS_BRAVE_WALLET_DEFI_CATEGORY},
    {"braveWalletNftCategory", IDS_BRAVE_WALLET_NFT_CATEGORY},
    {"braveWalletSearchCategory", IDS_BRAVE_WALLET_SEARCH_CATEGORY},
    {"braveWalletDefiButtonText", IDS_BRAVE_WALLET_DEFI_BUTTON_TEXT},
    {"braveWalletNftButtonText", IDS_BRAVE_WALLET_NFT_BUTTON_TEXT},
    {"braveWalletCompoundName", IDS_BRAVE_WALLET_COMPOUND_NAME},
    {"braveWalletCompoundDescription", IDS_BRAVE_WALLET_COMPOUND_DESCRIPTION},
    {"braveWalletMakerName", IDS_BRAVE_WALLET_MAKER_NAME},
    {"braveWalletMakerDescription", IDS_BRAVE_WALLET_MAKER_DESCRIPTION},
    {"braveWalletAaveName", IDS_BRAVE_WALLET_AAVE_NAME},
    {"braveWalletAaveDescription", IDS_BRAVE_WALLET_AAVE_DESCRIPTION},
    {"braveWalletOpenSeaName", IDS_BRAVE_WALLET_OPEN_SEA_NAME},
    {"braveWalletOpenSeaDescription", IDS_BRAVE_WALLET_OPEN_SEA_DESCRIPTION},
    {"braveWalletRaribleName", IDS_BRAVE_WALLET_RARIBLE_NAME},
    {"braveWalletRaribleDescription", IDS_BRAVE_WALLET_RARIBLE_DESCRIPTION},
    {"braveWalletSearchText", IDS_BRAVE_WALLET_SEARCH_TEXT},
    {"braveWalletSideNavCrypto", IDS_BRAVE_WALLET_SIDE_NAV_CRYPTO},
    {"braveWalletSideNavRewards", IDS_BRAVE_WALLET_SIDE_NAV_REWARDS},
    {"braveWalletSideNavCards", IDS_BRAVE_WALLET_SIDE_NAV_CARDS},
    {"braveWalletTopNavPortfolio", IDS_BRAVE_WALLET_TOP_NAV_PORTFOLIO},
    {"braveWalletTopTabPrices", IDS_BRAVE_WALLET_TOP_TAB_PRICES},
    {"braveWalletTopTabApps", IDS_BRAVE_WALLET_TOP_TAB_APPS},
    {"braveWalletTopNavNFTS", IDS_BRAVE_WALLET_TOP_NAV_N_F_T_S},
    {"braveWalletTopNavAccounts", IDS_BRAVE_WALLET_TOP_NAV_ACCOUNTS},
    {"braveWalletChartLive", IDS_BRAVE_WALLET_CHART_LIVE},
    {"braveWalletChartOneDay", IDS_BRAVE_WALLET_CHART_ONE_DAY},
    {"braveWalletChartOneWeek", IDS_BRAVE_WALLET_CHART_ONE_WEEK},
    {"braveWalletChartOneMonth", IDS_BRAVE_WALLET_CHART_ONE_MONTH},
    {"braveWalletChartThreeMonths", IDS_BRAVE_WALLET_CHART_THREE_MONTHS},
    {"braveWalletChartOneYear", IDS_BRAVE_WALLET_CHART_ONE_YEAR},
    {"braveWalletChartAllTime", IDS_BRAVE_WALLET_CHART_ALL_TIME},
    {"braveWalletAddCoin", IDS_BRAVE_WALLET_ADD_COIN},
    {"braveWalletBalance", IDS_BRAVE_WALLET_BALANCE},
    {"braveWalletAccounts", IDS_BRAVE_WALLET_ACCOUNTS},
    {"braveWalletAccount", IDS_BRAVE_WALLET_ACCOUNT},
    {"braveWalletTransactions", IDS_BRAVE_WALLET_TRANSACTIONS},
    {"braveWalletPrice", IDS_BRAVE_WALLET_PRICE},
    {"braveWalletBack", IDS_BRAVE_WALLET_BACK},
    {"braveWalletAddAccount", IDS_BRAVE_WALLET_ADD_ACCOUNT},
    {"braveWalletBuy", IDS_BRAVE_WALLET_BUY},
    {"braveWalletSend", IDS_BRAVE_WALLET_SEND},
    {"braveWalletSwap", IDS_BRAVE_WALLET_SWAP},
    {"braveWalletBssToolTip", IDS_BRAVE_WALLET_BSS_TOOL_TIP},
    {"braveWalletButtonContinue", IDS_BRAVE_WALLET_BUTTON_CONTINUE},
    {"braveWalletButtonCopy", IDS_BRAVE_WALLET_BUTTON_COPY},
    {"braveWalletButtonVerify", IDS_BRAVE_WALLET_BUTTON_VERIFY},
    {"braveWalletWelcomeTitle", IDS_BRAVE_WALLET_WELCOME_TITLE},
    {"braveWalletWelcomeDescription", IDS_BRAVE_WALLET_WELCOME_DESCRIPTION},
    {"braveWalletWelcomeButton", IDS_BRAVE_WALLET_WELCOME_BUTTON},
    {"braveWalletWelcomeRestoreButton",
     IDS_BRAVE_WALLET_WELCOME_RESTORE_BUTTON},
    {"braveWalletBackupIntroTitle", IDS_BRAVE_WALLET_BACKUP_INTRO_TITLE},
    {"braveWalletBackupIntroDescription",
     IDS_BRAVE_WALLET_BACKUP_INTRO_DESCRIPTION},
    {"braveWalletBackupIntroTerms", IDS_BRAVE_WALLET_BACKUP_INTRO_TERMS},
    {"braveWalletBackupButtonSkip", IDS_BRAVE_WALLET_BACKUP_BUTTON_SKIP},
    {"braveWalletBackupButtonCancel", IDS_BRAVE_WALLET_BACKUP_BUTTON_CANCEL},
    {"braveWalletRecoveryTitle", IDS_BRAVE_WALLET_RECOVERY_TITLE},
    {"braveWalletRecoveryDescription", IDS_BRAVE_WALLET_RECOVERY_DESCRIPTION},
    {"braveWalletRecoveryWarning1", IDS_BRAVE_WALLET_RECOVERY_WARNING1},
    {"braveWalletRecoveryWarning2", IDS_BRAVE_WALLET_RECOVERY_WARNING2},
    {"braveWalletRecoveryWarning3", IDS_BRAVE_WALLET_RECOVERY_WARNING3},
    {"braveWalletRecoveryTerms", IDS_BRAVE_WALLET_RECOVERY_TERMS},
    {"braveWalletVerifyRecoveryTitle", IDS_BRAVE_WALLET_VERIFY_RECOVERY_TITLE},
    {"braveWalletVerifyRecoveryDescription",
     IDS_BRAVE_WALLET_VERIFY_RECOVERY_DESCRIPTION},
    {"braveWalletVerifyError", IDS_BRAVE_WALLET_VERIFY_ERROR},
    {"braveWalletCreatePasswordTitle", IDS_BRAVE_WALLET_CREATE_PASSWORD_TITLE},
    {"braveWalletCreatePasswordDescription",
     IDS_BRAVE_WALLET_CREATE_PASSWORD_DESCRIPTION},
    {"braveWalletCreatePasswordInput", IDS_BRAVE_WALLET_CREATE_PASSWORD_INPUT},
    {"braveWalletConfirmPasswordInput",
     IDS_BRAVE_WALLET_CONFIRM_PASSWORD_INPUT},
    {"braveWalletCreatePasswordError", IDS_BRAVE_WALLET_CREATE_PASSWORD_ERROR},
    {"braveWalletConfirmPasswordError",
     IDS_BRAVE_WALLET_CONFIRM_PASSWORD_ERROR},
    {"braveWalletLockScreenTitle", IDS_BRAVE_WALLET_LOCK_SCREEN_TITLE},
    {"braveWalletLockScreenButton", IDS_BRAVE_WALLET_LOCK_SCREEN_BUTTON},
    {"braveWalletLockScreenError", IDS_BRAVE_WALLET_LOCK_SCREEN_ERROR},
    {"braveWalletWalletPopupSettings", IDS_BRAVE_WALLET_WALLET_POPUP_SETTINGS},
    {"braveWalletWalletPopupLock", IDS_BRAVE_WALLET_WALLET_POPUP_LOCK},
    {"braveWalletWalletPopupBackup", IDS_BRAVE_WALLET_WALLET_POPUP_BACKUP},
    {"braveWalletBackupWarningText", IDS_BRAVE_WALLET_BACKUP_WARNING_TEXT},
    {"braveWalletBackupButton", IDS_BRAVE_WALLET_BACKUP_BUTTON},
    {"braveWalletDismissButton", IDS_BRAVE_WALLET_DISMISS_BUTTON},
    {"braveWalletDefaultWalletBanner", IDS_BRAVE_WALLET_DEFAULT_WALLET_BANNER},
    {"braveWalletRestoreTite", IDS_BRAVE_WALLET_RESTORE_TITE},
    {"braveWalletRestoreDescription", IDS_BRAVE_WALLET_RESTORE_DESCRIPTION},
    {"braveWalletRestoreError", IDS_BRAVE_WALLET_RESTORE_ERROR},
    {"braveWalletRestorePlaceholder", IDS_BRAVE_WALLET_RESTORE_PLACEHOLDER},
    {"braveWalletRestoreShowPhrase", IDS_BRAVE_WALLET_RESTORE_SHOW_PHRASE},
    {"braveWalletRestoreLegacyCheckBox",
     IDS_BRAVE_WALLET_RESTORE_LEGACY_CHECK_BOX},
    {"braveWalletRestoreFormText", IDS_BRAVE_WALLET_RESTORE_FORM_TEXT},
    {"braveWalletToolTipCopyToClipboard",
     IDS_BRAVE_WALLET_TOOL_TIP_COPY_TO_CLIPBOARD},
    {"braveWalletAccountsPrimary", IDS_BRAVE_WALLET_ACCOUNTS_PRIMARY},
    {"braveWalletAccountsSecondary", IDS_BRAVE_WALLET_ACCOUNTS_SECONDARY},
    {"braveWalletAccountsSecondaryDisclaimer",
     IDS_BRAVE_WALLET_ACCOUNTS_SECONDARY_DISCLAIMER},
    {"braveWalletAccountsAssets", IDS_BRAVE_WALLET_ACCOUNTS_ASSETS},
    {"braveWalletAccountsEditVisibleAssets",
     IDS_BRAVE_WALLET_ACCOUNTS_EDIT_VISIBLE_ASSETS},
    {"braveWalletAddAccountCreate", IDS_BRAVE_WALLET_ADD_ACCOUNT_CREATE},
    {"braveWalletAddAccountImport", IDS_BRAVE_WALLET_ADD_ACCOUNT_IMPORT},
    {"braveWalletAddAccountHardware", IDS_BRAVE_WALLET_ADD_ACCOUNT_HARDWARE},
    {"braveWalletAddAccountConnect", IDS_BRAVE_WALLET_ADD_ACCOUNT_CONNECT},
    {"braveWalletAddAccountPlaceholder",
     IDS_BRAVE_WALLET_ADD_ACCOUNT_PLACEHOLDER},
    {"braveWalletImportAccountDisclaimer",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_DISCLAIMER},
    {"braveWalletImportAccountPlaceholder",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_PLACEHOLDER},
    {"braveWalletImportAccountKey", IDS_BRAVE_WALLET_IMPORT_ACCOUNT_KEY},
    {"braveWalletImportAccountFile", IDS_BRAVE_WALLET_IMPORT_ACCOUNT_FILE},
    {"braveWalletImportAccountUploadButton",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_UPLOAD_BUTTON},
    {"braveWalletImportAccountUploadPlaceholder",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_UPLOAD_PLACEHOLDER},
    {"braveWalletImportAccountError", IDS_BRAVE_WALLET_IMPORT_ACCOUNT_ERROR},
    {"braveWalletConnectHardwareTitle",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_TITLE},
    {"braveWalletConnectHardwareInfo1",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_INFO1},
    {"braveWalletConnectHardwareInfo2",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_INFO2},
    {"braveWalletConnectHardwareInfo3",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_INFO3},
    {"braveWalletConnectHardwareTrezor",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_TREZOR},
    {"braveWalletConnectHardwareLedger",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_LEDGER},
    {"braveWalletConnectingHardwareWallet",
     IDS_BRAVE_WALLET_CONNECTING_HARDWARE_WALLET},
    {"braveWalletAddCheckedAccountsHardwareWallet",
     IDS_BRAVE_WALLET_ADD_CHECKED_ACCOUNTS_HARDWARE_WALLET},
    {"braveWalletLoadMoreAccountsHardwareWallet",
     IDS_BRAVE_WALLET_LOAD_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"braveWalletLoadingMoreAccountsHardwareWallet",
     IDS_BRAVE_WALLET_LOADING_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"braveWalletSearchScannedAccounts",
     IDS_BRAVE_WALLET_SEARCH_SCANNED_ACCOUNTS},
    {"braveWalletSwitchHDPathTextHardwareWallet",
     IDS_BRAVE_WALLET_SWITCH_H_D_PATH_TEXT_HARDWARE_WALLET},
    {"braveWalletLedgerLiveDerivationPath",
     IDS_BRAVE_WALLET_LEDGER_LIVE_DERIVATION_PATH},
    {"braveWalletLedgerLegacyDerivationPath",
     IDS_BRAVE_WALLET_LEDGER_LEGACY_DERIVATION_PATH},
    {"braveWalletUnknownInternalError",
     IDS_BRAVE_WALLET_UNKNOWN_INTERNAL_ERROR},
    {"braveWalletAccountSettingsDetails",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_DETAILS},
    {"braveWalletAccountSettingsWatchlist",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_WATCHLIST},
    {"braveWalletAccountSettingsPrivateKey",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_PRIVATE_KEY},
    {"braveWalletAccountSettingsSave", IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_SAVE},
    {"braveWalletAccountSettingsRemove",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_REMOVE},
    {"braveWalletWatchlistAddCustomAsset",
     IDS_BRAVE_WALLET_WATCHLIST_ADD_CUSTOM_ASSET},
    {"braveWalletWatchListTokenName", IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_NAME},
    {"braveWalletWatchListTokenAddress",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_ADDRESS},
    {"braveWalletWatchListTokenSymbol",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_SYMBOL},
    {"braveWalletWatchListTokenDecimals",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_DECIMALS},
    {"braveWalletWatchListAdd", IDS_BRAVE_WALLET_WATCH_LIST_ADD},
    {"braveWalletWatchListDoneButton", IDS_BRAVE_WALLET_WATCH_LIST_DONE_BUTTON},
    {"braveWalletWatchListSuggestion", IDS_BRAVE_WALLET_WATCH_LIST_SUGGESTION},
    {"braveWalletWatchListNoAsset", IDS_BRAVE_WALLET_WATCH_LIST_NO_ASSET},
    {"braveWalletWatchListSearchPlaceholder",
     IDS_BRAVE_WALLET_WATCH_LIST_SEARCH_PLACEHOLDER},
    {"braveWalletWatchListError", IDS_BRAVE_WALLET_WATCH_LIST_ERROR},
    {"braveWalletAccountSettingsDisclaimer",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_DISCLAIMER},
    {"braveWalletAccountSettingsShowKey",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_SHOW_KEY},
    {"braveWalletAccountSettingsHideKey",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_HIDE_KEY},
    {"braveWalletAccountSettingsUpdateError",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_UPDATE_ERROR},
    {"braveWalletPreset25", IDS_BRAVE_WALLET_PRESET25},
    {"braveWalletPreset50", IDS_BRAVE_WALLET_PRESET50},
    {"braveWalletPreset75", IDS_BRAVE_WALLET_PRESET75},
    {"braveWalletPreset100", IDS_BRAVE_WALLET_PRESET100},
    {"braveWalletNetworkETH", IDS_BRAVE_WALLET_NETWORK_E_T_H},
    {"braveWalletNetworkMain", IDS_BRAVE_WALLET_NETWORK_MAIN},
    {"braveWalletNetworkTest", IDS_BRAVE_WALLET_NETWORK_TEST},
    {"braveWalletNetworkRopsten", IDS_BRAVE_WALLET_NETWORK_ROPSTEN},
    {"braveWalletNetworkKovan", IDS_BRAVE_WALLET_NETWORK_KOVAN},
    {"braveWalletNetworkRinkeby", IDS_BRAVE_WALLET_NETWORK_RINKEBY},
    {"braveWalletNetworkGoerli", IDS_BRAVE_WALLET_NETWORK_GOERLI},
    {"braveWalletNetworkBinance", IDS_BRAVE_WALLET_NETWORK_BINANCE},
    {"braveWalletNetworkBinanceAbbr", IDS_BRAVE_WALLET_NETWORK_BINANCE_ABBR},
    {"braveWalletNetworkLocalhost", IDS_BRAVE_WALLET_NETWORK_LOCALHOST},
    {"braveWalletSelectAccount", IDS_BRAVE_WALLET_SELECT_ACCOUNT},
    {"braveWalletSearchAccount", IDS_BRAVE_WALLET_SEARCH_ACCOUNT},
    {"braveWalletSelectNetwork", IDS_BRAVE_WALLET_SELECT_NETWORK},
    {"braveWalletSelectAsset", IDS_BRAVE_WALLET_SELECT_ASSET},
    {"braveWalletSearchAsset", IDS_BRAVE_WALLET_SEARCH_ASSET},
    {"braveWalletSwapFrom", IDS_BRAVE_WALLET_SWAP_FROM},
    {"braveWalletSwapTo", IDS_BRAVE_WALLET_SWAP_TO},
    {"braveWalletSwapEstimate", IDS_BRAVE_WALLET_SWAP_ESTIMATE},
    {"braveWalletSwapMarket", IDS_BRAVE_WALLET_SWAP_MARKET},
    {"braveWalletSwapLimit", IDS_BRAVE_WALLET_SWAP_LIMIT},
    {"braveWalletSwapPriceIn", IDS_BRAVE_WALLET_SWAP_PRICE_IN},
    {"braveWalletBuyTitle", IDS_BRAVE_WALLET_BUY_TITLE},
    {"braveWalletBuyDescription", IDS_BRAVE_WALLET_BUY_DESCRIPTION},
    {"braveWalletBuyWyreButton", IDS_BRAVE_WALLET_BUY_WYRE_BUTTON},
    {"braveWalletBuyFaucetButton", IDS_BRAVE_WALLET_BUY_FAUCET_BUTTON},
    {"braveWalletSignTransactionTitle",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_TITLE},
    {"braveWalletSignWarning", IDS_BRAVE_WALLET_SIGN_WARNING},
    {"braveWalletSignWarningTitle", IDS_BRAVE_WALLET_SIGN_WARNING_TITLE},
    {"braveWalletSignTransactionMessageTitle",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_MESSAGE_TITLE},
    {"braveWalletSignTransactionButton",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_BUTTON},
    {"braveWalletAllowSpendTitle", IDS_BRAVE_WALLET_ALLOW_SPEND_TITLE},
    {"braveWalletAllowSpendDescriptionFirstHalf",
     IDS_BRAVE_WALLET_ALLOW_SPEND_DESCRIPTION_FIRST_HALF},
    {"braveWalletAllowSpendDescriptionSecondHalf",
     IDS_BRAVE_WALLET_ALLOW_SPEND_DESCRIPTION_SECOND_HALF},
    {"braveWalletAllowSpendBoxTitle", IDS_BRAVE_WALLET_ALLOW_SPEND_BOX_TITLE},
    {"braveWalletAllowSpendTransactionFee",
     IDS_BRAVE_WALLET_ALLOW_SPEND_TRANSACTION_FEE},
    {"braveWalletAllowSpendEditButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_EDIT_BUTTON},
    {"braveWalletAllowSpendDetailsButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_DETAILS_BUTTON},
    {"braveWalletAllowSpendRejectButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_REJECT_BUTTON},
    {"braveWalletAllowSpendConfirmButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_CONFIRM_BUTTON},
    {"braveWalletAllowAddNetworkTitle",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_TITLE},
    {"braveWalletAllowAddNetworkDescription",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_DESCRIPTION},
    {"braveWalletAllowAddNetworkLearnMoreButton",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_LEARN_MORE_BUTTON},
    {"braveWalletAllowAddNetworkName", IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_NAME},
    {"braveWalletAllowAddNetworkUrl", IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_URL},
    {"braveWalletAllowAddNetworkDetailsButton",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_DETAILS_BUTTON},
    {"braveWalletAllowAddNetworkApproveButton",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_APPROVE_BUTTON},
    {"braveWalletAllowAddNetworkChainID",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_CHAIN_I_D},
    {"braveWalletAllowAddNetworkCurrencySymbol",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_CURRENCY_SYMBOL},
    {"braveWalletAllowAddNetworkExplorer",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_EXPLORER},
    {"braveWalletConfirmTransactionTotal",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_TOTAL},
    {"braveWalletConfirmTransactionGasFee",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_GAS_FEE},
    {"braveWalletConfirmTransactionBid",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_BID},
    {"braveWalletConfirmTransactionAmountGas",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_AMOUNT_GAS},
    {"braveWalletConfirmTransactionNoData",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_NO_DATA},
    {"braveWalletConfirmTransactionNext",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_NEXT},
    {"braveWalletConfirmTransactionFrist",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_FRIST},
    {"braveWalletConfirmTransactions", IDS_BRAVE_WALLET_CONFIRM_TRANSACTIONS},
    {"braveWalletPanelTitle", IDS_BRAVE_WALLET_PANEL_TITLE},
    {"braveWalletPanelConnected", IDS_BRAVE_WALLET_PANEL_CONNECTED},
    {"braveWalletSitePermissionsAccounts",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_ACCOUNTS},
    {"braveWalletSitePermissionsTitle",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_TITLE},
    {"braveWalletSitePermissionsDisconnect",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_DISCONNECT},
    {"braveWalletPanelNotConnected", IDS_BRAVE_WALLET_PANEL_NOT_CONNECTED},
    {"braveWalletTransactionDetailBoxFunction",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_BOX_FUNCTION},
    {"braveWalletTransactionDetailBoxHex",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_BOX_HEX},
    {"braveWalletTransactionDetailBoxBytes",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_BOX_BYTES},
    {"braveWalletConnectWithSiteTitle",
     IDS_BRAVE_WALLET_CONNECT_WITH_SITE_TITLE},
    {"braveWalletConnectWithSiteDescription1",
     IDS_BRAVE_WALLET_CONNECT_WITH_SITE_DESCRIPTION1},
    {"braveWalletConnectWithSiteDescription2",
     IDS_BRAVE_WALLET_CONNECT_WITH_SITE_DESCRIPTION2},
    {"braveWalletConnectWithSiteNext", IDS_BRAVE_WALLET_CONNECT_WITH_SITE_NEXT},
    {"braveWalletConnectWithSiteHeaderTitle",
     IDS_BRAVE_WALLET_CONNECT_WITH_SITE_HEADER_TITLE},
    {"braveWalletImportFromExternalNewPassword",
     IDS_BRAVE_WALLET_IMPORT_FROM_EXTERNAL_NEW_PASSWORD},
    {"braveWalletImportFromExternalCreatePassword",
     IDS_BRAVE_WALLET_IMPORT_FROM_EXTERNAL_CREATE_PASSWORD},
    {"braveWalletImportFromExternalPasswordCheck",
     IDS_BRAVE_WALLET_IMPORT_FROM_EXTERNAL_PASSWORD_CHECK},
    {"braveWalletImportMetaMaskTitle", IDS_BRAVE_WALLET_IMPORT_META_MASK_TITLE},
    {"braveWalletImportTitle", IDS_BRAVE_WALLET_IMPORT_TITLE},
    {"braveWalletImportDescriptionOne",
     IDS_BRAVE_WALLET_IMPORT_DESCRIPTION_ONE},
    {"braveWalletImportDescriptionTwo",
     IDS_BRAVE_WALLET_IMPORT_DESCRIPTION_TWO},
    {"braveWalletImportMetaMaskInput", IDS_BRAVE_WALLET_IMPORT_META_MASK_INPUT},
    {"braveWalletImportBraveLegacyTitle",
     IDS_BRAVE_WALLET_IMPORT_BRAVE_LEGACY_TITLE},
    {"braveWalletCryptoWalletsDetected",
     IDS_BRAVE_WALLET_CRYPTO_WALLETS_DETECTED},
    {"braveWalletCryptoWalletsDescriptionOne",
     IDS_BRAVE_WALLET_CRYPTO_WALLETS_DESCRIPTION_ONE},
    {"braveWalletCryptoWalletsDescriptionTwoFirst",
     IDS_BRAVE_WALLET_CRYPTO_WALLETS_DESCRIPTION_TWO_FIRST},
    {"braveWalletCryptoWalletsDescriptionTwoSecond",
     IDS_BRAVE_WALLET_CRYPTO_WALLETS_DESCRIPTION_TWO_SECOND},
    {"braveWalletImportBraveLegacyDescription",
     IDS_BRAVE_WALLET_IMPORT_BRAVE_LEGACY_DESCRIPTION},
    {"braveWalletImportBraveLegacyInput",
     IDS_BRAVE_WALLET_IMPORT_BRAVE_LEGACY_INPUT},
    {"braveWalletImportBraveLegacyAltButton",
     IDS_BRAVE_WALLET_IMPORT_BRAVE_LEGACY_ALT_BUTTON},
    {"braveWalletConnectHardwarePanelConnected",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_CONNECTED},
    {"braveWalletConnectHardwarePanelDisconnected",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_DISCONNECTED},
    {"braveWalletConnectHardwarePanelInstructions",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_INSTRUCTIONS},
    {"braveWalletConnectHardwarePanelConnect",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_CONNECT},
    {"braveWalletConnectHardwarePanelConfirmation",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_CONFIRMATION},
    {"braveWalletTransactionSent", IDS_BRAVE_WALLET_TRANSACTION_SENT},
    {"braveWalletTransactionReceived", IDS_BRAVE_WALLET_TRANSACTION_RECEIVED},
    {"braveWalletTransactionExplorerMissing",
     IDS_BRAVE_WALLET_TRANSACTION_EXPLORER_MISSING},
    {"braveWalletTransactionExplorer", IDS_BRAVE_WALLET_TRANSACTION_EXPLORER},
    {"braveWalletTransactionPlaceholder",
     IDS_BRAVE_WALLET_TRANSACTION_PLACEHOLDER},
    {"braveWalletEditGasTitle1", IDS_BRAVE_WALLET_EDIT_GAS_TITLE1},
    {"braveWalletEditGasTitle2", IDS_BRAVE_WALLET_EDIT_GAS_TITLE2},
    {"braveWalletEditGasDescription", IDS_BRAVE_WALLET_EDIT_GAS_DESCRIPTION},
    {"braveWalletEditGasLow", IDS_BRAVE_WALLET_EDIT_GAS_LOW},
    {"braveWalletEditGasOptimal", IDS_BRAVE_WALLET_EDIT_GAS_OPTIMAL},
    {"braveWalletEditGasHigh", IDS_BRAVE_WALLET_EDIT_GAS_HIGH},
    {"braveWalletEditGasLimit", IDS_BRAVE_WALLET_EDIT_GAS_LIMIT},
    {"braveWalletEditGasPerGasPrice", IDS_BRAVE_WALLET_EDIT_GAS_PER_GAS_PRICE},
    {"braveWalletEditGasPerTipLimit", IDS_BRAVE_WALLET_EDIT_GAS_PER_TIP_LIMIT},
    {"braveWalletEditGasPerPriceLimit",
     IDS_BRAVE_WALLET_EDIT_GAS_PER_PRICE_LIMIT},
    {"braveWalletEditGasMaxFee", IDS_BRAVE_WALLET_EDIT_GAS_MAX_FEE},
    {"braveWalletEditGasMaximumFee", IDS_BRAVE_WALLET_EDIT_GAS_MAXIMUM_FEE},
    {"braveWalletEditGasBaseFee", IDS_BRAVE_WALLET_EDIT_GAS_BASE_FEE},
    {"braveWalletEditGasGwei", IDS_BRAVE_WALLET_EDIT_GAS_GWEI},
    {"braveWalletEditGasSetCustom", IDS_BRAVE_WALLET_EDIT_GAS_SET_CUSTOM},
    {"braveWalletEditGasSetSuggested", IDS_BRAVE_WALLET_EDIT_GAS_SET_SUGGESTED},
    {"braveWalletSwapInsufficientBalance",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_BALANCE},
    {"braveWalletSwapInsufficientEthBalance",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_ETH_BALANCE},
    {"braveWalletSwapInsufficientLiquidity",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_LIQUIDITY},
    {"braveWalletSwapInsufficientAllowance",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_ALLOWANCE},
    {"braveWalletSwapUnknownError", IDS_BRAVE_WALLET_SWAP_UNKNOWN_ERROR},
    {"braveWalletUnlockError", IDS_BRAVE_WALLET_UNLOCK_ERROR},
    {"braveWalletDeviceUnknownScheme", IDS_BRAVE_WALLET_UNKNOWN_SCHEME_ERROR},
    {"braveWalletApprovalTransactionIntent",
     IDS_BRAVE_WALLET_APPROVAL_TRANSACTION_INTENT}};

const char kRopstenSwapBaseAPIURL[] = "https://ropsten.api.0x.org/";
const char kRopstenBuyTokenPercentageFee[] = "0.00875";
const char kRopstenFeeRecipient[] =
    "0xa92D461a9a988A7f11ec285d39783A637Fdd6ba4";

const char kSwapBaseAPIURL[] = "https://api.0x.org/";
const char kBuyTokenPercentageFee[] = "0.00875";
const char kFeeRecipient[] = "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";

}  // namespace brave_wallet

#endif  // BRAVE_COMPONENTS_BRAVE_WALLET_BROWSER_BRAVE_WALLET_CONSTANTS_H_
