/* Copyright (c) 2020 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_COMPONENTS_BRAVE_WALLET_BROWSER_BRAVE_WALLET_CONSTANTS_H_
#define BRAVE_COMPONENTS_BRAVE_WALLET_BROWSER_BRAVE_WALLET_CONSTANTS_H_

#include <string>
#include <vector>

#include "base/no_destructor.h"
#include "brave/components/brave_wallet/common/brave_wallet.mojom.h"
#include "brave/components/brave_wallet/common/brave_wallet_types.h"
#include "components/grit/brave_components_strings.h"
#include "ui/base/webui/web_ui_util.h"

namespace brave_wallet {

constexpr char kAssetRatioBaseURL[] = "https://ratios.rewards.brave.com/";

constexpr uint256_t kDefaultSendEthGasLimit = 21000;
constexpr uint256_t kDefaultERC20TransferGasLimit = 300000;
constexpr uint256_t kDefaultERC721TransferGasLimit = 800000;
constexpr uint256_t kDefaultERC20ApproveGasLimit = 300000;

constexpr int32_t kAutoLockMinutesMin = 1;
constexpr int32_t kAutoLockMinutesMax = 10080;

constexpr char kWalletBaseDirectory[] = "BraveWallet";
constexpr char kImageSourceHost[] = "erc-token-images";
constexpr char kWyreID[] = "AC_MGNVBGHPA9T";
constexpr char kWyreBaseUrl[] = "https://pay.sendwyre.com";
constexpr char kRampBaseUrl[] = "https://buy.ramp.network";
constexpr char kRampID[] = "8yxja8782as5essk2myz3bmh4az6gpq4nte9n2gf";
constexpr char kSardineStorefrontBaseURL[] = "https://crypto.sardine.ai";
constexpr char kSardineClientTokensURL[] =
    "https://api.sardine.ai/v1/auth/client-tokens";

constexpr webui::LocalizedString kLocalizedStrings[] = {
    {"braveWalletOrdinalTwentyFourth", IDS_BRAVE_WALLET_ORDINAL_TWENTY_FOURTH},
    {"braveWalletOrdinalTwentyThird", IDS_BRAVE_WALLET_ORDINAL_TWENTY_THIRD},
    {"braveWalletOrdinalTwentySecond", IDS_BRAVE_WALLET_ORDINAL_TWENTY_SECOND},
    {"braveWalletOrdinalTwentyFirst", IDS_BRAVE_WALLET_ORDINAL_TWENTY_FIRST},
    {"braveWalletOrdinalTwentieth", IDS_BRAVE_WALLET_ORDINAL_TWENTIETH},
    {"braveWalletOrdinalNineteenth", IDS_BRAVE_WALLET_ORDINAL_NINETEENTH},
    {"braveWalletOrdinalEighteenth", IDS_BRAVE_WALLET_ORDINAL_EIGHTEENTH},
    {"braveWalletOrdinalSeventeenth", IDS_BRAVE_WALLET_ORDINAL_SEVENTEENTH},
    {"braveWalletOrdinalSixteenth", IDS_BRAVE_WALLET_ORDINAL_SIXTEENTH},
    {"braveWalletOrdinalFifteenth", IDS_BRAVE_WALLET_ORDINAL_FIFTEENTH},
    {"braveWalletOrdinalFourteenth", IDS_BRAVE_WALLET_ORDINAL_FOURTEENTH},
    {"braveWalletOridinalThirteenth", IDS_BRAVE_WALLET_ORIDINAL_THIRTEENTH},
    {"braveWalletOrdinalTwelfth", IDS_BRAVE_WALLET_ORDINAL_TWELFTH},
    {"braveWalletOrdinalSuffixOther", IDS_BRAVE_WALLET_ORDINAL_SUFFIX_OTHER},
    {"braveWalletOrdinalSuffixFew", IDS_BRAVE_WALLET_ORDINAL_SUFFIX_FEW},
    {"braveWalletOrdinalSuffixTwo", IDS_BRAVE_WALLET_ORDINAL_SUFFIX_TWO},
    {"braveWalletOrdinalSuffixOne", IDS_BRAVE_WALLET_ORDINAL_SUFFIX_ONE},
    {"braveWalletOrdinalEleventh", IDS_BRAVE_WALLET_ORDINAL_ELEVENTH},
    {"braveWalletOrdinalTenth", IDS_BRAVE_WALLET_ORDINAL_TENTH},
    {"braveWalletOrdinalNinth", IDS_BRAVE_WALLET_ORDINAL_NINTH},
    {"braveWalletOrdinalEighth", IDS_BRAVE_WALLET_ORDINAL_EIGHTH},
    {"braveWalletOrdinalSeventh", IDS_BRAVE_WALLET_ORDINAL_SEVENTH},
    {"braveWalletOrdinalSixth", IDS_BRAVE_WALLET_ORDINAL_SIXTH},
    {"braveWalletOrdinalFifth", IDS_BRAVE_WALLET_ORDINAL_FIFTH},
    {"braveWalletOrdinalFourth", IDS_BRAVE_WALLET_ORDINAL_FOURTH},
    {"braveWalletOrdinalSecond", IDS_BRAVE_WALLET_ORDINAL_SECOND},
    {"braveWalletEnterYourPassword", IDS_BRAVE_WALLET_ENTER_YOUR_PASSWORD},
    {"braveWalletClickToSwitch", IDS_BRAVE_WALLET_CLICK_TO_SWITCH},
    {"braveWalletUnlockNeededToCreateAccount",
     IDS_BRAVE_WALLET_UNLOCK_NEEDED_TO_CREATE_ACCOUNT},
    {"braveWalletMultiChain", IDS_BRAVE_WALLET_MULTI_CHAIN},
    {"braveWalletPerksBrowserNative", IDS_BRAVE_WALLET_PERKS_BROWSER_NATIVE},
    {"braveWalletPerksTokens", IDS_BRAVE_WALLET_PERKS_TOKENS},
    {"braveWallet", IDS_BRAVE_WALLET},
    {"braveWalletDefiCategory", IDS_BRAVE_WALLET_DEFI_CATEGORY},
    {"braveWalletNftCategory", IDS_BRAVE_WALLET_NFT_CATEGORY},
    {"braveWalletSearchCategory", IDS_BRAVE_WALLET_SEARCH_CATEGORY},
    {"braveWalletDefiButtonText", IDS_BRAVE_WALLET_DEFI_BUTTON_TEXT},
    {"braveWalletNftButtonText", IDS_BRAVE_WALLET_NFT_BUTTON_TEXT},
    {"braveWalletCompoundName", IDS_BRAVE_WALLET_COMPOUND_NAME},
    {"braveWalletCompoundDescription", IDS_BRAVE_WALLET_COMPOUND_DESCRIPTION},
    {"braveWalletMakerName", IDS_BRAVE_WALLET_MAKER_NAME},
    {"braveWalletMakerDescription", IDS_BRAVE_WALLET_MAKER_DESCRIPTION},
    {"braveWalletAaveName", IDS_BRAVE_WALLET_AAVE_NAME},
    {"braveWalletAaveDescription", IDS_BRAVE_WALLET_AAVE_DESCRIPTION},
    {"braveWalletOpenSeaName", IDS_BRAVE_WALLET_OPEN_SEA_NAME},
    {"braveWalletOpenSeaDescription", IDS_BRAVE_WALLET_OPEN_SEA_DESCRIPTION},
    {"braveWalletRaribleName", IDS_BRAVE_WALLET_RARIBLE_NAME},
    {"braveWalletRaribleDescription", IDS_BRAVE_WALLET_RARIBLE_DESCRIPTION},
    {"braveWalletSearchText", IDS_BRAVE_WALLET_SEARCH_TEXT},
    {"braveWalletSideNavCrypto", IDS_BRAVE_WALLET_SIDE_NAV_CRYPTO},
    {"braveWalletSideNavRewards", IDS_BRAVE_WALLET_SIDE_NAV_REWARDS},
    {"braveWalletSideNavCards", IDS_BRAVE_WALLET_SIDE_NAV_CARDS},
    {"braveWalletTopNavPortfolio", IDS_BRAVE_WALLET_TOP_NAV_PORTFOLIO},
    {"braveWalletTopTabPrices", IDS_BRAVE_WALLET_TOP_TAB_PRICES},
    {"braveWalletTopTabApps", IDS_BRAVE_WALLET_TOP_TAB_APPS},
    {"braveWalletTopNavNFTS", IDS_BRAVE_WALLET_TOP_NAV_N_F_T_S},
    {"braveWalletTopNavAccounts", IDS_BRAVE_WALLET_TOP_NAV_ACCOUNTS},
    {"braveWalletTopNavMarket", IDS_BRAVE_WALLET_TOP_NAV_MARKET},
    {"braveWalletChartLive", IDS_BRAVE_WALLET_CHART_LIVE},
    {"braveWalletChartOneDay", IDS_BRAVE_WALLET_CHART_ONE_DAY},
    {"braveWalletChartOneWeek", IDS_BRAVE_WALLET_CHART_ONE_WEEK},
    {"braveWalletChartOneMonth", IDS_BRAVE_WALLET_CHART_ONE_MONTH},
    {"braveWalletChartThreeMonths", IDS_BRAVE_WALLET_CHART_THREE_MONTHS},
    {"braveWalletChartOneYear", IDS_BRAVE_WALLET_CHART_ONE_YEAR},
    {"braveWalletChartAllTime", IDS_BRAVE_WALLET_CHART_ALL_TIME},
    {"braveWalletAddCoin", IDS_BRAVE_WALLET_ADD_COIN},
    {"braveWalletBalance", IDS_BRAVE_WALLET_BALANCE},
    {"braveWalletPortfolioAssetNetworkDescription",
     IDS_BRAVE_WALLET_PORTFOLIO_ASSET_NETWORK_DESCRIPTION},
    {"braveWalletAccounts", IDS_BRAVE_WALLET_ACCOUNTS},
    {"braveWalletAccount", IDS_BRAVE_WALLET_ACCOUNT},
    {"braveWalletOwner", IDS_BRAVE_WALLET_OWNER},
    {"braveWalletTransactions", IDS_BRAVE_WALLET_TRANSACTIONS},
    {"braveWalletPrice", IDS_BRAVE_WALLET_PRICE},
    {"braveWalletBack", IDS_BRAVE_WALLET_BACK},
    {"braveWalletAddAccount", IDS_BRAVE_WALLET_ADD_ACCOUNT},
    {"braveWalletPoweredByCoinGecko", IDS_BRAVE_WALLET_POWERED_BY_COIN_GECKO},
    {"braveWalletBuy", IDS_BRAVE_WALLET_BUY},
    {"braveWalletSend", IDS_BRAVE_WALLET_SEND},
    {"braveWalletSwap", IDS_BRAVE_WALLET_SWAP},
    {"braveWalletReset", IDS_BRAVE_WALLET_RESET},
    {"braveWalletBuyNotSupportedTooltip",
     IDS_BRAVE_WALLET_BUY_NOT_SUPPORTED_TOOLTIP},
    {"braveWalletSwapNotSupportedTooltip",
     IDS_BRAVE_WALLET_SWAP_NOT_SUPPORTED_TOOLTIP},
    {"braveWalletSlippageToleranceWarning",
     IDS_BRAVE_WALLET_SLIPPAGE_TOLERANCE_WARNING},
    {"braveWalletSlippageToleranceTitle",
     IDS_BRAVE_WALLET_SLIPPAGE_TOLERANCE_TITLE},
    {"braveWalletExpiresInTitle", IDS_BRAVE_WALLET_EXPIRES_IN_TITLE},
    {"braveWalletSendPlaceholder", IDS_BRAVE_WALLET_SEND_PLACEHOLDER},
    {"braveWalletSendNoURLPlaceholder",
     IDS_BRAVE_WALLET_SEND_NO_URL_PLACEHOLDER},
    {"braveWalletSwapDisclaimer", IDS_BRAVE_WALLET_SWAP_DISCLAIMER},
    {"braveWalletSwapDisclaimerDescription",
     IDS_BRAVE_WALLET_SWAP_DISCLAIMER_DESCRIPTION},
    {"braveWalletJupiterSwapDisclaimerDescription",
     IDS_BRAVE_WALLET_JUPITER_SWAP_DISCLAIMER_DESCRIPTION},
    {"braveWalletSwapFeesNotice", IDS_BRAVE_WALLET_SWAP_FEES_NOTICE},
    {"braveWalletDecimalPlacesError", IDS_BRAVE_WALLET_DECIMAL_PLACES_ERROR},
    {"braveWalletCreateAccountDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_DESCRIPTION},
    {"braveWalletCreateAccountYes", IDS_BRAVE_WALLET_CREATE_ACCOUNT_YES},
    {"braveWalletCreateAccountNo", IDS_BRAVE_WALLET_CREATE_ACCOUNT_NO},
    {"braveWalletButtonContinue", IDS_BRAVE_WALLET_BUTTON_CONTINUE},
    {"braveWalletButtonNext", IDS_BRAVE_WALLET_BUTTON_NEXT},
    {"braveWalletButtonGotIt", IDS_BRAVE_WALLET_BUTTON_GOT_IT},
    {"braveWalletButtonCopy", IDS_BRAVE_WALLET_BUTTON_COPY},
    {"braveWalletButtonCopied", IDS_BRAVE_WALLET_BUTTON_COPIED},
    {"braveWalletButtonVerify", IDS_BRAVE_WALLET_BUTTON_VERIFY},
    {"braveWalletButtonClose", IDS_BRAVE_WALLET_BUTTON_CLOSE},
    {"braveWalletButtonMore", IDS_BRAVE_WALLET_BUTTON_MORE},
    {"braveWalletButtonDone", IDS_BRAVE_WALLET_BUTTON_DONE},
    {"braveWalletWelcomeTitle", IDS_BRAVE_WALLET_WELCOME_TITLE},
    {"braveWalletWelcomeButton", IDS_BRAVE_WALLET_WELCOME_BUTTON},
    {"braveWalletWelcomeRestoreButton",
     IDS_BRAVE_WALLET_WELCOME_RESTORE_BUTTON},
    {"braveWalletImportExistingWallet",
     IDS_BRAVE_WALLET_IMPORT_EXISTING_WALLET},
    {"braveWalletBackupIntroTitle", IDS_BRAVE_WALLET_BACKUP_INTRO_TITLE},
    {"braveWalletBackupIntroDescription",
     IDS_BRAVE_WALLET_BACKUP_INTRO_DESCRIPTION},
    {"braveWalletBackupIntroTerms", IDS_BRAVE_WALLET_BACKUP_INTRO_TERMS},
    {"braveWalletButtonSkip", IDS_BRAVE_WALLET_BUTTON_SKIP},
    {"braveWalletButtonCancel", IDS_BRAVE_WALLET_BUTTON_CANCEL},
    {"braveWalletRecoveryTitle", IDS_BRAVE_WALLET_RECOVERY_TITLE},
    {"braveWalletRecoveryDescription", IDS_BRAVE_WALLET_RECOVERY_DESCRIPTION},
    {"braveWalletRecoveryWarning1", IDS_BRAVE_WALLET_RECOVERY_WARNING1},
    {"braveWalletRecoveryWarning2", IDS_BRAVE_WALLET_RECOVERY_WARNING2},
    {"braveWalletRecoveryWarning3", IDS_BRAVE_WALLET_RECOVERY_WARNING3},
    {"braveWalletRecoveryTerms", IDS_BRAVE_WALLET_RECOVERY_TERMS},
    {"braveWalletVerifyRecoveryTitle", IDS_BRAVE_WALLET_VERIFY_RECOVERY_TITLE},
    {"braveWalletVerifyRecoveryDescription",
     IDS_BRAVE_WALLET_VERIFY_RECOVERY_DESCRIPTION},
    {"braveWalletVerifyError", IDS_BRAVE_WALLET_VERIFY_ERROR},
    {"braveWalletVerifyRecoveryPhraseTitle",
     IDS_BRAVE_WALLET_VERIFY_RECOVERY_PHRASE_TITLE},
    {"braveWalletVerifyRecoveryPhraseInstructions",
     IDS_BRAVE_WALLET_VERIFY_RECOVERY_PHRASE_INSTRUCTIONS},
    {"braveWalletVerifyPhraseError", IDS_BRAVE_WALLET_VERIFY_PHRASE_ERROR},
    {"braveWalletCreatePasswordTitle", IDS_BRAVE_WALLET_CREATE_PASSWORD_TITLE},
    {"braveWalletCreatePasswordDescription",
     IDS_BRAVE_WALLET_CREATE_PASSWORD_DESCRIPTION},
    {"braveWalletCreatePasswordInput", IDS_BRAVE_WALLET_CREATE_PASSWORD_INPUT},
    {"braveWalletConfirmPasswordInput",
     IDS_BRAVE_WALLET_CONFIRM_PASSWORD_INPUT},
    {"braveWalletCreatePasswordError", IDS_BRAVE_WALLET_CREATE_PASSWORD_ERROR},
    {"braveWalletConfirmPasswordError",
     IDS_BRAVE_WALLET_CONFIRM_PASSWORD_ERROR},
    {"braveWalletLockScreenTitle", IDS_BRAVE_WALLET_LOCK_SCREEN_TITLE},
    {"braveWalletLockScreenButton", IDS_BRAVE_WALLET_LOCK_SCREEN_BUTTON},
    {"braveWalletLockScreenError", IDS_BRAVE_WALLET_LOCK_SCREEN_ERROR},
    {"braveWalletWalletPopupSettings", IDS_BRAVE_WALLET_WALLET_POPUP_SETTINGS},
    {"braveWalletWalletPopupLock", IDS_BRAVE_WALLET_WALLET_POPUP_LOCK},
    {"braveWalletWalletPopupBackup", IDS_BRAVE_WALLET_WALLET_POPUP_BACKUP},
    {"braveWalletWalletPopupConnectedSites",
     IDS_BRAVE_WALLET_WALLET_POPUP_CONNECTED_SITES},
    {"braveWalletBackupWarningText", IDS_BRAVE_WALLET_BACKUP_WARNING_TEXT},
    {"braveWalletBackupButton", IDS_BRAVE_WALLET_BACKUP_BUTTON},
    {"braveWalletDismissButton", IDS_BRAVE_WALLET_DISMISS_BUTTON},
    {"braveWalletDefaultWalletBanner", IDS_BRAVE_WALLET_DEFAULT_WALLET_BANNER},
    {"braveWalletRestoreTite", IDS_BRAVE_WALLET_RESTORE_TITE},
    {"braveWalletRestoreDescription", IDS_BRAVE_WALLET_RESTORE_DESCRIPTION},
    {"braveWalletRestoreError", IDS_BRAVE_WALLET_RESTORE_ERROR},
    {"braveWalletRestorePlaceholder", IDS_BRAVE_WALLET_RESTORE_PLACEHOLDER},
    {"braveWalletRestoreShowPhrase", IDS_BRAVE_WALLET_RESTORE_SHOW_PHRASE},
    {"braveWalletRestoreLegacyCheckBox",
     IDS_BRAVE_WALLET_RESTORE_LEGACY_CHECK_BOX},
    {"braveWalletRestoreFormText", IDS_BRAVE_WALLET_RESTORE_FORM_TEXT},
    {"braveWalletToolTipCopyToClipboard",
     IDS_BRAVE_WALLET_TOOL_TIP_COPY_TO_CLIPBOARD},
    {"braveWalletToolTipCopiedToClipboard",
     IDS_BRAVE_WALLET_TOOL_TIP_COPIED_TO_CLIPBOARD},
    {"braveWalletPasteFromClipboard", IDS_BRAVE_WALLET_PASTE_FROM_CLIPBOARD},
    {"braveWalletAccountsPrimary", IDS_BRAVE_WALLET_ACCOUNTS_PRIMARY},
    {"braveWalletAccountsPrimaryDisclaimer",
     IDS_BRAVE_WALLET_ACCOUNTS_PRIMARY_DISCLAIMER},
    {"braveWalletAccountsSecondary", IDS_BRAVE_WALLET_ACCOUNTS_SECONDARY},
    {"braveWalletAccountsSecondaryDisclaimer",
     IDS_BRAVE_WALLET_ACCOUNTS_SECONDARY_DISCLAIMER},
    {"braveWalletAccountsAssets", IDS_BRAVE_WALLET_ACCOUNTS_ASSETS},
    {"braveWalletAccountsEditVisibleAssets",
     IDS_BRAVE_WALLET_ACCOUNTS_EDIT_VISIBLE_ASSETS},
    {"braveWalletAddAccountCreate", IDS_BRAVE_WALLET_ADD_ACCOUNT_CREATE},
    {"braveWalletCreateAccount", IDS_BRAVE_WALLET_CREATE_ACCOUNT},
    {"braveWalletCreateAccountButton", IDS_BRAVE_WALLET_CREATE_ACCOUNT_BUTTON},
    {"braveWalletCreateAccountImportAccount",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_IMPORT_ACCOUNT},
    {"braveWalletCreateAccountTitle", IDS_BRAVE_WALLET_CREATE_ACCOUNT_TITLE},
    {"braveWalletCreateAccountEthereumDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_ETHEREUM_DESCRIPTION},
    {"braveWalletCreateAccountSolanaDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_SOLANA_DESCRIPTION},
    {"braveWalletCreateAccountFilecoinDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_FILECOIN_DESCRIPTION},
    {"braveWalletFilecoinPrivateKeyProtocol",
     IDS_BRAVE_WALLET_FILECOIN_PRIVATE_KEY_PROTOCOL},
    {"braveWalletAddAccountImport", IDS_BRAVE_WALLET_ADD_ACCOUNT_IMPORT},
    {"braveWalletAddAccountImportHardware",
     IDS_BRAVE_WALLET_ADD_ACCOUNT_IMPORT_HARDWARE},
    {"braveWalletAddAccountHardware", IDS_BRAVE_WALLET_ADD_ACCOUNT_HARDWARE},
    {"braveWalletAddAccountConnect", IDS_BRAVE_WALLET_ADD_ACCOUNT_CONNECT},
    {"braveWalletAddAccountPlaceholder",
     IDS_BRAVE_WALLET_ADD_ACCOUNT_PLACEHOLDER},
    {"braveWalletImportAccountDisclaimer",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_DISCLAIMER},
    {"braveWalletImportAccountPlaceholder",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_PLACEHOLDER},
    {"braveWalletImportAccountKey", IDS_BRAVE_WALLET_IMPORT_ACCOUNT_KEY},
    {"braveWalletImportAccountFile", IDS_BRAVE_WALLET_IMPORT_ACCOUNT_FILE},
    {"braveWalletImportAccountUploadButton",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_UPLOAD_BUTTON},
    {"braveWalletImportAccountUploadPlaceholder",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_UPLOAD_PLACEHOLDER},
    {"braveWalletImportAccountError", IDS_BRAVE_WALLET_IMPORT_ACCOUNT_ERROR},
    {"braveWalletConnectHardwareTitle",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_TITLE},
    {"braveWalletConnectHardwareInfo1",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_INFO1},
    {"braveWalletConnectHardwareInfo2",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_INFO2},
    {"braveWalletConnectHardwareWrongApplicationUserHint",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_WRONG_APPLICATION_USER_HINT},
    {"braveWalletConnectHardwareTrezor",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_TREZOR},
    {"braveWalletConnectHardwareLedger",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_LEDGER},
    {"braveWalletConnectHardwareAuthorizationNeeded",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_AUTHORIZATION_NEEDED},
    {"braveWalletConnectingHardwareWallet",
     IDS_BRAVE_WALLET_CONNECTING_HARDWARE_WALLET},
    {"braveWalletAddCheckedAccountsHardwareWallet",
     IDS_BRAVE_WALLET_ADD_CHECKED_ACCOUNTS_HARDWARE_WALLET},
    {"braveWalletLoadMoreAccountsHardwareWallet",
     IDS_BRAVE_WALLET_LOAD_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"braveWalletLoadingMoreAccountsHardwareWallet",
     IDS_BRAVE_WALLET_LOADING_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"braveWalletSearchScannedAccounts",
     IDS_BRAVE_WALLET_SEARCH_SCANNED_ACCOUNTS},
    {"braveWalletSwitchHDPathTextHardwareWallet",
     IDS_BRAVE_WALLET_SWITCH_H_D_PATH_TEXT_HARDWARE_WALLET},
    {"braveWalletLedgerLiveDerivationPath",
     IDS_BRAVE_WALLET_LEDGER_LIVE_DERIVATION_PATH},
    {"braveWalletLedgerLegacyDerivationPath",
     IDS_BRAVE_WALLET_LEDGER_LEGACY_DERIVATION_PATH},
    {"braveWalletConnectHardwareSearchNothingFound",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_SEARCH_NOTHING_FOUND},
    {"braveWalletUnknownInternalError",
     IDS_BRAVE_WALLET_UNKNOWN_INTERNAL_ERROR},
    {"braveWalletAccountSettingsDetails",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_DETAILS},
    {"braveWalletAccountSettingsWatchlist",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_WATCHLIST},
    {"braveWalletAccountSettingsPrivateKey",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_PRIVATE_KEY},
    {"braveWalletAccountSettingsSave", IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_SAVE},
    {"braveWalletAccountSettingsRemove",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_REMOVE},
    {"braveWalletWatchlistAddCustomAsset",
     IDS_BRAVE_WALLET_WATCHLIST_ADD_CUSTOM_ASSET},
    {"braveWalletWatchListTokenName", IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_NAME},
    {"braveWalletWatchListTokenAddress",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_ADDRESS},
    {"braveWalletWatchListTokenSymbol",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_SYMBOL},
    {"braveWalletWatchListTokenDecimals",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_DECIMALS},
    {"braveWalletWatchListAdd", IDS_BRAVE_WALLET_WATCH_LIST_ADD},
    {"braveWalletWatchListDoneButton", IDS_BRAVE_WALLET_WATCH_LIST_DONE_BUTTON},
    {"braveWalletWatchListSuggestion", IDS_BRAVE_WALLET_WATCH_LIST_SUGGESTION},
    {"braveWalletWatchListNoAsset", IDS_BRAVE_WALLET_WATCH_LIST_NO_ASSET},
    {"braveWalletWatchListSearchPlaceholder",
     IDS_BRAVE_WALLET_WATCH_LIST_SEARCH_PLACEHOLDER},
    {"braveWalletWatchListError", IDS_BRAVE_WALLET_WATCH_LIST_ERROR},
    {"braveWalletWatchListTokenId", IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_ID},
    {"braveWalletWatchListTokenIdError",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_ID_ERROR},
    {"braveWalletWatchListAdvanced", IDS_BRAVE_WALLET_WATCH_LIST_ADVANCED},
    {"braveWalletWatchListCoingeckoId",
     IDS_BRAVE_WALLET_WATCH_LIST_COINGECKO_ID},
    {"braveWalletIconURL", IDS_BRAVE_WALLET_ICON_URL},
    {"braveWalletAddAsset", IDS_BRAVE_WALLET_ADD_ASSET},
    {"braveWalletAccountSettingsDisclaimer",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_DISCLAIMER},
    {"braveWalletFilExportPrivateKeyFormatDescription",
     IDS_BRAVE_WALLET_FIL_EXPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"braveWalletFilImportPrivateKeyFormatDescription",
     IDS_BRAVE_WALLET_FIL_IMPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"braveWalletAccountSettingsShowKey",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_SHOW_KEY},
    {"braveWalletAccountSettingsHideKey",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_HIDE_KEY},
    {"braveWalletAccountSettingsUpdateError",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_UPDATE_ERROR},
    {"braveWalletPreset25", IDS_BRAVE_WALLET_PRESET25},
    {"braveWalletPreset50", IDS_BRAVE_WALLET_PRESET50},
    {"braveWalletPreset75", IDS_BRAVE_WALLET_PRESET75},
    {"braveWalletPreset100", IDS_BRAVE_WALLET_PRESET100},
    {"braveWalletUnsupportedNetwork", IDS_BRAVE_WALLET_UNSUPPORTED_NETWORK},
    {"braveWalletNetworkETH", IDS_BRAVE_WALLET_NETWORK_E_T_H},
    {"braveWalletNetworkMain", IDS_BRAVE_WALLET_NETWORK_MAIN},
    {"braveWalletNetworkTest", IDS_BRAVE_WALLET_NETWORK_TEST},
    {"braveWalletNetworkRopsten", IDS_BRAVE_WALLET_NETWORK_ROPSTEN},
    {"braveWalletNetworkKovan", IDS_BRAVE_WALLET_NETWORK_KOVAN},
    {"braveWalletNetworkRinkeby", IDS_BRAVE_WALLET_NETWORK_RINKEBY},
    {"braveWalletNetworkGoerli", IDS_BRAVE_WALLET_NETWORK_GOERLI},
    {"braveWalletNetworkBinance", IDS_BRAVE_WALLET_NETWORK_BINANCE},
    {"braveWalletNetworkBinanceAbbr", IDS_BRAVE_WALLET_NETWORK_BINANCE_ABBR},
    {"braveWalletNetworkLocalhost", IDS_BRAVE_WALLET_NETWORK_LOCALHOST},
    {"braveWalletSelectAccount", IDS_BRAVE_WALLET_SELECT_ACCOUNT},
    {"braveWalletSearchAccount", IDS_BRAVE_WALLET_SEARCH_ACCOUNT},
    {"braveWalletSelectNetwork", IDS_BRAVE_WALLET_SELECT_NETWORK},
    {"braveWalletSelectAsset", IDS_BRAVE_WALLET_SELECT_ASSET},
    {"braveWalletSearchAsset", IDS_BRAVE_WALLET_SEARCH_ASSET},
    {"braveWalletSwapFrom", IDS_BRAVE_WALLET_SWAP_FROM},
    {"braveWalletSwapTo", IDS_BRAVE_WALLET_SWAP_TO},
    {"braveWalletSwapEstimate", IDS_BRAVE_WALLET_SWAP_ESTIMATE},
    {"braveWalletSwapMarket", IDS_BRAVE_WALLET_SWAP_MARKET},
    {"braveWalletSwapLimit", IDS_BRAVE_WALLET_SWAP_LIMIT},
    {"braveWalletSwapPriceIn", IDS_BRAVE_WALLET_SWAP_PRICE_IN},
    {"braveWalletBuyTitle", IDS_BRAVE_WALLET_BUY_TITLE},
    {"braveWalletBuyDescription", IDS_BRAVE_WALLET_BUY_DESCRIPTION},
    {"braveWalletBuyContinueButton", IDS_BRAVE_WALLET_BUY_CONTINUE_BUTTON},
    {"braveWalletSignTransactionTitle",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_TITLE},
    {"braveWalletSignWarning", IDS_BRAVE_WALLET_SIGN_WARNING},
    {"braveWalletSignWarningTitle", IDS_BRAVE_WALLET_SIGN_WARNING_TITLE},
    {"braveWalletSignTransactionMessageTitle",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_MESSAGE_TITLE},
    {"braveWalletSignTransactionButton",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_BUTTON},
    {"braveWalletProvideEncryptionKeyTitle",
     IDS_BRAVE_WALLET_PROVIDE_ENCRYPTION_KEY_TITLE},
    {"braveWalletProvideEncryptionKeyDescription",
     IDS_BRAVE_WALLET_PROVIDE_ENCRYPTION_KEY_DESCRIPTION},
    {"braveWalletProvideEncryptionKeyButton",
     IDS_BRAVE_WALLET_PROVIDE_ENCRYPTION_KEY_BUTTON},
    {"braveWalletReadEncryptedMessageTitle",
     IDS_BRAVE_WALLET_READ_ENCRYPTED_MESSAGE_TITLE},
    {"braveWalletReadEncryptedMessageDecryptButton",
     IDS_BRAVE_WALLET_READ_ENCRYPTED_MESSAGE_DECRYPT_BUTTON},
    {"braveWalletReadEncryptedMessageButton",
     IDS_BRAVE_WALLET_READ_ENCRYPTED_MESSAGE_BUTTON},
    {"braveWalletAllowSpendTitle", IDS_BRAVE_WALLET_ALLOW_SPEND_TITLE},
    {"braveWalletAllowSpendDescription",
     IDS_BRAVE_WALLET_ALLOW_SPEND_DESCRIPTION},
    {"braveWalletAllowSpendBoxTitle", IDS_BRAVE_WALLET_ALLOW_SPEND_BOX_TITLE},
    {"braveWalletAllowSpendTransactionFee",
     IDS_BRAVE_WALLET_ALLOW_SPEND_TRANSACTION_FEE},
    {"braveWalletAllowSpendEditButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_EDIT_BUTTON},
    {"braveWalletAllowSpendDetailsButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_DETAILS_BUTTON},
    {"braveWalletAllowSpendRejectButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_REJECT_BUTTON},
    {"braveWalletAllowSpendConfirmButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_CONFIRM_BUTTON},
    {"braveWalletAllowSpendCurrentAllowance",
     IDS_BRAVE_WALLET_ALLOW_SPEND_CURRENT_ALLOWANCE},
    {"braveWalletAllowSpendProposedAllowance",
     IDS_BRAVE_WALLET_ALLOW_SPEND_PROPOSED_ALLOWANCE},
    {"braveWalletAllowSpendUnlimitedWarningTitle",
     IDS_BRAVE_WALLET_ALLOW_SPEND_UNLIMITED_WARNING_TITLE},
    {"braveWalletAllowAddNetworkTitle",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_TITLE},
    {"braveWalletAllowChangeNetworkTitle",
     IDS_BRAVE_WALLET_ALLOW_CHANGE_NETWORK_TITLE},
    {"braveWalletAllowChangeNetworkDescription",
     IDS_BRAVE_WALLET_ALLOW_CHANGE_NETWORK_DESCRIPTION},
    {"braveWalletAllowChangeNetworkButton",
     IDS_BRAVE_WALLET_ALLOW_CHANGE_NETWORK_BUTTON},
    {"braveWalletAllowAddNetworkDescription",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_DESCRIPTION},
    {"braveWalletAllowAddNetworkLearnMoreButton",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_LEARN_MORE_BUTTON},
    {"braveWalletAllowAddNetworkName", IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_NAME},
    {"braveWalletAllowAddNetworkUrl", IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_URL},
    {"braveWalletAllowAddNetworkDetailsButton",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_DETAILS_BUTTON},
    {"braveWalletAllowAddNetworkButton",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_BUTTON},
    {"braveWalletAllowAddNetworkChainID",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_CHAIN_I_D},
    {"braveWalletAllowAddNetworkCurrencySymbol",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_CURRENCY_SYMBOL},
    {"braveWalletAllowAddNetworkExplorer",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_EXPLORER},
    {"braveWalletAllowAddNetworkNetworkPanelTitle",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_PANEL_TITLE},
    {"braveWalletAllowAddNetworkDetailsPanelTitle",
     IDS_BRAVE_WALLET_ALLOW_ADD_DETAILS_PANEL_TITLE},
    {"braveWalletConfirmTransactionTotal",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_TOTAL},
    {"braveWalletConfirmTransactionGasFee",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_GAS_FEE},
    {"braveWalletConfirmTransactionTransactionFee",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_TRANSACTION_FEE},
    {"braveWalletConfirmTransactionBid",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_BID},
    {"braveWalletConfirmTransactionAmountGas",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_AMOUNT_GAS},
    {"braveWalletConfirmTransactionAmountFee",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_AMOUNT_FEE},
    {"braveWalletConfirmTransactionNoData",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_NO_DATA},
    {"braveWalletConfirmTransactionNext",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_NEXT},
    {"braveWalletConfirmTransactionFrist",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_FRIST},
    {"braveWalletConfirmTransactions", IDS_BRAVE_WALLET_CONFIRM_TRANSACTIONS},
    {"braveWalletConfirmTransactionAccountCreationFee",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_ACCOUNT_CREATION_FEE},
    {"braveWalletPanelTitle", IDS_BRAVE_WALLET_PANEL_TITLE},
    {"braveWalletPanelConnected", IDS_BRAVE_WALLET_PANEL_CONNECTED},
    {"braveWalletSitePermissionsAccounts",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_ACCOUNTS},
    {"braveWalletSitePermissionsTitle",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_TITLE},
    {"braveWalletSitePermissionsDisconnect",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_DISCONNECT},
    {"braveWalletSitePermissionsSwitch",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_SWITCH},
    {"braveWalletSitePermissionsTrust",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_TRUST},
    {"braveWalletSitePermissionsRevoke",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_REVOKE},
    {"braveWalletSitePermissionsNewAccount",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_NEW_ACCOUNT},
    {"braveWalletPanelNotConnected", IDS_BRAVE_WALLET_PANEL_NOT_CONNECTED},
    {"braveWalletPanelViewAccountAssets",
     IDS_BRAVE_WALLET_PANEL_VIEW_ACCOUNT_ASSETS},
    {"braveWalletAssetsPanelTitle", IDS_BRAVE_WALLET_ASSETS_PANEL_TITLE},
    {"braveWalletPanelDisconnected", IDS_BRAVE_WALLET_PANEL_DISCONNECTED},
    {"braveWalletPanelBlocked", IDS_BRAVE_WALLET_PANEL_BLOCKED},
    {"braveWalletWelcomePanelDescription",
     IDS_BRAVE_WALLET_WELCOME_PANEL_DESCRIPTION},
    {"braveWalletLearnMore", IDS_BRAVE_WALLET_LEARN_MORE},
    {"braveWalletTransactionDetailBoxFunction",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_BOX_FUNCTION},
    {"braveWalletTransactionDetailBoxHex",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_BOX_HEX},
    {"braveWalletTransactionDetailBoxBytes",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_BOX_BYTES},
    {"braveWalletConnectWithSiteTitle",
     IDS_BRAVE_WALLET_CONNECT_WITH_SITE_TITLE},
    {"braveWalletConnectWithSiteDescription",
     IDS_BRAVE_WALLET_CONNECT_WITH_SITE_DESCRIPTION},
    {"braveWalletConnectWithSiteNext", IDS_BRAVE_WALLET_CONNECT_WITH_SITE_NEXT},
    {"braveWalletConnectWithSiteHeaderTitle",
     IDS_BRAVE_WALLET_CONNECT_WITH_SITE_HEADER_TITLE},
    {"braveWalletCryptoWalletsDetected",
     IDS_BRAVE_WALLET_CRYPTO_WALLETS_DETECTED},
    {"braveWalletCryptoWalletsDescriptionTwo",
     IDS_BRAVE_WALLET_CRYPTO_WALLETS_DESCRIPTION_TWO},
    {"braveWalletImportBraveLegacyDescription",
     IDS_BRAVE_WALLET_IMPORT_BRAVE_LEGACY_DESCRIPTION},
    {"braveWalletImportBraveLegacyInput",
     IDS_BRAVE_WALLET_IMPORT_BRAVE_LEGACY_INPUT},
    {"braveWalletConnectHardwarePanelConnected",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_CONNECTED},
    {"braveWalletConnectHardwarePanelDisconnected",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_DISCONNECTED},
    {"braveWalletConnectHardwarePanelInstructions",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_INSTRUCTIONS},
    {"braveWalletConnectHardwarePanelConnect",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_CONNECT},
    {"braveWalletConnectHardwarePanelConfirmation",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_CONFIRMATION},
    {"braveWalletConnectHardwarePanelOpenApp",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_OPEN_APP},
    {"braveWalletTransactionSent", IDS_BRAVE_WALLET_TRANSACTION_SENT},
    {"braveWalletTransactionReceived", IDS_BRAVE_WALLET_TRANSACTION_RECEIVED},
    {"braveWalletTransactionExplorerMissing",
     IDS_BRAVE_WALLET_TRANSACTION_EXPLORER_MISSING},
    {"braveWalletTransactionExplorer", IDS_BRAVE_WALLET_TRANSACTION_EXPLORER},
    {"braveWalletTransactionCopyHash", IDS_BRAVE_WALLET_TRANSACTION_COPY_HASH},
    {"braveWalletTransactionSpeedup", IDS_BRAVE_WALLET_TRANSACTION_SPEEDUP},
    {"braveWalletTransactionCancel", IDS_BRAVE_WALLET_TRANSACTION_CANCEL},
    {"braveWalletTransactionRetry", IDS_BRAVE_WALLET_TRANSACTION_RETRY},
    {"braveWalletTransactionStatusUnapproved",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_UNAPPROVED},
    {"braveWalletTransactionStatusApproved",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_APPROVED},
    {"braveWalletTransactionStatusRejected",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_REJECTED},
    {"braveWalletTransactionStatusSubmitted",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_SUBMITTED},
    {"braveWalletTransactionStatusConfirmed",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_CONFIRMED},
    {"braveWalletTransactionStatusError",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_ERROR},
    {"braveWalletTransactionStatusDropped",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_DROPPED},
    {"braveWalletRecentTransactions", IDS_BRAVE_WALLET_RECENT_TRANSACTIONS},
    {"braveWalletTransactionDetails", IDS_BRAVE_WALLET_TRANSACTION_DETAILS},
    {"braveWalletTransactionDetailDate",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_DATE},
    {"braveWalletTransactionDetailSpeedUp",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_SPEEDUP},
    {"braveWalletTransactionDetailHash",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_HASH},
    {"braveWalletTransactionDetailNetwork",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_NETWORK},
    {"braveWalletTransactionDetailStatus",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_STATUS},
    {"braveWalletTransactionPlaceholder",
     IDS_BRAVE_WALLET_TRANSACTION_PLACEHOLDER},
    {"braveWalletTransactionApproveUnlimited",
     IDS_BRAVE_WALLET_TRANSACTION_APPROVE_UNLIMITED},
    {"braveWalletEditGasTitle1", IDS_BRAVE_WALLET_EDIT_GAS_TITLE1},
    {"braveWalletEditGasTitle2", IDS_BRAVE_WALLET_EDIT_GAS_TITLE2},
    {"braveWalletEditGasDescription", IDS_BRAVE_WALLET_EDIT_GAS_DESCRIPTION},
    {"braveWalletEditGasLow", IDS_BRAVE_WALLET_EDIT_GAS_LOW},
    {"braveWalletEditGasOptimal", IDS_BRAVE_WALLET_EDIT_GAS_OPTIMAL},
    {"braveWalletEditGasHigh", IDS_BRAVE_WALLET_EDIT_GAS_HIGH},
    {"braveWalletEditGasLimit", IDS_BRAVE_WALLET_EDIT_GAS_LIMIT},
    {"braveWalletEditGasPerGasPrice", IDS_BRAVE_WALLET_EDIT_GAS_PER_GAS_PRICE},
    {"braveWalletEditGasPerTipLimit", IDS_BRAVE_WALLET_EDIT_GAS_PER_TIP_LIMIT},
    {"braveWalletEditGasPerPriceLimit",
     IDS_BRAVE_WALLET_EDIT_GAS_PER_PRICE_LIMIT},
    {"braveWalletEditGasMaxFee", IDS_BRAVE_WALLET_EDIT_GAS_MAX_FEE},
    {"braveWalletEditGasMaximumFee", IDS_BRAVE_WALLET_EDIT_GAS_MAXIMUM_FEE},
    {"braveWalletEditGasBaseFee", IDS_BRAVE_WALLET_EDIT_GAS_BASE_FEE},
    {"braveWalletEditGasGwei", IDS_BRAVE_WALLET_EDIT_GAS_GWEI},
    {"braveWalletEditGasSetCustom", IDS_BRAVE_WALLET_EDIT_GAS_SET_CUSTOM},
    {"braveWalletEditGasSetSuggested", IDS_BRAVE_WALLET_EDIT_GAS_SET_SUGGESTED},
    {"braveWalletEditGasZeroGasPriceWarning",
     IDS_BRAVE_WALLET_EDIT_GAS_ZERO_GAS_PRICE_WARNING},
    {"braveWalletAdvancedTransactionSettings",
     IDS_BRAVE_WALLET_ADVANCED_TRANSACTION_SETTINGS},
    {"braveWalletAdvancedTransactionSettingsPlaceholder",
     IDS_BRAVE_WALLET_ADVANCED_TRANSACTION_SETTINGS_PLACEHOLDER},
    {"braveWalletEditNonce", IDS_BRAVE_WALLET_EDIT_NONCE},
    {"braveWalletEditNonceInfo", IDS_BRAVE_WALLET_EDIT_NONCE_INFO},
    {"braveWalletEditPermissionsTitle",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_TITLE},
    {"braveWalletEditPermissionsDescription",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_DESCRIPTION},
    {"braveWalletEditPermissionsButton",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_BUTTON},
    {"braveWalletEditPermissionsProposedAllowance",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_PROPOSED_ALLOWANCE},
    {"braveWalletEditPermissionsCustomAllowance",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_CUSTOM_ALLOWANCE},
    {"braveWalletNotValidEthAddress", IDS_BRAVE_WALLET_NOT_VALID_ETH_ADDRESS},
    {"braveWalletNotValidSolAddress", IDS_BRAVE_WALLET_NOT_VALID_SOL_ADDRESS},
    {"braveWalletNotValidAddress", IDS_BRAVE_WALLET_NOT_VALID_ADDRESS},
    {"braveWalletNotDomain", IDS_BRAVE_WALLET_NOT_DOMAIN},
    {"braveWalletSameAddressError", IDS_BRAVE_WALLET_SAME_ADDRESS_ERROR},
    {"braveWalletContractAddressError",
     IDS_BRAVE_WALLET_CONTRACT_ADDRESS_ERROR},
    {"braveWalletAddressMissingChecksumInfoWarning",
     IDS_BRAVE_WALLET_ADDRESS_MISSING_CHECKSUM_INFO_WARNING},
    {"braveWalletNotValidChecksumAddressError",
     IDS_BRAVE_WALLET_NOT_VALID_CHECKSUM_ADDRESS_ERROR},
    {"braveWalletMissingGasLimitError",
     IDS_BRAVE_WALLET_MISSING_GAS_LIMIT_ERROR},
    {"braveWalletZeroBalanceError", IDS_BRAVE_WALLET_ZERO_BALANCE_ERROR},
    {"braveWalletAddressRequiredError",
     IDS_BRAVE_WALLET_ADDRESS_REQUIRED_ERROR},
    {"braveWalletQueueOf", IDS_BRAVE_WALLET_QUEUE_OF},
    {"braveWalletQueueNext", IDS_BRAVE_WALLET_QUEUE_NEXT},
    {"braveWalletQueueFirst", IDS_BRAVE_WALLET_QUEUE_FIRST},
    {"braveWalletQueueRejectAll", IDS_BRAVE_WALLET_QUEUE_REJECT_ALL},
    {"braveWalletSwapInsufficientBalance",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_BALANCE},
    {"braveWalletSwapInsufficientFundsForGas",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_FUNDS_FOR_GAS},
    {"braveWalletSwapInsufficientLiquidity",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_LIQUIDITY},
    {"braveWalletSwapInsufficientAllowance",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_ALLOWANCE},
    {"braveWalletSwapUnknownError", IDS_BRAVE_WALLET_SWAP_UNKNOWN_ERROR},
    {"braveWalletUnlockError", IDS_BRAVE_WALLET_UNLOCK_ERROR},
    {"braveWalletDeviceUnknownScheme", IDS_BRAVE_WALLET_UNKNOWN_SCHEME_ERROR},
    {"braveWalletApprovalTransactionIntent",
     IDS_BRAVE_WALLET_APPROVAL_TRANSACTION_INTENT},
    {"braveWalletLedgerFilecoinUnlockError",
     IDS_BRAVE_WALLET_LEDGER_FILECOIN_UNLOCK_ERROR},
    {"braveWalletLedgerValidationError",
     IDS_BRAVE_WALLET_LEDGER_VALIDATION_ERROR},
    {"braveWalletHardwareAccountNotFound",
     IDS_BRAVE_WALLET_HARDWARE_ACCOUNT_NOT_FOUND_ERROR},
    {"braveWalletCreateBridgeError",
     IDS_BRAVE_WALLET_HARDWARE_CREATE_BRIDGE_ERROR},
    {"braveWalletProcessTransactionError",
     IDS_BRAVE_WALLET_HARDWARE_PROCESS_TRANSACTION_ERROR},
    {"braveWalletApproveTransactionError",
     IDS_BRAVE_WALLET_HARDWARE_APPROVE_TRANSACTION_ERROR},
    {"braveWalletTransactionNotFoundSignError",
     IDS_BRAVE_WALLET_HARDWARE_TRANSACTION_NOT_FOUND_ERROR},
    {"braveWalletSignOnDeviceError",
     IDS_BRAVE_WALLET_HARDWARE_TRANSACTION_DEVICE_ERROR},
    {"braveWalletNoMessageToSignError",
     IDS_BRAVE_WALLET_HARDWARE_TRANSACTION_NO_MESSAGE_TO_SIGN_ERROR},
    {"braveWalletProcessMessageError",
     IDS_BRAVE_WALLET_HARDWARE_SIGN_MESSAGE_ERROR},
    {"braveWalletHardwareOperationUnsupportedError",
     IDS_BRAVE_WALLET_HARDWARE_OPERATION_UNSUPPORTED_ERROR},
    {"braveWalletUnknownKeyringError",
     IDS_BRAVE_WALLET_HARDWARE_UNKNOWN_KEYRING_ERROR},
    {"braveWalletBridgeCommandInProgress",
     IDS_BRAVE_WALLET_HARDWARE_COMMAND_IN_PROGRESS_ERROR},
    {"braveWalletBridgeNotReady",
     IDS_BRAVE_WALLET_HARDWARE_BRIDGE_NOT_READY_ERROR},
    {"braveWalletAddSuggestedTokenTitle",
     IDS_BRAVE_WALLET_ADD_SUGGESTED_TOKEN_TITLE},
    {"braveWalletAddSuggestedTokenDescription",
     IDS_BRAVE_WALLET_ADD_SUGGESTED_TOKEN_DESCRIPTION},
    {"braveWalletNFTDetailBlockchain", IDS_BRAVE_WALLET_NFT_DETAIL_BLOCKCHAIN},
    {"braveWalletNFTDetailTokenStandard",
     IDS_BRAVE_WALLET_NFT_DETAIL_TOKEN_STANDARD},
    {"braveWalletNFTDetailTokenID", IDS_BRAVE_WALLET_NFT_DETAIL_TOKEN_ID},
    {"braveWalletTrezorSignTypedDataError",
     IDS_BRAVE_WALLET_TREZOR_SIGN_TYPED_DATA_ERROR},
    {"braveWalletSweepstakesTitle", IDS_BRAVE_WALLET_SWEEPSTAKES_TITLE},
    {"braveWalletSweepstakesDescription",
     IDS_BRAVE_WALLET_SWEEPSTAKES_DESCRIPTION},
    {"braveWalletSweepstakesCallToAction",
     IDS_BRAVE_WALLET_SWEEPSTAKES_CALL_TO_ACTION},
    {"braveWalletNotValidFilAddress", IDS_BRAVE_WALLET_NOT_VALID_FIL_ADDRESS},
    {"braveWalletBuyWithWyre", IDS_BRAVE_WALLET_BUY_WITH_WYRE},
    {"braveWalletBuyWithRamp", IDS_BRAVE_WALLET_BUY_WITH_RAMP},
    {"braveWalletBuyWithSardine", IDS_BRAVE_WALLET_BUY_WITH_SARDINE},
    {"braveWalletBuyRampNetworkName", IDS_BRAVE_WALLET_BUY_RAMP_NETWORK_NAME},
    {"braveWalletBuyWyreName", IDS_BRAVE_WALLET_BUY_WYRE_NAME},
    {"braveWalletBuySardineName", IDS_BRAVE_WALLET_BUY_SARDINE_NAME},
    {"braveWalletBuyRampDescription", IDS_BRAVE_WALLET_BUY_RAMP_DESCRIPTION},
    {"braveWalletBuyWyreDescription", IDS_BRAVE_WALLET_BUY_WYRE_DESCRIPTION},
    {"braveWalletBuySardineDescription",
     IDS_BRAVE_WALLET_BUY_SARDINE_DESCRIPTION},
    {"braveWalletNetworkFilterAll", IDS_BRAVE_WALLET_NETWORK_FILTER_ALL},
    {"braveWalletAssetFilterAllAssets",
     IDS_BRAVE_WALLET_ASSET_FILTER_ALL_ASSETS},
    {"braveWalletAssetFilterNFTs", IDS_BRAVE_WALLET_ASSET_FILTER_NFTS},
    {"braveWalletAssetFilterLowToHigh",
     IDS_BRAVE_WALLET_ASSET_FILTER_LOW_TO_HIGH},
    {"braveWalletAssetFilterHighToLow",
     IDS_BRAVE_WALLET_ASSET_FILTER_HIGHT_TO_LOW},
    {"braveWalletEditGasLimitError", IDS_BRAVE_WALLET_EDIT_GAS_LIMIT_ERROR},
    {"braveWalletApproveTransaction", IDS_BRAVE_WALLET_APPROVE_TRANSACTION},
    {"braveWalletSolanaSystemProgram", IDS_BRAVE_WALLET_SOLANA_SYSTEM_PROGRAM},
    {"braveWalletSolanaConfigProgram", IDS_BRAVE_WALLET_SOLANA_CONFIG_PROGRAM},
    {"braveWalletSolanaStakeProgram", IDS_BRAVE_WALLET_SOLANA_STAKE_PROGRAM},
    {"braveWalletSolanaVoteProgram", IDS_BRAVE_WALLET_SOLANA_VOTE_PROGRAM},
    {"braveWalletSolanaBPFLoader", IDS_BRAVE_WALLET_SOLANA_BP_FLOADER},
    {"braveWalletSolanaParamKeyFromPubkey",
     IDS_BRAVE_WALLET_SOLANA_PARAM_KEY_FROMPUBKEY},
    {"braveWalletSolanaParamKeyToPubkey",
     IDS_BRAVE_WALLET_SOLANA_PARAM_KEY_TOPUBKEY},
    {"braveWalletSolanaParamKeyLamports",
     IDS_BRAVE_WALLET_SOLANA_PARAM_KEY_LAMPORTS},
    {"braveWalletSolanaParamKeyNewAccountPubkey",
     IDS_BRAVE_WALLET_SOLANA_PARAM_KEY_NEWACCOUNTPUBKEY},
    {"braveWalletSolanaAccounts", IDS_BRAVE_WALLET_SOLANA_ACCOUNTS},
    {"braveWalletSolanaData", IDS_BRAVE_WALLET_SOLANA_DATA},
    {"braveWalletSolanaProgramID", IDS_BRAVE_WALLET_SOLANA_PROGRAM_ID},
    {"braveWalletSolanaMaxRetries", IDS_BRAVE_WALLET_SOLANA_MAX_RETRIES},
    {"braveWalletSolanaPreflightCommitment",
     IDS_BRAVE_WALLET_SOLANA_PREFLIGHT_COMMITMENT},
    {"braveWalletSolanaSkipPreflight", IDS_BRAVE_WALLET_SOLANA_SKIP_PREFLIGHT},
    {"braveWalletSolanaEd25519Program",
     IDS_BRAVE_WALLET_SOLANA_ED25519_PROGRAM},
    {"braveWalletSolanaSecp256k1Program",
     IDS_BRAVE_WALLET_SOLANA_SECP256K1_PROGRAM},
    {"braveWalletNetworkFilterSecondary",
     IDS_BRAVE_WALLET_NETWORK_FILTER_SECONDARY},
    {"braveWalletSelectCurrency", IDS_BRAVE_WALLET_SELECT_CURRENCY},
    {"braveWalletSearchCurrency", IDS_BRAVE_WALLET_SEARCH_CURRENCY},
    {"braveWalletHelpCenter", IDS_BRAVE_WALLET_HELP_CENTER},
    {"braveWalletHelpCenterText", IDS_BRAVE_WALLET_HELP_CENTER_TEXT},
    {"braveWalletBuyTapBuyNotSupportedMessage",
     IDS_BRAVE_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"braveWalletAuroraModalTitle", IDS_BRAVE_WALLET_AURORA_MODAL_TITLE},
    {"braveWalletAuroraModalDescription",
     IDS_BRAVE_WALLET_AURORA_MODAL_DESCRIPTION},
    {"braveWalletAuroraModalLearnMore",
     IDS_BRAVE_WALLET_AURORA_MODAL_LEARN_MORE},
    {"braveWalletAuroraModalLearnMoreAboutRisk",
     IDS_BRAVE_WALLET_AURORA_MODAL_LEARN_MORE_ABOUT_RISK},
    {"braveWalletAuroraModalDontShowAgain",
     IDS_BRAVE_WALLET_AURORA_MODAL_DONT_SHOW_AGAIN},
    {"braveWalletAuroraModalOPenButtonText",
     IDS_BRAVE_WALLET_AURORA_MODAL_OPEN_BUTTON_TEXT},
    {"braveWalletPasswordStrengthTooltipHeading",
     IDS_BRAVE_WALLET_PASSWORD_STRENGTH_TOOLTIP_HEADING},
    {"braveWalletPasswordStrengthTooltipIsLongEnough",
     IDS_BRAVE_WALLET_PASSWORD_STRENGTH_TOOLTIP_IS_LONG_ENOUGH},
    {"braveWalletPasswordMatch", IDS_BRAVE_WALLET_PASSWORD_MATCH},
    {"braveWalletPasswordIsStrong", IDS_BRAVE_WALLET_PASSWORD_IS_STRONG},
    {"braveWalletPasswordIsMediumStrength",
     IDS_BRAVE_WALLET_PASSWORD_IS_MEDIUM_STRENGTH},
    {"braveWalletPasswordIsWeak", IDS_BRAVE_WALLET_PASSWORD_IS_WEAK},
    {"braveWalletOnboardingRecoveryPhraseBackupIntroTitle",
     IDS_BRAVE_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_TITLE},
    {"braveWalletOnboardingRecoveryPhraseBackupIntroDescription",
     IDS_BRAVE_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_DESCRIPTION},
    {"braveWalletRecoveryPhraseBackupWarning",
     IDS_BRAVE_WALLET_RECOVERY_PHRASE_BACKUP_WARNING},
    {"braveWalletRecoveryPhraseBackupWarningImportant",
     IDS_BRAVE_WALLET_RECOVERY_PHRASE_BACKUP_WARNING_IMPORTANT},
    {"braveWalletRecoveryPhraseBackupTitle",
     IDS_BRAVE_WALLET_RECOVERY_PHRASE_BACKUP_TITLE},
    {"braveWalletCopiedToClipboard", IDS_BRAVE_WALLET_COPIED_TO_CLIPBOARD},
    {"braveWalletClickToSeeRecoveryPhrase",
     IDS_BRAVE_WALLET_CLICK_TO_SEE_RECOVERY_PHRASE},
    {"braveWalletOrdinalFirst", IDS_BRAVE_WALLET_ORDINAL_FIRST},
    {"braveWalletOrdinalThird", IDS_BRAVE_WALLET_ORDINAL_THIRD},
    {"braveWalletOnboardingSuccessTitle",
     IDS_BRAVE_WALLET_ONBOARDING_SUCCESS_TITLE},
    {"braveWalletOnboardingSuccessDescription",
     IDS_BRAVE_WALLET_ONBOARDING_SUCCESS_DESCRIPTION},
    {"braveWalletArticleLinkWhatsARecoveryPhrase",
     IDS_BRAVE_WALLET_ARTICLE_LINK_WHATS_A_RECOVERY_PHRASE},
    {"braveWalletImportOrRestoreWalletTitle",
     IDS_BRAVE_WALLET_IMPORT_OR_RESTORE_WALLET_TITLE},
    {"braveWalletImportOrRestoreDescription",
     IDS_BRAVE_WALLET_IMPORT_OR_RESTORE_DESCRIPTION},
    {"braveWalletRestoreMyBraveWallet",
     IDS_BRAVE_WALLET_RESTORE_MY_BRAVE_WALLET},
    {"braveWalletRestoreMyBraveWalletInstructions",
     IDS_BRAVE_WALLET_RESTORE_MY_BRAVE_WALLET_INSTRUCTIONS},
    {"braveWalletRestoreMyBraveWalletDescription",
     IDS_BRAVE_WALLET_RESTORE_MY_BRAVE_WALLET_DESCRIPTION},
    {"braveWalletImportFromMetaMask", IDS_BRAVE_WALLET_IMPORT_FROM_META_MASK},
    {"braveWalletImportFromMetaMaskDescription",
     IDS_BRAVE_WALLET_IMPORT_FROM_META_MASK_DESCRIPTION},
    {"braveWalletImportFromMetaMaskSeedInstructions",
     IDS_BRAVE_WALLET_IMPORT_FROM_META_MASK_SEED_INSTRUCTIONS},
    {"braveWalletCreateWalletInsteadLink",
     IDS_BRAVE_WALLET_CREATE_WALLET_INSTEAD_LINK},
    {"braveWalletImportPasswordError", IDS_BRAVE_WALLET_IMPORT_PASSWORD_ERROR},
    {"braveWalletMetaMaskExtensionDetected",
     IDS_BRAVE_WALLET_METAMASK_EXTENSION_DETECTED},
    {"braveWalletMetaMaskExtensionImportDescription",
     IDS_BRAVE_WALLET_METAMASK_EXTENSION_IMPORT_DESCRIPTION},
    {"braveWalletMetaMaskPasswordInputPlaceholder",
     IDS_BRAVE_WALLET_METAMASK_PASSWORD_INPUT_PLACEHOLDER},
    {"braveWalletInputLabelPassword", IDS_BRAVE_WALLET_INPUT_LABEL_PASSWORD},
    {"braveWalletLearnAboutMyWallet", IDS_BRAVE_WALLET_LEARN_ABOUT_MY_WALLET},
    {"braveWalletDisclosuresTitle", IDS_BRAVE_WALLET_DISCLOSURES_TITLE},
    {"braveWalletDisclosuresDescription",
     IDS_BRAVE_WALLET_DISCLOSURES_DESCRIPTION},
    {"braveWalletSelfCustodyDisclosureCheckboxText",
     IDS_BRAVE_WALLET_SELF_CUSTODY_DISCLOSURE_CHECKBOX_TEXT},
    {"braveWalletTermsOfServiceCheckboxText",
     IDS_BRAVE_WALLET_TERMS_OF_SERVICE_CHECKBOX_TEXT},
    {"braveWalletBuyCryptoButton", IDS_BRAVE_WALLET_BUY_CRYPTO_BUTTON},
    {"braveWalletDepositCryptoButton", IDS_BRAVE_WALLET_DEPOSIT_CRYPTO_BUTTON},
    {"braveWalletCheckingInstalledExtensions",
     IDS_BRAVE_WALLET_CHECKING_INSTALLED_EXTENSIONS},
    {"braveWalletImportFromLegacy", IDS_BRAVE_WALLET_IMPORT_FROM_LEGACY},
    {"braveWalletBuySelectAsset", IDS_BRAVE_WALLET_BUY_SELECT_ASSET},
    {"braveWalletFundWalletTitle", IDS_BRAVE_WALLET_FUND_WALLET_TITLE},
    {"braveWalletDepositFundsTitle", IDS_BRAVE_WALLET_DEPOSIT_FUNDS_TITLE},
    {"braveWalletDepositX", IDS_BRAVE_WALLET_DEPOSIT_X},
    {"braveWalletDepositSolSplTokens", IDS_BRAVE_WALLET_DEPOSIT_SOL_SPL_TOKENS},
    {"braveWalletDepositErc", IDS_BRAVE_WALLET_DEPOSIT_ERC},
    {"braveWalletDepositOnlySendOnXNetwork",
     IDS_BRAVE_WALLET_DEPOSIT_ONLY_SEND_ON_X_NETWORK},
    {"braveWalletFundWalletDescription",
     IDS_BRAVE_WALLET_FUND_WALLET_DESCRIPTION},
    {"braveWalletLearnMoreAboutBraveWallet",
     IDS_BRAVE_WALLET_LEARN_MORE_ABOUT_BRAVE_WALLET},
    {"braveWalletMarketDataAllAssetsFilter",
     IDS_BRAVE_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"braveWalletMarketDataTradableFilter",
     IDS_BRAVE_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"braveWalletMarketDataAssetsColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"braveWalletMarketDataPriceColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"braveWalletMarketData24HrColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"braveWalletMarketDataMarketCapColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"braveWalletMarketDataVolumeColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"braveWalletMarketDataNoAssetsFound",
     IDS_BRAVE_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"braveWalletMarketDataCoinNotSupported",
     IDS_BRAVE_WALLET_MARKET_DATA_COIN_NOT_SUPPORTED},
    {"braveWalletInformation", IDS_BRAVE_WALLET_INFORMATION},
    {"braveWalletRankStat", IDS_BRAVE_WALLET_RANK_STAT},
    {"braveWalletVolumeStat", IDS_BRAVE_WALLET_VOLUME_STAT},
    {"braveWalletMarketCapStat", IDS_BRAVE_WALLET_MARKET_CAP_STAT},
    {"braveWalletBuyTapBuyNotSupportedMessage",
     IDS_BRAVE_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"braveWalletHelpCenterText", IDS_BRAVE_WALLET_HELP_CENTER_TEXT},
    {"braveWalletMarketDataAllAssetsFilter",
     IDS_BRAVE_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"braveWalletMarketDataTradableFilter",
     IDS_BRAVE_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"braveWalletMarketDataAssetsColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"braveWalletMarketDataPriceColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"braveWalletMarketData24HrColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"braveWalletMarketDataMarketCapColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"braveWalletMarketDataVolumeColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"braveWalletMarketDataNoAssetsFound",
     IDS_BRAVE_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"braveWalletMarketDataCoinNotSupported",
     IDS_BRAVE_WALLET_MARKET_DATA_COIN_NOT_SUPPORTED},
    {"braveWalletInformation", IDS_BRAVE_WALLET_INFORMATION},
    {"braveWalletRankStat", IDS_BRAVE_WALLET_RANK_STAT},
    {"braveWalletVolumeStat", IDS_BRAVE_WALLET_VOLUME_STAT},
    {"braveWalletMarketCapStat", IDS_BRAVE_WALLET_MARKET_CAP_STAT},
    {"braveWalletHelpCenter", IDS_BRAVE_WALLET_HELP_CENTER},
    {"braveWalletBuyTapBuyNotSupportedMessage",
     IDS_BRAVE_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
};

// 0x swap constants
constexpr char kRopstenSwapBaseAPIURL[] = "https://ropsten.api.0x.org/";
// As of 22-02-2022, this address is controlled by @onyb.
constexpr char kRopstenFeeRecipient[] =
    "0xa92D461a9a988A7f11ec285d39783A637Fdd6ba4";
constexpr char kPolygonSwapBaseAPIURL[] = "https://polygon.api.0x.org/";
constexpr char kBinanceSmartChainSwapBaseAPIURL[] = "https://bsc.api.0x.org/";
constexpr char kAvalancheSwapBaseAPIURL[] = "https://avalanche.api.0x.org/";
constexpr char kFantomSwapBaseAPIURL[] = "https://fantom.api.0x.org/";
constexpr char kCeloSwapBaseAPIURL[] = "https://celo.api.0x.org/";
constexpr char kOptimismSwapBaseAPIURL[] = "https://optimism.api.0x.org/";
constexpr char kSwapBaseAPIURL[] = "https://api.0x.org/";
constexpr char kBuyTokenPercentageFee[] = "0.00875";
constexpr char kFeeRecipient[] = "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";
constexpr char kAffiliateAddress[] =
    "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";

// Jupiter swap constants
constexpr char kSolanaSwapBaseAPIURL[] = "https://quote-api.jup.ag/";
constexpr char kSolanaBuyTokenFeeBps[] = "85";
constexpr char kSolanaFeeRecipient[] =
    "8eekKfUAGSJbq3CdA2TmHb8tKuyzd5gtEas3MYAtXzrT";

constexpr int64_t kBlockTrackerDefaultTimeInSeconds = 20;

constexpr char kPolygonMainnetEndpoint[] = "https://mainnet-polygon.brave.com/";

// Unstoppable domains record key for ethereum address.
constexpr char kCryptoEthAddressKey[] = "crypto.ETH.address";

// ERC-165 identifier for ERC721 interface.
constexpr char kERC1155InterfaceId[] = "0xd9b67a26";
constexpr char kERC1155MetadataInterfaceId[] = "0x0e89341c";
constexpr char kERC721InterfaceId[] = "0x80ac58cd";
constexpr char kERC721MetadataInterfaceId[] = "0x5b5e139f";

constexpr char kEthereumPrefKey[] = "ethereum";
constexpr char kFilecoinPrefKey[] = "filecoin";
constexpr char kSolanaPrefKey[] = "solana";

const std::vector<mojom::BlockchainToken>& GetWyreBuyTokens();
const std::vector<mojom::BlockchainToken>& GetRampBuyTokens();
const std::vector<mojom::OnRampCurrency>& GetOnRampCurrenciesList();
const std::vector<mojom::BlockchainToken>& GetSardineBuyTokens();
const std::string GetSardineNetworkName(const std::string& chain_id);
const base::flat_map<std::string, std::string>& GetInfuraChainEndpoints();

}  // namespace brave_wallet

#endif  // BRAVE_COMPONENTS_BRAVE_WALLET_BROWSER_BRAVE_WALLET_CONSTANTS_H_
