/* Copyright (c) 2020 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_COMPONENTS_BRAVE_WALLET_BROWSER_BRAVE_WALLET_CONSTANTS_H_
#define BRAVE_COMPONENTS_BRAVE_WALLET_BROWSER_BRAVE_WALLET_CONSTANTS_H_

#include <string>
#include <vector>

#include "brave/components/brave_wallet/common/brave_wallet_types.h"
#include "components/grit/brave_components_strings.h"
#include "ui/base/webui/web_ui_util.h"

namespace brave_wallet {

inline constexpr char kBraveServicesKeyHeader[] = "x-brave-key";

constexpr uint256_t kDefaultSendEthGasLimit = 21000;
constexpr uint256_t kDefaultERC20TransferGasLimit = 300000;
constexpr uint256_t kDefaultERC721TransferGasLimit = 800000;
constexpr uint256_t kDefaultERC20ApproveGasLimit = 300000;

constexpr int32_t kAutoLockMinutesMin = 1;
constexpr int32_t kAutoLockMinutesMax = 10080;

constexpr int32_t kAssetDiscoveryMinutesPerRequest = 1;

inline constexpr char kWalletBaseDirectory[] = "BraveWallet";
inline constexpr char kImageSourceHost[] = "erc-token-images";
inline constexpr char kRampBaseUrl[] = "https://app.ramp.network";
inline constexpr char kOffRampEnabledFlows[] = "OFFRAMP";
inline constexpr char kOnRampEnabledFlows[] = "ONRAMP";
inline constexpr char kOnRampID[] = "8yxja8782as5essk2myz3bmh4az6gpq4nte9n2gf";
inline constexpr char kOffRampID[] = "y57zqta99ohs7o2paf4ak6vpfb7wf8ubj9krwtwe";
inline constexpr char kSardineStorefrontBaseURL[] = "https://crypto.sardine.ai";
inline constexpr char kSardineClientTokensURL[] =
    "https://api.sardine.ai/v1/auth/client-tokens";
inline constexpr char kTransakURL[] = "https://global.transak.com/";
inline constexpr char kTransakApiKey[] = "985d14f0-4cf5-4a4c-8917-78107620d3b7";
inline constexpr char kCoinbaseURL[] = "https://pay.coinbase.com";
inline constexpr char kCoinbaseAppId[] = "8072ff71-8469-4fef-9404-7c905e2359c9";
inline constexpr char kSimpleHashUrl[] = "https://api.simplehash.com";
inline constexpr char kSimpleHashBraveProxyUrl[] =
    "https://simplehash.wallet.brave.com";

inline constexpr size_t kSimpleHashMaxBatchSize = 50;

inline constexpr webui::LocalizedString kLocalizedStrings[] = {
    {"braveWalletWatchOnly", IDS_BRAVE_WALLET_WATCH_ONLY},
    {"braveWalletNftSymbolFieldExplanation",
     IDS_BRAVE_WALLET_NFT_SYMBOL_FIELD_EXPLANATION},
    {"braveWalletNftNameFieldExplanation",
     IDS_BRAVE_WALLET_NFT_NAME_FIELD_EXPLANATION},
    {"braveWalletExempliGratia", IDS_BRAVE_WALLET_EXEMPLI_GRATIA},
    {"braveWalletUnownedNftAlert", IDS_BRAVE_WALLET_UNOWNED_NFT_ALERT},
    {"braveWalletWatchThisNft", IDS_BRAVE_WALLET_WATCH_THIS_NFT},
    {"braveWalletFetchNftMetadataError",
     IDS_BRAVE_WALLET_FETCH_NFT_METADATA_ERROR},
    {"braveWalletWhatIsAnNftTokenId", IDS_BRAVE_WALLET_WHAT_IS_AN_NFT_TOKEN_ID},
    {"braveWalletWhatIsAnNftContractAddress",
     IDS_BRAVE_WALLET_WHAT_IS_AN_NFT_CONTRACT_ADDRESS},
    {"braveWalletGroupByCollection", IDS_BRAVE_WALLET_GROUP_BY_COLLECTION},
    {"braveWalletAddNftModalDescription",
     IDS_BRAVE_WALLET_ADD_NFT_MODAL_DESCRIPTION},
    {"braveWalletHideNotOwnedNfTs", IDS_BRAVE_WALLET_HIDE_NOT_OWNED_NF_TS},
    {"braveWalletNoRoutesFound", IDS_BRAVE_WALLET_NO_ROUTES_FOUND},
    {"braveWalletPrivateKeyImportType",
     IDS_BRAVE_WALLET_PRIVATE_KEY_IMPORT_TYPE},
    {"braveWalletEnterPasswordIfApplicable",
     IDS_BRAVE_WALLET_ENTER_PASSWORD_IF_APPLICABLE},
    {"braveWalletFoundIssues", IDS_BRAVE_WALLET_FOUND_ISSUES},
    {"braveWalletContract", IDS_BRAVE_WALLET_CONTRACT},
    {"braveWalletFoundRisks", IDS_BRAVE_WALLET_FOUND_RISKS},
    {"braveWalletProceedButton", IDS_BRAVE_WALLET_PROCEED_BUTTON},
    {"braveWalletUntrustedRequestWarning",
     IDS_BRAVE_WALLET_UNTRUSTED_REQUEST_WARNING},
    {"braveWalletRiskOfLossAction", IDS_BRAVE_WALLET_RISK_OF_LOSS_ACTION},
    {"braveWalletTestNetworkAccount", IDS_BRAVE_WALLET_TEST_NETWORK_ACCOUNT},
    {"braveWalletPopular", IDS_BRAVE_WALLET_POPULAR},
    {"braveWalletFeatured", IDS_BRAVE_WALLET_FEATURED},
    {"braveWalletShowTestnets", IDS_BRAVE_WALLET_SHOW_TESTNETS},
    {"braveWalletChooseChainsToUse", IDS_BRAVE_WALLET_CHOOSE_CHAINS_TO_USE},
    {"braveWalletSupportedNetworks", IDS_BRAVE_WALLET_SUPPORTED_NETWORKS},
    {"braveWalletAddNetworksAnytimeInSettings",
     IDS_BRAVE_WALLET_ADD_NETWORKS_ANYTIME_IN_SETTINGS},
    {"braveWalletContinueWithXItems", IDS_BRAVE_WALLET_CONTINUE_WITH_X_ITEMS},
    {"braveWalletTopNavExplore", IDS_BRAVE_WALLET_TOP_NAV_EXPLORE},
    {"braveWalletWeb3", IDS_BRAVE_WALLET_WEB_3},
    {"braveWalletSpenderAddress", IDS_BRAVE_WALLET_SPENDER_ADDRESS},
    {"braveWalletTokenIsVerifiedByLists",
     IDS_BRAVE_WALLET_TOKEN_IS_VERIFIED_BY_LISTS},
    {"braveWalletTokenIsVerified", IDS_BRAVE_WALLET_TOKEN_IS_VERIFIED},
    {"braveWalletTokenIsUnverified", IDS_BRAVE_WALLET_TOKEN_IS_UNVERIFIED},
    {"braveWalletUnlimitedAssetAmount",
     IDS_BRAVE_WALLET_UNLIMITED_ASSET_AMOUNT},
    {"braveWalletFrom", IDS_BRAVE_WALLET_FROM},
    {"braveWalletReceive", IDS_BRAVE_WALLET_RECEIVE},
    {"braveWalletChangeAnytimeInSettings",
     IDS_BRAVE_WALLET_CHANGE_ANYTIME_IN_SETTINGS},
    {"braveWalletAvailable", IDS_BRAVE_WALLET_AVAILABLE},
    {"braveWalletAvailableBalanceDescription",
     IDS_BRAVE_WALLET_AVAILABLE_BALANCE_DESCRIPTION},
    {"braveWalletPending", IDS_BRAVE_WALLET_PENDING},
    {"braveWalletPendingBalanceDescription",
     IDS_BRAVE_WALLET_PENDING_BALANCE_DESCRIPTION},
    {"braveWalletTotalBalanceDescription",
     IDS_BRAVE_WALLET_TOTAL_BALANCE_DESCRIPTION},
    {"braveWalletUnavailableBalances", IDS_BRAVE_WALLET_UNAVAILABLE_BALANCES},
    {"braveWalletTransactionSimulationTerms",
     IDS_BRAVE_WALLET_TRANSACTION_SIMULATION_TERMS},
    {"braveWalletButtonEnable", IDS_BRAVE_WALLET_BUTTON_ENABLE},
    {"braveWalletButtonNoThanks", IDS_BRAVE_WALLET_BUTTON_NO_THANKS},
    {"braveWalletTransactionSimulationDetectPhishing",
     IDS_BRAVE_WALLET_TRANSACTION_SIMULATION_DETECT_PHISHING},
    {"braveWalletTransactionSimulationDetectMalicious",
     IDS_BRAVE_WALLET_TRANSACTION_SIMULATION_DETECT_MALICIOUS},
    {"braveWalletTransactionSimulationSeeEstimates",
     IDS_BRAVE_WALLET_TRANSACTION_SIMULATION_SEE_ESTIMATES},
    {"braveWalletEnableEnhancedTransactionDetailsTitle",
     IDS_BRAVE_WALLET_ENABLE_ENHANCED_TRANSACTION_DETAILS_TITLE},
    {"braveWalletNetworkFees", IDS_BRAVE_WALLET_NETWORK_FEES},
    {"braveWalletSolanaSysvarRentProgram",
     IDS_BRAVE_WALLET_SOLANA_SYSVAR_RENT_PROGRAM},
    {"braveWalletSolanaMetaDataProgram",
     IDS_BRAVE_WALLET_SOLANA_META_DATA_PROGRAM},
    {"braveWalletSolanaAssociatedTokenProgram",
     IDS_BRAVE_WALLET_SOLANA_ASSOCIATED_TOKEN_PROGRAM},
    {"braveWalletSolanaTokenProgram", IDS_BRAVE_WALLET_SOLANA_TOKEN_PROGRAM},
    {"braveWalletTransactionHasFeeEstimatesError",
     IDS_BRAVE_WALLET_TRANSACTION_HAS_FEE_ESTIMATES_ERROR},
    {"braveWalletGasFeeLimitLowerThanBaseFeeWarning",
     IDS_BRAVE_WALLET_GAS_FEE_LIMIT_LOWER_THAN_BASE_FEE_WARNING},
    {"braveWalletTokenMintAddress", IDS_BRAVE_WALLET_TOKEN_MINT_ADDRESS},
    {"braveWalletActivity", IDS_BRAVE_WALLET_ACTIVITY},
    {"braveWalletTokenDecimalsIsRequiredError",
     IDS_BRAVE_WALLET_TOKEN_DECIMALS_IS_REQUIRED_ERROR},
    {"braveWalletTokenSymbolIsRequiredError",
     IDS_BRAVE_WALLET_TOKEN_SYMBOL_IS_REQUIRED_ERROR},
    {"braveWalletInvalidTokenContractAddressError",
     IDS_BRAVE_WALLET_INVALID_TOKEN_CONTRACT_ADDRESS_ERROR},
    {"braveWalletTokenNameIsRequiredError",
     IDS_BRAVE_WALLET_TOKEN_NAME_IS_REQUIRED_ERROR},
    {"braveWalletNetworkIsRequiredError",
     IDS_BRAVE_WALLET_NETWORK_IS_REQUIRED_ERROR},
    {"braveWalletEnterYourPasswordToStartBackup",
     IDS_BRAVE_WALLET_ENTER_YOUR_PASSWORD_TO_START_BACKUP},
    {"braveWalletEnterAPasswordToContinue",
     IDS_BRAVE_WALLET_ENTER_A_PASSWORD_TO_CONTINUE},
    {"braveWalletNoTransactionsYetDescription",
     IDS_BRAVE_WALLET_NO_TRANSACTIONS_YET_DESCRIPTION},
    {"braveWalletNoTransactionsYet", IDS_BRAVE_WALLET_NO_TRANSACTIONS_YET},
    {"braveWalletInvalidMnemonicError", IDS_WALLET_INVALID_MNEMONIC_ERROR},
    {"braveWalletImportWalletTypeTitle",
     IDS_BRAVE_WALLET_IMPORT_WALLET_TYPE_TITLE},
    {"braveWalletImportWalletTypeHotWalletTitle",
     IDS_BRAVE_WALLET_IMPORT_WALLET_TYPE_HOT_WALLET_TITLE},
    {"braveWalletImportWalletTypeHotWalletDescription",
     IDS_BRAVE_WALLET_IMPORT_WALLET_TYPE_HOT_WALLET_DESCRIPTION},
    {"braveWalletImportWalletTypeHardwareWalletTitle",
     IDS_BRAVE_WALLET_IMPORT_WALLET_TYPE_HARDWARE_WALLET_TITLE},
    {"braveWalletImportWalletTypeHardwareWalletDescription",
     IDS_BRAVE_WALLET_IMPORT_WALLET_TYPE_HARDWARE_WALLET_DESCRIPTION},
    {"braveWalletRecoveryPhraseLengthError",
     IDS_BRAVE_WALLET_RECOVERY_PHRASE_LENGTH_ERROR},
    {"braveWalletOrdinalTwentyFourth", IDS_BRAVE_WALLET_ORDINAL_TWENTY_FOURTH},
    {"braveWalletOrdinalTwentyThird", IDS_BRAVE_WALLET_ORDINAL_TWENTY_THIRD},
    {"braveWalletOrdinalTwentySecond", IDS_BRAVE_WALLET_ORDINAL_TWENTY_SECOND},
    {"braveWalletOrdinalTwentyFirst", IDS_BRAVE_WALLET_ORDINAL_TWENTY_FIRST},
    {"braveWalletOrdinalTwentieth", IDS_BRAVE_WALLET_ORDINAL_TWENTIETH},
    {"braveWalletOrdinalNineteenth", IDS_BRAVE_WALLET_ORDINAL_NINETEENTH},
    {"braveWalletOrdinalEighteenth", IDS_BRAVE_WALLET_ORDINAL_EIGHTEENTH},
    {"braveWalletOrdinalSeventeenth", IDS_BRAVE_WALLET_ORDINAL_SEVENTEENTH},
    {"braveWalletOrdinalSixteenth", IDS_BRAVE_WALLET_ORDINAL_SIXTEENTH},
    {"braveWalletOrdinalFifteenth", IDS_BRAVE_WALLET_ORDINAL_FIFTEENTH},
    {"braveWalletOrdinalFourteenth", IDS_BRAVE_WALLET_ORDINAL_FOURTEENTH},
    {"braveWalletOrdinalThirteenth", IDS_BRAVE_WALLET_ORDINAL_THIRTEENTH},
    {"braveWalletOrdinalTwelfth", IDS_BRAVE_WALLET_ORDINAL_TWELFTH},
    {"braveWalletOrdinalSuffixOther", IDS_BRAVE_WALLET_ORDINAL_SUFFIX_OTHER},
    {"braveWalletOrdinalSuffixFew", IDS_BRAVE_WALLET_ORDINAL_SUFFIX_FEW},
    {"braveWalletOrdinalSuffixTwo", IDS_BRAVE_WALLET_ORDINAL_SUFFIX_TWO},
    {"braveWalletOrdinalSuffixOne", IDS_BRAVE_WALLET_ORDINAL_SUFFIX_ONE},
    {"braveWalletOrdinalEleventh", IDS_BRAVE_WALLET_ORDINAL_ELEVENTH},
    {"braveWalletOrdinalTenth", IDS_BRAVE_WALLET_ORDINAL_TENTH},
    {"braveWalletOrdinalNinth", IDS_BRAVE_WALLET_ORDINAL_NINTH},
    {"braveWalletOrdinalEighth", IDS_BRAVE_WALLET_ORDINAL_EIGHTH},
    {"braveWalletOrdinalSeventh", IDS_BRAVE_WALLET_ORDINAL_SEVENTH},
    {"braveWalletOrdinalSixth", IDS_BRAVE_WALLET_ORDINAL_SIXTH},
    {"braveWalletOrdinalFifth", IDS_BRAVE_WALLET_ORDINAL_FIFTH},
    {"braveWalletOrdinalFourth", IDS_BRAVE_WALLET_ORDINAL_FOURTH},
    {"braveWalletOrdinalSecond", IDS_BRAVE_WALLET_ORDINAL_SECOND},
    {"braveWalletRemoveAccountModalTitle",
     IDS_BRAVE_WALLET_REMOVE_ACCOUNT_MODAL_TITLE},
    {"braveWalletViewDecodedMessage", IDS_BRAVE_WALLET_VIEW_DECODED_MESSAGE},
    {"braveWalletViewEncodedMessage", IDS_BRAVE_WALLET_VIEW_ENCODED_MESSAGE},
    {"braveWalletNonAsciiCharactersInMessageWarning",
     IDS_BRAVE_WALLET_NON_ASCII_CHARACTERS_IN_MESSAGE_WARNING},
    {"braveWalletEnterYourPassword", IDS_BRAVE_WALLET_ENTER_YOUR_PASSWORD},
    {"braveWalletEnterYourBraveWalletPassword",
     IDS_BRAVE_WALLET_ENTER_YOUR_BRAVE_WALLET_PASSWORD},
    {"braveWalletClickToSwitch", IDS_BRAVE_WALLET_CLICK_TO_SWITCH},
    {"braveWalletMultiChain", IDS_BRAVE_WALLET_MULTI_CHAIN},
    {"braveWalletPerksBrowserNative", IDS_BRAVE_WALLET_PERKS_BROWSER_NATIVE},
    {"braveWalletPerksTokens", IDS_BRAVE_WALLET_PERKS_TOKENS},
    {"braveWallet", IDS_BRAVE_WALLET},
    {"braveWalletSearchText", IDS_BRAVE_WALLET_SEARCH_TEXT},
    {"braveWalletSideNavCrypto", IDS_BRAVE_WALLET_SIDE_NAV_CRYPTO},
    {"braveWalletSideNavRewards", IDS_BRAVE_WALLET_SIDE_NAV_REWARDS},
    {"braveWalletSideNavCards", IDS_BRAVE_WALLET_SIDE_NAV_CARDS},
    {"braveWalletTopNavPortfolio", IDS_BRAVE_WALLET_TOP_NAV_PORTFOLIO},
    {"braveWalletTopTabPrices", IDS_BRAVE_WALLET_TOP_TAB_PRICES},
    {"braveWalletTopNavNFTS", IDS_BRAVE_WALLET_TOP_NAV_N_F_T_S},
    {"braveWalletTopNavAccounts", IDS_BRAVE_WALLET_TOP_NAV_ACCOUNTS},
    {"braveWalletTopNavMarket", IDS_BRAVE_WALLET_TOP_NAV_MARKET},
    {"braveWalletChartOneHour", IDS_BRAVE_WALLET_CHART_ONE_HOUR},
    {"braveWalletChartOneDay", IDS_BRAVE_WALLET_CHART_ONE_DAY},
    {"braveWalletChartOneWeek", IDS_BRAVE_WALLET_CHART_ONE_WEEK},
    {"braveWalletChartOneMonth", IDS_BRAVE_WALLET_CHART_ONE_MONTH},
    {"braveWalletChartThreeMonths", IDS_BRAVE_WALLET_CHART_THREE_MONTHS},
    {"braveWalletChartOneYear", IDS_BRAVE_WALLET_CHART_ONE_YEAR},
    {"braveWalletChartAllTime", IDS_BRAVE_WALLET_CHART_ALL_TIME},
    {"braveWalletChartOneHourAbbr", IDS_BRAVE_WALLET_CHART_ONE_HOUR_ABBR},
    {"braveWalletChartOneDayAbbr", IDS_BRAVE_WALLET_CHART_ONE_DAY_ABBR},
    {"braveWalletChartOneWeekAbbr", IDS_BRAVE_WALLET_CHART_ONE_WEEK_ABBR},
    {"braveWalletChartOneMonthAbbr", IDS_BRAVE_WALLET_CHART_ONE_MONTH_ABBR},
    {"braveWalletChartThreeMonthsAbbr",
     IDS_BRAVE_WALLET_CHART_THREE_MONTHS_ABBR},
    {"braveWalletChartOneYearAbbr", IDS_BRAVE_WALLET_CHART_ONE_YEAR_ABBR},
    {"braveWalletChartAllTimeAbbr", IDS_BRAVE_WALLET_CHART_ALL_TIME_ABBR},
    {"braveWalletAddCoin", IDS_BRAVE_WALLET_ADD_COIN},
    {"braveWalletBalance", IDS_BRAVE_WALLET_BALANCE},
    {"braveWalletPortfolioAssetNetworkDescription",
     IDS_BRAVE_WALLET_PORTFOLIO_ASSET_NETWORK_DESCRIPTION},
    {"braveWalletAccounts", IDS_BRAVE_WALLET_ACCOUNTS},
    {"braveWalletSubviewAccount", IDS_BRAVE_WALLET_SUBVIEW_ACCOUNT},
    {"braveWalletOwner", IDS_BRAVE_WALLET_OWNER},
    {"braveWalletTransactions", IDS_BRAVE_WALLET_TRANSACTIONS},
    {"braveWalletPrice", IDS_BRAVE_WALLET_PRICE},
    {"braveWalletBack", IDS_BRAVE_WALLET_BACK},
    {"braveWalletAddAccount", IDS_BRAVE_WALLET_ADD_ACCOUNT},
    {"braveWalletPoweredByCoinGecko", IDS_BRAVE_WALLET_POWERED_BY_COIN_GECKO},
    {"braveWalletBuy", IDS_BRAVE_WALLET_BUY},
    {"braveWalletSend", IDS_BRAVE_WALLET_SEND},
    {"braveWalletSwap", IDS_BRAVE_WALLET_SWAP},
    {"braveWalletBridge", IDS_BRAVE_WALLET_BRIDGE},
    {"braveWalletReset", IDS_BRAVE_WALLET_RESET},
    {"braveWalletSell", IDS_BRAVE_WALLET_SELL},
    {"braveWalletNotEnoughBalance", IDS_BRAVE_WALLET_NOT_ENOUGH_BALANCE},
    {"braveWalletChooseAssetToSend", IDS_BRAVE_WALLET_CHOOSE_ASSET_TO_SEND},
    {"braveWalletChooseAssetToSwap", IDS_BRAVE_WALLET_CHOOSE_ASSET_TO_SWAP},
    {"braveWalletEnterRecipientAddress",
     IDS_BRAVE_WALLET_ENTER_RECIPIENT_ADDRESS},
    {"braveWalletNotEnoughFunds", IDS_BRAVE_WALLET_NOT_ENOUGH_FUNDS},
    {"braveWalletSendHalf", IDS_BRAVE_WALLET_SEND_HALF},
    {"braveWalletSendMax", IDS_BRAVE_WALLET_SEND_MAX},
    {"braveWalletReviewOrder", IDS_BRAVE_WALLET_REVIEW_ORDER},
    {"braveWalletReviewSend", IDS_BRAVE_WALLET_REVIEW_SEND},
    {"braveWalletNoAvailableTokens", IDS_BRAVE_WALLET_NO_AVAILIBLE_TOKENS},
    {"braveWalletSearchTokens", IDS_BRAVE_WALLET_SEARCH_TOKENS},
    {"braveWalletSearchNFTs", IDS_BRAVE_WALLET_SEARCH_NFTS},
    {"braveWalletChooseAsset", IDS_BRAVE_WALLET_CHOOSE_ASSET},
    {"braveWalletOrdinalsWarningMessage",
     IDS_BRAVE_WALLET_ORDINALS_WARNING_MESSAGE},
    {"braveWalletUserUnderstandsLabel",
     IDS_BRAVE_WALLET_USER_UNDERSTANDS_LABEL},
    {"braveWalletChooseRecipient", IDS_BRAVE_WALLET_CHOOSE_RECIPIENT},
    {"braveWalletMyAddresses", IDS_BRAVE_WALLET_MY_ADDRESSES},
    {"braveWalletAddressOrDomainPlaceholder",
     IDS_BRAVE_WALLET_ADDRESS_OR_DOMAIN_PLACEHOLDER},
    {"braveWalletSendTo", IDS_BRAVE_WALLET_SEND_TO},
    {"braveWalletInvalidDomainExtension",
     IDS_BRAVE_WALLET_INVALID_DOMAIN_EXTENSION},
    {"braveWalletChooseAccount", IDS_BRAVE_WALLET_CHOOSE_ACCOUNT},
    {"braveWalletMarketPrice", IDS_BRAVE_WALLET_MARKET_PRICE},
    {"braveWalletOwned", IDS_BRAVE_WALLET_OWNED},
    {"braveWalletNotOwned", IDS_BRAVE_WALLET_NOT_OWNED},
    {"braveWalletAmount24H", IDS_BRAVE_WALLET_AMOUNT_24H},
    {"braveWalletChooseAssetToBridge", IDS_BRAVE_WALLET_CHOOSE_ASSET_TO_BRIDGE},
    {"braveWalletReviewSwap", IDS_BRAVE_WALLET_REVIEW_SWAP},
    {"braveWalletChooseQuoteProvider", IDS_BRAVE_WALLET_CHOOSE_QUOTE_PROVIDER},
    {"braveWalletQuoteProviderInfo", IDS_BRAVE_WALLET_QUOTE_PROVIDER_INFO},
    {"braveWalletNotAvailable", IDS_BRAVE_WALLET_REVIEW_NOT_AVAILABLE},
    {"braveWalletUpdate", IDS_BRAVE_WALLET_REVIEW_UPDATE},
    {"braveWalletProviderNotSupported",
     IDS_BRAVE_WALLET_PROVIDER_NOT_SUPPORTED},
    {"braveWalletChangeProvider", IDS_BRAVE_WALLET_CHANGE_PROVIDER},
    {"braveWalletRoute", IDS_BRAVE_WALLET_ROUTE},
    {"braveWalletMaxSlippage", IDS_BRAVE_WALLET_MAX_SLIPPAGE},
    {"braveWalletMaxSlippageDescription",
     IDS_BRAVE_WALLET_SLIPPAGE_DESCRIPTION},
    {"braveWalletPriceImpactDescription",
     IDS_BRAVE_WALLET_PRICE_IMPACT_DESCRIPTION},
    {"braveWalletSuggestedValues", IDS_BRAVE_WALLET_SUGGESTED_VALUES},
    {"braveWalletMainstreamAssetPairs",
     IDS_BRAVE_WALLET_MAINSTREAM_ASSET_PAIRS},
    {"braveWalletStablecoinPairs", IDS_BRAVE_WALLET_STABLECOIN_PAIRS},
    {"braveWalletOthers", IDS_BRAVE_WALLET_OTHERS},
    {"braveWalletSuggested", IDS_BRAVE_WALLET_SUGGESTED},
    {"braveWalletCustom", IDS_BRAVE_WALLET_CUSTOM},
    {"braveWalletCheapest", IDS_BRAVE_WALLET_CHEAPEST},
    {"braveWalletFastest", IDS_BRAVE_WALLET_FASTEST},
    {"braveWalletOnNetwork", IDS_BRAVE_WALLET_ON_NETWORK},
    {"braveWalletRoutes", IDS_BRAVE_WALLET_ROUTES},
    {"braveWalletSwapOnNetworkViaExchange",
     IDS_BRAVE_WALLET_SWAP_ON_NETWORK_VIA_EXCHANGE},
    {"braveWalletBridgeFromNetworkToNetwork",
     IDS_BRAVE_WALLET_BRIDGE_FROM_NETWORK_TO_NETWORK},
    {"braveWalletExchangeNamePlusSteps",
     IDS_BRAVE_WALLET_EXCHANGE_NAME_PLUS_STEPS},
    {"braveWalletExchangeViaProvider", IDS_BRAVE_WALLET_EXCHANGE_VIA_PROVIDER},
    {"braveWalletSortBy", IDS_BRAVE_WALLET_SORT_BY},
    {"braveWalletEstTime", IDS_BRAVE_WALLET_EST_TIME},
    {"braveWalletExchangeRate", IDS_BRAVE_WALLET_EXCHANGE_RATE},
    {"braveWalletExchangeFor", IDS_BRAVE_WALLET_EXCHANGE_FOR},
    {"braveWalletRecipient", IDS_BRAVE_WALLET_RECIPIENT},
    {"braveWalletReviewBridge", IDS_BRAVE_WALLET_REVIEW_BRIDGE},
    {"braveWalletSlippageToleranceWarning",
     IDS_BRAVE_WALLET_SLIPPAGE_TOLERANCE_WARNING},
    {"braveWalletExpiresInTitle", IDS_BRAVE_WALLET_EXPIRES_IN_TITLE},
    {"braveWalletSendPlaceholder", IDS_BRAVE_WALLET_SEND_PLACEHOLDER},
    {"braveWalletSendNoURLPlaceholder",
     IDS_BRAVE_WALLET_SEND_NO_URL_PLACEHOLDER},
    {"braveWalletSwapDisclaimer", IDS_BRAVE_WALLET_SWAP_DISCLAIMER},
    {"braveWalletSwapDisclaimerDescription",
     IDS_BRAVE_WALLET_SWAP_DISCLAIMER_DESCRIPTION},
    {"braveWalletJupiterSwapDisclaimerDescription",
     IDS_BRAVE_WALLET_JUPITER_SWAP_DISCLAIMER_DESCRIPTION},
    {"braveWalletSwapFeesNotice", IDS_BRAVE_WALLET_SWAP_FEES_NOTICE},
    {"braveWalletDecimalPlacesError", IDS_BRAVE_WALLET_DECIMAL_PLACES_ERROR},
    {"braveWalletCreateAccountDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_DESCRIPTION},
    {"braveWalletCreateAccountYes", IDS_BRAVE_WALLET_CREATE_ACCOUNT_YES},
    {"braveWalletCreateAccountNo", IDS_BRAVE_WALLET_CREATE_ACCOUNT_NO},
    {"braveWalletButtonContinue", IDS_BRAVE_WALLET_BUTTON_CONTINUE},
    {"braveWalletButtonNext", IDS_BRAVE_WALLET_BUTTON_NEXT},
    {"braveWalletButtonVerifyPhrase", IDS_BRAVE_WALLET_BUTTON_GOT_IT},
    {"braveWalletButtonCopy", IDS_BRAVE_WALLET_BUTTON_COPY},
    {"braveWalletButtonCopied", IDS_BRAVE_WALLET_BUTTON_COPIED},
    {"braveWalletButtonVerify", IDS_BRAVE_WALLET_BUTTON_VERIFY},
    {"braveWalletButtonClose", IDS_BRAVE_WALLET_BUTTON_CLOSE},
    {"braveWalletButtonMore", IDS_BRAVE_WALLET_BUTTON_MORE},
    {"braveWalletButtonDone", IDS_BRAVE_WALLET_BUTTON_DONE},
    {"braveWalletWelcomeTitle", IDS_BRAVE_WALLET_WELCOME_TITLE},
    {"braveWalletWelcomeRestoreButton",
     IDS_BRAVE_WALLET_WELCOME_RESTORE_BUTTON},
    {"braveWalletWelcomeDescription", IDS_BRAVE_WALLET_WELCOME_DESCRIPTION},
    {"braveWalletWelcomeNewWalletTitle",
     IDS_BRAVE_WALLET_WELCOME_NEW_WALLET_TITLE},
    {"braveWalletWelcomeNewWalletDescription",
     IDS_BRAVE_WALLET_WELCOME_NEW_WALLET_DESCRIPTION},
    {"braveWalletWelcomeImportWalletTitle",
     IDS_BRAVE_WALLET_WELCOME_IMPORT_WALLET_TITLE},
    {"braveWalletWelcomeImportWalletDescription",
     IDS_BRAVE_WALLET_WELCOME_IMPORT_WALLET_DESCRIPTION},
    {"braveWalletWelcomeWatchOnlyTitle",
     IDS_BRAVE_WALLET_WELCOME_WATCH_ONLY_TITLE},
    {"braveWalletCopyright", IDS_BRAVE_WALLET_WELCOME_COPYRIGHT},
    {"braveWalletWelcomeDividerText", IDS_BRAVE_WALLET_WELCOME_DIVIDER_TEXT},
    {"braveWalletBackupIntroTitle", IDS_BRAVE_WALLET_BACKUP_INTRO_TITLE},
    {"braveWalletBackupIntroTerms", IDS_BRAVE_WALLET_BACKUP_INTRO_TERMS},
    {"braveWalletButtonSkip", IDS_BRAVE_WALLET_BUTTON_SKIP},
    {"braveWalletButtonCancel", IDS_BRAVE_WALLET_BUTTON_CANCEL},
    {"braveWalletButtonSaveChanges", IDS_BRAVE_WALLET_BUTTON_SAVE_CHANGES},
    {"braveWalletRecoveryTitle", IDS_BRAVE_WALLET_RECOVERY_TITLE},
    {"braveWalletRecoveryDescription", IDS_BRAVE_WALLET_RECOVERY_DESCRIPTION},
    {"braveWalletRecoveryWarning1", IDS_BRAVE_WALLET_RECOVERY_WARNING1},
    {"braveWalletRecoveryWarning2", IDS_BRAVE_WALLET_RECOVERY_WARNING2},
    {"braveWalletRecoveryWarning3", IDS_BRAVE_WALLET_RECOVERY_WARNING3},
    {"braveWalletRecoveryTerms", IDS_BRAVE_WALLET_RECOVERY_TERMS},
    {"braveWalletVerifyRecoveryTitle", IDS_BRAVE_WALLET_VERIFY_RECOVERY_TITLE},
    {"braveWalletVerifyRecoveryDescription",
     IDS_BRAVE_WALLET_VERIFY_RECOVERY_DESCRIPTION},
    {"braveWalletVerifyError", IDS_BRAVE_WALLET_VERIFY_ERROR},
    {"braveWalletVerifyRecoveryPhraseTitle",
     IDS_BRAVE_WALLET_VERIFY_RECOVERY_PHRASE_TITLE},
    {"braveWalletVerifyRecoveryPhraseInstructions",
     IDS_BRAVE_WALLET_VERIFY_RECOVERY_PHRASE_INSTRUCTIONS},
    {"braveWalletVerifyPhraseError", IDS_BRAVE_WALLET_VERIFY_PHRASE_ERROR},
    {"braveWalletCreatePasswordTitle", IDS_BRAVE_WALLET_CREATE_PASSWORD_TITLE},
    {"braveWalletCreatePasswordDescription",
     IDS_BRAVE_WALLET_CREATE_PASSWORD_DESCRIPTION},
    {"braveWalletCreatePasswordInput", IDS_BRAVE_WALLET_CREATE_PASSWORD_INPUT},
    {"braveWalletConfirmPasswordInput",
     IDS_BRAVE_WALLET_CONFIRM_PASSWORD_INPUT},
    {"braveWalletCreatePasswordError", IDS_BRAVE_WALLET_CREATE_PASSWORD_ERROR},
    {"braveWalletConfirmPasswordError",
     IDS_BRAVE_WALLET_CONFIRM_PASSWORD_ERROR},
    {"braveWalletLockScreenTitle", IDS_BRAVE_WALLET_LOCK_SCREEN_TITLE},
    {"braveWalletLockScreenButton", IDS_BRAVE_WALLET_LOCK_SCREEN_BUTTON},
    {"braveWalletLockScreenError", IDS_BRAVE_WALLET_LOCK_SCREEN_ERROR},
    {"braveWalletUnlockWallet", IDS_BRAVE_WALLET_UNLOCK_WALLET},
    {"braveWalletWalletPopupSettings", IDS_BRAVE_WALLET_WALLET_POPUP_SETTINGS},
    {"braveWalletWalletPopupLock", IDS_BRAVE_WALLET_WALLET_POPUP_LOCK},
    {"braveWalletWalletPopupBackup", IDS_BRAVE_WALLET_WALLET_POPUP_BACKUP},
    {"braveWalletWalletPopupConnectedSites",
     IDS_BRAVE_WALLET_WALLET_POPUP_CONNECTED_SITES},
    {"braveWalletWalletPopupHideBalances",
     IDS_BRAVE_WALLET_WALLET_POPUP_HIDE_BALANCES},
    {"braveWalletWalletPopupShowGraph",
     IDS_BRAVE_WALLET_WALLET_POPUP_SHOW_GRAPH},
    {"braveWalletWalletNFTsTab", IDS_BRAVE_WALLET_WALLET_NFTS_TAB},
    {"braveWalletBackupWarningText", IDS_BRAVE_WALLET_BACKUP_WARNING_TEXT},
    {"braveWalletBackupButton", IDS_BRAVE_WALLET_BACKUP_BUTTON},
    {"braveWalletDismissButton", IDS_BRAVE_WALLET_DISMISS_BUTTON},
    {"braveWalletDefaultWalletBanner", IDS_BRAVE_WALLET_DEFAULT_WALLET_BANNER},
    {"braveWalletRestoreTite", IDS_BRAVE_WALLET_RESTORE_TITE},
    {"braveWalletRestoreDescription", IDS_BRAVE_WALLET_RESTORE_DESCRIPTION},
    {"braveWalletRestoreError", IDS_BRAVE_WALLET_RESTORE_ERROR},
    {"braveWalletRestorePlaceholder", IDS_BRAVE_WALLET_RESTORE_PLACEHOLDER},
    {"braveWalletRestoreShowPhrase", IDS_BRAVE_WALLET_RESTORE_SHOW_PHRASE},
    {"braveWalletRestoreLegacyCheckBox",
     IDS_BRAVE_WALLET_RESTORE_LEGACY_CHECK_BOX},
    {"braveWalletRestoreFormText", IDS_BRAVE_WALLET_RESTORE_FORM_TEXT},
    {"braveWalletSkipBackupWarning", IDS_BRAVE_WALLET_SKIP_BACKUP_WARNING},
    {"braveWalletSkipBackup", IDS_WALLET_SKIP_BACKUP},
    {"braveWalletGoBack", IDS_BRAVE_WALLET_GO_BACK},
    {"braveWalletToolTipCopyToClipboard",
     IDS_BRAVE_WALLET_TOOL_TIP_COPY_TO_CLIPBOARD},
    {"braveWalletToolTipCopiedToClipboard",
     IDS_BRAVE_WALLET_TOOL_TIP_COPIED_TO_CLIPBOARD},
    {"braveWalletClickToCopy", IDS_BRAVE_WALLET_CLICK_TO_COPY},
    {"braveWalletPasteFromClipboard", IDS_BRAVE_WALLET_PASTE_FROM_CLIPBOARD},
    {"braveWalletAccountsPrimary", IDS_BRAVE_WALLET_ACCOUNTS_PRIMARY},
    {"braveWalletAccountsSecondary", IDS_BRAVE_WALLET_ACCOUNTS_SECONDARY},
    {"braveWalletConnectedHardwareWallets",
     IDS_BRAVE_WALLET_CONNECTED_HARDWARE_WALLETS},
    {"braveWalletAccountsAssets", IDS_BRAVE_WALLET_ACCOUNTS_ASSETS},
    {"braveWalletAccountsEditVisibleAssets",
     IDS_BRAVE_WALLET_ACCOUNTS_EDIT_VISIBLE_ASSETS},
    {"braveWalletAccountBalance", IDS_BRAVE_WALLET_ACCOUNT_BALANCE},
    {"braveWalletViewAddressOn", IDS_BRAVE_WALLET_VIEW_ADDRESS_ON},
    {"braveWalletNetworkExplorer", IDS_BRAVE_WALLET_NETWORK_EXPLORER},
    {"braveWalletAddAccountCreate", IDS_BRAVE_WALLET_ADD_ACCOUNT_CREATE},
    {"braveWalletCreateAccount", IDS_BRAVE_WALLET_CREATE_ACCOUNT},
    {"braveWalletCreateAccountButton", IDS_BRAVE_WALLET_CREATE_ACCOUNT_BUTTON},
    {"braveWalletCreateAccountImportAccount",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_IMPORT_ACCOUNT},
    {"braveWalletCreateAccountTitle", IDS_BRAVE_WALLET_CREATE_ACCOUNT_TITLE},
    {"braveWalletCreateAccountEthereumDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_ETHEREUM_DESCRIPTION},
    {"braveWalletCreateAccountSolanaDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_SOLANA_DESCRIPTION},
    {"braveWalletCreateAccountFilecoinDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_FILECOIN_DESCRIPTION},
    {"braveWalletCreateAccountBitcoinDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_BITCOIN_DESCRIPTION},
    {"braveWalletCreateAccountZCashDescription",
     IDS_BRAVE_WALLET_CREATE_ACCOUNT_ZCASH_DESCRIPTION},
    {"braveWalletFilecoinPrivateKeyProtocol",
     IDS_BRAVE_WALLET_FILECOIN_PRIVATE_KEY_PROTOCOL},
    {"braveWalletAddAccountImport", IDS_BRAVE_WALLET_ADD_ACCOUNT_IMPORT},
    {"braveWalletAddAccountImportHardware",
     IDS_BRAVE_WALLET_ADD_ACCOUNT_IMPORT_HARDWARE},
    {"braveWalletAddAccountHardware", IDS_BRAVE_WALLET_ADD_ACCOUNT_HARDWARE},
    {"braveWalletAddAccountConnect", IDS_BRAVE_WALLET_ADD_ACCOUNT_CONNECT},
    {"braveWalletAddAccountPlaceholder",
     IDS_BRAVE_WALLET_ADD_ACCOUNT_PLACEHOLDER},
    {"braveWalletImportAccountDisclaimer",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_DISCLAIMER},
    {"braveWalletImportAccountPlaceholder",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_PLACEHOLDER},
    {"braveWalletImportAccountKey", IDS_BRAVE_WALLET_IMPORT_ACCOUNT_KEY},
    {"braveWalletImportAccountFile", IDS_BRAVE_WALLET_IMPORT_ACCOUNT_FILE},
    {"braveWalletImportAccountUploadButton",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_UPLOAD_BUTTON},
    {"braveWalletImportAccountUploadPlaceholder",
     IDS_BRAVE_WALLET_IMPORT_ACCOUNT_UPLOAD_PLACEHOLDER},
    {"braveWalletImportAccountError", IDS_BRAVE_WALLET_IMPORT_ACCOUNT_ERROR},
    {"braveWalletImportAccount", IDS_BRAVE_WALLET_IMPORT_ACCOUNT},
    {"braveWalletConnectHardwareTitle",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_TITLE},
    {"braveWalletConnectHardwareInfo1",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_INFO1},
    {"braveWalletConnectHardwareInfo2",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_INFO2},
    {"braveWalletConnectHardwareWrongApplicationUserHint",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_WRONG_APPLICATION_USER_HINT},
    {"braveWalletConnectHardwareTrezor",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_TREZOR},
    {"braveWalletConnectHardwareLedger",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_LEDGER},
    {"braveWalletConnectHardwareAuthorizationNeeded",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_AUTHORIZATION_NEEDED},
    {"braveWalletConnectingHardwareWallet",
     IDS_BRAVE_WALLET_CONNECTING_HARDWARE_WALLET},
    {"braveWalletAddCheckedAccountsHardwareWallet",
     IDS_BRAVE_WALLET_ADD_CHECKED_ACCOUNTS_HARDWARE_WALLET},
    {"braveWalletLoadMoreAccountsHardwareWallet",
     IDS_BRAVE_WALLET_LOAD_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"braveWalletLoadingMoreAccountsHardwareWallet",
     IDS_BRAVE_WALLET_LOADING_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"braveWalletSearchScannedAccounts",
     IDS_BRAVE_WALLET_SEARCH_SCANNED_ACCOUNTS},
    {"braveWalletSwitchHDPathTextHardwareWallet",
     IDS_BRAVE_WALLET_SWITCH_H_D_PATH_TEXT_HARDWARE_WALLET},
    {"braveWalletHDPath", IDS_BRAVE_WALLET_H_D_PATH},
    {"braveWalletLedgerLiveDerivationPath",
     IDS_BRAVE_WALLET_LEDGER_LIVE_DERIVATION_PATH},
    {"braveWalletLedgerLegacyDerivationPath",
     IDS_BRAVE_WALLET_LEDGER_LEGACY_DERIVATION_PATH},
    {"braveWalletConnectHardwareSearchNothingFound",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_SEARCH_NOTHING_FOUND},
    {"braveWalletAuthorizeHardwareWallet",
     IDS_BRAVE_WALLET_AUTHORIZE_HARDWARE_WALLET},
    {"braveWalletConnectHardwareWallet",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_WALLET},
    {"braveWallectConnectHardwareDescription",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_WALLET_DESCRIPTION},
    {"braveWalletImportHardwareWalletDescription",
     IDS_BRAVE_WALLET_IMPORT_HARDWARE_WALLET_DESCRIPTION},
    {"braveWalletConnectHardwareWalletSelectBlockchain",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_WALLET_SELECT_BLOCKCHAIN},
    {"braveWalletConnectHardwareDeviceDescription",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_DEVICE_DESCRIPTION},
    {"braveWalletUnknownInternalError",
     IDS_BRAVE_WALLET_UNKNOWN_INTERNAL_ERROR},
    {"braveWalletAccountSettingsDetails",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_DETAILS},
    {"braveWalletAccountSettingsWatchlist",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_WATCHLIST},
    {"braveWalletAccountSettingsPrivateKey",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_PRIVATE_KEY},
    {"braveWalletAccountSettingsSave", IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_SAVE},
    {"braveWalletAccountSettingsRemove",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_REMOVE},
    {"braveWalletWatchlistAddCustomAsset",
     IDS_BRAVE_WALLET_WATCHLIST_ADD_CUSTOM_ASSET},
    {"braveWalletWatchListTokenName", IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_NAME},
    {"braveWalletWatchListTokenAddress",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_ADDRESS},
    {"braveWalletWatchListTokenSymbol",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_SYMBOL},
    {"braveWalletWatchListTokenDecimals",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_DECIMALS},
    {"braveWalletWatchListAdd", IDS_BRAVE_WALLET_WATCH_LIST_ADD},
    {"braveWalletWatchListDoneButton", IDS_BRAVE_WALLET_WATCH_LIST_DONE_BUTTON},
    {"braveWalletWatchListNoAsset", IDS_BRAVE_WALLET_WATCH_LIST_NO_ASSET},
    {"braveWalletWatchListSearchPlaceholder",
     IDS_BRAVE_WALLET_WATCH_LIST_SEARCH_PLACEHOLDER},
    {"braveWalletWatchListError", IDS_BRAVE_WALLET_WATCH_LIST_ERROR},
    {"braveWalletCustomTokenExistsError",
     IDS_BRAVE_WALLET_CUSTOM_TOKEN_EXISTS_ERROR},
    {"braveWalletWatchListTokenId", IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_ID},
    {"braveWalletWatchListTokenIdError",
     IDS_BRAVE_WALLET_WATCH_LIST_TOKEN_ID_ERROR},
    {"braveWalletWatchListAdvanced", IDS_BRAVE_WALLET_WATCH_LIST_ADVANCED},
    {"braveWalletWatchListCoingeckoId",
     IDS_BRAVE_WALLET_WATCH_LIST_COINGECKO_ID},
    {"braveWalletIconURL", IDS_BRAVE_WALLET_ICON_URL},
    {"braveWalletAddAsset", IDS_BRAVE_WALLET_ADD_ASSET},
    {"braveWalletAccountsExport", IDS_BRAVE_WALLET_ACCOUNTS_EXPORT},
    {"braveWalletAccountsDeposit", IDS_BRAVE_WALLET_ACCOUNTS_DEPOSIT},
    {"braveWalletAccountsRemove", IDS_BRAVE_WALLET_ACCOUNTS_REMOVE},
    {"braveWalletAccountSettings", IDS_BRAVE_WALLET_ACCOUNT_SETTINGS},
    {"braveWalletNoAvailableAssets", IDS_BRAVE_WALLET_NO_AVAILABLE_ASSETS},
    {"braveWalletNoAvailableAssetsDescription",
     IDS_BRAVE_WALLET_NO_AVAILABLE_ASSETS_DESCRIPTION},
    {"braveWalletAccountSettingsDisclaimer",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_DISCLAIMER},
    {"braveWalletFilExportPrivateKeyFormatDescription",
     IDS_BRAVE_WALLET_FIL_EXPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"braveWalletFilImportPrivateKeyFormatDescription",
     IDS_BRAVE_WALLET_FIL_IMPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"braveWalletBtcImportPrivateKeyFormatDescription",
     IDS_BRAVE_WALLET_BTC_IMPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"braveWalletAccountSettingsShowKey",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_SHOW_KEY},
    {"braveWalletAccountSettingsHideKey",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_HIDE_KEY},
    {"braveWalletAccountSettingsUpdateError",
     IDS_BRAVE_WALLET_ACCOUNT_SETTINGS_UPDATE_ERROR},
    {"braveWalletPreset25", IDS_BRAVE_WALLET_PRESET25},
    {"braveWalletPreset50", IDS_BRAVE_WALLET_PRESET50},
    {"braveWalletPreset75", IDS_BRAVE_WALLET_PRESET75},
    {"braveWalletPreset100", IDS_BRAVE_WALLET_PRESET100},
    {"braveWalletUnsupportedNetwork", IDS_BRAVE_WALLET_UNSUPPORTED_NETWORK},
    {"braveWalletNetworkETH", IDS_BRAVE_WALLET_NETWORK_E_T_H},
    {"braveWalletNetworkMain", IDS_BRAVE_WALLET_NETWORK_MAIN},
    {"braveWalletNetworkTest", IDS_BRAVE_WALLET_NETWORK_TEST},
    {"braveWalletNetworkSepolia", IDS_BRAVE_WALLET_NETWORK_SEPOLIA},
    {"braveWalletNetworkLocalhost", IDS_BRAVE_WALLET_NETWORK_LOCALHOST},
    {"braveWalletSelectAccount", IDS_BRAVE_WALLET_SELECT_ACCOUNT},
    {"braveWalletSearchAccount", IDS_BRAVE_WALLET_SEARCH_ACCOUNT},
    {"braveWalletSelectNetwork", IDS_BRAVE_WALLET_SELECT_NETWORK},
    {"braveWalletSelectAsset", IDS_BRAVE_WALLET_SELECT_ASSET},
    {"braveWalletSearchAsset", IDS_BRAVE_WALLET_SEARCH_ASSET},
    {"braveWalletSwapFrom", IDS_BRAVE_WALLET_SWAP_FROM},
    {"braveWalletSwapTo", IDS_BRAVE_WALLET_SWAP_TO},
    {"braveWalletSwapEstimate", IDS_BRAVE_WALLET_SWAP_ESTIMATE},
    {"braveWalletSwapMarket", IDS_BRAVE_WALLET_SWAP_MARKET},
    {"braveWalletSwapLimit", IDS_BRAVE_WALLET_SWAP_LIMIT},
    {"braveWalletSwapPriceIn", IDS_BRAVE_WALLET_SWAP_PRICE_IN},
    {"braveWalletBuyTitle", IDS_BRAVE_WALLET_BUY_TITLE},
    {"braveWalletBuyDescription", IDS_BRAVE_WALLET_BUY_DESCRIPTION},
    {"braveWalletBuyContinueButton", IDS_BRAVE_WALLET_BUY_CONTINUE_BUTTON},
    {"braveWalletSignTransactionTitle",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_TITLE},
    {"braveWalletSignWarning", IDS_BRAVE_WALLET_SIGN_WARNING},
    {"braveWalletSignWarningTitle", IDS_BRAVE_WALLET_SIGN_WARNING_TITLE},
    {"braveWalletSignTransactionMessageTitle",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_MESSAGE_TITLE},
    {"braveWalletSignTransactionEIP712MessageDomain",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_DOMAIN},
    {"braveWalletSignTransactionEIP712MessageTitle",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_TITLE},
    {"braveWalletSignTransactionEIP712MessageHideDetails",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_HIDE_DETAILS},
    {"braveWalletSignTransactionButton",
     IDS_BRAVE_WALLET_SIGN_TRANSACTION_BUTTON},
    {"braveWalletProvideEncryptionKeyTitle",
     IDS_BRAVE_WALLET_PROVIDE_ENCRYPTION_KEY_TITLE},
    {"braveWalletProvideEncryptionKeyDescription",
     IDS_BRAVE_WALLET_PROVIDE_ENCRYPTION_KEY_DESCRIPTION},
    {"braveWalletProvideEncryptionKeyButton",
     IDS_BRAVE_WALLET_PROVIDE_ENCRYPTION_KEY_BUTTON},
    {"braveWalletReadEncryptedMessageTitle",
     IDS_BRAVE_WALLET_READ_ENCRYPTED_MESSAGE_TITLE},
    {"braveWalletReadEncryptedMessageDecryptButton",
     IDS_BRAVE_WALLET_READ_ENCRYPTED_MESSAGE_DECRYPT_BUTTON},
    {"braveWalletReadEncryptedMessageButton",
     IDS_BRAVE_WALLET_READ_ENCRYPTED_MESSAGE_BUTTON},
    {"braveWalletAllowSpendTitle", IDS_BRAVE_WALLET_ALLOW_SPEND_TITLE},
    {"braveWalletAllowSpendDescription",
     IDS_BRAVE_WALLET_ALLOW_SPEND_DESCRIPTION},
    {"braveWalletAllowSpendBoxTitle", IDS_BRAVE_WALLET_ALLOW_SPEND_BOX_TITLE},
    {"braveWalletAllowSpendTransactionFee",
     IDS_BRAVE_WALLET_ALLOW_SPEND_TRANSACTION_FEE},
    {"braveWalletAllowSpendEditButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_EDIT_BUTTON},
    {"braveWalletAllowSpendDetailsButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_DETAILS_BUTTON},
    {"braveWalletAllowSpendRejectButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_REJECT_BUTTON},
    {"braveWalletAllowSpendConfirmButton",
     IDS_BRAVE_WALLET_ALLOW_SPEND_CONFIRM_BUTTON},
    {"braveWalletAllowSpendCurrentAllowance",
     IDS_BRAVE_WALLET_ALLOW_SPEND_CURRENT_ALLOWANCE},
    {"braveWalletAllowSpendProposedAllowance",
     IDS_BRAVE_WALLET_ALLOW_SPEND_PROPOSED_ALLOWANCE},
    {"braveWalletAllowSpendUnlimitedWarningTitle",
     IDS_BRAVE_WALLET_ALLOW_SPEND_UNLIMITED_WARNING_TITLE},
    {"braveWalletAllowAddNetworkTitle",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_TITLE},
    {"braveWalletAllowChangeNetworkTitle",
     IDS_BRAVE_WALLET_ALLOW_CHANGE_NETWORK_TITLE},
    {"braveWalletAllowChangeNetworkDescription",
     IDS_BRAVE_WALLET_ALLOW_CHANGE_NETWORK_DESCRIPTION},
    {"braveWalletAllowChangeNetworkButton",
     IDS_BRAVE_WALLET_ALLOW_CHANGE_NETWORK_BUTTON},
    {"braveWalletAllowAddNetworkDescription",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_DESCRIPTION},
    {"braveWalletAllowAddNetworkLearnMoreButton",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_LEARN_MORE_BUTTON},
    {"braveWalletAllowAddNetworkName", IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_NAME},
    {"braveWalletAllowAddNetworkUrl", IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_URL},
    {"braveWalletAllowAddNetworkDetailsButton",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_DETAILS_BUTTON},
    {"braveWalletAllowAddNetworkButton",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_BUTTON},
    {"braveWalletChainId", IDS_BRAVE_WALLET_CHAIN_ID},
    {"braveWalletAllowAddNetworkCurrencySymbol",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_CURRENCY_SYMBOL},
    {"braveWalletAllowAddNetworkExplorer",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_EXPLORER},
    {"braveWalletAllowAddNetworkNetworkPanelTitle",
     IDS_BRAVE_WALLET_ALLOW_ADD_NETWORK_PANEL_TITLE},
    {"braveWalletAllowAddNetworkDetailsPanelTitle",
     IDS_BRAVE_WALLET_ALLOW_ADD_DETAILS_PANEL_TITLE},
    {"braveWalletConfirmTransactionTotal",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_TOTAL},
    {"braveWalletConfirmTransactionGasFee",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_GAS_FEE},
    {"braveWalletConfirmTransactionTransactionFee",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_TRANSACTION_FEE},
    {"braveWalletConfirmTransactionBid",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_BID},
    {"braveWalletConfirmTransactionAmountGas",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_AMOUNT_GAS},
    {"braveWalletConfirmTransactionAmountFee",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_AMOUNT_FEE},
    {"braveWalletConfirmTransactionNoData",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_NO_DATA},
    {"braveWalletConfirmTransactionNext",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_NEXT},
    {"braveWalletConfirmTransactionFirst",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_FIRST},
    {"braveWalletConfirmTransactions", IDS_BRAVE_WALLET_CONFIRM_TRANSACTIONS},
    {"braveWalletConfirmTransactionAccountCreationFee",
     IDS_BRAVE_WALLET_CONFIRM_TRANSACTION_ACCOUNT_CREATION_FEE},
    {"braveWalletTransactionGasLimit", IDS_BRAVE_WALLET_TRANSACTION_GAS_LIMIT},
    {"braveWalletTransactionGasPremium",
     IDS_BRAVE_WALLET_TRANSACTION_GAS_PREMIUM},
    {"braveWalletTransactionGasFeeCap",
     IDS_BRAVE_WALLET_TRANSACTION_GAS_FEE_CAP},
    {"braveWalletPanelTitle", IDS_BRAVE_WALLET_PANEL_TITLE},
    {"braveWalletPanelConnected", IDS_BRAVE_WALLET_PANEL_CONNECTED},
    {"braveWalletSitePermissionsAccounts",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_ACCOUNTS},
    {"braveWalletSitePermissionsDisconnect",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_DISCONNECT},
    {"braveWalletSitePermissionsSwitch",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_SWITCH},
    {"braveWalletSitePermissionsTrust",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_TRUST},
    {"braveWalletSitePermissionsRevoke",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_REVOKE},
    {"braveWalletChangeNetwork", IDS_BRAVE_WALLET_CHANGE_NETWORK},
    {"braveWalletChangeAccount", IDS_BRAVE_WALLET_CHANGE_ACCOUNT},
    {"braveWalletActive", IDS_BRAVE_WALLET_ACTIVE},
    {"braveWalletNotConnected", IDS_BRAVE_WALLET_NOT_CONNECTED},
    {"braveWalletConnectedAccounts", IDS_BRAVE_WALLET_CONNECTED_ACCOUNTS},
    {"braveWalletAvailableAccounts", IDS_BRAVE_WALLET_AVAILABLE_ACCOUNTS},
    {"braveWalletSitePermissionsNewAccount",
     IDS_BRAVE_WALLET_SITE_PERMISSIONS_NEW_ACCOUNT},
    {"braveWalletPanelBlocked", IDS_BRAVE_WALLET_PANEL_BLOCKED},
    {"braveWalletTitle", IDS_BRAVE_WALLET_TITLE},
    {"braveWalletWelcomePanelDescription",
     IDS_BRAVE_WALLET_WELCOME_PANEL_DESCRIPTION},
    {"braveWalletLearnMore", IDS_BRAVE_WALLET_LEARN_MORE},
    {"braveWalletTransactionDetailBoxFunction",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_BOX_FUNCTION},
    {"braveWalletTransactionDetailBoxHex",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_BOX_HEX},
    {"braveWalletTransactionDetailBoxBytes",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_BOX_BYTES},
    {"braveWalletConnectWithSiteNext", IDS_BRAVE_WALLET_CONNECT_WITH_SITE_NEXT},
    {"braveWalletConnectWallet", IDS_BRAVE_WALLET_CONNECT_WALLET},
    {"braveWalletConnectWithSite", IDS_BRAVE_WALLET_CONNECT_WITH_SITE},
    {"braveWalletConnectPermittedLabel",
     IDS_BRAVE_WALLET_CONNECT_PERMITTED_LABEL},
    {"braveWalletConnectNotPermittedLabel",
     IDS_BRAVE_WALLET_CONNECT_NOT_PERMITTED_LABEL},
    {"braveWalletConnectPermissionBalanceAndActivity",
     IDS_BRAVE_WALLET_CONNECT_PERMISSION_BALANCE_AND_ACTIVITY},
    {"braveWalletConnectPermissionRequestApproval",
     IDS_BRAVE_WALLET_CONNECT_PERMISSION_REQUEST_APPROVAL},
    {"braveWalletConnectPermissionAddress",
     IDS_BRAVE_WALLET_CONNECT_PERMISSION_ADDRESS},
    {"braveWalletConnectPermissionMoveFunds",
     IDS_BRAVE_WALLET_CONNECT_PERMISSION_MOVE_FUNDS},
    {"braveWalletConnectTrustWarning", IDS_BRAVE_WALLET_CONNECT_TRUST_WARNING},
    {"braveWalletPermissionDuration", IDS_BRAVE_WALLET_PERMISSION_DURATION},
    {"braveWalletPermissionUntilClose",
     IDS_BRAVE_WALLET_PERMISSION_UNTIL_CLOSE},
    {"braveWalletPermissionOneDay", IDS_BRAVE_WALLET_PERMISSION_ONE_DAY},
    {"braveWalletPermissionOneWeek", IDS_BRAVE_WALLET_PERMISSION_ONE_WEEK},
    {"braveWalletPermissionForever", IDS_BRAVE_WALLET_PERMISSION_FOREVER},
    {"braveWalletCryptoWalletsDetected",
     IDS_BRAVE_WALLET_CRYPTO_WALLETS_DETECTED},
    {"braveWalletLegacyWalletDetected",
     IDS_BRAVE_WALLET_LEGACY_WALLET_DETECTED},
    {"braveWalletCryptoWalletsDescriptionTwo",
     IDS_BRAVE_WALLET_CRYPTO_WALLETS_DESCRIPTION_TWO},
    {"braveWalletImportBraveLegacyDescription",
     IDS_BRAVE_WALLET_IMPORT_BRAVE_LEGACY_DESCRIPTION},
    {"braveWalletImportBraveLegacyInput",
     IDS_BRAVE_WALLET_IMPORT_BRAVE_LEGACY_INPUT},
    {"braveWalletConnectHardwarePanelConnected",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_CONNECTED},
    {"braveWalletConnectHardwarePanelDisconnected",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_DISCONNECTED},
    {"braveWalletConnectHardwarePanelInstructions",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_INSTRUCTIONS},
    {"braveWalletConnectHardwarePanelConnect",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_CONNECT},
    {"braveWalletConnectHardwarePanelConfirmation",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_CONFIRMATION},
    {"braveWalletConnectHardwarePanelOpenApp",
     IDS_BRAVE_WALLET_CONNECT_HARDWARE_PANEL_OPEN_APP},
    {"braveWalletTransactionSent", IDS_BRAVE_WALLET_TRANSACTION_SENT},
    {"braveWalletTransactionReceived", IDS_BRAVE_WALLET_TRANSACTION_RECEIVED},
    {"braveWalletTransactionExplorerMissing",
     IDS_BRAVE_WALLET_TRANSACTION_EXPLORER_MISSING},
    {"braveWalletTransactionExplorer", IDS_BRAVE_WALLET_TRANSACTION_EXPLORER},
    {"braveWalletTransactionCopyHash", IDS_BRAVE_WALLET_TRANSACTION_COPY_HASH},
    {"braveWalletTransactionSpeedup", IDS_BRAVE_WALLET_TRANSACTION_SPEEDUP},
    {"braveWalletTransactionCancel", IDS_BRAVE_WALLET_TRANSACTION_CANCEL},
    {"braveWalletTransactionRetry", IDS_BRAVE_WALLET_TRANSACTION_RETRY},
    {"braveWalletTransactionStatusUnapproved",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_UNAPPROVED},
    {"braveWalletTransactionStatusApproved",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_APPROVED},
    {"braveWalletTransactionStatusRejected",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_REJECTED},
    {"braveWalletTransactionStatusSubmitted",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_SUBMITTED},
    {"braveWalletTransactionStatusConfirmed",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_CONFIRMED},
    {"braveWalletTransactionStatusError",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_ERROR},
    {"braveWalletTransactionStatusDropped",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_DROPPED},
    {"braveWalletTransactionStatusSigned",
     IDS_BRAVE_WALLET_TRANSACTION_STATUS_SIGNED},
    {"braveWalletOn", IDS_BRAVE_WALLET_ON},
    {"braveWalletRecentTransactions", IDS_BRAVE_WALLET_RECENT_TRANSACTIONS},
    {"braveWalletTransactionDetailHash",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_HASH},
    {"braveWalletTransactionDetailNetwork",
     IDS_BRAVE_WALLET_TRANSACTION_DETAIL_NETWORK},
    {"braveWalletTransactionPlaceholder",
     IDS_BRAVE_WALLET_TRANSACTION_PLACEHOLDER},
    {"braveWalletTransactionApproveUnlimited",
     IDS_BRAVE_WALLET_TRANSACTION_APPROVE_UNLIMITED},
    {"braveWalletEditGasTitle1", IDS_BRAVE_WALLET_EDIT_GAS_TITLE1},
    {"braveWalletEditGasTitle2", IDS_BRAVE_WALLET_EDIT_GAS_TITLE2},
    {"braveWalletEditGasDescription", IDS_BRAVE_WALLET_EDIT_GAS_DESCRIPTION},
    {"braveWalletEditGasLow", IDS_BRAVE_WALLET_EDIT_GAS_LOW},
    {"braveWalletEditGasOptimal", IDS_BRAVE_WALLET_EDIT_GAS_OPTIMAL},
    {"braveWalletEditGasHigh", IDS_BRAVE_WALLET_EDIT_GAS_HIGH},
    {"braveWalletEditGasLimit", IDS_BRAVE_WALLET_EDIT_GAS_LIMIT},
    {"braveWalletEditGasPerGasPrice", IDS_BRAVE_WALLET_EDIT_GAS_PER_GAS_PRICE},
    {"braveWalletEditGasPerTipLimit", IDS_BRAVE_WALLET_EDIT_GAS_PER_TIP_LIMIT},
    {"braveWalletEditGasPerPriceLimit",
     IDS_BRAVE_WALLET_EDIT_GAS_PER_PRICE_LIMIT},
    {"braveWalletEditGasMaxFee", IDS_BRAVE_WALLET_EDIT_GAS_MAX_FEE},
    {"braveWalletEditGasMaximumFee", IDS_BRAVE_WALLET_EDIT_GAS_MAXIMUM_FEE},
    {"braveWalletEditGasBaseFee", IDS_BRAVE_WALLET_EDIT_GAS_BASE_FEE},
    {"braveWalletEditGasGwei", IDS_BRAVE_WALLET_EDIT_GAS_GWEI},
    {"braveWalletEditGasSetCustom", IDS_BRAVE_WALLET_EDIT_GAS_SET_CUSTOM},
    {"braveWalletEditGasSetSuggested", IDS_BRAVE_WALLET_EDIT_GAS_SET_SUGGESTED},
    {"braveWalletEditGasZeroGasPriceWarning",
     IDS_BRAVE_WALLET_EDIT_GAS_ZERO_GAS_PRICE_WARNING},
    {"braveWalletAdvancedTransactionSettings",
     IDS_BRAVE_WALLET_ADVANCED_TRANSACTION_SETTINGS},
    {"braveWalletAdvancedTransactionSettingsPlaceholder",
     IDS_BRAVE_WALLET_ADVANCED_TRANSACTION_SETTINGS_PLACEHOLDER},
    {"braveWalletEditNonce", IDS_BRAVE_WALLET_EDIT_NONCE},
    {"braveWalletEditNonceInfo", IDS_BRAVE_WALLET_EDIT_NONCE_INFO},
    {"braveWalletEditPermissionsTitle",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_TITLE},
    {"braveWalletEditPermissionsDescription",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_DESCRIPTION},
    {"braveWalletEditPermissionsButton",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_BUTTON},
    {"braveWalletEditPermissionsProposedAllowance",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_PROPOSED_ALLOWANCE},
    {"braveWalletEditPermissionsCustomAllowance",
     IDS_BRAVE_WALLET_EDIT_PERMISSIONS_CUSTOM_ALLOWANCE},
    {"braveWalletNotValidEthAddress", IDS_BRAVE_WALLET_NOT_VALID_ETH_ADDRESS},
    {"braveWalletNotValidSolAddress", IDS_BRAVE_WALLET_NOT_VALID_SOL_ADDRESS},
    {"braveWalletNotValidAddress", IDS_BRAVE_WALLET_NOT_VALID_ADDRESS},
    {"braveWalletNotDomain", IDS_BRAVE_WALLET_NOT_DOMAIN},
    {"braveWalletSameAddressError", IDS_BRAVE_WALLET_SAME_ADDRESS_ERROR},
    {"braveWalletContractAddressError",
     IDS_BRAVE_WALLET_CONTRACT_ADDRESS_ERROR},
    {"braveWalletFailedChecksumTitle", IDS_BRAVE_WALLET_FAILED_CHECKSUM_TITLE},
    {"braveWalletFailedChecksumDescription",
     IDS_BRAVE_WALLET_FAILED_CHECKSUM_DESCRIPTION},
    {"braveWalletHowToSolve", IDS_BRAVE_WALLET_HOW_TO_SOLVE},
    {"braveWalletAddressMissingChecksumInfoWarning",
     IDS_BRAVE_WALLET_ADDRESS_MISSING_CHECKSUM_INFO_WARNING},
    {"braveWalletNotValidChecksumAddressError",
     IDS_BRAVE_WALLET_NOT_VALID_CHECKSUM_ADDRESS_ERROR},
    {"braveWalletMissingGasLimitError",
     IDS_BRAVE_WALLET_MISSING_GAS_LIMIT_ERROR},
    {"braveWalletZeroBalanceError", IDS_BRAVE_WALLET_ZERO_BALANCE_ERROR},
    {"braveWalletAddressRequiredError",
     IDS_BRAVE_WALLET_ADDRESS_REQUIRED_ERROR},
    {"braveWalletInvalidZcashUnifiedRecipientAddress",
     IDS_BRAVE_WALLET_INVALID_ZCASH_UNIFIED_RECIPIENT_ADDRESS},
    {"braveWalletChecksumModalTitle", IDS_BRAVE_WALLET_CHECKSUM_MODAL_TITLE},
    {"braveWalletChecksumModalDescription",
     IDS_BRAVE_WALLET_CHECKSUM_MODAL_DESCRIPTION},
    {"braveWalletChecksumModalStepOneTitle",
     IDS_BRAVE_WALLET_CHECKSUM_MODAL_STEP_ONE_TITLE},
    {"braveWalletChecksumModalStepOneDescription",
     IDS_BRAVE_WALLET_CHECKSUM_MODAL_STEP_ONE_DESCRIPTION},
    {"braveWalletChecksumModalStepTwoTitle",
     IDS_BRAVE_WALLET_CHECKSUM_MODAL_STEP_TWO_TITLE},
    {"braveWalletChecksumModalStepTwoDescription",
     IDS_BRAVE_WALLET_CHECKSUM_MODAL_STEP_TWO_DESCRIPTION},
    {"braveWalletChecksumModalNeedHelp",
     IDS_BRAVE_WALLET_CHECKSUM_MODAL_NEED_HELP},
    {"braveWalletQueueOf", IDS_BRAVE_WALLET_QUEUE_OF},
    {"braveWalletQueueNext", IDS_BRAVE_WALLET_QUEUE_NEXT},
    {"braveWalletQueueFirst", IDS_BRAVE_WALLET_QUEUE_FIRST},
    {"braveWalletQueueRejectAll", IDS_BRAVE_WALLET_QUEUE_REJECT_ALL},
    {"braveWalletSwapInsufficientBalance",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_BALANCE},
    {"braveWalletSwapInsufficientFundsForGas",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_FUNDS_FOR_GAS},
    {"braveWalletSwapInsufficientLiquidity",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_LIQUIDITY},
    {"braveWalletSwapInsufficientAllowance",
     IDS_BRAVE_WALLET_SWAP_INSUFFICIENT_ALLOWANCE},
    {"braveWalletSwapUnknownError", IDS_BRAVE_WALLET_SWAP_UNKNOWN_ERROR},
    {"braveWalletSwapReviewSpend", IDS_BRAVE_WALLET_SWAP_REVIEW_SPEND},
    {"braveWalletSwapReviewReceive", IDS_BRAVE_WALLET_SWAP_REVIEW_RECEIVE},
    {"braveWalletSwapReviewHeader", IDS_BRAVE_WALLET_SWAP_REVIEW_HEADER},
    {"braveWalletSolanaSwap", IDS_BRAVE_WALLET_SOLANA_SWAP},
    {"braveWalletUnlockError", IDS_BRAVE_WALLET_UNLOCK_ERROR},
    {"braveWalletDeviceUnknownScheme", IDS_BRAVE_WALLET_UNKNOWN_SCHEME_ERROR},
    {"braveWalletApprovalTransactionIntent",
     IDS_BRAVE_WALLET_APPROVAL_TRANSACTION_INTENT},
    {"braveWalletNoAccountsWithABalance",
     IDS_BRAVE_WALLET_NO_ACCOUNTS_WITH_A_BALANCE},
    {"braveWalletNoAccountsWithABalanceDescription",
     IDS_BRAVE_WALLET_NO_ACCOUNTS_WITH_A_BALANCE_DESCRIPTION},
    {"braveWalletLedgerFilecoinUnlockError",
     IDS_BRAVE_WALLET_LEDGER_FILECOIN_UNLOCK_ERROR},
    {"braveWalletLedgerValidationError",
     IDS_BRAVE_WALLET_LEDGER_VALIDATION_ERROR},
    {"braveWalletHardwareAccountNotFound",
     IDS_BRAVE_WALLET_HARDWARE_ACCOUNT_NOT_FOUND_ERROR},
    {"braveWalletCreateBridgeError",
     IDS_BRAVE_WALLET_HARDWARE_CREATE_BRIDGE_ERROR},
    {"braveWalletProcessTransactionError",
     IDS_BRAVE_WALLET_HARDWARE_PROCESS_TRANSACTION_ERROR},
    {"braveWalletApproveTransactionError",
     IDS_BRAVE_WALLET_HARDWARE_APPROVE_TRANSACTION_ERROR},
    {"braveWalletTransactionNotFoundSignError",
     IDS_BRAVE_WALLET_HARDWARE_TRANSACTION_NOT_FOUND_ERROR},
    {"braveWalletSignOnDeviceError",
     IDS_BRAVE_WALLET_HARDWARE_TRANSACTION_DEVICE_ERROR},
    {"braveWalletNoMessageToSignError",
     IDS_BRAVE_WALLET_HARDWARE_TRANSACTION_NO_MESSAGE_TO_SIGN_ERROR},
    {"braveWalletProcessMessageError",
     IDS_BRAVE_WALLET_HARDWARE_SIGN_MESSAGE_ERROR},
    {"braveWalletHardwareOperationUnsupportedError",
     IDS_BRAVE_WALLET_HARDWARE_OPERATION_UNSUPPORTED_ERROR},
    {"braveWalletUnknownKeyringError",
     IDS_BRAVE_WALLET_HARDWARE_UNKNOWN_KEYRING_ERROR},
    {"braveWalletBridgeCommandInProgress",
     IDS_BRAVE_WALLET_HARDWARE_COMMAND_IN_PROGRESS_ERROR},
    {"braveWalletBridgeNotReady",
     IDS_BRAVE_WALLET_HARDWARE_BRIDGE_NOT_READY_ERROR},
    {"braveWalletAddSuggestedTokenTitle",
     IDS_BRAVE_WALLET_ADD_SUGGESTED_TOKEN_TITLE},
    {"braveWalletAddSuggestedTokenDescription",
     IDS_BRAVE_WALLET_ADD_SUGGESTED_TOKEN_DESCRIPTION},
    {"braveWalletNFTDetailBlockchain", IDS_BRAVE_WALLET_NFT_DETAIL_BLOCKCHAIN},
    {"braveWalletNFTDetailTokenStandard",
     IDS_BRAVE_WALLET_NFT_DETAIL_TOKEN_STANDARD},
    {"braveWalletNFTDetailTokenID", IDS_BRAVE_WALLET_NFT_DETAIL_TOKEN_ID},
    {"braveWalletNFTDetailContractAddress",
     IDS_BRAVE_WALLET_NFT_DETAIL_CONTRACT_ADDRESS},
    {"braveWalletNFTDetailDescription",
     IDS_BRAVE_WALLET_NFT_DETAIL_DESCRIPTION},
    {"braveWalletNFTDetailImageAddress",
     IDS_BRAVE_WALLET_NFT_DETAIL_IMAGE_ADDRESS},
    {"braveWalletNFTDetailsOverview", IDS_BRAVE_WALLET_NFT_DETAILS_OVERVIEW},
    {"braveWalletNFTDetailsOwnedBy", IDS_BRAVE_WALLET_NFT_DETAILS_OWNED_BY},
    {"braveWalletNFTDetailsViewAccount",
     IDS_BRAVE_WALLET_NFT_DETAILS_VIEW_ACCOUNT},
    {"braveWalletNFTDetailsPinningStatusLabel",
     IDS_BRAVE_WALLET_NFT_DETAILS_PINNING_STATUS_LABEL},
    {"braveWalletNFTDetailsCid", IDS_BRAVE_WALLET_NFT_DETAILS_CID},
    {"braveWalletNFTDetailsNotAvailable",
     IDS_BRAVE_WALLET_NFT_DETAILS_NOT_AVAILABLE},
    {"braveWalletNFTDetailsProperties",
     IDS_BRAVE_WALLET_NFT_DETAILS_PROPERTIES},
    {"braveWalletTrezorSignTypedDataError",
     IDS_BRAVE_WALLET_TREZOR_SIGN_TYPED_DATA_ERROR},
    {"braveWalletSweepstakesTitle", IDS_BRAVE_WALLET_SWEEPSTAKES_TITLE},
    {"braveWalletSweepstakesDescription",
     IDS_BRAVE_WALLET_SWEEPSTAKES_DESCRIPTION},
    {"braveWalletSweepstakesCallToAction",
     IDS_BRAVE_WALLET_SWEEPSTAKES_CALL_TO_ACTION},
    {"braveWalletNotValidFilAddress", IDS_BRAVE_WALLET_NOT_VALID_FIL_ADDRESS},
    {"braveWalletBuyWithRamp", IDS_BRAVE_WALLET_BUY_WITH_RAMP},
    {"braveWalletSellWithProvider", IDS_BRAVE_WALLET_SELL_WITH_PROVIDER},
    {"braveWalletBuyDisclaimer", IDS_BRAVE_WALLET_BUY_DISCLAIMER},
    {"braveWalletBuyWithSardine", IDS_BRAVE_WALLET_BUY_WITH_SARDINE},
    {"braveWalletBuyWithTransak", IDS_BRAVE_WALLET_BUY_WITH_TRANSAK},
    {"braveWalletBuyWithStripe", IDS_BRAVE_WALLET_BUY_WITH_STRIPE},
    {"braveWalletBuyWithCoinbase", IDS_BRAVE_WALLET_BUY_WITH_COINBASE},
    {"braveWalletBuyRampNetworkName", IDS_BRAVE_WALLET_BUY_RAMP_NETWORK_NAME},
    {"braveWalletBuySardineName", IDS_BRAVE_WALLET_BUY_SARDINE_NAME},
    {"braveWalletBuyTransakName", IDS_BRAVE_WALLET_BUY_TRANSAK_NAME},
    {"braveWalletBuyStripeName", IDS_BRAVE_WALLET_BUY_STRIPE_NAME},
    {"braveWalletBuyCoinbaseName", IDS_BRAVE_WALLET_BUY_COINBASE_NAME},
    {"braveWalletBuyRampDescription", IDS_BRAVE_WALLET_BUY_RAMP_DESCRIPTION},
    {"braveWalletBuySardineDescription",
     IDS_BRAVE_WALLET_BUY_SARDINE_DESCRIPTION},
    {"braveWalletBuyTransakDescription",
     IDS_BRAVE_WALLET_BUY_TRANSAK_DESCRIPTION},
    {"braveWalletBuyStripeDescription",
     IDS_BRAVE_WALLET_BUY_STRIPE_DESCRIPTION},
    {"braveWalletBuyCoinbaseDescription",
     IDS_BRAVE_WALLET_BUY_COINBASE_DESCRIPTION},
    {"braveWalletNetworkFilterAll", IDS_BRAVE_WALLET_NETWORK_FILTER_ALL},
    {"braveWalletAssetFilterLowToHigh",
     IDS_BRAVE_WALLET_ASSET_FILTER_LOW_TO_HIGH},
    {"braveWalletAssetFilterHighToLow",
     IDS_BRAVE_WALLET_ASSET_FILTER_HIGH_TO_LOW},
    {"braveWalletAssetFilterAToZ", IDS_BRAVE_WALLET_ASSET_FILTER_A_TO_Z},
    {"braveWalletAssetFilterZToA", IDS_BRAVE_WALLET_ASSET_FILTER_Z_TO_A},
    {"braveWalletNone", IDS_BRAVE_WALLET_NONE},
    {"braveWalletNetworks", IDS_BRAVE_WALLET_NETWORKS},
    {"braveWalletPortfolioGroupByTitle",
     IDS_BRAVE_WALLET_PORTFOLIO_GROUP_BY_TITLE},
    {"braveWalletPortfolioGroupByDescription",
     IDS_BRAVE_WALLET_PORTFOLIO_GROUP_BY_DESCRIPTION},
    {"braveWalletPortfolioFiltersTitle",
     IDS_BRAVE_WALLET_PORTFOLIO_FILTERS_TITLE},
    {"braveWalletPortfolioNftsFiltersTitle",
     IDS_BRAVE_WALLET_PORTFOLIO_NFTS_FILTERS_TITLE},
    {"braveWalletSortAssets", IDS_BRAVE_WALLET_SORT_ASSETS},
    {"braveWalletSortAssetsDescription",
     IDS_BRAVE_WALLET_SORT_ASSETS_DESCRIPTION},
    {"braveWalletHideSmallBalances", IDS_BRAVE_WALLET_SMALL_BALANCES},
    {"braveWalletHideSmallBalancesDescription",
     IDS_BRAVE_WALLET_SMALL_BALANCES_DESCRIPTION},
    {"braveWalletSelectAccounts", IDS_BRAVE_WALLET_SELECT_ACCOUNTS},
    {"braveWalletSelectNetworks", IDS_BRAVE_WALLET_SELECT_NETWORKS},
    {"braveWalletSelectAll", IDS_BRAVE_WALLET_SELECT_ALL},
    {"braveWalletDeselectAll", IDS_BRAVE_WALLET_DESELECT_ALL},
    {"braveWalletPrimaryNetworks", IDS_BRAVE_WALLET_PRIMARY_NETWORKS},
    {"braveWalletETHAccountDescription",
     IDS_BRAVE_WALLET_ETH_ACCOUNT_DESCRIPTION},
    {"braveWalletSOLAccountDescription",
     IDS_BRAVE_WALLET_SOL_ACCOUNT_DESCRIPTION},
    {"braveWalletFILAccountDescription",
     IDS_BRAVE_WALLET_FIL_ACCOUNT_DESCRIPTION},
    {"braveWalletBTCMainnetAccountDescription",
     IDS_BRAVE_WALLET_BTC_MAINNET_ACCOUNT_DESCRIPTION},
    {"braveWalletBTCTestnetAccountDescription",
     IDS_BRAVE_WALLET_BTC_TESTNET_ACCOUNT_DESCRIPTION},
    {"braveWalletZECAccountDescription",
     IDS_BRAVE_WALLET_ZEC_ACCOUNT_DESCRIPTION},
    {"braveWalletZECTestnetAccountDescription",
     IDS_BRAVE_WALLET_ZEC_TESTNET_ACCOUNT_DESCRIPTION},
    {"braveWalletShowNetworkLogoOnNftsTitle",
     IDS_BRAVE_WALLET_SHOW_NETWORK_LOGO_ON_NFTS_TITLE},
    {"braveWalletShowNetworkLogoOnNftsDescription",
     IDS_BRAVE_WALLET_SHOW_NETWORK_LOGO_ON_NFTS_DESCRIPTION},
    {"braveWalletShowSpamNftsTitle", IDS_BRAVE_WALLET_SHOW_SPAM_NFTS_TITLE},
    {"braveWalletShowSpamNftsDescription",
     IDS_BRAVE_WALLET_SHOW_SPAM_NFTS_DESCRIPTION},
    {"braveWalletPortfolioSettings", IDS_BRAVE_WALLET_PORTFOLIO_SETTINGS},
    {"braveWalletAccountFilterAllAccounts",
     IDS_BRAVE_WALLET_ACCOUNT_FILTER_ALL_ACCOUNTS},
    {"braveWalletTransactionSubmittedTitle",
     IDS_BRAVE_WALLET_TRANSACTION_SUBMITTED_TITLE},
    {"braveWalletTransactionSubmittedDescription",
     IDS_BRAVE_WALLET_TRANSACTION_SUBMITTED_DESCRIPTION},
    {"braveWalletTransactionSignedTitle",
     IDS_BRAVE_WALLET_TRANSACTION_SIGNED_TITLE},
    {"braveWalletTransactionSignedDescription",
     IDS_BRAVE_WALLET_TRANSACTION_SIGNED_DESCRIPTION},
    {"braveWalletTransactionFailedHeaderTitle",
     IDS_BRAVE_WALLET_TRANSACTION_FAILED_HEADER_TITLE},
    {"braveWalletTransactionFailedTitle",
     IDS_BRAVE_WALLET_TRANSACTION_FAILED_TITLE},
    {"braveWalletTransactionFailedDescription",
     IDS_BRAVE_WALLET_TRANSACTION_FAILED_DESCRIPTION},
    {"braveWalletTransactionFailedSwapNextCTA",
     IDS_BRAVE_WALLET_TRANSACTION_FAILED_SWAP_NEXT_CTA},
    {"braveWalletTransactionFailedNextCTA",
     IDS_BRAVE_WALLET_TRANSACTION_FAILED_NEXT_CTA},
    {"braveWalletTransactionFailedViewErrorCTA",
     IDS_BRAVE_WALLET_TRANSACTION_FAILED_VIEW_ERROR_CTA},
    {"braveWalletTransactionFailedReceiptCTA",
     IDS_BRAVE_WALLET_TRANSACTION_FAILED_RECEIPT_CTA},
    {"braveWalletTransactionFailedModalTitle",
     IDS_BRAVE_WALLET_TRANSACTION_FAILED_MODAL_TITLE},
    {"braveWalletTransactionFailedModalSubtitle",
     IDS_BRAVE_WALLET_TRANSACTION_FAILED_MODAL_SUBTITLE},
    {"braveWalletTransactionCompleteSwapHeaderTitle",
     IDS_BRAVE_WALLET_TRANSACTION_COMPLETE_SWAP_HEADER_TITLE},
    {"braveWalletTransactionCompleteTitle",
     IDS_BRAVE_WALLET_TRANSACTION_COMPLETE_TITLE},
    {"braveWalletTransactionCompleteDescription",
     IDS_BRAVE_WALLET_TRANSACTION_COMPLETE_DESCRIPTION},
    {"braveWalletTransactionCompleteReceiptCTA",
     IDS_BRAVE_WALLET_TRANSACTION_COMPLETE_RECEIPT_CTA},
    {"braveWalletTransactionConfirmingTitle",
     IDS_BRAVE_WALLET_TRANSACTION_CONFIRMING_TITLE},
    {"braveWalletTransactionConfirmingDescription",
     IDS_BRAVE_WALLET_TRANSACTION_CONFIRMING_DESCRIPTION},
    {"braveWalletTransactionConfirmingText",
     IDS_BRAVE_WALLET_TRANSACTION_CONFIRMING_TEXT},
    {"braveWalletTransactionIntentDappInteraction",
     IDS_BRAVE_WALLET_TRANSACTION_INTENT_DAPP_INTERACTION},
    {"braveWalletTransactionIntentSend",
     IDS_BRAVE_WALLET_TRANSACTION_INTENT_SEND},
    {"braveWalletTransactionIntentSwap",
     IDS_BRAVE_WALLET_TRANSACTION_INTENT_SWAP},
    {"braveWalletSignInWithBraveWallet",
     IDS_BRAVE_WALLET_SIGN_IN_WITH_BRAVE_WALLET},
    {"braveWalletSignInWithBraveWalletMessage",
     IDS_BRAVE_WALLET_SIGN_IN_WITH_BRAVE_WALLET_MESSAGE},
    {"braveWalletSeeDetails", IDS_BRAVE_WALLET_SEE_DETAILS},
    {"braveWalletSignIn", IDS_BRAVE_WALLET_SIGN_IN},
    {"braveWalletOrigin", IDS_BRAVE_WALLET_ORIGIN},
    {"braveWalletAddress", IDS_BRAVE_WALLET_ADDRESS},
    {"braveWalletStatement", IDS_BRAVE_WALLET_STATEMENT},
    {"braveWalletUri", IDS_BRAVE_WALLET_URI},
    {"braveWalletVersion", IDS_BRAVE_WALLET_VERSION},
    {"braveWalletNonce", IDS_BRAVE_WALLET_NONCE},
    {"braveWalletIssuedAt", IDS_BRAVE_WALLET_ISSUED_AT},
    {"braveWalletExpirationTime", IDS_BRAVE_WALLET_EXPIRATION_TIME},
    {"braveWalletNotBefore", IDS_BRAVE_WALLET_NOT_BEFORE},
    {"braveWalletRequestId", IDS_BRAVE_WALLET_REQUEST_ID},
    {"braveWalletResources", IDS_BRAVE_WALLET_RESOURCES},
    {"braveWalletSecurityRiskDetected",
     IDS_BRAVE_WALLET_SECURITY_RISK_DETECTED},
    {"braveWalletEditGasLimitError", IDS_BRAVE_WALLET_EDIT_GAS_LIMIT_ERROR},
    {"braveWalletApproveTransaction", IDS_BRAVE_WALLET_APPROVE_TRANSACTION},
    {"braveWalletSolanaSystemProgram", IDS_BRAVE_WALLET_SOLANA_SYSTEM_PROGRAM},
    {"braveWalletSolanaConfigProgram", IDS_BRAVE_WALLET_SOLANA_CONFIG_PROGRAM},
    {"braveWalletSolanaStakeProgram", IDS_BRAVE_WALLET_SOLANA_STAKE_PROGRAM},
    {"braveWalletSolanaVoteProgram", IDS_BRAVE_WALLET_SOLANA_VOTE_PROGRAM},
    {"braveWalletSolanaBPFLoader", IDS_BRAVE_WALLET_SOLANA_BP_FLOADER},
    {"braveWalletSolanaAccounts", IDS_BRAVE_WALLET_SOLANA_ACCOUNTS},
    {"braveWalletSolanaData", IDS_BRAVE_WALLET_SOLANA_DATA},
    {"braveWalletSolanaProgramID", IDS_BRAVE_WALLET_SOLANA_PROGRAM_ID},
    {"braveWalletSolanaMaxRetries", IDS_BRAVE_WALLET_SOLANA_MAX_RETRIES},
    {"braveWalletSolanaPreflightCommitment",
     IDS_BRAVE_WALLET_SOLANA_PREFLIGHT_COMMITMENT},
    {"braveWalletSolanaSkipPreflight", IDS_BRAVE_WALLET_SOLANA_SKIP_PREFLIGHT},
    {"braveWalletSolanaAddressLookupTableAccount",
     IDS_BRAVE_WALLET_SOLANA_ADDRESS_LOOKUP_TABLE_ACCOUNT},
    {"braveWalletSolanaAddressLookupTableIndex",
     IDS_BRAVE_WALLET_SOLANA_ADDRESS_LOOKUP_TABLE_INDEX},
    {"braveWalletSolanaEd25519Program",
     IDS_BRAVE_WALLET_SOLANA_ED25519_PROGRAM},
    {"braveWalletSolanaSecp256k1Program",
     IDS_BRAVE_WALLET_SOLANA_SECP256K1_PROGRAM},
    {"braveWalletNetworkFilterSecondary",
     IDS_BRAVE_WALLET_NETWORK_FILTER_SECONDARY},
    {"braveWalletNetworkFilterTestNetworks",
     IDS_BRAVE_WALLET_NETWORK_FILTER_TEST_NETWORKS},
    {"braveWalletSelectCurrency", IDS_BRAVE_WALLET_SELECT_CURRENCY},
    {"braveWalletSearchCurrency", IDS_BRAVE_WALLET_SEARCH_CURRENCY},
    {"braveWalletHelpCenter", IDS_BRAVE_WALLET_HELP_CENTER},
    {"braveWalletHelpCenterText", IDS_BRAVE_WALLET_HELP_CENTER_TEXT},
    {"braveWalletBuyTapBuyNotSupportedMessage",
     IDS_BRAVE_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"braveWalletAuroraModalTitle", IDS_BRAVE_WALLET_AURORA_MODAL_TITLE},
    {"braveWalletAuroraModalDescription",
     IDS_BRAVE_WALLET_AURORA_MODAL_DESCRIPTION},
    {"braveWalletAuroraModalLearnMore",
     IDS_BRAVE_WALLET_AURORA_MODAL_LEARN_MORE},
    {"braveWalletAuroraModalLearnMoreAboutRisk",
     IDS_BRAVE_WALLET_AURORA_MODAL_LEARN_MORE_ABOUT_RISK},
    {"braveWalletAuroraModalDontShowAgain",
     IDS_BRAVE_WALLET_AURORA_MODAL_DONT_SHOW_AGAIN},
    {"braveWalletAuroraModalOPenButtonText",
     IDS_BRAVE_WALLET_AURORA_MODAL_OPEN_BUTTON_TEXT},
    {"braveWalletBridgeToAuroraButton",
     IDS_BRAVE_WALLET_BRIDGE_TO_AURORA_BUTTON},
    {"braveWalletPasswordStrengthTooltipHeading",
     IDS_BRAVE_WALLET_PASSWORD_STRENGTH_TOOLTIP_HEADING},
    {"braveWalletPasswordStrengthTooltipIsLongEnough",
     IDS_BRAVE_WALLET_PASSWORD_STRENGTH_TOOLTIP_IS_LONG_ENOUGH},
    {"braveWalletPasswordMatch", IDS_BRAVE_WALLET_PASSWORD_MATCH},
    {"braveWalletPasswordIsStrong", IDS_BRAVE_WALLET_PASSWORD_IS_STRONG},
    {"braveWalletPasswordIsMediumStrength",
     IDS_BRAVE_WALLET_PASSWORD_IS_MEDIUM_STRENGTH},
    {"braveWalletPasswordIsWeak", IDS_BRAVE_WALLET_PASSWORD_IS_WEAK},
    {"braveWalletAutoLockTitle", IDS_BRAVE_WALLET_AUTO_LOCK_TITLE},
    {"braveWalletAutoLockDurationMinutes",
     IDS_BRAVE_WALLET_AUTO_LOCK_DURATION_MINUTES},
    {"braveWalletAutoLockDurationHours",
     IDS_BRAVE_WALLET_AUTO_LOCK_DURATION_HOURS},
    {"braveWalletCreatingWallet", IDS_BRAVE_WALLET_CREATING_WALLET},
    {"braveWalletOnboardingRecoveryPhraseBackupIntroTitle",
     IDS_BRAVE_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_TITLE},
    {"braveWalletOnboardingRecoveryPhraseBackupIntroDescription",
     IDS_BRAVE_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_DESCRIPTION},
    {"braveWalletRecoveryPhraseBackupWarning",
     IDS_BRAVE_WALLET_RECOVERY_PHRASE_BACKUP_WARNING},
    {"braveWalletRecoveryPhraseBackupWarningImportant",
     IDS_BRAVE_WALLET_RECOVERY_PHRASE_BACKUP_WARNING_IMPORTANT},
    {"braveWalletRecoveryWordInstructions",
     IDS_BRAVE_WALLET_RECOVERY_WORD_INSTRUCTIONS},
    {"braveWalletVerifyRecoveryPhraseGoBack",
     IDS_BRAVE_WALLET_VERIFY_RECOVERY_PHRASE_GO_BACK},
    {"braveWalletRecoveryPhraseBackupTitle",
     IDS_BRAVE_WALLET_RECOVERY_PHRASE_BACKUP_TITLE},
    {"braveWalletCopiedToClipboard", IDS_BRAVE_WALLET_COPIED_TO_CLIPBOARD},
    {"braveWalletClickToSeeRecoveryPhrase",
     IDS_BRAVE_WALLET_CLICK_TO_SEE_RECOVERY_PHRASE},
    {"braveWalletOrdinalFirst", IDS_BRAVE_WALLET_ORDINAL_FIRST},
    {"braveWalletOrdinalThird", IDS_BRAVE_WALLET_ORDINAL_THIRD},
    {"braveWalletOnboardingSuccessTitle",
     IDS_BRAVE_WALLET_ONBOARDING_SUCCESS_TITLE},
    {"braveWalletOnboardingSuccessDescription",
     IDS_BRAVE_WALLET_ONBOARDING_SUCCESS_DESCRIPTION},
    {"braveWalletOnboardingSuccessGoToPortfolio",
     IDS_BRAVE_WALLET_ONBOARDING_SUCCESS_GO_TO_PORTFOLIO},
    {"braveWalletArticleLinkWhatsARecoveryPhrase",
     IDS_BRAVE_WALLET_ARTICLE_LINK_WHATS_A_RECOVERY_PHRASE},
    {"braveWalletImportOrRestoreWalletTitle",
     IDS_BRAVE_WALLET_IMPORT_OR_RESTORE_WALLET_TITLE},
    {"braveWalletImportOrRestoreDescription",
     IDS_BRAVE_WALLET_IMPORT_OR_RESTORE_DESCRIPTION},
    {"braveWalletRestoreMyBraveWallet",
     IDS_BRAVE_WALLET_RESTORE_MY_BRAVE_WALLET},
    {"braveWalletRestoreMyBraveWalletInstructions",
     IDS_BRAVE_WALLET_RESTORE_MY_BRAVE_WALLET_INSTRUCTIONS},
    {"braveWalletRestoreMyBraveWalletDescription",
     IDS_BRAVE_WALLET_RESTORE_MY_BRAVE_WALLET_DESCRIPTION},
    {"braveWalletImportFromMetaMask", IDS_BRAVE_WALLET_IMPORT_FROM_META_MASK},
    {"braveWalletImportFromMetaMaskDescription",
     IDS_BRAVE_WALLET_IMPORT_FROM_META_MASK_DESCRIPTION},
    {"braveWalletImportFromMetaMaskSeedInstructions",
     IDS_BRAVE_WALLET_IMPORT_FROM_META_MASK_SEED_INSTRUCTIONS},
    {"braveWalletCreateWalletInsteadLink",
     IDS_BRAVE_WALLET_CREATE_WALLET_INSTEAD_LINK},
    {"braveWalletRestoreAlternateLength",
     IDS_BRAVE_WALLET_RESTORE_ALTERNATE_LENGTH},
    {"braveWalletRestoreWalletError", IDS_BRAVE_WALLET_RESTORE_WALLET_ERROR},
    {"braveWalletImportWithRecoveryPhrase",
     IDS_BRAVE_WALLET_IMPORT_WITH_RECOVERY_PHRASE},
    {"braveWalletMetamaskDetected", IDS_BRAVE_WALLET_METAMASK_DETECTED},
    {"braveWalletUsePassword", IDS_BRAVE_WALLET_USE_PASSWORD},
    {"braveWalletRecoveryPhraseWord", IDS_BRAVE_WALLET_RECOVERY_PHRASE_WORD},
    {"braveWalletImportPasswordError", IDS_BRAVE_WALLET_IMPORT_PASSWORD_ERROR},
    {"braveWalletMetaMaskExtensionDetected",
     IDS_BRAVE_WALLET_METAMASK_EXTENSION_DETECTED},
    {"braveWalletMetaMaskExtensionImportDescription",
     IDS_BRAVE_WALLET_METAMASK_EXTENSION_IMPORT_DESCRIPTION},
    {"braveWalletMetaMaskPasswordInputPlaceholder",
     IDS_BRAVE_WALLET_METAMASK_PASSWORD_INPUT_PLACEHOLDER},
    {"braveWalletInputLabelPassword", IDS_BRAVE_WALLET_INPUT_LABEL_PASSWORD},
    {"braveWalletLearnAboutMyWallet", IDS_BRAVE_WALLET_LEARN_ABOUT_MY_WALLET},
    {"braveWalletDisclosuresTitle", IDS_BRAVE_WALLET_DISCLOSURES_TITLE},
    {"braveWalletDisclosuresDescription",
     IDS_BRAVE_WALLET_DISCLOSURES_DESCRIPTION},
    {"braveWalletSelfCustodyDisclosureCheckboxText",
     IDS_BRAVE_WALLET_SELF_CUSTODY_DISCLOSURE_CHECKBOX_TEXT},
    {"braveWalletTermsOfServiceCheckboxText",
     IDS_BRAVE_WALLET_TERMS_OF_SERVICE_CHECKBOX_TEXT},
    {"braveWalletBuyCryptoButton", IDS_BRAVE_WALLET_BUY_CRYPTO_BUTTON},
    {"braveWalletDepositCryptoButton", IDS_BRAVE_WALLET_DEPOSIT_CRYPTO_BUTTON},
    {"braveWalletCheckingInstalledExtensions",
     IDS_BRAVE_WALLET_CHECKING_INSTALLED_EXTENSIONS},
    {"braveWalletImportFromLegacy", IDS_BRAVE_WALLET_IMPORT_FROM_LEGACY},
    {"braveWalletBuySelectAsset", IDS_BRAVE_WALLET_BUY_SELECT_ASSET},
    {"braveWalletFundWalletTitle", IDS_BRAVE_WALLET_FUND_WALLET_TITLE},
    {"braveWalletDepositFundsTitle", IDS_BRAVE_WALLET_DEPOSIT_FUNDS_TITLE},
    {"braveWalletDepositX", IDS_BRAVE_WALLET_DEPOSIT_X},
    {"braveWalletDepositSolSplTokens", IDS_BRAVE_WALLET_DEPOSIT_SOL_SPL_TOKENS},
    {"braveWalletDepositErc", IDS_BRAVE_WALLET_DEPOSIT_ERC},
    {"braveWalletDepositOnlySendOnXNetwork",
     IDS_BRAVE_WALLET_DEPOSIT_ONLY_SEND_ON_X_NETWORK},
    {"braveWalletFundWalletDescription",
     IDS_BRAVE_WALLET_FUND_WALLET_DESCRIPTION},
    {"braveWalletLearnMoreAboutBraveWallet",
     IDS_BRAVE_WALLET_LEARN_MORE_ABOUT_BRAVE_WALLET},
    {"braveWalletMarketDataAllAssetsFilter",
     IDS_BRAVE_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"braveWalletMarketDataTradableFilter",
     IDS_BRAVE_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"braveWalletMarketDataAssetsColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"braveWalletMarketDataPriceColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"braveWalletMarketData24HrColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"braveWalletMarketDataMarketCapColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"braveWalletMarketDataVolumeColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"braveWalletMarketDataNoAssetsFound",
     IDS_BRAVE_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"braveWalletInformation", IDS_BRAVE_WALLET_INFORMATION},
    {"braveWalletRankStat", IDS_BRAVE_WALLET_RANK_STAT},
    {"braveWalletVolumeStat", IDS_BRAVE_WALLET_VOLUME_STAT},
    {"braveWalletMarketCapStat", IDS_BRAVE_WALLET_MARKET_CAP_STAT},
    {"braveWalletBuyTapBuyNotSupportedMessage",
     IDS_BRAVE_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"braveWalletHelpCenterText", IDS_BRAVE_WALLET_HELP_CENTER_TEXT},
    {"braveWalletMarketDataAllAssetsFilter",
     IDS_BRAVE_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"braveWalletMarketDataTradableFilter",
     IDS_BRAVE_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"braveWalletMarketDataAssetsColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"braveWalletMarketDataPriceColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"braveWalletMarketData24HrColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"braveWalletMarketDataMarketCapColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"braveWalletMarketDataVolumeColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"braveWalletMarketDataBuyDepositColumn",
     IDS_BRAVE_WALLET_MARKET_DATA_BUY_DEPOSIT_COLUMN},
    {"braveWalletMarketDataNoAssetsFound",
     IDS_BRAVE_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"braveWalletInformation", IDS_BRAVE_WALLET_INFORMATION},
    {"braveWalletRankStat", IDS_BRAVE_WALLET_RANK_STAT},
    {"braveWalletVolumeStat", IDS_BRAVE_WALLET_VOLUME_STAT},
    {"braveWalletMarketCapStat", IDS_BRAVE_WALLET_MARKET_CAP_STAT},
    {"braveWalletBuyTapBuyNotSupportedMessage",
     IDS_BRAVE_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"braveWalletSearchingForDomain", IDS_BRAVE_WALLET_SEARCHING_FOR_DOMAIN},
    {"braveWalletEnsOffChainLookupTitle",
     IDS_BRAVE_WALLET_ENS_OFF_CHAIN_LOOKUP_TITLE},
    {"braveWalletEnsOffChainLookupDescription",
     IDS_BRAVE_WALLET_ENS_OFF_CHAIN_LOOKUP_DESCRIPTION},
    {"braveWalletEnsOffChainButton", IDS_BRAVE_WALLET_ENS_OFF_CHAIN_BUTTON},
    {"braveWalletPortfolioTokenDetailsMenuLabel",
     IDS_BRAVE_WALLET_PORTFOLIO_TOKEN_DETAILS_MENU_LABEL},
    {"braveWalletPortfolioViewOnExplorerMenuLabel",
     IDS_BRAVE_WALLET_PORTFOLIO_VIEW_ON_EXPLORER_MENU_LABEL},
    {"braveWalletPortfolioHideTokenMenuLabel",
     IDS_BRAVE_WALLET_PORTFOLIO_VIEW_HIDE_TOKEN_LABEL},
    {"braveWalletHideTokenModalTitle", IDS_BRAVE_WALLET_HIDE_TOKEN_MODAL_TITLE},
    {"braveWalletTokenContractAddress",
     IDS_BRAVE_WALLET_TOKEN_CONTRACT_ADDRESS},
    {"braveWalletTokenDecimal", IDS_BRAVE_WALLET_TOKEN_DECIMAL},
    {"braveWalletMakeTokenVisibleInstructions",
     IDS_BRAVE_WALLET_MAKE_TOKEN_VISIBLE_INSTRUCTIONS},
    {"braveWalletConfirmHidingToken", IDS_BRAVE_WALLET_CONFIRM_HIDING_TOKEN},
    {"braveWalletCancelHidingToken", IDS_BRAVE_WALLET_CANCEL_HIDING_TOKEN},
    {"braveWalletMyAssets", IDS_BRAVE_WALLET_MY_ASSETS},
    {"braveWalletAvailableAssets", IDS_BRAVE_WALLET_AVAILABLE_ASSETS},
    {"braveWalletDidntFindAssetEndOfList",
     IDS_BRAVE_WALLET_DIDNT_FIND_ASSET_END_OF_LIST},
    {"braveWalletDidntFindAssetInList",
     IDS_BRAVE_WALLET_DIDNT_FIND_ASSET_IN_LIST},
    {"braveWalletAssetNotFound", IDS_BRAVE_WALLET_ASSET_NOT_FOUND},
    {"braveWalletRequestFeatureButtonText",
     IDS_BRAVE_WALLET_REQUEST_FEATURE_BUTTON_TEXT},
    {"braveWalletEnsOffchainProceedWithYes",
     IDS_BRAVE_WALLET_ENS_OFFCHAIN_PROCEED_WITH_YES},
    {"braveWalletEnsOffchainProceedWithNo",
     IDS_BRAVE_WALLET_ENS_OFFCHAIN_PROCEED_WITH_NO},
    {"braveWalletEnsOffchainDontShowAgain",
     IDS_BRAVE_WALLET_ENS_OFFCHAIN_DONT_SHOW_AGAIN},
    {"braveWalletEnsOffchainWarning", IDS_BRAVE_WALLET_ENS_OFFCHAIN_WARNING},
    {"braveWalletAddAssetTokenTabTitle",
     IDS_BRAVE_WALLET_ADD_ASSET_TOKEN_TAB_TITLE},
    {"braveWalletAddAssetNftTabTitle",
     IDS_BRAVE_WALLET_ADD_ASSET_NFT_TAB_TITLE},
    {"braveWalletNftFetchingError", IDS_BRAVE_WALLET_NFT_FETCHING_ERROR},
    {"braveWalletEditToken", IDS_BRAVE_WALLET_EDIT_TOKEN},
    {"braveWalletFEVMAddressTranslationTitle",
     IDS_BRAVE_WALLET_FEVM_ADDRESS_TRANSLATION_TITLE},
    {"braveWalletFEVMAddressTranslationDescription",
     IDS_BRAVE_WALLET_FEVM_ADDRESS_TRANSLATION_DESCRIPTION},

    // Brave Swap
    {"braveSwap", IDS_BRAVE_SWAP},
    {"braveSwapApproveToken", IDS_BRAVE_SWAP_APPROVE_TOKEN},
    {"braveSwapInsufficientBalance", IDS_BRAVE_SWAP_INSUFFICIENT_BALANCE},
    {"braveSwapInsufficientLiquidity", IDS_BRAVE_SWAP_INSUFFICIENT_LIQUIDITY},
    {"braveSwapSelectToken", IDS_BRAVE_SWAP_SELECT_TOKEN},
    {"braveSwapHalf", IDS_BRAVE_SWAP_HALF},
    {"braveSwapMax", IDS_BRAVE_SWAP_MAX},
    {"braveSwapEnterAnAmount", IDS_BRAVE_SWAP_ENTER_AN_AMOUNT},
    {"braveWalletFetchingQuote", IDS_BRAVE_WALLET_FETCHING_QUOTE},
    {"braveWalletReceiveEstimate", IDS_BRAVE_WALLET_RECEIVE_ESTIMATE},
    {"braveWalletFromToken", IDS_BRAVE_WALLET_FROM_TOKEN},
    {"braveWalletToToken", IDS_BRAVE_WALLET_TO_TOKEN},
    {"braveWalletNewQuoteIn", IDS_BRAVE_WALLET_NEW_QUOTE_IN},
    {"braveSwapBalance", IDS_BRAVE_SWAP_BALANCE},
    {"braveSwapSelectAToken", IDS_BRAVE_SWAP_SELECT_A_TOKEN},
    {"braveSwapShowTokensWithZeroBalances",
     IDS_BRAVE_SWAP_SHOW_TOKENS_WITH_ZERO_BALANCES},
    {"braveSwapHideTokensWithZeroBalances",
     IDS_BRAVE_SWAP_HIDE_TOKENS_WITH_ZERO_BALANCES},
    {"braveSwapSearchToken", IDS_BRAVE_SWAP_SEARCH_TOKEN},
    {"braveSwapOption", IDS_BRAVE_SWAP_OPTION},
    {"braveSwapPriceImpact", IDS_BRAVE_SWAP_PRICE_IMPACT},
    {"braveSwapMinimumReceivedAfterSlippage",
     IDS_BRAVE_SWAP_MINIMUM_RECEIVED_AFTER_SLIPPAGE},
    {"braveSwapNetworkFee", IDS_BRAVE_SWAP_NETWORK_FEE},
    {"braveSwapBraveFee", IDS_BRAVE_SWAP_BRAVE_FEE},
    {"braveSwapFree", IDS_BRAVE_SWAP_FREE},
    {"braveSwapSwapAndSend", IDS_BRAVE_SWAP_SWAP_AND_SEND},
    {"braveSwapNoExtraFees", IDS_BRAVE_SWAP_NO_EXTRA_FEES},
    {"braveSwapConfirmAddress", IDS_BRAVE_SWAP_CONFIRM_ADDRESS},
    {"braveSwapAddressInputePlaceholder",
     IDS_BRAVE_SWAP_ADDRESS_INPUT_PLACEHOLDER},
    {"braveSwapSelectAccount", IDS_BRAVE_SWAP_SELECT_ACCOUNT},
    {"braveSwapToAccount", IDS_BRAVE_SWAP_TO_ACCOUNT},
    {"braveSwapToAddress", IDS_BRAVE_SWAP_TO_ADDRESS},
    {"braveSwapSlow", IDS_BRAVE_SWAP_SLOW},
    {"braveSwapAverage", IDS_BRAVE_SWAP_AVERAGE},
    {"braveSwapFast", IDS_BRAVE_SWAP_FAST},
    {"braveSwapGwei", IDS_BRAVE_SWAP_GWEI},
    {"braveSwapSlippageTolerance", IDS_BRAVE_SWAP_SLIPPAGE_TOLERANCE},
    {"braveSwapExchanges", IDS_BRAVE_SWAP_EXCHANGES},
    {"braveSwapDirectRouteTitle", IDS_BRAVE_SWAP_DIRECT_ROUTE_TITLE},
    {"braveSwapDirectRouteDescription",
     IDS_BRAVE_SWAP_DIRECT_ROUTE_DESCRIPTION},
    {"braveSwapNetworkFeeDescription", IDS_BRAVE_SWAP_NETWORK_FEE_DESCRIPTION},
    {"braveSwapCoinGeckoCheaper", IDS_BRAVE_SWAP_COINGECKO_CHEAPER},
    {"braveSwapCoinGeckoWithin", IDS_BRAVE_SWAP_COINGECKO_WITHIN},
    {"braveSwapCoinGeckoExpensive", IDS_BRAVE_SWAP_COINGECKO_EXPENSIVE},
    {"braveSwapAPI", IDS_BRAVE_SWAP_API},
    {"braveSwapName", IDS_BRAVE_SWAP_NAME},
    {"braveSwapDisconnectWallet", IDS_BRAVE_SWAP_DISCONNECT_WALLET},
    {"braveSwapAdvanced", IDS_BRAVE_SWAP_ADVANCED},
    {"braveSwapAccounts", IDS_BRAVE_SWAP_ACCOUNTS},
    {"braveSwapWallet", IDS_BRAVE_SWAP_WALLET},
    {"braveSwapBest", IDS_BRAVE_SWAP_BEST},
    {"braveSwapHelpCenter", IDS_BRAVE_SWAP_HELP_CENTER},
    {"braveSwapPrivacyPolicy", IDS_BRAVE_SWAP_PRIVACY_POLICY},
    {"braveSwapPrivacyDescription", IDS_BRAVE_SWAP_PRIVACY_DESCRIPTION},
    {"braveSwapV2Disclaimer", IDS_BRAVE_SWAP_V2_DISCLAIMER},
    {"braveSwapV2Privacy", IDS_BRAVE_SWAP_V2_PRIVACY},
    {"braveSwapChangeNetwork", IDS_BRAVE_SWAP_CHANGE_NETWORK},

    {"braveNftsTabImportNft", IDS_BRAVE_WALLET_NFTS_TAB_IMPORT_NFT},
    {"braveNftsTabEmptyStateHeading",
     IDS_BRAVE_WALLET_NFTS_TAB_EMPTY_STATE_HEADING},
    {"braveNftsTabEmptyStateSubHeading",
     IDS_BRAVE_WALLET_NFTS_TAB_EMPTY_STATE_SUBHEADING},
    {"braveNftsTabEmptyStateDisclaimer",
     IDS_BRAVE_WALLET_NFTS_TAB_EMPTY_STATE_DISCLAIMER},
    {"braveNftsTabHide", IDS_BRAVE_WALLET_NFTS_TAB_HIDE},
    {"braveNftsTabUnhide", IDS_BRAVE_WALLET_NFTS_TAB_UNHIDE},
    {"braveNftsTabEdit", IDS_BRAVE_WALLET_NFTS_TAB_EDIT},
    {"braveWalletNftUnspam", IDS_BRAVE_WALLET_NFT_UNSPAM},
    {"braveWalletNftJunk", IDS_BRAVE_WALLET_NFT_JUNK},
    {"braveWalletRemoveNftModalHeader",
     IDS_BRAVE_WALLET_REMOVE_NFT_MODAL_HEADER},
    {"braveWalletRemoveNftModalDescription",
     IDS_BRAVE_WALLET_REMOVE_NFT_MODAL_DESCRIPTION},
    {"braveWalletRemoveNftModalCancel",
     IDS_BRAVE_WALLET_REMOVE_NFT_MODAL_CANCEL},
    {"braveWalletRemoveNftModalConfirm",
     IDS_BRAVE_WALLET_REMOVE_NFT_MODAL_CONFIRM},
    {"braveWalletNftMoveToSpam", IDS_BRAVE_WALLET_NFT_MOVE_TO_SPAM},
    {"braveNftsTab", IDS_BRAVE_WALLET_NFTS_TAB},
    {"braveNftsTabHidden", IDS_BRAVE_WALLET_NFTS_TAB_HIDDEN},
    {"braveNftsTabCollected", IDS_BRAVE_WALLET_NFTS_TAB_COLLECTED},
    {"braveNftsTabRemove", IDS_BRAVE_WALLET_NFTS_TAB_REMOVE},
    {"braveWalletAddNftModalTitle", IDS_BRAVE_WALLET_ADD_NFT_MODAL_TITLE},
    {"braveWalletEditNftModalTitle", IDS_BRAVE_WALLET_EDIT_NFT_MODAL_TITLE},
    {"braveWalletEnableNftAutoDiscoveryModalHeader",
     IDS_BRAVE_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_HEADER},
    {"braveWalletEnableNftAutoDiscoveryModalDescription",
     IDS_BRAVE_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_DESCRIPTION},
    {"braveWalletEnableNftAutoDiscoveryModalConfirm",
     IDS_BRAVE_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_CONFIRM},
    {"braveWalletEnableNftAutoDiscoveryModalCancel",
     IDS_BRAVE_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_CANCEL},
    {"braveWalletAutoDiscoveryEmptyStateHeading",
     IDS_BRAVE_WALLET_AUTO_DISCOVERY_EMPTY_STATE_HEADING},
    {"braveWalletAutoDiscoveryEmptyStateSubHeading",
     IDS_BRAVE_WALLET_AUTO_DISCOVERY_EMPTY_STATE_SUB_HEADING},
    {"braveWalletAutoDiscoveryEmptyStateFooter",
     IDS_BRAVE_WALLET_AUTO_DISCOVERY_EMPTY_STATE_FOOTER},
    {"braveWalletAutoDiscoveryEmptyStateActions",
     IDS_BRAVE_WALLET_AUTO_DISCOVERY_EMPTY_STATE_ACTIONS},
    {"braveWalletAutoDiscoveryEmptyStateRefresh",
     IDS_BRAVE_WALLET_AUTO_DISCOVERY_EMPTY_STATE_REFRESH},
    {"braveWalletUphold", IDS_BRAVE_WALLET_UPHOLD},
    {"braveWalletGemini", IDS_BRAVE_WALLET_GEMINI},
    {"braveWalletZebpay", IDS_BRAVE_WALLET_ZEBPAY},
    {"braveWalletBitflyer", IDS_BRAVE_WALLET_BITFLYER},
    {"braveWalletRewardsAccount", IDS_BRAVE_WALLET_REWARDS_ACCOUNT},
    {"braveWalletBraveRewardsTitle", IDS_BRAVE_WALLET_BRAVE_REWARDS_TITLE},
    {"braveWalletBraveRewardsDescription",
     IDS_BRAVE_WALLET_BRAVE_REWARDS_DESCRIPTION},
    {"braveWalletBraveRewardsLoggedOutDescription",
     IDS_BRAVE_WALLET_BRAVE_REWARDS_LOGGED_OUT_DESCRIPTION},
    {"braveWalletLogIn", IDS_BRAVE_WALLET_LOG_IN},
    {"braveWalletViewOn", IDS_BRAVE_WALLET_VIEW_ON},
    {"braveWalletRewardsSettings", IDS_BRAVE_WALLET_REWARDS_SETTINGS},
    {"braveWalletPlatforms", IDS_BRAVE_WALLET_PLATFORMS},
    {"braveWalletNoDappsFound", IDS_BRAVE_WALLET_NO_DAPPS_FOUND},
    {"braveWalletActiveWallets", IDS_BRAVE_WALLET_ACTIVE_WALLETS},
    {"braveWalletVisitDapp", IDS_BRAVE_WALLET_VISIT_DAPP},
    {"braveWalletFilters", IDS_BRAVE_WALLET_FILTERS},
    {"braveWalletClearFilters", IDS_BRAVE_WALLET_CLEAR_FILTERS},
    {"braveWalletShowMore", IDS_BRAVE_WALLET_SHOW_MORE}};

// 0x swap constants
inline constexpr char kZeroExSepoliaBaseAPIURL[] =
    "https://sepolia.api.0x.wallet.brave.com";
inline constexpr char kZeroExPolygonBaseAPIURL[] =
    "https://polygon.api.0x.wallet.brave.com";
inline constexpr char kZeroExBinanceSmartChainBaseAPIURL[] =
    "https://bsc.api.0x.wallet.brave.com";
inline constexpr char kZeroExAvalancheBaseAPIURL[] =
    "https://avalanche.api.0x.wallet.brave.com";
inline constexpr char kZeroExFantomBaseAPIURL[] =
    "https://fantom.api.0x.wallet.brave.com";
inline constexpr char kZeroExCeloBaseAPIURL[] =
    "https://celo.api.0x.wallet.brave.com";
inline constexpr char kZeroExOptimismBaseAPIURL[] =
    "https://optimism.api.0x.wallet.brave.com";
inline constexpr char kZeroExArbitrumBaseAPIURL[] =
    "https://arbitrum.api.0x.wallet.brave.com";
inline constexpr char kZeroExBaseBaseAPIURL[] =
    "https://base.api.0x.wallet.brave.com";
inline constexpr char kZeroExEthereumBaseAPIURL[] =
    "https://api.0x.wallet.brave.com";
inline constexpr char kEVMFeeRecipient[] =
    "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";
inline constexpr char kAffiliateAddress[] =
    "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";

// Jupiter swap constants
inline constexpr char kJupiterBaseAPIURL[] = "https://jupiter.wallet.brave.com";
inline constexpr char kJupiterReferralKey[] =
    "7yke2kxg6ewNsun61qBkdsLdxuXcUiB8CMB47Zv39Aoy";
inline constexpr char kJupiterReferralProgram[] =
    "REFER4ZgmyYx9c6He5XfaTMiGfdLwRnkV4RPp9t9iF3";
inline constexpr char kJupiterReferralProgramHeader[] = "referral_ata";
inline constexpr char kWrappedSolanaMintAddress[] =
    "So11111111111111111111111111111111111111112";

// Blowfish simulations constants
inline constexpr char kBlowfishBaseAPIURL[] =
    "https://blowfish.wallet.brave.com";
inline constexpr char kBlowfishAPIVersionHeader[] = "X-Api-Version";
inline constexpr char kBlowfishAPIVersion[] = "2023-06-05";

// LiFi constants
inline constexpr char kLiFiBaseAPIURL[] = "https://lifi.wallet.brave.com";
inline constexpr char kLiFiIntegratorID[] = "brave";
inline constexpr char kLiFiNativeEVMAssetContractAddress[] =
    "0x0000000000000000000000000000000000000000";
inline constexpr char kLiFiNativeSVMAssetContractAddress[] =
    "So11111111111111111111111111111111111111112";

// LiFi // 0x common constants
inline constexpr char kNativeEVMAssetContractAddress[] =
    "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";

constexpr int64_t kBlockTrackerDefaultTimeInSeconds = 20;
constexpr int64_t kLogTrackerDefaultTimeInSeconds = 20;
constexpr int64_t kSolanaBlockTrackerTimeInSeconds = 2;

// Ankr constants
inline constexpr char kAnkrAdvancedAPIBaseURL[] =
    "https://multichain.ankr.wallet.brave.com/";

// Unstoppable domains record key for ethereum address.
inline constexpr char kCryptoEthAddressKey[] = "crypto.ETH.address";
// Unstoppable domains record key for solana address.
inline constexpr char kCryptoSolAddressKey[] = "crypto.SOL.address";
// Unstoppable domains record key for filecoin address.
inline constexpr char kCryptoFilAddressKey[] = "crypto.FIL.address";

// ERC-165 identifier for ERC721 interface.
inline constexpr char kERC1155InterfaceId[] = "0xd9b67a26";
inline constexpr char kERC1155MetadataInterfaceId[] = "0x0e89341c";
inline constexpr char kERC721InterfaceId[] = "0x80ac58cd";
inline constexpr char kERC721MetadataInterfaceId[] = "0x5b5e139f";

inline constexpr char kBitcoinPrefKey[] = "bitcoin";
inline constexpr char kZCashPrefKey[] = "zcash";
inline constexpr char kEthereumPrefKey[] = "ethereum";
inline constexpr char kFilecoinPrefKey[] = "filecoin";
inline constexpr char kSolanaPrefKey[] = "solana";

inline constexpr char kEthereumBlockTagEarliest[] = "earliest";
inline constexpr char kEthereumBlockTagLatest[] = "latest";

inline constexpr char kBitcoinTestnetRpcEndpoint[] =
    "https://blockstream.info/testnet/api/";

inline constexpr char kMeldRpcEndpoint[] = "https://api-meld.wallet.brave.com";
inline constexpr char kMeldRpcVersionHeader[] = "Meld-Version";
inline constexpr char kMeldRpcVersion[] = "2023-05-26";

const std::string GetSardineNetworkName(const std::string& chain_id);
const base::flat_map<std::string, std::string>&
GetEthBalanceScannerContractAddresses();
const std::vector<std::string>& GetEthSupportedNftInterfaces();
// Returns the URL for the Ratios service.
const std::string GetAssetRatioBaseURL();
const base::flat_map<std::string, std::string>& GetAnkrBlockchains();
// https://docs.rs/solana-program/1.18.10/src/solana_program/clock.rs.html#129-131
inline constexpr int kSolanaValidBlockHeightThreshold = 150;
}  // namespace brave_wallet

#endif  // BRAVE_COMPONENTS_BRAVE_WALLET_BROWSER_BRAVE_WALLET_CONSTANTS_H_
