/* Copyright (c) 2024 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

// Schema for Meld responses.
namespace meld_integration_responses {
    dictionary Logos {
        DOMString? dark;
        DOMString? light;
        DOMString? darkShort;
        DOMString? lightShort;
    };

    dictionary Country {
        DOMString countryCode;
        DOMString? name;
        DOMString? flag;
    };

    dictionary CountriesResponse {
        Country[]? countries;
    };

    dictionary CryptoCurrency {
        DOMString currencyCode;
        DOMString? name;
        long? decimalPlaces;
        DOMString? chainCode;
        DOMString? chainName;
        DOMString? chainId;
        DOMString? contract;
        DOMString? symbol;
    };

    dictionary CryptoCurrenciesResponse {
        CryptoCurrency[]? currencies;
    };

    dictionary FiatCurrency {
        DOMString currencyCode;
        DOMString? name;
        long? decimalPlaces;
        DOMString? symbol;
    };

    dictionary FiatCurrenciesResponse {
        FiatCurrency[]? currencies;
    };

    dictionary PaymentMethod {
        DOMString method;
        DOMString? name;
        DOMString? paymentType;
        Logos? logo;
    };

    dictionary CryptoQuote {
        DOMString? transactionType;
        DOMString? sourceAmount;
        DOMString? sourceAmountWithoutFees;
        DOMString? fiatAmountWithoutFees;
        DOMString? destinationAmountWithoutFees;
        DOMString? sourceCurrencyCode;
        DOMString? countryCode;
        DOMString? totalFee;
        DOMString? networkFee;
        DOMString? transactionFee;
        DOMString? destinationAmount;
        DOMString? destinationCurrencyCode;
        DOMString? exchangeRate;
        DOMString? paymentMethodType;
        DOMString? customerScore;
        DOMString? serviceProvider;
    };

    dictionary CryptoQuoteResponse {
        CryptoQuote[]? quotes;
        DOMString? message;
        DOMString? error;
    };

    dictionary ServiceProvider {
        DOMString serviceProvider;
        DOMString? name;
        DOMString status;
        DOMString[] categories;
        any categoryStatuses;
        DOMString? websiteUrl;
        Logos? logos;
    };

    dictionary MeldError {
        DOMString? code;
        DOMString? message;
        DOMString[]? errors;
        DOMString? requestId;
        DOMString? timestamp;
    };

    dictionary CryptoWidgetResult {
        DOMString id;
        DOMString? externalSessionId;
        DOMString? externalCustomerId;
        DOMString customerId;
        DOMString widgetUrl;
        DOMString token;
    };
};
