name: Assign labels

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  label:
    name: Assign labels
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: set ci managed labels (automatically set and unset)
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
        configuration-path: .github/synced-labels.yml

    - name: set optional labels
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: false
        configuration-path: .github/optional-labels.yml

    - name: comment on fork PRs
      if: github.event.pull_request.head.repo.full_name != github.repository && (github.event.action == 'opened' || github.event.action == 'reopened')
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        gh pr comment "$PR_NUMBER" -R "$GITHUB_REPOSITORY" -b "We don't run CI on fork PRs except when mirrored using [this workflow](https://github.com/brave/brave-core/actions/workflows/sync-and-rebase-pr-from-fork.yml)."
