name: Assign author

on:
  pull_request:
    types: [opened, reopened, closed]

permissions:
  pull-requests: write

jobs:
  assign:
    name: Assign author
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160 # v1.6.2
