name: Auto Assign on license-update labels for Sanctions Compliance

on:
  pull_request:
    types: labeled

permissions:
  pull-requests: write

jobs:
  assign-user:
        runs-on: ubuntu-slim
    if: github.event.label.name == 'license-update'
    steps:
      - name: Auto Assign on license-update labels for Sanctions Compliance
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['mrose17']
            })
