name: Bump DEPS
on:
  workflow_dispatch:
    inputs:
      dep:
        description: "Dependency"
        required: true
        type: string
        default: "vendor/web-discovery-project"
      ref:
        description: "New ref for dependency"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-bump:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: auto-bump
        run: |
          set -x

          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git config push.default simple
          gh api /repos/brave/web-discovery-project/commits/main -q .sha
          exit 0

          SED=sed
          DATE=date

          # Inputs
          DEP="${{ inputs.dep }}"
          DEPREF="${{ inputs.ref }}"
          [[ -z "$DEP" ]] && { echo Input dependency cannot be empty; exit 1; }
          [[ -z "$DEPREF" ]] && { echo Input ref cannot be empty; exit 1; }

          DATETIME="$($DATE '+%Y-%m-%d-%H-%M')"
          readarray -t milestones < <(gh api /repos/brave/brave-core/milestones -q ".[] | .title" | grep -Fv Closed)
          branches=( "${milestones[@]/*Nightly/master}" )
          branches=( "${branches[@]/ -*/}" )
          echo Branches to operate on:
          declare -p branches
          for branch in "${branches[@]}"
          do
            git switch "$branch"
            pr_branch="pr-auto-bump-deps-${branch}-${DATETIME}"
            git switch -c "$pr_branch"
            "$SED" -i -e "s|\(.*${DEP}.*\)@\(.*\)\",$|\1@${DEPREF}\",|" DEPS
            git add DEPS
            git commit -m "Auto bump DEPS ${DEP}"
            git push -u origin "$pr_branch"
            # gh pr create --base "${branch}" -f -t "Auto bump ${DEP}" -l "CI/run-audit-deps"
          done
