# Description: Run this by visiting https://github.com/brave/brave-core/actions/workflows/bump-deps.yaml
# and clicking the `Run workflow` button on the top-right.
# You can also run it from cli by: `gh workflow run bump-deps.yaml -f ref=commit-hash`
name: Bump DEPS
on:
  workflow_dispatch:
    inputs:
      dep:
        description: "Dependency"
        required: true
        type: string
        default: "vendor/web-discovery-project"
      ref:
        description: "New ref for dependency"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-bump:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: auto-bump
        run: |
          set -x

          SED=sed

          # Inputs
          DEP="${{ inputs.dep }}"
          DEPREF="${{ inputs.ref }}"

          [[ "${DEP:?}" =~ ^[a-zA-Z/-]+$ ]] || { echo Input dependency validation failed; exit 1; }
          if [[ -z "${DEPREF}" ]]; then
            echo "Attempting to guess ref hash"
            DEP_REPO=$(sed -n '/deps = {/, /^}/p' DEPS | sed 's/deps =//' | python3 -c "import sys,ast; d=ast.literal_eval(sys.stdin.read()); print(d[\"vendor/omaha\"][\"url\"])" | grep -Po '(?<=github.com/).*?(?=.git@)')
            gh api /repos/"${DEP_REPO}"/commits/master -q .sha > /tmp/DEPREF || gh api /repos/"${DEP_REPO}"/commits/main -q .sha > /tmp/DEPREF
            DEPREF=$(</tmp/DEPREF)
          fi
          [[ "${DEPREF:?}" =~ ^[a-z0-9]+$ ]] || { echo Dependency reference validation failed; exit 1; }

          readarray -t milestones < <(gh api /repos/${GITHUB_REPOSITORY:?}/milestones -q ".[] | .title" | grep -Fv Closed)
          branches=( "${milestones[@]/*Nightly/master}" )
          branches=( "${branches[@]/ -*/}" )
          echo "Branches to operate on: ${branches[*]}"
          for branch in "${branches[2]}"
          do
            git switch "$branch"
            pr_branch="pr-auto-bump-deps-${branch}-${DEP}-${DEPREF}"
            git switch -c "$pr_branch"
            "$SED" -i -e "s,^\(\s*\"$DEP\"\s*:\s*\"https.*\)@[^\"]*\",\1@$DEPREF\"," \
                      -e "/^\s*\"${DEP//\//\\/}\"\s*:\s*{/,/@/ s/@[^\"]*/@$DEPREF/" DEPS
            # git add DEPS
            # git commit -m "Auto bump DEPS ${DEP}@${DEPREF}"
            git push -u origin "$pr_branch"
            gh api --method PUT /repos/${GITHUB_REPOSITORY}/contents/DEPS --field message="Auto bump DEPS ${DEP}@${DEPREF}" --field content=@<( base64 -i DEPS ) --field encoding="base64" --field branch="$pr_branch" --field sha=$( git rev-parse $pr_branch:DEPS )
            git restore DEPS
            git pull
            # gh pr create --base "${branch}" -f -t "Auto bump DEPS ${DEP}@${DEPREF}" -l "CI/run-audit-deps"
          done
