# See: .github/labeler.yml

name: "Add CI labels"
on:
- pull_request_target
jobs:
  addCiLabels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
