name: Compare Chromium versions

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  compare-chromium-versions:
    runs-on: ubuntu-slim
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .github/workflows/scripts
        if: github.event.pull_request.head.repo.full_name == github.repository
      - name: Check if CI and merge are allowed based on the Chromium version in the target branch
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: bash .github/workflows/scripts/compare-chromium-versions.sh
