name: Require Checklist
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
#   issues:
#     types: [opened, edited, deleted]
jobs:
  require-checklist:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -eux -o pipefail
          unchecked=$(gh api "$REPOFULLNAME"/"$PRNUM" --jq '.body' | awk '/## Reviewer Checklist/,/## After-merge Checklist/' | grep '\[ \]')
          echo "$unchecked"
          [ -n "$unchecked" ] && echo "Found unchecked reviewer items. Failing..." && exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOFULLNAME: ${{ github.event.repository.full_name }}
          PRNUM: ${{ github.event.number }}
