name: Require Reviewer Checklist

on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review, review_requested]
    branches: [master, 1.*]

jobs:
  require-reviewer-checklist:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.event.repository.full_name }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          if gh pr view "$PR_NUMBER" -R "$REPO_NAME" --json body --jq '.body' | sed -n '/## Reviewer Checklist/,/## After-merge Checklist/p' | grep '\[ \]'; then
              echo "Found unchecked reviewer items. Failing..."
              exit 1
          fi
