name: Trigger sync PR from fork

on:
  pull_request_review:
    types: [submitted]

permissions:
  actions: write # Required to trigger other workflows

jobs:
  test-job:
    if: >-
      ${{ github.event.review.user.type != 'Bot'
      && contains(github.event.review.body, '/run-ci')
      && contains(fromJSON('["OWNER", "MEMBER"]'), github.event.review.author_association) }}
    runs-on: ubuntu-slim
    steps:
      - run: echo "Placeholder for testing"
