# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/ui/webui/custom_profile_image/buildflags/buildflags.gni")

assert(enable_brave_custom_profile_image_webui)

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  sources = [ "brave_profile_customization_browsertest.cc" ]
  deps = [
    "//base",
    "//base/test:test_support",
    "//brave/browser/ui/webui/custom_profile_image",
    "//chrome/common",
    "//chrome/test:test_support",
    "//content/test:test_support",
  ]
  data_deps = [ "//chrome:browser_tests_pak" ]
}
