# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

substitutions:
  - description: |
      Register Brave's side panel action ids.
    regex:
      re_pattern: '(#define SIDE_PANEL_ACTION_IDS \\\n)'
      replace: |
        \1  E(kActionSidePanelShowPlaylist) \
          E(kActionSidePanelShowChatUI) \
          E(kActionSidePanelShowBraveNews) \
          E(kActionSidePanelShowWallet) \
  - description: |
      Register Brave's toolbar action ids.
    regex:
      re_pattern: '(#define TOOLBAR_PINNABLE_ACTION_IDS \\\n)'
      replace: |
        \1  E(kActionShowPartitionedStorage) \
          E(kActionShowPsstIcon) \
